In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("spearman_corr.csv")
df_month

May_6  November_7   April_8  August_3  December_2  November_3  \
0   0.426002   -0.414703  0.133591  0.577440   -0.233301    0.827789   
1   0.343893   -0.414703  0.146146  0.577440   -0.233301    0.827789   
2   0.197382    0.119779  0.100033  0.806378   -0.675635    0.192062   
3  -0.069665   -0.082401  0.006054  0.512310   -0.410518    0.484618   
4  -0.835852   -1.015143 -0.124219  0.211962   -0.230980    0.434227   
5  -0.070522   -0.818627  0.016689 -0.290574   -0.454416   -0.226640   
6  -0.573413   -1.069754  0.154757  0.582391   -0.428709    0.448013   
7   0.461886   -0.768627 -0.186963  0.066570   -0.485894    0.431479   
8   0.548707   -0.137888  0.084944  0.594337   -0.251346    0.661389   
9  -0.522139   -0.548753  0.120713  0.498273   -0.357940    0.235838   
10  0.147972   -0.530598 -0.002915  0.542509   -0.030573    0.224968   
11  0.447703   -0.857654  0.147970 -0.133022   -0.486048    1.120995   
12 -0.126166   -0.811415  0.179310  0.823436   -0.153545    0.219366   
13 -0.078589   -1.169312  0.302660  0.483234   -0.411928    0.541565   
14  0.200709   -0.400256  0.076961 -0.394600   -0.103696    0.264699   
15  0.359966   -1.089294  0.117638  0.621513   -0.441663    0.900897   
16 -0.485582   -1.062109  0.189012  0.005352   -0.510809    0.379595   
17 -0.098261   -1.445140  0.049449  0.470284    0.166106    0.586143   
18  0.033565   -0.438656 -0.051335 -0.282387   -0.444339    0.563617   
19  0.759252   -0.700344 -0.146433 -0.322828   -0.553474   -0.052203   
20  0.140413   -0.036264  0.317657  0.682713   -0.136651    0.452011   
21  0.153274    0.033722 -0.127904 -0.038600   -0.229183    0.334612   
22  0.216580   -0.364840  0.162633  0.127533   -0.135916    0.548504   
23 -0.012037   -0.772920  0.458715  0.245341   -0.238661    0.424697   
24 -0.000847   -0.658674  0.094069 -0.404809   -0.453884    0.135475   
25  0.600718   -0.318289  0.005257  0.793525   -0.204982    0.544852   
26  0.361158   -0.392938  0.021758  0.155925   -0.172416    0.892909   
27 -0.469536   -0.763604 -0.043283  0.116156   -0.886626    0.813336   
28  0.169024    0.254993 -0.182786  0.060142   -0.288673    0.500395   
29  0.776547    0.502166  0.105175  0.714239   -0.516111    0.419865   
30 -0.194545   -0.202859  0.161175  1.229435   -0.064378    0.674656   
31 -0.471821   -1.104039  0.242990  0.202320   -0.208003    0.418590   
32  0.262121    0.043108 -0.107454  0.147966   -0.351253    1.016309   
33  0.296479   -0.015937 -0.272283  0.198766   -0.444716    1.041260   
34  0.961588   -0.036404 -0.103149 -0.647471   -0.142551    0.529207   
35  0.547697    0.164452 -0.157881 -0.348586   -0.302652    0.400338   
36  0.308813    0.132246  0.277105  0.169143   -0.363727    0.593754   
37 -0.162653   -1.059555 -0.117465  0.350897   -0.119492    0.875497   
38 -0.295998   -0.496676  0.010101  0.431102   -0.263344    0.361816   
39  0.408300    0.037235 -0.420608 -0.076090   -0.713316   -0.093573   
40  0.205959   -1.671818  0.353169 -0.317858   -0.351209    1.110276   
41 -0.747444   -1.154535  0.159591  0.152743   -0.274645    0.677305   
42 -0.261200   -0.586629  0.043581  0.138711   -0.030522    0.714004   
43  0.075356   -1.054226  0.015448  0.723950   -0.065773    0.281642   
44  0.174079   -0.426612 -0.237113 -0.340012   -0.300018    0.031610   
45 -0.037975    0.101509 -0.155063  0.580025   -0.501479    0.363339   
46 -0.390822   -0.221160  0.127236 -0.154983   -0.473571    0.683805   
47  0.677045   -0.410010  0.286343 -0.085728   -0.442984    0.586652   
48 -0.148528   -0.526568  0.306458  0.224066   -0.601254    0.400467   
49 -0.394659   -0.523534 -0.186369  0.841855   -0.337605    0.284612   
50 -0.063721   -0.619278  0.410396  0.433475   -0.461946    0.065375   
51 -0.007191   -0.749957 -0.117755 -0.042938   -0.551127   -0.054909   
52 -0.246229   -0.979028  0.263265  0.560965   -0.262369    0.543907   
53 -0.500057   -0.817030  0.343352  0.133667   -0.316473    0.653280   
54 -0.121197   -1.084560 -0.306003  0.783340   

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :15]
x_train = scaler.fit_transform(x_train)
x_train

array([[ 8.00392258e-01,  1.96206982e-01,  4.68800272e-01,
         8.37058200e-01,  4.63406536e-01,  1.00704222e+00,
        -8.61740180e-04, -1.05186079e+00,  1.12945149e+00,
        -6.64194451e-01,  5.72517314e-02,  1.85361455e+00,
         8.36360147e-01,  1.40275185e+00,  1.94917315e+00],
       [ 5.99962738e-01,  1.96206982e-01,  5.40242756e-01,
         8.37058200e-01,  4.63406536e-01,  1.00704222e+00,
        -8.61740180e-04, -1.05186079e+00,  3.23931147e-01,
        -6.64194451e-01,  1.17578300e+00,  1.85361455e+00,
         2.60135554e-01, -5.64129977e-01, -7.98897996e-01],
       [ 2.42325872e-01,  1.26539456e+00,  2.77842071e-01,
         1.39762905e+00, -1.80468815e+00, -1.05673058e+00,
        -2.92204700e-01,  1.63739144e+00,  6.19079707e-01,
         1.94219393e-02, -7.39545568e-01, -1.37602248e-01,
         1.08526806e+00,  3.03631732e-01, -1.13124190e+00],
       [-4.09545368e-01,  8.60950296e-01, -2.56930982e-01,
         6.77581581e-01, -4.45288575e-01, -1.07000855

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [8]:
x_test = df_month.iloc[43:, :15]
x_test = scaler.fit_transform(x_test)
x_test

array([[ 0.55246073, -1.47227458, -0.01423719,  1.04123018,  1.53844362,
        -0.21366782,  0.30927054,  0.30390221,  0.30741913, -0.23063938,
        -0.87091215,  0.90734781,  0.00871995, -0.41539967, -0.85333003],
       [ 0.91023503,  0.39980905, -0.99370166, -1.52375434,  0.23963755,
        -1.30719891,  0.3964202 ,  0.64981022, -2.01935477,  0.53150929,
         0.13949488, -1.04281091, -1.55002498, -0.30350288,  1.29814413],
       [ 0.14174452,  1.97512047, -0.67549985,  0.69425834, -0.87738844,
         0.14363979, -1.75832353,  0.54646797,  0.52429441,  0.49624286,
        -0.01487948,  0.14528413,  0.74404162,  0.48560543,  0.28656954],
       [-1.1369821 ,  1.01264568,  0.41929119, -1.07768958, -0.72264986,
         1.54521584,  0.29484982, -0.61516424, -1.72048995,  1.42786149,
         1.54936741,  0.34601994,  0.35206372, -1.49293413,  0.52327805],
       [ 2.73299469,  0.44933151,  1.03633024, -0.91072967, -0.55305608,
         1.12031226,  0.30302576, -0.37770529, 

In [9]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] 
    y_test.append(y_ts)

In [10]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 18}
Best Score: 0.3817135826831141
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 21}
Best Score: 0.2750481614157656
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 20}
Best Score: 0.24354247685435587
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 23}
Best Score: 0.21434163116652544
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 9}
Best Score: 0.24208413401944529


In [13]:
y_pred_list

[array([-0.40634889,  0.32968838,  0.26103346, -0.08011685, -0.01550172,
        -0.09711117, -0.41194363, -0.05897614,  0.39891933, -0.59245195,
        -0.48601176,  0.15385714, -0.23293503,  0.47231238,  0.39921617,
        -0.08256076]),
 array([-0.38553607,  0.47490308,  0.22063734, -0.13899643,  0.19069321,
         0.15371514, -0.39668024, -0.0813479 ,  0.1986273 , -0.61842617,
        -0.59426942,  0.00933715, -0.28903341,  0.40822581,  0.6449786 ,
        -0.06744479]),
 array([-0.23210944,  0.36398452,  0.26532738, -0.02150119,  0.07280357,
        -0.0833631 , -0.3626566 , -0.12588393,  0.38354762, -0.80822857,
        -0.58952143,  0.2359119 , -0.12212744,  0.2223369 ,  0.4000625 ,
        -0.21722619]),
 array([-0.42388503,  0.3948739 ,  0.16729924,  0.23810587, -0.08572072,
         0.10016052, -0.20048112, -0.00504188,  0.42348179, -0.71400477,
        -0.43355329,  0.17796741,  0.13143194,  0.3900473 ,  0.49275617,
        -0.33054426]),
 array([-0.29668318,  0.6347568 

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.7975128249226534,
 0.8374821787989046,
 0.8278171251278995,
 0.8428156489608913,
 0.7561199648397343]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+vwind/15 predictors/spearson/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'slp+vwind (2001-2016) 15p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'15p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+vwind/15 predictors/spearson/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Air_Temperature/15 predictors/spearson/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'Air_Temperature Predicted vs Actual 15p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'15p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Air_Temperature/15 predictors/spearson/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:

y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 18}
Best Score: 0.3817135826831141
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 21}
Best Score: 0.2750481614157656
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 20}
Best Score: 0.24354247685435587
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 23}
Best Score: 0.21434163116652544
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 9}
Best Score: 0.24208413401944529


In [21]:
y_pred_list_rf

[array([-0.40634889,  0.32968838,  0.26103346, -0.08011685, -0.01550172,
        -0.09711117, -0.41194363, -0.05897614,  0.39891933, -0.59245195,
        -0.48601176,  0.15385714, -0.23293503,  0.47231238,  0.39921617,
        -0.08256076]),
 array([-0.38553607,  0.47490308,  0.22063734, -0.13899643,  0.19069321,
         0.15371514, -0.39668024, -0.0813479 ,  0.1986273 , -0.61842617,
        -0.59426942,  0.00933715, -0.28903341,  0.40822581,  0.6449786 ,
        -0.06744479]),
 array([-0.23210944,  0.36398452,  0.26532738, -0.02150119,  0.07280357,
        -0.0833631 , -0.3626566 , -0.12588393,  0.38354762, -0.80822857,
        -0.58952143,  0.2359119 , -0.12212744,  0.2223369 ,  0.4000625 ,
        -0.21722619]),
 array([-0.42388503,  0.3948739 ,  0.16729924,  0.23810587, -0.08572072,
         0.10016052, -0.20048112, -0.00504188,  0.42348179, -0.71400477,
        -0.43355329,  0.17796741,  0.13143194,  0.3900473 ,  0.49275617,
        -0.33054426]),
 array([-0.29668318,  0.6347568 

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.7975128249226534,
 0.8374821787989046,
 0.8278171251278995,
 0.8428156489608913,
 0.7561199648397343]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Air_Temperature/15 predictors/spearson/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'Air_Temperature (2001-2016) 15p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'15_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Air_Temperature/15 predictors/spearson/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Air_Temperature/15 predictors/spearson/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'Air_Temperature Predicted vs Actual 15p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'15p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Air_Temperature/15 predictors/spearson/comparison plots/randomforest
