In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df['avg'] = df[['june', 'july', 'august', 'september']].mean(axis=1)

In [4]:
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [5]:
df_month = pd.read_csv("spearman_corr.csv")
df_month

April_7   April_4   April_5  April_11  April_13    July_6  November_5  \
0  -0.431286 -0.340860 -0.549567 -0.568145 -0.267017 -0.497566   -0.353314   
1  -0.533980 -0.399154 -0.455645 -0.476096 -0.424836 -0.497566   -0.353314   
2  -0.374850 -0.239554 -0.408891 -0.465391 -0.450850 -0.614742   -0.466834   
3  -0.604850 -0.517645 -0.708450 -0.739045 -0.450262 -0.579358   -0.379293   
4  -0.219154 -0.391761 -0.215144 -0.441211 -0.520404 -0.524663   -0.344270   
5  -0.502544 -0.270182 -0.328922 -0.432368 -0.521861 -0.472274   -0.390347   
6  -0.497069 -0.552591 -0.420962 -0.575021 -0.293576 -0.481949   -0.434477   
7  -0.394057 -0.294222 -0.369803 -0.544543 -0.353479 -0.209288   -0.418211   
8  -0.557030 -0.404795 -0.537414 -0.487596 -0.198219 -0.428058   -0.369277   
9  -0.284371 -0.300480 -0.369547 -0.454457 -0.540177 -0.468773   -0.315025   
10 -0.348182 -0.543712 -0.357692 -0.550210 -0.510692 -0.357153   -0.389027   
11 -0.192281 -0.368806 -0.315139 -0.410530 -0.455138 -0.406740   -0.423627   
12 -0.572110 -0.487405 -0.428276 -0.561987 -0.413038 -0.454944   -0.417658   
13 -0.423295 -0.512052 -0.399894 -0.529663 -0.289887 -0.493929   -0.452621   
14 -0.415653 -0.388512 -0.168685 -0.342697 -0.495303 -0.429653   -0.340081   
15 -0.578203 -0.714446 -0.751165 -0.588312 -0.280174 -0.503611   -0.495925   
16 -0.374572 -0.506431 -0.554055 -0.422096 -0.463900 -0.513313   -0.286112   
17 -0.500755 -0.548926 -0.584862 -0.582584 -0.325171 -0.592881   -0.488217   
18 -0.305194 -0.440616 -0.383723 -0.458873 -0.553981 -0.399561   -0.395362   
19 -0.406520 -0.432716 -0.077767 -0.293167 -0.409111 -0.422900   -0.468622   
20 -0.396659 -0.560590 -0.387925 -0.404867 -0.423366 -0.525276   -0.511226   
21 -0.441504 -0.548319 -0.423060 -0.457743 -0.490486 -0.618296   -0.220388   
22 -0.551280 -0.232324 -0.658006 -0.576628 -0.327259 -0.520815   -0.433556   
23 -0.362009 -0.525662 -0.471235 -0.376668 -0.372504 -0.496582   -0.361462   
24 -0.235150 -0.444678 -0.442271 -0.378760 -0.477313 -0.457584   -0.451836   
25 -0.548240 -0.805514 -0.591371 -0.564049 -0.434629 -0.448200   -0.433960   
26 -0.320183 -0.389276 -0.430851 -0.502651 -0.342292 -0.516112   -0.547350   
27 -0.424715 -0.491967 -0.551948 -0.559727 -0.507096 -0.512646   -0.476032   
28 -0.286889 -0.513054 -0.290689 -0.333885 -0.540019 -0.672474   -0.498278   
29 -0.280564 -0.425557 -0.574257 -0.451164 -0.350293 -0.518401   -0.466593   
30 -0.503383 -0.406358 -0.658284 -0.421655 -0.505737 -0.568946   -0.515255   
31 -0.565964 -0.268610 -0.480833 -0.518273 -0.303179 -0.455583   -0.565025   
32 -0.356089 -0.121127 -0.343315 -0.430668 -0.372841 -0.388778   -0.537607   
33 -0.259823 -0.173832 -0.244460 -0.248509 -0.577246 -0.308767   -0.374238   
34 -0.449066 -0.299757 -0.614879 -0.609666 -0.403638 -0.376681   -0.405016   
35 -0.271381 -0.363845 -0.578201 -0.328711 -0.563792 -0.414749   -0.370974   
36 -0.370990 -0.420868 -0.566988 -0.556192 -0.417874 -0.573427   -0.366075   
37 -0.413732 -0.411556 -0.453704 -0.473017 -0.600980 -0.443736   -0.319382   
38 -0.468329 -0.554480 -0.597489 -0.700745 -0.435196 -0.434604   -0.543098   
39 -0.256946 -0.130251 -0.251026 -0.377071 -0.580381 -0.389333   -0.261157   
40 -0.474925 -0.791606 -0.684428 -0.479777 -0.450933 -0.443824   -0.424816   
41 -0.387030 -0.646953 -0.428697 -0.450348 -0.386700 -0.383833   -0.618170   
42 -0.352520 -0.631703 -0.577317 -0.471784 -0.494927 -0.511371   -0.623693   
43 -0.497775 -0.563856 -0.500221 -0.431309 -0.560613 -0.451221   -0.540865   
44 -0.311749 -0.238074 -0.489227 -0.463905 -0.527454 -0.528306   -0.350893   
45 -0.359644 -0.446160 -0.586343 -0.515407 -0.603873 -0.349998   -0.519605   
46 -0.349015 -0.439374 -0.593329 -0.650240 -0.367803 -0.352609   -0.382669   
47 -0.272314 -0.509295 -0.616664 -0.408994 -0.495172 -0.496010   -0.373440   
48 -0.426067 -0.498002 -0.288485 -0.611042 -0.395109 -0.410075   -0.541505   
49 -0.339446 -0.193974 -0.603408 -0.513747 -0.468425 -0.435615   -0.413872   
50 -0.481539 -0.501090 -0.5

In [6]:
scaler = StandardScaler()

In [7]:
x_train = df_month.iloc[:42, :15]
x_train = scaler.fit_transform(x_train)
x_train

array([[-2.12958609e-01,  6.00802725e-01, -6.34893454e-01,
        -8.78737603e-01,  1.70152422e+00, -2.99629749e-01,
         8.08118252e-01, -1.93442811e-01,  4.18705284e-01,
        -1.04895146e+00,  2.03158100e-01, -2.28289458e+00,
         1.08891471e+00,  5.95663422e-01, -2.05353481e-02],
       [-1.15676189e+00,  2.20207748e-01, -4.40533780e-03,
         3.02713354e-02,  5.89122043e-02, -2.99629749e-01,
         8.08118252e-01, -1.93442811e-01,  6.91063508e-01,
        -1.04895146e+00,  2.03158100e-01,  1.25887151e+00,
        -5.68132731e-01,  5.95663422e-01, -8.36113034e-01],
       [ 3.05710219e-01,  1.26221948e+00,  3.09448555e-01,
         1.35980142e-01, -2.11850735e-01, -1.66471145e+00,
        -5.46692644e-01,  1.53708967e-01, -1.00936014e+00,
        -4.58785709e-01,  1.32088560e-02,  8.04986099e-01,
         7.76555646e-01, -1.53675773e+00,  4.52271179e-01],
       [-1.80808277e+00, -5.53409186e-01, -1.70144530e+00,
        -2.56642485e+00, -2.05732915e-01, -1.25249129

In [8]:
y_train = df.iloc[:42]['july']
y_train

0     0.04
1    -0.28
2    -0.25
3    -0.32
4    -0.30
5     0.72
6    -0.65
7     0.81
8     0.23
9    -0.10
10    0.31
11    0.10
12   -0.98
13   -0.64
14    0.83
15   -1.14
16   -0.65
17   -1.24
18    0.15
19    0.45
20   -0.48
21   -0.20
22    0.02
23   -0.43
24    0.64
25   -0.11
26   -0.40
27   -0.61
28    0.16
29    1.34
30   -1.54
31   -0.47
32    0.15
33    0.62
34    0.27
35    0.33
36    0.16
37    0.03
38   -0.14
39    1.60
40   -0.73
41   -0.84
Name: july, dtype: float64

In [9]:
x_test = df_month.iloc[43:, :15]
x_test = scaler.fit_transform(x_test)
x_test

array([[-1.50752145, -0.97137041, -0.18863529,  0.48478774, -0.88689176,
         0.0525772 , -1.30579234,  1.44118638, -0.88739356,  0.09049562,
        -1.63809368,  0.09795089, -0.29223134,  0.66050153, -0.65083045],
       [ 0.61317162,  1.34809689, -0.10153433,  0.1264471 , -0.54433976,
        -1.06878142,  1.54878631, -0.07678093, -1.37347906,  0.70463833,
         1.747676  , -0.83386268,  1.15406335,  0.28096751,  1.91073157],
       [ 0.06717257, -0.13340794, -0.87092413, -0.43973827, -1.33378676,
         1.5250869 , -0.98634227,  1.44061926,  1.01150555,  0.24004078,
        -0.21717499, -0.94413466, -0.38427723,  1.26996346,  0.54919854],
       [ 0.18834098, -0.08509921, -0.92626894, -1.92200503,  1.10492252,
         1.48710362,  1.0713107 ,  1.18042617,  0.52164405,  2.47547091,
        -1.33507657, -0.64463683,  0.49584133,  1.15866182, -0.5530387 ],
       [ 1.06273186, -0.58291436, -1.11114295,  0.73010375, -0.21085494,
        -0.5989677 ,  1.20999325, -0.16567843, 

In [10]:
y_test = df.iloc[43:]['july']
y_test

43    0.01
44    0.57
45    0.14
46    0.41
47   -0.01
48    0.03
49   -0.37
50   -0.04
51    0.69
52   -0.89
53   -0.23
54    0.44
55   -0.28
56    0.13
57    1.56
58   -0.25
Name: july, dtype: float64

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

# Assuming x_train and y_train are your training data
# Adjust this based on your actual data

# Define the parameter grid
param_grid = {
    'base_estimator__max_depth': range(1, 5),
    'n_estimators': range(1, 51)
}

# Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

# Create the GridSearchCV object
grid_search = GridSearchCV(bagging_reg, param_grid, cv=3, scoring='r2')

# Fit the grid search to the data
grid_search.fit(x_train, y_train)

# Get the best parameters and the corresponding score
best_params = grid_search.best_params_
best_score = grid_search.best_score_
best_max_depth = best_params['base_estimator__max_depth']
best_n_estimators = best_params['n_estimators']

print(f"Best Parameters: {best_params}")
print(f"Best Score: {best_score}")


Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 29}
Best Score: 0.17106399368326222


In [12]:
best_max_depth

3

In [13]:
best_n_estimators

29

In [14]:
def model_bag_reg(max_depth,n_estimators,x_test):
    regressor = BaggingRegressor(
          base_estimator=DecisionTreeRegressor(max_depth=max_depth),
          n_estimators=n_estimators,
          oob_score=True,
          random_state=0)
    regressor.fit(x_train,y_train)
    score = regressor.score(x_train,y_train)
    y_pred_br5 = regressor.predict(x_test)
    return score,y_pred_br5

In [15]:
score,pred_bag_reg_mean = model_bag_reg(best_max_depth,best_n_estimators,x_test)

In [16]:
pred_bag_reg_mean

array([-0.06729812, -0.03540631,  0.21821964,  0.37132422, -0.31430822,
       -0.07188911, -0.13628789, -0.26353826,  0.29098591, -0.33990184,
        0.31372608, -0.05696966, -0.08478758,  0.31701468,  0.00538507,
       -0.54407332])

In [17]:
corr_bag_reg_mean = np.corrcoef(pred_bag_reg_mean, y_test)
corr_bag_reg_mean

array([[1.        , 0.40111189],
       [0.40111189, 1.        ]])

# Random Forest

In [18]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

# Assuming x_train and y_train are your training data
# Adjust this based on your actual data

# Define the parameter grid
param_grid = {
    'n_estimators': range(1,51),  # Adjust as needed
    'max_depth': range(1,5),  # Adjust as needed

}

# Create the RandomForestRegressor
random_forest_reg = RandomForestRegressor(random_state=0)

# Create the GridSearchCV object
grid_search = GridSearchCV(random_forest_reg, param_grid, cv=3, scoring='r2')

# Fit the grid search to the data
grid_search.fit(x_train, y_train)

# Get the best parameters and the corresponding score
best_params = grid_search.best_params_
best_score = grid_search.best_score_

# Save the best values into separate variables
best_max_depth = best_params['max_depth']
best_n_estimators = best_params['n_estimators']

print(f"Best Parameters: {best_params}")
print(f"Best Score: {best_score}")
print(f"Best max_depth: {best_max_depth}")
print(f"Best n_estimators: {best_n_estimators}")


Best Parameters: {'max_depth': 4, 'n_estimators': 29}
Best Score: 0.18895972299475308
Best max_depth: 4
Best n_estimators: 29


In [19]:
def Randomforest(max_depth,n_estimators,x_test): 
    RF = RandomForestRegressor(
          n_estimators=n_estimators,
          max_depth=max_depth,
          
          random_state=0)
    RF.fit(x_train,y_train)
    score = RF.score(x_train,y_train)
    y_pred_rf = RF.predict(x_test)
    return score,y_pred_rf
    

In [20]:
score,pred_rf_mean = Randomforest(best_max_depth,best_n_estimators,x_test)

In [21]:
corr_rf_mean = np.corrcoef(pred_rf_mean, y_test)
corr_rf_mean

array([[1.       , 0.4493503],
       [0.4493503, 1.       ]])