In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("mutual_corr.csv")
df_month

July_4     May_5      July   April_8   April_2  October_5   April_3  \
0  -0.035646 -0.297254  0.116877 -0.752232  0.467579   0.015344 -0.128409   
1  -0.035646  0.289295  0.116877 -0.507175  0.775496   0.015344  0.076556   
2  -0.026609  0.332815 -0.525955 -0.538692  0.330257   0.084460 -0.179884   
3  -0.050294 -0.072422 -0.276801 -0.375539  0.499516   0.107016 -0.094489   
4  -0.240937  0.392898 -0.017141 -0.531919 -0.011843  -0.324095  0.035687   
5  -0.673967 -0.032447  0.584025 -0.546058 -0.034051   0.115252 -0.173557   
6  -0.101286  0.302982  0.393098 -0.596641 -0.170367   0.175994  0.003694   
7   0.113929 -0.081629  0.234448 -0.125865  0.007114   0.079383 -0.082095   
8   0.007671  0.329287  0.088683 -0.244421  0.747785  -0.114815 -0.060377   
9  -0.075417  0.353181  0.031045 -0.429741  0.263944  -0.074636 -0.193876   
10 -0.414009  0.422312  0.520458 -0.498900  0.135967   0.488424  0.032416   
11 -0.476931 -0.236341  0.645759 -0.414461  0.160935   0.078177 -0.022096   
12 -0.141292  0.156141  0.268169 -0.392599  0.216078   0.199450  0.142841   
13  0.009309  0.287421  0.396011  0.024898 -0.167336   0.199503 -0.351175   
14  0.015765  0.065102  0.492185 -0.491030  0.403210   0.557899 -0.183701   
15 -0.253378 -0.125724  0.265857  0.039972  0.726264   0.426828  0.106782   
16 -0.039817  0.167563 -0.148352  0.056228  0.111164   0.110905 -0.109959   
17 -0.141078  0.139540  0.514082 -0.041017  0.001393   0.570095 -0.151687   
18  0.301398  0.028532  0.142608 -0.177979  0.142326  -0.077855 -0.043509   
19  0.123009  0.151726  0.603538 -0.347884  0.179413   0.101712 -0.041355   
20 -0.537036  0.212023  0.354534 -0.211276  0.418707   0.473750 -0.208647   
21  0.104025 -0.089164  0.222823 -0.123577  0.986354   0.630519  0.315303   
22 -0.074388 -0.010611  0.233119 -0.612722  0.383087   0.741023 -0.185728   
23 -0.053541  0.302234 -0.180404 -0.697513  0.264723   0.962004 -0.155117   
24  0.074452  0.087091  0.419113 -0.441759  0.714488   0.293078  0.138616   
25 -0.027405 -0.272205 -0.045396 -0.035387  0.503581  -0.013222 -0.108965   
26  0.023711  0.246232  0.121770  0.015496  0.343440   0.922503 -0.095922   
27 -0.019547  0.255186 -0.076713 -0.069822  0.400664   0.186850 -0.038599   
28 -0.347454  0.122198  0.113812 -0.386288  0.656566   0.589664  0.045818   
29 -0.296243  0.020863  0.447997 -0.363607  0.702794   1.088789  0.048446   
30 -0.004430  0.115684 -0.196103  0.089110  0.172164   0.664266 -0.087027   
31 -0.415983  0.117840 -0.095913  0.100058  0.437272   0.475158 -0.256002   
32 -0.337284 -0.312472  0.541539 -0.280409  0.257934   0.561126 -0.003995   
33 -0.277968 -0.279961  0.262425 -0.449811  0.307677   0.118206  0.266497   
34 -0.492681 -0.056424  0.303647 -0.259469  1.107241   0.495091 -0.000007   
35 -0.684682  0.095439  0.206133 -0.031490  0.635085   0.554383  0.076354   
36 -0.766578 -0.082032  0.474627 -0.395775  0.701632   0.452623  0.176985   
37 -0.379983  0.016872 -0.058311 -0.228544  0.490319   0.202798  0.107429   
38 -0.266514  0.301422 -0.000772  0.192542  0.099627   0.423065  0.091680   
39 -0.390587  0.006721  0.283720 -0.197086  0.594530   0.427109  0.193127   
40 -0.182678 -0.490755  0.312771 -0.130963  0.349437   0.261970 -0.129364   
41 -0.199596  0.213295 -0.031607 -0.041727  0.384636   0.286708 -0.035210   
42 -0.128606  0.325479  0.263674  0.213278  0.428025   0.475872 -0.249665   
43 -0.166937  0.113373  0.097700 -0.280296  0.476748   0.402879  0.081163   
44 -0.338431 -0.124534  0.418517 -0.443991  0.633441   0.729512  0.085782   
45 -0.045586 -0.038363  0.495520 -0.456806  0.536105   0.340152  0.026338   
46 -0.256564  0.277222  0.261435 -0.387250  0.883645   0.300441  0.042672   
47 -0.142735 -0.146976  0.067377 -0.302033  0.897409   0.254045  0.244672   
48 -0.221568  0.109101  0.126139 -0.308201  0.201739   0.730296  0.026297   
49 -0.285513  0.182761  0.339477 -0.207096  0.105539  -0.047438 -0.103174   
50 -0.133723  0.057700  0.097000  0.119860  0.390515   0.417259 -0.200384   
51

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :20]
x_train = scaler.fit_transform(x_train)
x_train

array([[ 6.19362128e-01, -1.72256897e+00, -2.84325545e-01,
        -2.01425422e+00,  3.22546509e-01, -1.00524025e+00,
        -6.96083435e-01,  3.70542446e-01,  8.79202224e-01,
        -1.63413258e+00, -1.16668465e-02,  1.44714970e+00,
        -6.49861386e-01,  3.21303273e-01, -1.26697956e+00,
         5.79366520e-01, -1.02639822e+00, -2.03286668e+00,
        -7.03691586e-01,  1.40009568e-01],
       [ 6.19362128e-01,  1.00165398e+00, -2.84325545e-01,
        -9.85022860e-01,  1.38085309e+00, -1.00524025e+00,
         7.54595543e-01,  3.70542446e-01,  8.79202224e-01,
        -1.63413258e+00, -1.16668465e-02,  1.15737452e+00,
        -6.49861386e-01,  2.58345472e+00, -1.26697956e+00,
         5.79366520e-01, -9.85275215e-01, -2.03286668e+00,
         6.34560486e-01, -1.62190761e-01],
       [ 6.57336519e-01,  1.20378620e+00, -2.72172433e+00,
        -1.11739027e+00, -1.49428162e-01, -7.78811316e-01,
        -1.06040142e+00,  3.89974154e-01,  1.03864771e+00,
        -1.88163771e+00, -1.2

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] #df.iloc[43:]['avg']
    y_test.append(y_ts)

In [8]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [9]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

In [10]:
x_test = df_month.iloc[43:, :20]
x_test = scaler.fit_transform(x_test)
x_test

array([[-1.87616942e-01, -8.26992879e-02, -1.24748269e+00,
         4.66967512e-01, -9.98279173e-02, -7.99553785e-04,
         1.75649501e-02, -7.49518632e-02,  8.94785115e-01,
         6.87216605e-01,  2.05004660e-01,  4.80161439e-01,
         1.33246282e+00, -1.13547566e+00, -1.33232446e+00,
        -9.33084308e-01, -1.10077899e-01, -1.79804348e+00,
        -1.36675955e-01, -5.72956505e-01],
       [-1.09250919e+00, -1.40790969e+00,  3.27544864e-01,
        -3.06291619e-01,  3.18781632e-01,  1.44653626e+00,
         4.23951570e-02, -3.23710859e-02, -1.95008206e+00,
        -7.45427821e-01,  1.15946712e+00, -1.76269911e+00,
         9.86239715e-01, -1.13894920e-01,  2.79624620e-02,
         1.50755832e-01, -5.86062164e-01,  1.76511990e+00,
         9.52225878e-01, -2.76984792e-01],
       [ 4.52693685e-01, -9.27913142e-01,  7.05588723e-01,
        -3.66822860e-01,  5.87459726e-02, -2.78744500e-01,
        -2.77178737e-01, -2.44565772e-01,  2.77715515e-01,
         1.19933152e+00,  2.6

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 44}
Best Score: 0.1264871036024165
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 5}
Best Score: 0.20331514235732828
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 23}
Best Score: 0.1840199623166579
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 13}
Best Score: 0.18200461331314638
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 29}
Best Score: -0.025480908783441003


In [13]:
y_pred_list

[array([-0.05521844,  0.39466528, -0.03919192,  0.2010001 ,  0.06748359,
         0.25546713, -0.25834707, -0.32791119,  0.08129684, -0.43428118,
        -0.42127511,  0.10193245,  0.04700582, -0.06845715,  0.39093376,
         0.05072722]),
 array([ 0.09162857,  0.15448571,  0.15448571,  0.1776    ,  0.27259524,
         0.35413333, -0.292     , -0.044     ,  0.18912381, -0.40630476,
        -0.3567619 ,  0.33553333,  0.11685714, -0.17585714,  0.57712381,
         0.2422    ]),
 array([-0.00942837,  0.1729231 ,  0.02157753,  0.31893918, -0.01664457,
        -0.02327329, -0.29362893, -0.48229795,  0.05304449, -0.31522881,
        -0.40019685, -0.02116722,  0.0412906 ,  0.0138288 ,  0.19840489,
         0.09951695]),
 array([-0.11253609,  0.33081292,  0.05581301,  0.14954454, -0.1366843 ,
         0.07202411, -0.17187739, -0.31102536,  0.04372999, -0.15174968,
        -0.18892436, -0.0748019 ,  0.10893038,  0.03157637,  0.26452142,
         0.17849082]),
 array([-0.42774791,  0.38891572

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.8336951022555447,
 0.6317321878648421,
 0.6068402530674057,
 0.589993781996309,
 0.7249638919859415]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+sst/20 predictors/kendall/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'slp+sst (2001-2016) 20p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+sst/20 predictors/kendall/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+sst/20 predictors/kendall/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'slp+sst Predicted vs Actual 20p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+sst/20 predictors/kendall/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:
y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 44}
Best Score: 0.1264871036024165
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 5}
Best Score: 0.20331514235732828
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 23}
Best Score: 0.1840199623166579
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 13}
Best Score: 0.18200461331314638
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 29}
Best Score: -0.025480908783441003


In [21]:
y_pred_list_rf

[array([-0.05521844,  0.39466528, -0.03919192,  0.2010001 ,  0.06748359,
         0.25546713, -0.25834707, -0.32791119,  0.08129684, -0.43428118,
        -0.42127511,  0.10193245,  0.04700582, -0.06845715,  0.39093376,
         0.05072722]),
 array([ 0.09162857,  0.15448571,  0.15448571,  0.1776    ,  0.27259524,
         0.35413333, -0.292     , -0.044     ,  0.18912381, -0.40630476,
        -0.3567619 ,  0.33553333,  0.11685714, -0.17585714,  0.57712381,
         0.2422    ]),
 array([-0.00942837,  0.1729231 ,  0.02157753,  0.31893918, -0.01664457,
        -0.02327329, -0.29362893, -0.48229795,  0.05304449, -0.31522881,
        -0.40019685, -0.02116722,  0.0412906 ,  0.0138288 ,  0.19840489,
         0.09951695]),
 array([-0.11253609,  0.33081292,  0.05581301,  0.14954454, -0.1366843 ,
         0.07202411, -0.17187739, -0.31102536,  0.04372999, -0.15174968,
        -0.18892436, -0.0748019 ,  0.10893038,  0.03157637,  0.26452142,
         0.17849082]),
 array([-0.42774791,  0.38891572

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.8336951022555447,
 0.6317321878648421,
 0.6068402530674057,
 0.589993781996309,
 0.7249638919859415]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+sst/20 predictors/kendall/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'slp+sst (2001-2016) 20p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+sst/20 predictors/kendall/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+sst/20 predictors/kendall/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'slp+sst Predicted vs Actual 20p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+sst/20 predictors/kendall/comparison plots/randomforest
