In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("mutual_corr.csv")
df_month

August   April_6  November_9     May_4      July  December  August_6  \
0  -0.738326 -0.301980    0.069234 -0.771465 -0.282972 -0.717073 -0.281517   
1  -0.738326 -0.631036    0.069234 -0.693543 -0.282972 -0.717073 -0.281517   
2  -0.695796 -0.482993    0.096896 -0.833585  0.024735 -0.476478 -0.357975   
3  -0.947883 -0.013548    0.206812 -0.895129 -0.480516 -1.036485 -0.740435   
4  -0.607567 -0.535569    0.281363 -0.806471 -0.318698  0.073743 -0.751791   
5  -0.553747 -0.513097    0.328863 -0.686994 -0.451876 -0.387426 -0.617012   
6  -0.856548 -0.530454   -0.184806 -1.034953 -0.335775 -0.910498 -0.652016   
7  -0.195088 -0.596512    0.016471 -1.052326 -0.317907 -0.018828 -0.285899   
8  -0.644855 -0.643774   -0.164050 -1.066844 -0.228131  0.069151 -0.406965   
9  -0.980771 -0.561194    0.116569 -1.191484 -0.398887 -0.306188 -0.239752   
10 -0.649642  0.047388   -0.338679 -0.783846 -0.176470 -0.103149 -0.374419   
11 -0.869427 -0.295634   -0.305920 -0.780243 -0.612539 -0.394225 -0.216166   
12 -0.923796 -0.135304    0.374637 -0.874649 -0.349064 -0.256789 -0.142124   
13 -0.802844 -0.320404    0.626730 -0.763495 -0.358547 -0.175638 -0.345152   
14 -0.345760 -0.362342    0.089436 -0.661820 -0.608618  0.022039 -0.465585   
15 -0.842513 -0.259362    0.224387 -0.821221 -0.425789 -0.933287 -0.276291   
16 -0.929642 -0.208148    0.458070 -1.067972 -0.239326 -0.095038 -0.250753   
17 -0.613427 -0.234426    0.878477 -0.607790 -0.230007 -0.360705 -0.147925   
18 -0.637092 -0.302807    0.430257 -0.965550 -0.345586 -0.502902 -0.494739   
19 -0.505379 -0.130184    0.452508 -0.627250 -0.658500 -0.477501 -0.634594   
20 -0.937131 -0.030418    0.058221 -0.671692 -0.370724 -0.368491 -0.630319   
21 -0.817189 -0.573952    0.054164 -0.711322 -0.185867 -0.074160 -0.391357   
22 -0.815767 -0.070290   -0.096476 -1.311122  0.020546 -0.630909 -0.519670   
23 -0.815053 -0.224776    0.048739 -0.996655  0.008225 -0.681412 -0.068805   
24 -0.250273 -0.416928    0.208256 -0.785403 -0.432229 -0.209473 -0.502890   
25 -0.983868 -0.643155   -0.454533 -1.044103 -0.609283 -0.761062 -0.197076   
26 -1.031509 -0.359442   -0.197715 -0.744932 -0.353018 -0.607035 -0.149339   
27 -0.538390 -0.140792    0.531348 -0.689302 -0.438923 -0.472494 -0.390628   
28 -0.867833 -0.332336    0.414391 -1.189780 -0.219545  0.055753 -0.592950   
29 -0.413649 -0.251426    0.087649 -0.942845 -0.354293 -0.173729 -0.539136   
30 -1.248001 -0.416882    0.343072 -0.901456 -0.613108 -0.265459 -0.107957   
31 -0.835561 -0.396799    0.383450 -0.815414 -0.107483 -0.227913 -0.194243   
32 -0.834259 -0.631864   -0.168810 -1.157403 -0.222215 -0.976023 -0.256342   
33 -0.710545 -0.197668   -0.004256 -0.626331 -0.179417 -0.373498 -0.474330   
34 -0.493617 -0.355550   -0.268315 -1.136512 -0.663464 -0.753188 -0.308946   
35 -0.168705 -0.331555    0.002615 -0.943248 -0.378801 -0.460430 -0.338856   
36 -0.840497 -0.245685    0.089352 -1.178173 -0.150554 -0.293089 -0.391215   
37 -0.496251 -0.214843    0.058361 -0.913127 -0.000309 -0.255027 -0.766380   
38 -0.983520 -0.591013   -0.243122 -1.008284 -0.312259 -0.234846 -0.298268   
39 -0.172950 -0.755382   -0.042371 -0.842870 -0.487825 -0.068854 -0.252112   
40 -0.646220 -0.449251   -0.379949 -0.930208 -0.277241 -0.727007 -0.640345   
41 -0.915591 -0.639012    0.868201 -0.889877 -0.543093 -0.435933 -0.671405   
42 -0.671021 -0.030581    0.466853 -0.927800 -0.448426 -0.508981 -1.039283   
43 -0.402879 -0.475583    1.062395 -1.019033 -0.228014 -0.326749 -0.502407   
44 -0.341052 -0.927046    0.092848 -0.845561 -0.186894 -0.456510 -0.555655   
45 -0.445320 -0.643108    0.131427 -1.286470 -0.500198 -0.736443 -0.433960   
46 -0.582229  0.015050   -0.266698 -0.653631 -0.505696 -0.649792 -0.623650   
47 -0.424816 -0.663902   -0.108820 -1.028340 -0.029949 -1.081678 -0.689202   
48 -1.000447 -0.093196    0.126523 -1.073609 -0.382071 -0.520092 -0.223768   
49 -0.869858 -0.393340   -0.573848 -0.745181 -0.100789 -0.951528 -0.515654   
50 -1.127384 -0.175981    0.

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :5]
x_train = scaler.fit_transform(x_train)
x_train

array([[-0.10782168,  0.31344016, -0.16286179,  0.67237131,  0.27243368],
       [-0.10782168, -1.35442242, -0.16286179,  1.11113259,  0.27243368],
       [ 0.06492846, -0.60404901, -0.07322868,  0.3225832 ,  1.97868312],
       [-0.95900589,  1.77539741,  0.28294434, -0.02396281, -0.82295489],
       [ 0.4232996 , -0.87053832,  0.52451629,  0.47525555,  0.07433185],
       [ 0.64190888, -0.75663445,  0.67843583,  1.14801114, -0.66414663],
       [-0.58801849, -0.84461196, -0.98604984, -0.81128934, -0.02036168],
       [ 2.09872301, -1.17943487, -0.33383591, -0.90911375,  0.07871723],
       [ 0.2718425 , -1.41898731, -0.91879117, -0.99085819,  0.57652904],
       [-1.09259126, -1.0004221 , -0.00947774, -1.69268707, -0.37031928],
       [ 0.25239919,  2.08425808, -1.48465755,  0.60265353,  0.8629891 ],
       [-0.6403327 ,  0.3456056 , -1.37850509,  0.62294019, -1.5550317 ],
       [-0.86117074,  1.15826102,  0.82676139,  0.09135587, -0.09404736],
       [-0.36988234,  0.2200532 ,  1.6

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [8]:
x_test = df_month.iloc[43:, :5]
x_test = scaler.fit_transform(x_test)
x_test

array([[ 1.2110764 , -0.43350819,  2.5191267 , -0.82426347, -0.28693553],
       [ 1.41827358, -2.33016484,  0.27787584, -0.10098616, -0.09576099],
       [ 1.06884947, -1.13730397,  0.36705695, -1.93931743, -1.55235753],
       [ 0.61003692,  1.62770559, -0.55326813,  0.6992503 , -1.57791799],
       [ 1.13756046, -1.22466166, -0.18831095, -0.86306737,  0.63389703],
       [-0.79150174,  1.17295131,  0.35571943, -1.05181155, -1.00316987],
       [-0.35386805, -0.08799633, -1.26329194,  0.31754235,  0.30455057],
       [-1.21689321,  0.82516028,  0.53813133, -0.65091523,  0.79419711],
       [ 1.54417379,  0.02311008, -0.81533677,  0.92779076, -0.6207556 ],
       [-1.49011641,  0.56251422,  0.01176805,  1.58890076,  2.53053272],
       [-0.78246761, -0.34973935,  1.76285139,  0.262177  ,  0.53485342],
       [ 0.18511735,  1.07587339,  0.21214158,  0.47979202, -0.44408171],
       [-0.48980065, -0.69131809, -0.18373016,  1.76356252,  0.89325573],
       [-0.14228598, -0.09457562, -0.7

In [9]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] 
    y_test.append(y_ts)

In [10]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 22}
Best Score: 0.3681592000205466
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 14}
Best Score: 0.23618317294189534
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 7}
Best Score: 0.37542159624160787
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 22}
Best Score: 0.3388800250885568
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 50}
Best Score: 0.3298510440417763


In [13]:
y_pred_list

[array([ 0.74798128,  1.08715716,  0.81569663, -0.19674054,  0.86045312,
        -0.36606783, -0.23071808, -0.17779392,  1.00552756, -0.14955805,
        -0.64192574, -0.21610066, -0.0520511 , -0.19805709, -0.33783196,
        -0.09316651]),
 array([-0.15656179,  0.76220898,  0.44290719,  0.00142868,  0.55652028,
        -0.2650322 , -0.0871803 , -0.3837822 ,  0.70759787, -0.26598367,
        -0.74069898, -0.05027462, -0.03884697, -0.04561894, -0.314317  ,
        -0.09890033]),
 array([ 0.12904762,  0.93559524,  0.56077381,  0.32518537,  0.56077381,
        -0.41276164, -0.24295438, -0.37914599,  0.8237415 , -0.17680075,
        -0.60182116, -0.07130585, -0.06755472, -0.28315846, -0.24295438,
        -0.15805075]),
 array([ 0.9381657 ,  1.20152945,  0.74875246, -0.09863903,  0.81912566,
        -0.37397331, -0.17368058, -0.26398069,  1.15121885, -0.16812061,
        -0.65486414, -0.12760571,  0.02417002, -0.13976013, -0.34268466,
        -0.12208706]),
 array([ 1.13584108,  1.33611203

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.17070431696750438,
 0.3414758726249382,
 0.3210997730596614,
 0.16991313068858255,
 0.10746044382228119]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/5 predictors/kendall/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'AT+vwind (2001-2016) 5p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/5 predictors/kendall/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/5 predictors/kendall/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'AT+vwind Predicted vs Actual 5p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/5 predictors/kendall/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:

y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 22}
Best Score: 0.3681592000205466
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 14}
Best Score: 0.23618317294189534
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 7}
Best Score: 0.37542159624160787
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 22}
Best Score: 0.3388800250885568
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 50}
Best Score: 0.3298510440417763


In [21]:
y_pred_list_rf

[array([ 0.74798128,  1.08715716,  0.81569663, -0.19674054,  0.86045312,
        -0.36606783, -0.23071808, -0.17779392,  1.00552756, -0.14955805,
        -0.64192574, -0.21610066, -0.0520511 , -0.19805709, -0.33783196,
        -0.09316651]),
 array([-0.15656179,  0.76220898,  0.44290719,  0.00142868,  0.55652028,
        -0.2650322 , -0.0871803 , -0.3837822 ,  0.70759787, -0.26598367,
        -0.74069898, -0.05027462, -0.03884697, -0.04561894, -0.314317  ,
        -0.09890033]),
 array([ 0.12904762,  0.93559524,  0.56077381,  0.32518537,  0.56077381,
        -0.41276164, -0.24295438, -0.37914599,  0.8237415 , -0.17680075,
        -0.60182116, -0.07130585, -0.06755472, -0.28315846, -0.24295438,
        -0.15805075]),
 array([ 0.9381657 ,  1.20152945,  0.74875246, -0.09863903,  0.81912566,
        -0.37397331, -0.17368058, -0.26398069,  1.15121885, -0.16812061,
        -0.65486414, -0.12760571,  0.02417002, -0.13976013, -0.34268466,
        -0.12208706]),
 array([ 1.13584108,  1.33611203

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.17070431696750438,
 0.3414758726249382,
 0.3210997730596614,
 0.16991313068858255,
 0.10746044382228119]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/5 predictors/kendall/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'AT+vwind (2001-2016) 5p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/5 predictors/kendall/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/5 predictors/kendall/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'AT+vwind Predicted vs Actual 5p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'5p{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/5 predictors/kendall/comparison plots/randomforest
