In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("spearman_corr.csv")
df_month

August_3  November  November_3   March_3   April_2      July  August_2  \
0  -0.184693 -1.214892   -0.136173  0.014885 -0.653007 -0.164218  0.129304   
1  -0.184693 -1.214892   -0.136173 -0.009168 -0.907867 -0.164218  0.129304   
2  -0.868623 -1.081003    0.108331  0.113465 -0.791324  0.080121  0.263646   
3  -0.638803 -0.635890   -0.122380 -0.517431 -1.413735 -0.309253  0.093858   
4  -0.607522 -1.005138   -0.611427 -0.356117 -0.580686 -0.069573  0.676764   
5  -0.054206 -1.068305   -0.277523 -0.357794 -0.635126 -0.158134  0.548875   
6  -0.508316 -0.731337   -0.628275 -0.021923 -0.931604  0.113819  0.692267   
7  -0.210749 -1.387361   -0.114973 -0.213950 -0.576510 -0.410808 -0.099064   
8  -0.143427 -0.726642    0.293501 -0.846435 -0.251545 -0.247025  0.216196   
9  -0.238002 -1.174447   -0.018843 -0.532404 -0.933844 -0.025460  0.463331   
10 -0.429991 -0.670271    0.198077 -0.334520 -0.641796 -0.144258  0.692359   
11 -0.610245 -1.069782   -0.012159  0.204234 -0.671289 -0.299184 -0.002977   
12 -0.700056 -1.116879   -0.354435 -0.010904 -0.662611 -0.235598  0.718864   
13 -0.347165 -1.445867   -0.084961  0.013961 -1.522352 -0.176298  0.672098   
14 -0.291765 -0.802770   -0.252092 -0.094506 -0.876706 -0.072705  0.370919   
15 -0.250056 -1.571487   -0.350702  0.075048 -0.840241  0.098047  0.551728   
16 -0.766882 -1.263377   -0.083703  0.134561 -0.861421 -0.116093  0.547446   
17 -0.442839 -1.323865   -0.370886  0.037011 -1.261391  0.103842  0.043861   
18 -0.568356 -0.611949   -0.456529 -0.363193 -1.330379 -0.095381  0.579311   
19 -0.012688 -0.728484    0.015565 -0.152490 -0.609850  0.149429  0.437768   
20 -0.370367 -0.335074   -0.332858 -0.149210 -1.186382  0.266471  0.015488   
21 -0.313084 -0.898585    0.256552  0.125263 -0.757074 -0.096052  0.113251   
22  0.035354 -0.671149    0.168598 -0.244939 -0.929179 -0.098165 -0.135167   
23 -0.641326 -0.788098   -0.180514 -0.042712 -1.121083 -0.137716  1.102315   
24 -0.109967 -1.021461    0.256874 -0.201036 -0.641959 -0.170699  0.051115   
25 -0.281920 -1.583531    0.264522  0.122253 -0.783036 -0.007071  0.292573   
26 -0.526368 -0.766290   -0.073100  0.371928 -0.693648  0.257632  0.602277   
27 -0.322028 -1.362363    0.075626 -0.382245 -1.200400 -0.099545  0.105972   
28 -0.653181 -0.890509    0.055525 -0.358564 -0.908920 -0.159428  0.226919   
29  0.514767 -0.306353    0.411534 -0.216906 -0.974141 -0.267992  0.272224   
30 -0.529146 -1.082845   -0.181485 -0.314045 -1.192851  0.231383  0.744317   
31 -0.463989 -1.493175   -0.116002 -0.126009 -1.281334  0.418623  1.175177   
32 -0.299324 -1.006522   -0.132405 -0.513434 -0.386819 -0.035964  0.314160   
33  0.031223 -0.651608   -0.355521 -0.211687 -0.649596 -0.207801 -0.226839   
34 -0.397822 -0.336277    0.016238 -0.216981 -0.523960  0.137023  0.366309   
35  0.003421 -0.942377    0.265122 -0.216902 -0.719865 -0.295404  0.577917   
36  0.021890 -0.924365    0.195983 -0.351291 -0.755717  0.229772  0.158572   
37 -0.383311 -0.821479   -0.039877 -0.498756 -1.264500  0.028154  0.475374   
38 -0.316559 -1.127331   -0.214968 -0.177727 -1.081800  0.305908  0.906860   
39 -0.237813 -0.279633    0.394205 -0.544993 -0.645667 -0.586566  0.705498   
40 -0.315666 -1.014621   -0.362133  0.273304 -1.073101  0.184264  0.774074   
41 -0.508975 -1.926629   -0.005038 -0.048786 -1.411171 -0.021340  0.573104   
42  0.260668 -1.481841    0.118010 -0.158160 -1.228592 -0.116461 -0.387147   
43 -0.230796 -0.950949   -0.007947 -0.112331 -1.127126  0.230637  0.389005   
44  0.116478 -0.793945   -0.018967 -0.364338 -0.675230 -0.050802 -0.054906   
45  0.026354 -0.537465    0.041523 -0.000403 -0.902137  0.096135  0.235977   
46 -0.172852 -0.683440    0.369770 -0.330140 -1.261326  0.015129  0.009865   
47  0.178887 -0.853255    0.039464 -0.169150 -0.838592 -0.057228 -0.271827   
48 -0.304469 -0.886212   -0.340545 -0.554532 -1.206819  0.024225  0.122361   
49 -0.468586 -1.024624    0.057925 -0.170933 -0.945742  0.165056  0.979023   
50 -0.706236 -1.178582   -

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :5]
x_train = scaler.fit_transform(x_train)
x_train

array([[ 0.57931097, -0.65435752, -0.2529537 ,  0.74022016,  0.78540318],
       [ 0.57931097, -0.65435752, -0.2529537 ,  0.64393458, -0.08048112],
       [-2.0346281 , -0.28456113,  0.71256455,  1.13484488,  0.31547331],
       [-1.15626984,  0.94482318, -0.19848533, -1.39068898, -1.79916965],
       [-1.03671764, -0.07502531, -2.12967502, -0.74493435,  1.03111579],
       [ 1.07802598, -0.24948889, -0.81112901, -0.75164629,  0.84615472],
       [-0.65755475,  0.68120152, -2.19620771,  0.59287591, -0.16113051],
       [ 0.47972592, -1.13070995, -0.16923522, -0.17582716,  1.04530445],
       [ 0.73702653,  0.69416865,  1.44377933, -2.7077215 ,  2.14937371],
       [ 0.37556653, -0.54265091,  0.21036813, -1.45062835, -0.16873881],
       [-0.35820096,  0.84986418,  1.06696197, -0.65848108,  0.82349357],
       [-1.04712223, -0.25356887,  0.23676384,  1.49820121,  0.72329085],
       [-1.39037383, -0.38364846, -1.11484262,  0.63698389,  0.75277425],
       [-0.04164649, -1.29230056, -0.0

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [8]:
x_test = df_month.iloc[43:, :5]
x_test = scaler.fit_transform(x_test)
x_test

array([[-7.16388559e-03, -6.28562077e-01, -5.13741649e-02,
         4.60190969e-01, -2.88011871e-01],
       [ 1.24392774e+00, -9.10632370e-03, -1.08361743e-01,
        -6.94060975e-01,  1.51440288e+00],
       [ 9.19245682e-01,  1.00283320e+00,  2.04460336e-01,
         9.72849895e-01,  6.09367848e-01],
       [ 2.01587720e-01,  4.26893320e-01,  1.90198944e+00,
        -5.37426447e-01, -8.23274182e-01],
       [ 1.46876177e+00, -2.43111180e-01,  1.93811471e-01,
         1.99949255e-01,  8.62821503e-01],
       [-2.72575431e-01, -3.73143217e-01, -1.77140590e+00,
        -1.56519321e+00, -6.05870166e-01],
       [-8.63824785e-01, -9.19245491e-01,  2.89285955e-01,
         1.91780921e-01,  4.35448227e-01],
       [-1.71998173e+00, -1.52668714e+00, -4.87288035e-01,
         9.41984863e-02, -4.00539673e-01],
       [ 2.45190590e-01,  6.77139183e-02, -9.24430396e-01,
        -1.40710193e+00, -1.79121466e-01],
       [-5.49967087e-01,  2.40179856e+00, -4.86750736e-01,
         5.03853097e-01

In [9]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] 
    y_test.append(y_ts)

In [10]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 15}
Best Score: 0.2932883112885537
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 31}
Best Score: 0.17387935037721786
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 25}
Best Score: 0.4324100996064929
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 20}
Best Score: 0.2736119692134669
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 45}
Best Score: 0.22275660201151476


In [13]:
y_pred_list

[array([-0.45170038,  0.39726171,  0.26411016,  0.44024266,  0.39726171,
        -0.48427512, -0.27585477, -0.54637163, -0.02281384, -0.14495632,
        -0.13901417, -0.56336254,  0.06489437, -0.04712059,  0.7285913 ,
        -0.35357274]),
 array([-0.3411891 ,  0.29734319,  0.31058433,  0.43856108,  0.31663352,
        -0.36467702, -0.47105418, -0.6162285 ,  0.1089172 , -0.1826479 ,
        -0.18625568, -0.52562959,  0.05298244, -0.08048889,  0.74941033,
        -0.18660387]),
 array([-0.393111  ,  0.43340073,  0.0845449 ,  0.26779807,  0.31903854,
        -0.54418824, -0.35015736, -0.62253756,  0.03733686, -0.10352152,
        -0.23355551, -0.62139165,  0.050721  ,  0.04454239,  0.63198145,
        -0.385849  ]),
 array([-0.49471661,  0.3000566 ,  0.20572256,  0.13491921,  0.30140725,
        -0.58405136, -0.01229345, -0.37565042, -0.11081033, -0.13434957,
         0.06840811, -0.56952052,  0.00348374,  0.04826287,  0.30857543,
        -0.1399862 ]),
 array([-0.50236631,  0.41343203

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.5326479936169956,
 0.6242212807060787,
 0.5168130059571908,
 0.17413512452037958,
 0.45134167404131625]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/5 predictors/spearson/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'hgt+vwind (2001-2016) 5p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/5 predictors/spearson/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/5 predictors/spearson/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'hgt+vwind Predicted vs Actual 5p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/5 predictors/spearson/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:

y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 15}
Best Score: 0.2932883112885537
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 31}
Best Score: 0.17387935037721786
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 25}
Best Score: 0.4324100996064929
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 20}
Best Score: 0.2736119692134669
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 45}
Best Score: 0.22275660201151476


In [21]:
y_pred_list_rf

[array([-0.45170038,  0.39726171,  0.26411016,  0.44024266,  0.39726171,
        -0.48427512, -0.27585477, -0.54637163, -0.02281384, -0.14495632,
        -0.13901417, -0.56336254,  0.06489437, -0.04712059,  0.7285913 ,
        -0.35357274]),
 array([-0.3411891 ,  0.29734319,  0.31058433,  0.43856108,  0.31663352,
        -0.36467702, -0.47105418, -0.6162285 ,  0.1089172 , -0.1826479 ,
        -0.18625568, -0.52562959,  0.05298244, -0.08048889,  0.74941033,
        -0.18660387]),
 array([-0.393111  ,  0.43340073,  0.0845449 ,  0.26779807,  0.31903854,
        -0.54418824, -0.35015736, -0.62253756,  0.03733686, -0.10352152,
        -0.23355551, -0.62139165,  0.050721  ,  0.04454239,  0.63198145,
        -0.385849  ]),
 array([-0.49471661,  0.3000566 ,  0.20572256,  0.13491921,  0.30140725,
        -0.58405136, -0.01229345, -0.37565042, -0.11081033, -0.13434957,
         0.06840811, -0.56952052,  0.00348374,  0.04826287,  0.30857543,
        -0.1399862 ]),
 array([-0.50236631,  0.41343203

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.5326479936169956,
 0.6242212807060787,
 0.5168130059571908,
 0.17413512452037958,
 0.45134167404131625]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/5 predictors/spearson/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'hgt+vwind (2001-2016) 5p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/5 predictors/spearson/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/5 predictors/spearson/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'hgt+vwind Predicted vs Actual 5p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'5p{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/5 predictors/spearson/comparison plots/randomforest
