In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("mutual_corr.csv")
df_month

March_3     March  November_2  January_3  August_4  November_4     May_6  \
0   0.014885 -0.336650    0.478814  -0.046796 -0.087428   -0.136173 -0.264519   
1  -0.009168 -0.359282    0.478814   0.376407 -0.087428   -0.136173 -0.858258   
2   0.113465 -0.540676    0.609518  -0.177302 -0.059203    0.108331 -0.420201   
3  -0.517431 -0.498272    0.651053   0.154934 -0.051693   -0.122380 -0.371818   
4  -0.356117 -0.480834    1.195737   0.334612  0.404268   -0.611427  0.097631   
5  -0.357794  0.072213    0.129159   0.137515  0.448407   -0.277523 -0.013927   
6  -0.021923 -0.236433    0.309408  -0.403897  0.021571   -0.628275  0.171641   
7  -0.213950 -0.597791    0.140510   0.144941  0.443615   -0.114973 -0.410507   
8  -0.846435 -0.287527    0.138254  -0.126336 -0.076138    0.293501  0.267087   
9  -0.532404 -0.252568   -0.311381  -0.422571 -0.006048   -0.018843 -0.345718   
10 -0.334520 -0.355274   -0.221253  -0.405356  0.150326    0.198077 -0.270532   
11  0.204234 -0.153002    0.309413  -0.438999  0.114766   -0.012159 -0.370606   
12 -0.010904 -0.434107    0.423102   0.127220  0.325412   -0.354435 -0.093952   
13  0.013961 -0.084185    0.099336   0.412428  0.408880   -0.084961 -0.089826   
14 -0.094506 -0.153331    0.415620  -0.323726  0.525274   -0.252092 -0.306745   
15  0.075048 -0.233555    0.229275  -0.558173 -0.238353   -0.350702 -0.343318   
16  0.134561 -0.039769    0.164057  -0.056200  0.793408   -0.083703 -0.418931   
17  0.037011 -0.392955    0.499572  -0.224714 -0.007057   -0.370886 -0.599770   
18 -0.363193 -0.166312    0.342208  -0.486402  0.769874   -0.456529 -0.202193   
19 -0.152490  0.224791   -0.267592  -0.425800  0.504096    0.015565 -0.363640   
20 -0.149210 -0.287582   -0.015458  -0.012468 -0.305708   -0.332858 -0.585554   
21  0.125263 -0.351822    0.128489  -0.160435  0.423542    0.256552  0.134893   
22 -0.244939 -0.363617    0.188147  -0.059069 -0.066471    0.168598 -0.631479   
23 -0.042712 -0.021218    0.640512  -0.488872  0.386813   -0.180514 -0.345763   
24 -0.201036 -0.472556    0.378015   0.067025  0.063782    0.256874 -0.306790   
25  0.122253 -0.396873    0.168173  -0.205793 -0.048762    0.264522 -0.467803   
26  0.371928 -0.191383    1.233682  -0.329697  0.017582   -0.073100 -0.095201   
27 -0.382245  0.157575    0.678552  -0.223643  0.451768    0.075626 -0.527867   
28 -0.358564 -0.206922   -0.088136  -0.083629  0.180413    0.055525 -0.214247   
29 -0.216906 -0.358613   -0.085844  -0.194392 -0.048897    0.411534  0.352406   
30 -0.314045 -0.086209    0.855351  -0.101502 -0.339253   -0.181485 -0.809045   
31 -0.126009 -0.334650    1.152494  -0.426113  0.106895   -0.116002 -0.114240   
32 -0.513434 -0.320224    0.248117  -0.321832  0.103466   -0.132405 -0.601705   
33 -0.211687 -0.105944    0.961680   0.102700  0.066080   -0.355521  0.134503   
34 -0.216981 -0.470358   -0.103037  -0.184851  0.175227    0.016238  0.373092   
35 -0.216902 -0.148703   -0.132525  -0.371158  0.279097    0.265122 -1.456413   
36 -0.351291 -0.023075    0.284410   0.139344  0.239618    0.195983 -0.410594   
37 -0.498756 -0.210893    0.490220  -0.232818  0.130866   -0.039877 -0.198262   
38 -0.177727 -0.140516    0.545439  -0.092860  0.226443   -0.214968 -0.641935   
39 -0.544993 -0.334307   -0.536067   0.093295 -0.011137    0.394205 -0.537215   
40  0.273304 -0.103636    0.723163  -0.060748  0.028100   -0.362133 -0.012527   
41 -0.048786  0.004962    0.741242  -0.265228 -0.172678   -0.005038 -1.006054   
42 -0.158160 -0.386721    0.436696  -0.304663  0.431884    0.118010 -0.127673   
43 -0.112331 -0.075147    0.099948  -0.271740  0.536066   -0.007947 -0.487976   
44 -0.364338 -0.111786    0.804307   0.006992  0.060991   -0.018967 -1.351491   
45 -0.000403 -0.301264    0.286930  -0.008776 -0.073329    0.041523 -0.251851   
46 -0.330140 -0.141412    0.307944   0.138428  0.246638    0.369770 -0.245896   
47 -0.169150 -0.300924    0.299752  -0.187715  0.155532    0.039464 -0.874516   
48 -0.554532  0.217060    0.370609  

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :5]
x_train = scaler.fit_transform(x_train)
x_train

array([[ 0.74022016, -0.52338235,  0.34578166,  0.37664201, -0.89669596],
       [ 0.64393458, -0.64570411,  0.34578166,  2.11301158, -0.89669596],
       [ 1.13484488, -1.62608255,  0.67081796, -0.15881652, -0.78883745],
       [-1.39068898, -1.3969013 ,  0.77410672,  1.20432571, -0.76013654],
       [-0.74493435, -1.30265251,  2.12863387,  1.94152934,  0.98227758],
       [-0.75164629,  1.68639892, -0.52374418,  1.13285386,  1.15094882],
       [ 0.59287591,  0.01826215, -0.07549938, -1.08851678, -0.48016656],
       [-0.17582716, -1.93476905, -0.4955166 ,  1.16332129,  1.13263774],
       [-2.7077215 , -0.2578863 , -0.50112623,  0.05029591, -0.85355031],
       [-1.45062835, -0.06894568, -1.61928343, -1.16513316, -0.58570894],
       [-0.65848108, -0.62404034, -1.39515166, -1.0945037 ,  0.01186145],
       [ 1.49820121,  0.46918131, -0.0754852 , -1.2325376 , -0.1240281 ],
       [ 0.63698389, -1.05010806,  0.2072361 ,  1.09061699,  0.68093524],
       [ 0.73652089,  0.84111474, -0.5

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [8]:
x_test = df_month.iloc[43:, :5]
x_test = scaler.fit_transform(x_test)
x_test

array([[ 0.46019097,  0.76518399, -1.19495543, -0.67912407,  2.37792699],
       [-0.69406097,  0.59306736,  0.70576748,  1.03246434,  0.54444572],
       [ 0.97284989, -0.29704056, -0.69038146,  0.9356416 ,  0.02605507],
       [-0.53742645,  0.453894  , -0.63367476,  1.83956438,  1.26092271],
       [ 0.19994926, -0.29544147, -0.6557819 , -0.16315533,  0.90931263],
       [-1.56519321,  2.13787994, -0.4645728 , -1.97436685, -0.98253358],
       [ 0.19178092, -0.25754225, -1.42489249,  0.15226225, -0.31246118],
       [ 0.09419849, -1.38884701,  0.95251157,  0.42954825, -0.66125602],
       [-1.40710193,  0.17667894,  1.11890922,  1.42366693,  1.31432089],
       [ 0.5038531 ,  1.35860909, -0.46337779, -0.428629  , -0.88914529],
       [-1.03118959, -0.26402288,  1.414144  ,  0.43961473, -0.1626264 ],
       [-0.31376891,  0.52154821,  1.12226679, -1.74050147, -0.78472905],
       [ 1.65051635,  0.29452837, -1.59689318, -0.70657051,  0.02047144],
       [-0.49317978, -2.03773765,  0.2

In [9]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] 
    y_test.append(y_ts)

In [10]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 3}
Best Score: 0.03673476815548399
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 6}
Best Score: -0.061481917327499025
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 22}
Best Score: 0.10621459382403403
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 7}
Best Score: 0.036303732784010945
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 50}
Best Score: -0.24684846532022042


In [13]:
y_pred_list

[array([ 0.07033868, -0.29888808,  0.07033868,  0.07033868,  0.07033868,
         0.69568956,  0.07033868, -0.29888808, -0.29888808,  0.07033868,
        -0.29888808, -0.29888808,  0.07033868, -0.29888808,  0.07033868,
        -0.74979284]),
 array([ 0.25052704, -0.32632431, -0.00082481, -0.00082481, -0.00082481,
         0.22097344,  0.25052704, -0.32632431, -0.32632431, -0.00082481,
        -0.32632431, -0.32632431,  0.25052704, -0.00082481, -0.00082481,
        -0.53613383]),
 array([-0.12366365, -0.06539515, -0.12366365,  0.21093895,  0.03805464,
         0.22083046,  0.03805464, -0.23827947, -0.06539515, -0.19499223,
        -0.06539515, -0.06539515, -0.12366365,  0.04623001,  0.09458228,
        -0.57069282]),
 array([ 0.12869721, -0.27626204,  0.12869721,  0.12869721,  0.12869721,
         0.42809571,  0.12869721, -0.27626204, -0.27626204,  0.12869721,
        -0.27626204, -0.27626204,  0.12869721, -0.03685224,  0.12869721,
        -0.48507837]),
 array([ 0.09412186, -0.15505622

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.048477740603930224,
 -0.14152583381215636,
 0.3846183795673681,
 0.04128590657587574,
 0.09888098706922092]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/5 predictors/kendall/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'hgt+vwind (2001-2016) 5p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/5 predictors/kendall/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/5 predictors/kendall/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'hgt+vwind Predicted vs Actual 5p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/5 predictors/kendall/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:

y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 3}
Best Score: 0.03673476815548399
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 6}
Best Score: -0.061481917327499025
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 22}
Best Score: 0.10621459382403403
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 7}
Best Score: 0.036303732784010945
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 50}
Best Score: -0.24684846532022042


In [21]:
y_pred_list_rf

[array([ 0.07033868, -0.29888808,  0.07033868,  0.07033868,  0.07033868,
         0.69568956,  0.07033868, -0.29888808, -0.29888808,  0.07033868,
        -0.29888808, -0.29888808,  0.07033868, -0.29888808,  0.07033868,
        -0.74979284]),
 array([ 0.25052704, -0.32632431, -0.00082481, -0.00082481, -0.00082481,
         0.22097344,  0.25052704, -0.32632431, -0.32632431, -0.00082481,
        -0.32632431, -0.32632431,  0.25052704, -0.00082481, -0.00082481,
        -0.53613383]),
 array([-0.12366365, -0.06539515, -0.12366365,  0.21093895,  0.03805464,
         0.22083046,  0.03805464, -0.23827947, -0.06539515, -0.19499223,
        -0.06539515, -0.06539515, -0.12366365,  0.04623001,  0.09458228,
        -0.57069282]),
 array([ 0.12869721, -0.27626204,  0.12869721,  0.12869721,  0.12869721,
         0.42809571,  0.12869721, -0.27626204, -0.27626204,  0.12869721,
        -0.27626204, -0.27626204,  0.12869721, -0.03685224,  0.12869721,
        -0.48507837]),
 array([ 0.09412186, -0.15505622

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.048477740603930224,
 -0.14152583381215636,
 0.3846183795673681,
 0.04128590657587574,
 0.09888098706922092]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/5 predictors/kendall/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'hgt+vwind (2001-2016) 5p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/5 predictors/kendall/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/5 predictors/kendall/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'hgt+vwind Predicted vs Actual 5p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'5p{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/5 predictors/kendall/comparison plots/randomforest
