In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df['avg'] = df[['june', 'july', 'august', 'september']].mean(axis=1)

In [4]:
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [5]:
df_month = pd.read_csv("kendall_corr.csv")
df_month

April_6   April_3   April_4  April_11  January_5    July_6     May_7  \
0  -0.431286 -0.340860 -0.549567 -0.267017  -0.450133 -0.497566 -0.688259   
1  -0.533980 -0.399154 -0.455645 -0.424836  -0.419021 -0.497566 -0.364926   
2  -0.374850 -0.239554 -0.408891 -0.450850  -0.613263 -0.614742 -0.406362   
3  -0.604850 -0.517645 -0.708450 -0.450262  -0.483421 -0.579358 -0.486260   
4  -0.219154 -0.391761 -0.215144 -0.520404  -0.433390 -0.524663 -0.504949   
5  -0.502544 -0.270182 -0.328922 -0.521861  -0.492438 -0.472274 -0.450861   
6  -0.497069 -0.552591 -0.420962 -0.293576  -0.529186 -0.481949 -0.355995   
7  -0.394057 -0.294222 -0.369803 -0.353479  -0.447394 -0.209288 -0.554734   
8  -0.557030 -0.404795 -0.537414 -0.198219  -0.412634 -0.428058 -0.379854   
9  -0.284371 -0.300480 -0.369547 -0.540177  -0.324414 -0.468773 -0.458690   
10 -0.348182 -0.543712 -0.357692 -0.510692  -0.489001 -0.357153 -0.427739   
11 -0.192281 -0.368806 -0.315139 -0.455138  -0.443705 -0.406740 -0.582050   
12 -0.572110 -0.487405 -0.428276 -0.413038  -0.422745 -0.454944 -0.476350   
13 -0.423295 -0.512052 -0.399894 -0.289887  -0.373536 -0.493929 -0.368346   
14 -0.415653 -0.388512 -0.168685 -0.495303  -0.706897 -0.429653 -0.393799   
15 -0.578203 -0.714446 -0.751165 -0.280174  -0.286286 -0.503611 -0.565243   
16 -0.374572 -0.506431 -0.554055 -0.463900  -0.524383 -0.513313 -0.335414   
17 -0.500755 -0.548926 -0.584862 -0.325171  -0.376304 -0.592881 -0.370739   
18 -0.305194 -0.440616 -0.383723 -0.553981  -0.463494 -0.399561 -0.299535   
19 -0.406520 -0.432716 -0.077767 -0.409111  -0.613474 -0.422900 -0.372787   
20 -0.396659 -0.560590 -0.387925 -0.423366  -0.365495 -0.525276 -0.491119   
21 -0.441504 -0.548319 -0.423060 -0.490486  -0.751865 -0.618296 -0.710004   
22 -0.551280 -0.232324 -0.658006 -0.327259  -0.568383 -0.520815 -0.568226   
23 -0.362009 -0.525662 -0.471235 -0.372504  -0.226881 -0.496582 -0.536084   
24 -0.235150 -0.444678 -0.442271 -0.477313  -0.638702 -0.457584 -0.581931   
25 -0.548240 -0.805514 -0.591371 -0.434629  -0.530165 -0.448200 -0.521078   
26 -0.320183 -0.389276 -0.430851 -0.342292  -0.483120 -0.516112 -0.449420   
27 -0.424715 -0.491967 -0.551948 -0.507096  -0.604644 -0.512646 -0.423059   
28 -0.286889 -0.513054 -0.290689 -0.540019  -0.438223 -0.672474 -0.442319   
29 -0.280564 -0.425557 -0.574257 -0.350293  -0.412772 -0.518401 -0.604953   
30 -0.503383 -0.406358 -0.658284 -0.505737  -0.358153 -0.568946 -0.575528   
31 -0.565964 -0.268610 -0.480833 -0.303179  -0.536777 -0.455583 -0.467969   
32 -0.356089 -0.121127 -0.343315 -0.372841  -0.656930 -0.388778 -0.433157   
33 -0.259823 -0.173832 -0.244460 -0.577246  -0.717204 -0.308767 -0.504662   
34 -0.449066 -0.299757 -0.614879 -0.403638  -0.562708 -0.376681 -0.559778   
35 -0.271381 -0.363845 -0.578201 -0.563792  -0.595244 -0.414749 -0.531263   
36 -0.370990 -0.420868 -0.566988 -0.417874  -0.528754 -0.573427 -0.490945   
37 -0.413732 -0.411556 -0.453704 -0.600980  -0.625593 -0.443736 -0.548340   
38 -0.468329 -0.554480 -0.597489 -0.435196  -0.436125 -0.434604 -0.489142   
39 -0.256946 -0.130251 -0.251026 -0.580381  -0.507471 -0.389333 -0.527738   
40 -0.474925 -0.791606 -0.684428 -0.450933  -0.570711 -0.443824 -0.485118   
41 -0.387030 -0.646953 -0.428697 -0.386700  -0.493381 -0.383833 -0.368973   
42 -0.352520 -0.631703 -0.577317 -0.494927  -0.659179 -0.511371 -0.438639   
43 -0.497775 -0.563856 -0.500221 -0.560613  -0.608725 -0.451221 -0.458401   
44 -0.311749 -0.238074 -0.489227 -0.527454  -0.655265 -0.528306 -0.565323   
45 -0.359644 -0.446160 -0.586343 -0.603873  -0.426915 -0.349998 -0.577977   
46 -0.349015 -0.439374 -0.593329 -0.367803  -0.473817 -0.352609 -0.543610   
47 -0.272314 -0.509295 -0.616664 -0.495172  -0.349833 -0.496010 -0.580490   
48 -0.426067 -0.498002 -0.288485 -0.395109  -0.466432 -0.410075 -0.516813   
49 -0.339446 -0.193974 -0.603408 -0.468425  -0.461556 -0.435615 -0.428402   
50 -0.481539 -0.501090 -0.519775 -0.511671  -0.475970 -0.373548 -0.430166   
5

In [6]:
scaler = StandardScaler()

In [7]:
x_train = df_month.iloc[:42, :5]
x_train = scaler.fit_transform(x_train)
x_train

array([[-2.12958609e-01,  6.00802725e-01, -6.34893454e-01,
         1.70152422e+00,  4.18705284e-01],
       [-1.15676189e+00,  2.20207748e-01, -4.40533780e-03,
         5.89122043e-02,  6.91063508e-01],
       [ 3.05710219e-01,  1.26221948e+00,  3.09448555e-01,
        -2.11850735e-01, -1.00936014e+00],
       [-1.80808277e+00, -5.53409186e-01, -1.70144530e+00,
        -2.05732915e-01,  1.27296319e-01],
       [ 1.73662680e+00,  2.68472572e-01,  1.61003853e+00,
        -9.35775587e-01,  5.65273437e-01],
       [-8.67846524e-01,  1.06225322e+00,  8.46265460e-01,
        -9.50941461e-01,  4.83591653e-02],
       [-8.17526213e-01, -7.81566938e-01,  2.28417153e-01,
         1.42508688e+00, -2.73336076e-01],
       [ 1.29196211e-01,  9.05296406e-01,  5.71839072e-01,
         8.01610266e-01,  4.42679601e-01],
       [-1.36859862e+00,  1.83375189e-01, -5.53309471e-01,
         2.41758640e+00,  7.46975077e-01],
       [ 1.13725434e+00,  8.64440554e-01,  5.73553024e-01,
        -1.14157935e+00

In [8]:
y_train = df.iloc[:42]['april']
y_train

0     0.31
1     0.27
2     0.01
3     0.13
4    -0.32
5    -0.06
6    -0.53
7    -0.09
8     0.54
9    -0.53
10   -0.47
11    0.33
12    0.18
13   -0.97
14    0.21
15   -0.07
16   -1.00
17   -0.59
18   -0.42
19   -0.25
20   -0.37
21    0.17
22    0.20
23   -0.17
24    0.24
25    1.12
26   -0.60
27   -0.98
28   -0.41
29    0.89
30   -0.49
31   -1.11
32    0.26
33    0.21
34    1.41
35    0.92
36    0.03
37    0.27
38   -0.34
39    0.34
40    0.90
41   -0.81
Name: april, dtype: float64

In [9]:
x_test = df_month.iloc[43:, :5]
x_test = scaler.fit_transform(x_test)
x_test

array([[-1.50752145, -0.97137041, -0.18863529, -0.88689176, -0.88739356],
       [ 0.61317162,  1.34809689, -0.10153433, -0.54433976, -1.37347906],
       [ 0.06717257, -0.13340794, -0.87092413, -1.33378676,  1.01150555],
       [ 0.18834098, -0.08509921, -0.92626894,  1.10492252,  0.52164405],
       [ 1.06273186, -0.58291436, -1.11114295, -0.21085494,  1.81658855],
       [-0.69004902, -0.50250977,  1.48881294,  0.82283814,  0.59877628],
       [ 0.29743235,  1.66207329, -1.00612146,  0.06545441,  0.64970363],
       [-1.32242578, -0.5244943 , -0.34355107, -0.38129901,  0.49916081],
       [-0.29567949,  0.40290765,  1.53662667,  0.25302898, -0.19890582],
       [-0.97729913,  0.08958122, -0.11214297,  0.70031151, -0.08360272],
       [ 1.11210829,  2.13196178,  0.86584276,  1.43572322,  1.12523446],
       [ 0.01728153, -1.04104588,  0.53972691, -0.37173569, -1.95192801],
       [ 0.66451838, -0.6622124 ,  0.14420236,  1.67152009, -0.82287523],
       [ 2.33253795,  0.57369338,  2.0

In [10]:
y_test = df.iloc[43:]['april']
y_test

43   -0.30
44    0.14
45   -0.03
46    0.06
47    0.28
48   -0.30
49   -0.16
50   -0.89
51   -0.25
52    0.56
53   -0.74
54   -0.29
55   -0.08
56    0.28
57    0.90
58    1.05
Name: april, dtype: float64

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

# Assuming x_train and y_train are your training data
# Adjust this based on your actual data

# Define the parameter grid
param_grid = {
    'base_estimator__max_depth': range(1, 5),
    'n_estimators': range(1, 51)
}

# Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

# Create the GridSearchCV object
grid_search = GridSearchCV(bagging_reg, param_grid, cv=3, scoring='r2')

# Fit the grid search to the data
grid_search.fit(x_train, y_train)

# Get the best parameters and the corresponding score
best_params = grid_search.best_params_
best_score = grid_search.best_score_
best_max_depth = best_params['base_estimator__max_depth']
best_n_estimators = best_params['n_estimators']

print(f"Best Parameters: {best_params}")
print(f"Best Score: {best_score}")


Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 5}
Best Score: -0.06259685433566105


In [12]:
best_max_depth

1

In [13]:
best_n_estimators

5

In [14]:
def model_bag_reg(max_depth,n_estimators,x_test):
    regressor = BaggingRegressor(
          base_estimator=DecisionTreeRegressor(max_depth=max_depth),
          n_estimators=n_estimators,
          oob_score=True,
          random_state=0)
    regressor.fit(x_train,y_train)
    score = regressor.score(x_train,y_train)
    y_pred_br5 = regressor.predict(x_test)
    return score,y_pred_br5

In [15]:
score,pred_bag_reg_mean = model_bag_reg(best_max_depth,best_n_estimators,x_test)

In [16]:
pred_bag_reg_mean

array([-0.14794055,  0.06190627,  0.12598557, -0.00294373, -0.11597805,
       -0.27114055, -0.00294373, -0.27114055, -0.15810623, -0.15810623,
       -0.15810623, -0.05112805, -0.14794055,  0.19083557, -0.15810623,
       -0.11597805])

In [17]:
corr_bag_reg_mean = np.corrcoef(pred_bag_reg_mean, y_test)
corr_bag_reg_mean

array([[1.        , 0.23712825],
       [0.23712825, 1.        ]])

# Random Forest

In [18]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

# Assuming x_train and y_train are your training data
# Adjust this based on your actual data

# Define the parameter grid
param_grid = {
    'n_estimators': range(1,51),  # Adjust as needed
    'max_depth': range(1,5),  # Adjust as needed

}

# Create the RandomForestRegressor
random_forest_reg = RandomForestRegressor(random_state=0)

# Create the GridSearchCV object
grid_search = GridSearchCV(random_forest_reg, param_grid, cv=3, scoring='r2')

# Fit the grid search to the data
grid_search.fit(x_train, y_train)

# Get the best parameters and the corresponding score
best_params = grid_search.best_params_
best_score = grid_search.best_score_

# Save the best values into separate variables
best_max_depth = best_params['max_depth']
best_n_estimators = best_params['n_estimators']

print(f"Best Parameters: {best_params}")
print(f"Best Score: {best_score}")
print(f"Best max_depth: {best_max_depth}")
print(f"Best n_estimators: {best_n_estimators}")


Best Parameters: {'max_depth': 1, 'n_estimators': 5}
Best Score: -0.06259685433566098
Best max_depth: 1
Best n_estimators: 5


In [19]:
def Randomforest(max_depth,n_estimators,x_test): 
    RF = RandomForestRegressor(
          n_estimators=n_estimators,
          max_depth=max_depth,
          
          random_state=0)
    RF.fit(x_train,y_train)
    score = RF.score(x_train,y_train)
    y_pred_rf = RF.predict(x_test)
    return score,y_pred_rf
    

In [20]:
score,pred_rf_mean = Randomforest(best_max_depth,best_n_estimators,x_test)

In [21]:
corr_rf_mean = np.corrcoef(pred_rf_mean, y_test)
corr_rf_mean

array([[1.        , 0.23712825],
       [0.23712825, 1.        ]])

In [22]:
score

0.21867325466782706