In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("pearson_corr.csv")
df_month

April_5  November_4     May_8     May_4     May_9    June_5  February_2  \
0  -0.570061    0.092858 -0.676793  0.065741 -0.337310 -0.507901   -0.325414   
1  -0.610055    0.092858 -0.213397  0.061658 -0.290004 -0.507901   -0.213532   
2  -0.464105   -0.144591  0.376218  0.022404 -0.085953 -0.343425   -0.366403   
3  -0.464851    0.211338 -0.143403  0.277889 -0.161828 -0.256383   -0.325621   
4  -0.112498    0.227199  0.515070  0.221217 -0.055905 -0.333727   -0.127709   
5  -0.461749    0.489400 -0.538951  0.055913 -0.202906 -0.301398   -0.389314   
6  -0.608293    0.126746  0.322864  0.217356 -0.197503 -0.443026   -0.576245   
7   0.068665    0.238995 -0.214216 -0.190489 -0.571212 -0.247822   -0.199162   
8  -0.408084    0.179015  0.160824  0.263546 -0.407680 -0.469433   -0.156397   
9   0.042054    0.141883 -0.016718 -0.104601 -0.403877 -0.512329   -0.314276   
10 -0.255671    0.455007  0.228922 -0.338356 -0.353567 -0.265612   -0.018877   
11 -0.157474    0.179135 -0.229900 -0.439336 -0.468382 -0.312831   -0.523741   
12 -0.738392    0.005040 -0.030709  0.952202 -0.157656 -0.289191   -0.310806   
13 -0.194266    0.223754  0.337207  0.284914 -0.357723 -0.457938   -0.410265   
14 -0.280553    0.633382 -0.517346 -0.035865 -0.508596 -0.317867    0.043311   
15 -0.492447    0.032299  0.134008  0.372827 -0.328302 -0.405808   -0.397361   
16  0.166062    0.219758  0.360228  0.331880 -0.343313 -0.279303   -0.371938   
17 -0.660314    0.188692  0.249421  0.405057 -0.273289 -0.430021   -0.267355   
18  0.213139    0.351217  0.012463  0.116308 -0.392977 -0.472817   -0.335935   
19  0.606373    0.362247  0.310589  0.313823 -0.529498 -0.225282   -0.416325   
20 -0.326030    0.155631  0.181356  0.237816 -0.495646 -0.512943   -0.407247   
21 -0.809591    0.519816 -0.114694  0.351049 -0.330601 -0.425709   -0.191420   
22 -0.238749    0.257569  0.088831  0.148564 -0.570847 -0.547034   -0.166330   
23 -0.629029    0.247586  0.076044  0.194159 -0.288451 -0.348933   -0.027512   
24  0.349432    0.245470 -0.046078  0.001336 -0.551817 -0.527180   -0.049861   
25 -0.590192    0.312631 -0.074674  0.334786 -0.628421 -0.625973    0.200177   
26 -0.275855    0.307192 -0.065765  0.566342 -0.437272 -0.402614   -0.383944   
27 -0.292579    0.023683  0.114085  0.395951 -0.615443 -0.596399   -0.376372   
28 -0.712350    0.303569  0.124737 -0.513305 -0.678252 -0.468159   -0.232762   
29  0.283314    0.539929 -0.246756  0.118798 -0.757983 -0.259841   -0.118583   
30 -0.531603    0.435356  0.364203  0.181709 -0.558631 -0.723380   -0.206483   
31 -0.907749    0.317446  0.646683  0.716615 -0.038487 -0.623419   -0.051695   
32  0.138054    0.183706  0.218782  0.689553 -0.376851 -0.243628   -0.149154   
33 -0.290529    0.180805  0.000791  0.111346 -0.538462 -0.269600   -0.018394   
34  0.004190    0.437062 -0.027459 -0.411987 -0.727665 -0.427091    0.083948   
35 -0.017017    0.243300 -0.062084  0.583618 -0.398867 -0.131301   -0.052766   
36 -0.116412    0.384718 -0.292142  0.028672 -0.678270 -0.352882   -0.136387   
37 -0.108670    0.245904  0.508471  0.626141 -0.122335 -0.144636   -0.239407   
38 -0.289096    0.227608  0.534231  0.233171 -0.418038 -0.409067   -0.488575   
39  0.914952    0.518986 -0.036007 -0.664347 -0.708745 -0.323314    0.295783   
40 -0.634067    0.241738  0.315334  0.455446 -0.626410 -0.615711   -0.232702   
41 -0.589889   -0.077160  0.801749  0.132404 -0.246301 -0.517482   -0.338376   
42 -0.182564    0.191081  0.770140  0.203907 -0.380387 -0.333935    0.044343   
43 -0.285421    0.215475  0.418798  0.456425 -0.484326 -0.361383   -0.077674   
44 -0.281066    0.291262 -0.071165 -0.425534 -0.676542 -0.230283   -0.250278   
45 -0.683528    0.270770  0.552208  0.139935 -0.321186 -0.454762   -0.024651   
46  0.196889    0.129345  0.146915 -0.325004 -0.722667 -0.235599    0.276159   
47 -0.119217    0.535029  0.524433  0.279782 -0.345180 -0.447505   -0.364858   
48 -0.066958    0.198802  0.127219  0.871391  0.057364 -0.341785   -0.429336   
49  0

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :5]
x_train = scaler.fit_transform(x_train)
x_train

array([[-0.79875891, -0.96468849, -2.4435098 , -0.33190537,  0.3838594 ],
       [-0.90284252, -0.96468849, -0.95088184, -0.34424987,  0.63356955],
       [-0.52300614, -2.40950299,  0.94830649, -0.46292821,  1.71066054],
       [-0.52494903, -0.24376667, -0.72542578,  0.30949184,  1.31015467],
       [ 0.39205436, -0.14725503,  1.39555697,  0.13815042,  1.86927352],
       [-0.51687488,  1.44817587, -1.99951165, -0.36161923,  1.09331683],
       [-0.89825736, -0.75848523,  0.7764514 ,  0.12647701,  1.12183791],
       [ 0.8635321 , -0.07548051, -0.95351799, -1.10657559, -0.85080905],
       [-0.37721305, -0.44044325,  0.25450953,  0.26612801,  0.01240458],
       [ 0.79427568, -0.66637998, -0.31736411, -0.84690754,  0.03248278],
       [ 0.01944425,  1.23890484,  0.4738586 , -1.55362832,  0.29804364],
       [ 0.27500338, -0.43970902, -1.00403742, -1.85892789, -0.3080127 ],
       [-1.23684131, -1.49903569, -0.3624309 ,  2.34817116,  1.33217477],
       [ 0.179252  , -0.16821411,  0.8

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [8]:
x_test = df_month.iloc[43:, :5]
x_test = scaler.fit_transform(x_test)
x_test

array([[-0.35384492, -0.13320599,  0.07713988,  0.51902901, -0.49191253],
       [-0.33915351,  0.28521327, -1.14044717, -1.64900072, -1.19844819],
       [-1.6967388 ,  0.172075  ,  0.4086727 , -0.25896521,  0.10774594],
       [ 1.27308293, -0.60872528, -0.59850366, -1.40187958, -1.36799065],
       [ 0.20679276,  1.63103885,  0.33965073,  0.08480577,  0.01954931],
       [ 0.3830751 , -0.22525825, -0.6474504 ,  1.53910041,  1.49919519],
       [ 1.40289248, -1.23717723, -0.31615794, -0.25674317,  1.01598805],
       [-2.04136846, -0.12755875,  1.35817336,  0.60425039,  0.89098611],
       [-1.41897206,  0.50997758, -0.37012727, -0.06938458, -0.04937659],
       [-0.25248344, -1.24824839,  1.16516412,  0.85516781,  1.50016142],
       [ 0.94570343, -0.96025619,  1.30654896,  1.62471856,  1.5302261 ],
       [ 0.74875794,  1.23042144,  0.90235621,  0.85459774, -0.13587812],
       [-0.22859943,  1.00280678, -0.03879575,  0.52717042, -0.46917584],
       [-0.09957886,  1.51359616,  1.1

In [9]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] 
    y_test.append(y_ts)

In [10]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 29}
Best Score: 0.363814238802582
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 9}
Best Score: 0.2363150839301018
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 15}
Best Score: 0.40016147740510843
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 19}
Best Score: 0.37484419514157047
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 30}
Best Score: 0.3309454738960809


In [13]:
y_pred_list

[array([-0.1935465 ,  0.39588175,  0.02863334,  0.41024514,  0.02207776,
        -0.15792915,  0.07672486, -0.62724673, -0.08764355, -0.55535538,
        -0.45714346, -0.32713054, -0.05552135, -0.06466479,  0.68181851,
         0.12131979]),
 array([-0.08685513,  0.38623184,  0.00831284,  0.29994445, -0.11148009,
        -0.02756218,  0.09223075, -0.49438646,  0.05872522, -0.49438646,
        -0.49438646, -0.40809906,  0.05872522, -0.28830613,  0.38623184,
         0.29994445]),
 array([-0.14361457,  0.1440037 ,  0.14226481,  0.17809841,  0.05992273,
        -0.37599841, -0.10861624, -0.6567337 , -0.31098627, -0.6126083 ,
        -0.32731941, -0.22706111, -0.20235505,  0.17601667,  0.50968148,
         0.01862222]),
 array([-0.25023648,  0.49063743, -0.01435067,  0.27053363,  0.18024969,
        -0.2133831 , -0.06829073, -0.68713111, -0.40465163, -0.53103697,
        -0.36325919, -0.21333751, -0.18795938,  0.46282268,  0.85594152,
         0.26734211]),
 array([-0.20886792,  0.4289906 

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.7015069050549236,
 0.5971535530754618,
 0.6275352014455448,
 0.5898887908115075,
 0.6247099319060399]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+uwind/5 predictors/pearson/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'slp+uwind (2001-2016) 5p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+uwind/5 predictors/pearson/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+uwind/5 predictors/pearson/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'slp+uwind Predicted vs Actual 5p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+uwind/5 predictors/pearson/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:

y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 29}
Best Score: 0.363814238802582
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 9}
Best Score: 0.2363150839301018
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 15}
Best Score: 0.40016147740510843
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 19}
Best Score: 0.37484419514157047
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 30}
Best Score: 0.3309454738960809


In [21]:
y_pred_list_rf

[array([-0.1935465 ,  0.39588175,  0.02863334,  0.41024514,  0.02207776,
        -0.15792915,  0.07672486, -0.62724673, -0.08764355, -0.55535538,
        -0.45714346, -0.32713054, -0.05552135, -0.06466479,  0.68181851,
         0.12131979]),
 array([-0.08685513,  0.38623184,  0.00831284,  0.29994445, -0.11148009,
        -0.02756218,  0.09223075, -0.49438646,  0.05872522, -0.49438646,
        -0.49438646, -0.40809906,  0.05872522, -0.28830613,  0.38623184,
         0.29994445]),
 array([-0.14361457,  0.1440037 ,  0.14226481,  0.17809841,  0.05992273,
        -0.37599841, -0.10861624, -0.6567337 , -0.31098627, -0.6126083 ,
        -0.32731941, -0.22706111, -0.20235505,  0.17601667,  0.50968148,
         0.01862222]),
 array([-0.25023648,  0.49063743, -0.01435067,  0.27053363,  0.18024969,
        -0.2133831 , -0.06829073, -0.68713111, -0.40465163, -0.53103697,
        -0.36325919, -0.21333751, -0.18795938,  0.46282268,  0.85594152,
         0.26734211]),
 array([-0.20886792,  0.4289906 

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.7015069050549236,
 0.5971535530754618,
 0.6275352014455448,
 0.5898887908115075,
 0.6247099319060399]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+uwind/5 predictors/pearson/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'slp+uwind (2001-2016) 5p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+uwind/5 predictors/pearson/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+uwind/5 predictors/pearson/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'slp+uwind Predicted vs Actual 5p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'5p{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+uwind/5 predictors/pearson/comparison plots/randomforest
