In [150]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras.layers import Input, Dense
from keras.models import Model
from sklearn.preprocessing import normalize

In [151]:
df = pd.read_csv("project 1.csv")
df

airT         hgt        slp     Uwind     Vwind        olr       sst
0   -32.404984 -768.560791   1.621609 -1.952108 -0.871452 -47.445538 -0.973825
1   -31.890453 -771.096985   1.305570 -2.307280  0.155896 -46.907303 -0.974365
2   -32.320976 -775.395019   1.510948 -2.361962  0.872561 -46.690971 -0.974916
3   -32.411320 -779.455566   1.979502 -2.262750  1.767799 -47.460522 -0.975169
4   -33.016319 -781.542969   2.753553 -1.675639  2.574005 -48.169773 -0.975271
..         ...         ...        ...       ...       ...        ...       ...
319 -11.877342 -577.608826 -15.868583 -0.982829  0.504825 -35.813309       NaN
320 -12.517138 -580.763367 -16.862509 -1.523418  0.658751 -27.960745       NaN
321  -7.067920 -583.211975 -16.822027 -2.153407 -0.357583 -28.176806       NaN
322  -6.312740 -584.704163 -15.592834 -2.110729 -1.700504 -31.524090       NaN
323  -7.275416 -584.904907 -13.663765 -1.352651 -2.704739 -37.533978       NaN

[324 rows x 7 columns]

In [152]:
at = df['slp'].values
at

array([  1.62160921,   1.30557048,   1.51094842,   1.97950232,
         2.75355339,   3.59747887,   4.39111471,   5.20477295,
         5.7763567 ,   5.85945559,   5.82742691,   5.23308706,
         4.27749395,   4.4995532 ,   4.03409386,   3.4163363 ,
         3.37831807,   2.41920137,  -5.50036097,  -5.13388443,
        -4.14212513,  -1.28257966,   2.21294498,   4.70128107,
         6.61771107,   8.4374342 ,   9.30118942,   9.32770824,
         8.56545639,   7.67045975,   5.62680578,   3.42449236,
         1.00792849,   5.83004999,   8.26852989,  -1.31108499,
        -5.5166564 ,  -2.31649184,  -0.10780661,   3.50784087,
         8.94479179,  11.92329025,  13.35745525,  11.45080376,
         7.15519047,   1.92791569,   2.63001895,   6.32838964,
         7.29856968,   3.87549949,   0.25048265,  -1.74412823,
        -2.80316067,  -6.6573801 ,   2.38939095,   4.98399544,
         9.08982277,  12.86764812,  17.84952164,  19.53211975,
        14.78930283,  -0.69856304,  -6.8692236 ,  -8.35

In [153]:
ati = normalize(at.reshape(1,-1))
ati

array([[ 0.00888617,  0.00715433,  0.00827977,  0.01084737,  0.01508905,
         0.01971363,  0.02406264,  0.02852136,  0.03165355,  0.03210892,
         0.03193341,  0.02867651,  0.02344001,  0.02465686,  0.02210622,
         0.018721  ,  0.01851266,  0.01325685, -0.03014113, -0.0281329 ,
        -0.02269821, -0.00702834,  0.0121266 ,  0.0257623 ,  0.03626404,
         0.04623585,  0.05096909,  0.05111441,  0.04693739,  0.04203294,
         0.03083403,  0.01876569,  0.00552329,  0.03194778,  0.04531028,
        -0.00718454, -0.03023043, -0.01269402, -0.00059076,  0.01922243,
         0.04901609,  0.0653378 ,  0.07319681,  0.06274865,  0.03920935,
         0.01056468,  0.0144121 ,  0.0346786 ,  0.03999504,  0.02123714,
         0.00137261, -0.00955756, -0.01536089, -0.03648142,  0.0130935 ,
         0.02731153,  0.04981083,  0.07051274,  0.09781264,  0.10703302,
         0.08104311, -0.00382802, -0.03764229, -0.04579618, -0.03968297,
         0.01205469,  0.04651141,  0.0348161 ,  0.0

In [154]:
max_ati_value = np.amax(np.absolute(ati))
max_ati_value

0.134867180626087

In [155]:
ati.max()

0.134867180626087

In [197]:
hgt = df['Vwind'].values
#hgt = hgt[~np.isnan(hgt)]
hgt

array([-0.87145191,  0.15589593,  0.87256062,  1.76779902,  2.57400465,
        2.88840818,  2.83851695,  2.47607803,  1.77129459,  0.72920966,
       -0.53510868, -1.52415776, -1.86074746, -1.4319433 , -0.4810434 ,
       -0.10269021, -1.20688999, -1.85435689, -1.52880943, -0.71636462,
        0.93960428,  2.27763629,  3.0486443 ,  1.78477526,  2.58076763,
        1.71367681,  0.78292966, -0.34702423, -1.14596474, -1.17059243,
       -2.03651166, -1.26988173, -0.06335756,  5.73946905, -1.17303026,
       -5.73688078,  1.60921228,  1.91247272,  3.02439046,  2.57756615,
        3.57411575,  1.31734014,  1.58771479, -0.97025019, -1.83073139,
       -3.40354109, -0.09535006,  1.00133121,  0.13578604, -1.29092288,
       -1.1205709 , -0.31129917, -4.07518005, -0.66437733,  2.02479529,
        2.17718887,  2.822124  ,  2.99126983,  3.41525626,  1.40146446,
       -1.49923062, -4.000247  , -2.44929576, -0.86391449,  1.14700139,
        2.70458007,  0.90049547, -0.34386477,  0.78985322, -1.04

In [198]:
hgti = normalize(hgt.reshape(1,-1))
hgti

array([[-0.02462664,  0.00440551,  0.02465797,  0.04995679,  0.07273961,
         0.08162444,  0.08021455,  0.06997227,  0.05005557,  0.02060697,
        -0.01512181, -0.04307166, -0.05258345, -0.04046574, -0.01359396,
        -0.00290196, -0.03410589, -0.05240286, -0.04320311, -0.02024397,
         0.02655257,  0.06436444,  0.0861526 ,  0.05043653,  0.07293073,
         0.04842733,  0.02212506, -0.00980667, -0.03238418, -0.03308014,
        -0.05755043, -0.03588599, -0.00179044,  0.16219347, -0.03314903,
        -0.16212033,  0.04547524,  0.05404517,  0.08546721,  0.07284026,
         0.10100207,  0.03722713,  0.04486773, -0.02741861, -0.05173522,
        -0.09618174, -0.00269453,  0.02829694,  0.00383722, -0.0364806 ,
        -0.03166657, -0.0087971 , -0.1151618 , -0.01877485,  0.05721933,
         0.06152587,  0.07975129,  0.08453124,  0.09651281,  0.03960443,
        -0.04236723, -0.11304424, -0.06921542, -0.02441363,  0.03241347,
         0.07642958,  0.02544739, -0.00971738,  0.0

In [199]:
max_hgti_value = np.amax(np.absolute(hgti))
max_hgti_value

0.1714769462718235

In [200]:
hgti.max()

0.1714769462718235

In [201]:
ati_flat = np.ravel(ati)
hgti_flat = np.ravel(hgti)

In [202]:
hgti_flat.shape

(324,)

In [203]:
ati_flat.shape

(324,)

In [204]:
df_merged.shape

(648, 1)

In [205]:
data = {'airTi': ati_flat, 'hgti': hgti_flat}
df1 = pd.DataFrame(data)

In [206]:
df2 = df1.values.flatten()

In [207]:
df_merged = pd.DataFrame(df2, columns=['merged_column'])

In [208]:
df_merged

merged_column
0         0.008886
1        -0.024627
2         0.007154
3         0.004406
4         0.008280
..             ...
643      -0.010105
644      -0.085446
645      -0.048055
646      -0.074875
647      -0.076434

[648 rows x 1 columns]

In [209]:
df_merged.max()

merged_column    0.171477
dtype: float64

In [210]:
input_data = df_merged.values
input_data

array([[ 0.00888617],
       [-0.02462664],
       [ 0.00715433],
       [ 0.00440551],
       [ 0.00827977],
       [ 0.02465797],
       [ 0.01084737],
       [ 0.04995679],
       [ 0.01508905],
       [ 0.07273961],
       [ 0.01971363],
       [ 0.08162444],
       [ 0.02406264],
       [ 0.08021455],
       [ 0.02852136],
       [ 0.06997227],
       [ 0.03165355],
       [ 0.05005557],
       [ 0.03210892],
       [ 0.02060697],
       [ 0.03193341],
       [-0.01512181],
       [ 0.02867651],
       [-0.04307166],
       [ 0.02344001],
       [-0.05258345],
       [ 0.02465686],
       [-0.04046574],
       [ 0.02210622],
       [-0.01359396],
       [ 0.018721  ],
       [-0.00290196],
       [ 0.01851266],
       [-0.03410589],
       [ 0.01325685],
       [-0.05240286],
       [-0.03014113],
       [-0.04320311],
       [-0.0281329 ],
       [-0.02024397],
       [-0.02269821],
       [ 0.02655257],
       [-0.00702834],
       [ 0.06436444],
       [ 0.0121266 ],
       [ 0

In [107]:
# normalized_input_data = normalize(input_data.reshape(1, -1))
# normalized_input_data

In [211]:
input_data.shape

(648, 1)

In [212]:
input_data = np.reshape(input_data, (1, 648))

In [213]:
input_data.shape

(1, 648)

In [214]:
# normalized_input_data.shape

In [215]:
np.max(np.abs(input_data))

0.1714769462718235

In [216]:
input_dim = 648
hidden_dim = 65
input_layer = Input(shape = (input_dim,))
hidden_layer = Dense(hidden_dim,activation='tanh')(input_layer)
output_layer = Dense(input_dim,activation='linear')(hidden_layer)

In [217]:
autoencoder = Model(inputs=input_layer, outputs=output_layer)

In [218]:
autoencoder.compile(optimizer='adam', loss='mean_squared_error')

In [219]:
autoencoder.fit(input_data, input_data, epochs=10, batch_size=32)

Epoch 1/10
1/1 [==============================] - 0s 346ms/step - loss: 0.0041
Epoch 2/10
1/1 [==============================] - 0s 9ms/step - loss: 0.0033
Epoch 3/10
1/1 [==============================] - 0s 19ms/step - loss: 0.0028
Epoch 4/10
1/1 [==============================] - 0s 11ms/step - loss: 0.0025
Epoch 5/10
1/1 [==============================] - 0s 10ms/step - loss: 0.0023
Epoch 6/10
1/1 [==============================] - 0s 10ms/step - loss: 0.0021
Epoch 7/10
1/1 [==============================] - 0s 11ms/step - loss: 0.0019
Epoch 8/10
1/1 [==============================] - 0s 8ms/step - loss: 0.0017
Epoch 9/10
1/1 [==============================] - 0s 9ms/step - loss: 0.0015
Epoch 10/10
1/1 [==============================] - 0s 13ms/step - loss: 0.0013


In [220]:
encoded_data = autoencoder.predict(input_data)

1/1 [==============================] - 0s 63ms/step


In [221]:
decoded_data = autoencoder.predict(encoded_data)

1/1 [==============================] - 0s 34ms/step


In [222]:
print('Original Data:')
print(input_data)
print('Decoded Data:')
print(decoded_data)

Original Data:
[[ 0.00888617 -0.02462664  0.00715433  0.00440551  0.00827977  0.02465797
   0.01084737  0.04995679  0.01508905  0.07273961  0.01971363  0.08162444
   0.02406264  0.08021455  0.02852136  0.06997227  0.03165355  0.05005557
   0.03210892  0.02060697  0.03193341 -0.01512181  0.02867651 -0.04307166
   0.02344001 -0.05258345  0.02465686 -0.04046574  0.02210622 -0.01359396
   0.018721   -0.00290196  0.01851266 -0.03410589  0.01325685 -0.05240286
  -0.03014113 -0.04320311 -0.0281329  -0.02024397 -0.02269821  0.02655257
  -0.00702834  0.06436444  0.0121266   0.0861526   0.0257623   0.05043653
   0.03626404  0.07293073  0.04623585  0.04842733  0.05096909  0.02212506
   0.05111441 -0.00980667  0.04693739 -0.03238418  0.04203294 -0.03308014
   0.03083403 -0.05755043  0.01876569 -0.03588599  0.00552329 -0.00179044
   0.03194778  0.16219347  0.04531028 -0.03314903 -0.00718454 -0.16212033
  -0.03023043  0.04547524 -0.01269402  0.05404517 -0.00059076  0.08546721
   0.01922243  0.072840

In [223]:
weights = autoencoder.get_weights()[0]  # Get the weights of the first layer (between input and hidden)

weight_mean = np.mean(weights)
weight_std = np.std(weights)

threshold = weight_mean +  1.4* weight_std

potential_predictors = []
for i in range(hidden_dim):  # Iterate over the hidden nodes
    input_nodes = np.where(weights[:, i] > threshold)[0]  # Find the input nodes with weights above the threshold
    if len(input_nodes) >= input_dim * 0.1: # Check if at least 10% of input nodes participate
        predictor = np.sum(weights[input_nodes, i] * input_data[:,input_nodes])
        potential_predictors.append(predictor)

print("Potential predictors:")
print(potential_predictors)

Potential predictors:
[0.03388327354653374, -0.07894818778524999, 0.04310658078078281, 0.034948036768186204, -0.04253094814199457, 0.018169263780333834, 0.05020856112946956, 0.050260820891158, 0.040962614903746204, 0.0374905619422633, 0.0384256455463087, 0.0014178394051655415, -0.027395523450895465, 0.05880775261515733, 0.07885832680187294, -0.08520048620385133, -0.07436417917421977, 0.07713819199509896, -0.021551319270906644, 0.06250218715819143, -0.013965973814530394]


In [224]:
weights.shape

(648, 65)

In [225]:
pp = potential_predictors

In [226]:
weights

array([[ 0.058514  ,  0.05591441,  0.07696345, ..., -0.03082591,
        -0.08399765, -0.0838164 ],
       [ 0.08239681,  0.00691859,  0.02132324, ..., -0.00666321,
        -0.00399876,  0.06546585],
       [-0.08498348,  0.02611401,  0.02321121, ..., -0.04795361,
         0.02072554, -0.01262001],
       ...,
       [ 0.00952967, -0.03816605,  0.02788099, ..., -0.08604973,
        -0.04848361, -0.08244555],
       [ 0.01798837,  0.03360285,  0.00218877, ..., -0.01445786,
         0.07631613,  0.00084286],
       [-0.07299669,  0.04759544, -0.0168094 , ..., -0.08074229,
        -0.01803614, -0.01086983]], dtype=float32)

In [227]:
input_nodes

array([ 17,  37,  55,  61,  75,  98, 123, 126, 129, 133, 139, 150, 159,
       173, 174, 175, 176, 182, 184, 200, 205, 216, 217, 218, 223, 296,
       310, 314, 316, 332, 333, 346, 347, 348, 357, 377, 389, 391, 394,
       401, 413, 415, 417, 422, 455, 458, 462, 470, 480, 485, 499, 505,
       516, 533, 541, 550, 556, 559, 564, 602, 635, 637], dtype=int64)

In [228]:
weights.max()

0.0980787

In [229]:
weight_mean = np.mean(weights)
weight_std = np.std(weights)

In [230]:
weight_mean

-3.1134964e-06

In [231]:
weight_std

0.05320248

In [232]:
threshold =   2 * weight_std+weight_mean
threshold

0.10640184665908237

In [ ]:
# import csv

# csv_file_path = 'sst.csv'
# new_column_header = 'sst'
# #new_column_data = ['data1', 'data2', 'data3']  # Replace with your actual data

# # Create a new CSV file and write the header and data
# with open(csv_file_path, 'w', newline='') as csvfile:
#     writer = csv.writer(csvfile)
#     writer.writerow([new_column_header])  # Write the header row
#     writer.writerows(zip(pp))  # Write the data as a new column


In [233]:
import csv
filename = 'Vwind_slp.csv'

with open(filename, 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['Vwind+slp'])  # Write the header
    for item in pp:
        writer.writerow([item])
