In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras.layers import Input, Dense
from keras.models import Model
from sklearn.preprocessing import normalize

In [2]:
df = pd.read_csv("project 1.csv")
df

airT         hgt        slp     Uwind     Vwind        olr       sst
0   -32.404984 -768.560791   1.621609 -1.952108 -0.871452 -47.445538 -0.973825
1   -31.890453 -771.096985   1.305570 -2.307280  0.155896 -46.907303 -0.974365
2   -32.320976 -775.395019   1.510948 -2.361962  0.872561 -46.690971 -0.974916
3   -32.411320 -779.455566   1.979502 -2.262750  1.767799 -47.460522 -0.975169
4   -33.016319 -781.542969   2.753553 -1.675639  2.574005 -48.169773 -0.975271
..         ...         ...        ...       ...       ...        ...       ...
319 -11.877342 -577.608826 -15.868583 -0.982829  0.504825 -35.813309       NaN
320 -12.517138 -580.763367 -16.862509 -1.523418  0.658751 -27.960745       NaN
321  -7.067920 -583.211975 -16.822027 -2.153407 -0.357583 -28.176806       NaN
322  -6.312740 -584.704163 -15.592834 -2.110729 -1.700504 -31.524090       NaN
323  -7.275416 -584.904907 -13.663765 -1.352651 -2.704739 -37.533978       NaN

[324 rows x 7 columns]

In [3]:
slp = df['slp'].values
slp

array([  1.62160921,   1.30557048,   1.51094842,   1.97950232,
         2.75355339,   3.59747887,   4.39111471,   5.20477295,
         5.7763567 ,   5.85945559,   5.82742691,   5.23308706,
         4.27749395,   4.4995532 ,   4.03409386,   3.4163363 ,
         3.37831807,   2.41920137,  -5.50036097,  -5.13388443,
        -4.14212513,  -1.28257966,   2.21294498,   4.70128107,
         6.61771107,   8.4374342 ,   9.30118942,   9.32770824,
         8.56545639,   7.67045975,   5.62680578,   3.42449236,
         1.00792849,   5.83004999,   8.26852989,  -1.31108499,
        -5.5166564 ,  -2.31649184,  -0.10780661,   3.50784087,
         8.94479179,  11.92329025,  13.35745525,  11.45080376,
         7.15519047,   1.92791569,   2.63001895,   6.32838964,
         7.29856968,   3.87549949,   0.25048265,  -1.74412823,
        -2.80316067,  -6.6573801 ,   2.38939095,   4.98399544,
         9.08982277,  12.86764812,  17.84952164,  19.53211975,
        14.78930283,  -0.69856304,  -6.8692236 ,  -8.35

In [5]:
slpi = normalize(slp.reshape(1,-1))
slpi

array([[ 0.00888617,  0.00715433,  0.00827977,  0.01084737,  0.01508905,
         0.01971363,  0.02406264,  0.02852136,  0.03165355,  0.03210892,
         0.03193341,  0.02867651,  0.02344001,  0.02465686,  0.02210622,
         0.018721  ,  0.01851266,  0.01325685, -0.03014113, -0.0281329 ,
        -0.02269821, -0.00702834,  0.0121266 ,  0.0257623 ,  0.03626404,
         0.04623585,  0.05096909,  0.05111441,  0.04693739,  0.04203294,
         0.03083403,  0.01876569,  0.00552329,  0.03194778,  0.04531028,
        -0.00718454, -0.03023043, -0.01269402, -0.00059076,  0.01922243,
         0.04901609,  0.0653378 ,  0.07319681,  0.06274865,  0.03920935,
         0.01056468,  0.0144121 ,  0.0346786 ,  0.03999504,  0.02123714,
         0.00137261, -0.00955756, -0.01536089, -0.03648142,  0.0130935 ,
         0.02731153,  0.04981083,  0.07051274,  0.09781264,  0.10703302,
         0.08104311, -0.00382802, -0.03764229, -0.04579618, -0.03968297,
         0.01205469,  0.04651141,  0.0348161 ,  0.0

In [6]:
max_slpi_value = np.amax(np.absolute(slpi))
max_slpi_value

0.134867180626087

In [7]:
slpi.max()

0.134867180626087

In [9]:
sst = df['sst'].values
sst = sst[~np.isnan(sst)]
sst

array([-0.97382492, -0.9743647 , -0.97491556, -0.97516948, -0.97527063,
       -0.9753651 , -0.97533643, -0.9753629 , -0.97537178, -0.97537285,
       -0.97537065, -0.97536433, -0.67272669, -0.8085897 , -0.86937505,
       -0.96777219, -0.93935114, -0.92002577, -0.97536665, -0.97533268,
       -0.97536701, -0.97536808, -0.9753744 , -0.97142476, -0.3641384 ,
       -0.66355604, -0.74829125, -0.87085015, -0.81745541, -0.81745541,
       -0.83718628, -0.8371793 , -0.88057655, -0.93415773, -0.8569262 ,
       -0.88843685, -0.42184678, -0.7056123 , -0.81745541, -0.81745541,
       -0.81745541, -0.81745541, -0.81745541, -0.79201227, -0.74641764,
       -0.7047056 , -0.61824131, -0.7415306 , -0.52608293, -0.79223418,
       -0.81745541, -0.81745541, -0.81745541, -0.81745541, -0.82029706,
       -0.71206063, -0.50992155, -0.38500688, -0.28957784, -0.34195387,
       -0.3563714 , -0.48895377, -0.57575929, -0.81745541, -0.81745541,
       -0.81745541, -0.71013123, -0.36196476, -0.17357695, -0.09

In [10]:
ssti = normalize(sst.reshape(1,-1))
ssti

array([[-0.09023085, -0.09028086, -0.0903319 , -0.09035543, -0.0903648 ,
        -0.09037355, -0.0903709 , -0.09037335, -0.09037417, -0.09037427,
        -0.09037407, -0.09037348, -0.06233225, -0.07492079, -0.08055293,
        -0.08967002, -0.08703664, -0.08524602, -0.0903737 , -0.09037055,
        -0.09037373, -0.09037383, -0.09037441, -0.09000846, -0.03373965,
        -0.06148253, -0.06933377, -0.0806896 , -0.07574225, -0.07574225,
        -0.07757044, -0.07756979, -0.08159081, -0.08655544, -0.07939946,
        -0.08231912, -0.03908669, -0.0653793 , -0.07574225, -0.07574225,
        -0.07574225, -0.07574225, -0.07574225, -0.07338479, -0.06916017,
        -0.06529529, -0.05728385, -0.06870735, -0.04874481, -0.07340535,
        -0.07574225, -0.07574225, -0.07574225, -0.07574225, -0.07600555,
        -0.06597678, -0.04724736, -0.03567325, -0.02683116, -0.03168412,
        -0.03301999, -0.04530456, -0.05334763, -0.07574225, -0.07574225,
        -0.07574225, -0.06579801, -0.03353825, -0.0

In [11]:
max_ssti_value = np.amax(np.absolute(ssti))
max_ssti_value

0.1622358691643809

In [12]:
ssti.max()

0.1622358691643809

In [13]:
slpi_flat = np.ravel(slpi)
ssti_flat = np.ravel(ssti)

In [14]:
slpi_flat.shape

(324,)

In [15]:
ssti_flat.shape

(132,)

In [17]:
merged_list = []
#ssti_flat + slpi_flat
merged_list.extend(ssti_flat)
merged_list.extend(slpi_flat)

In [32]:
merged_list

[-0.09023084587574064,
 -0.09028085980030404,
 -0.09033190091069815,
 -0.09035542778399736,
 -0.09036479985864936,
 -0.09037355336099342,
 -0.09037089690981473,
 -0.09037334905423203,
 -0.09037417193330137,
 -0.0903742713533263,
 -0.09037406704656491,
 -0.09037348155249451,
 -0.06233225013052911,
 -0.07492079015246438,
 -0.08055292557708439,
 -0.08967002316713629,
 -0.08703663919469773,
 -0.08524602478251252,
 -0.09037369697799122,
 -0.09037054898605555,
 -0.0903737301488849,
 -0.09037382956890984,
 -0.0903744149703241,
 -0.09000845634448701,
 -0.03373965359621714,
 -0.061482533028515036,
 -0.0693337699229408,
 -0.08068960226030304,
 -0.07574225288023613,
 -0.07574225288023613,
 -0.07757043851826362,
 -0.07756979233442964,
 -0.08159081328320689,
 -0.08655543774967452,
 -0.07939946362080728,
 -0.0823191185210583,
 -0.039086688803197094,
 -0.06537930350000405,
 -0.07574225288023613,
 -0.07574225288023613,
 -0.07574225288023613,
 -0.07574225288023613,
 -0.07574225288023613,
 -0.0733847903

In [21]:
input_data = np.array(merged_list)
input_data

array([-0.09023085, -0.09028086, -0.0903319 , -0.09035543, -0.0903648 ,
       -0.09037355, -0.0903709 , -0.09037335, -0.09037417, -0.09037427,
       -0.09037407, -0.09037348, -0.06233225, -0.07492079, -0.08055293,
       -0.08967002, -0.08703664, -0.08524602, -0.0903737 , -0.09037055,
       -0.09037373, -0.09037383, -0.09037441, -0.09000846, -0.03373965,
       -0.06148253, -0.06933377, -0.0806896 , -0.07574225, -0.07574225,
       -0.07757044, -0.07756979, -0.08159081, -0.08655544, -0.07939946,
       -0.08231912, -0.03908669, -0.0653793 , -0.07574225, -0.07574225,
       -0.07574225, -0.07574225, -0.07574225, -0.07338479, -0.06916017,
       -0.06529529, -0.05728385, -0.06870735, -0.04874481, -0.07340535,
       -0.07574225, -0.07574225, -0.07574225, -0.07574225, -0.07600555,
       -0.06597678, -0.04724736, -0.03567325, -0.02683116, -0.03168412,
       -0.03301999, -0.04530456, -0.05334763, -0.07574225, -0.07574225,
       -0.07574225, -0.06579801, -0.03353825, -0.01608297, -0.00

In [22]:
input_data.shape

(456,)

In [33]:
input_data = input_data.reshape((1, 456))

In [34]:
input_dim = 456
hidden_dim = 45
input_layer = Input(shape = (input_dim,))
hidden_layer = Dense(hidden_dim,activation='tanh')(input_layer)
output_layer = Dense(input_dim,activation='linear')(hidden_layer)

In [35]:
autoencoder = Model(inputs=input_layer, outputs=output_layer)

In [36]:
autoencoder.compile(optimizer='adam', loss='mean_squared_error')

In [37]:
autoencoder.fit(input_data, input_data, epochs=10, batch_size=32)

Epoch 1/10
1/1 [==============================] - 2s 2s/step - loss: 0.0057
Epoch 2/10
1/1 [==============================] - 0s 16ms/step - loss: 0.0047
Epoch 3/10
1/1 [==============================] - 0s 13ms/step - loss: 0.0041
Epoch 4/10
1/1 [==============================] - 0s 14ms/step - loss: 0.0036
Epoch 5/10
1/1 [==============================] - 0s 11ms/step - loss: 0.0033
Epoch 6/10
1/1 [==============================] - 0s 11ms/step - loss: 0.0030
Epoch 7/10
1/1 [==============================] - 0s 10ms/step - loss: 0.0028
Epoch 8/10
1/1 [==============================] - 0s 8ms/step - loss: 0.0026
Epoch 9/10
1/1 [==============================] - 0s 16ms/step - loss: 0.0023
Epoch 10/10
1/1 [==============================] - 0s 11ms/step - loss: 0.0021


In [40]:
weights = autoencoder.get_weights()[0]  # Get the weights of the first layer (between input and hidden)

weight_mean = np.mean(weights)
weight_std = np.std(weights)

threshold = weight_mean +  1.4* weight_std

potential_predictors = []
for i in range(hidden_dim):  # Iterate over the hidden nodes
    input_nodes = np.where(weights[:, i] > threshold)[0]  # Find the input nodes with weights above the threshold
    if len(input_nodes) >= input_dim * 0.1: # Check if at least 10% of input nodes participate
        predictor = np.sum(weights[input_nodes, i] * input_data[:,input_nodes])
        potential_predictors.append(predictor)

print("Potential predictors:")
print(potential_predictors)

Potential predictors:
[0.00040317361778119225, -0.0950020708721992, -0.03836300406792466, -0.04994658345470493, -0.05828674529464058, -0.11128603290575759, -0.029433971722180406, 0.09947399009745127, 0.0005711832959758197, -0.021914029329703044, -0.06568337289095079, 0.08941372437981482, -0.10812812305944941, -0.06368961678068945, -0.06041727592847468]


In [41]:
weights.shape

(456, 45)

In [42]:
pp = potential_predictors

In [43]:
weights

array([[ 0.03776949,  0.08166246, -0.02194328, ..., -0.03766605,
         0.03030632, -0.07268601],
       [ 0.07452914,  0.05780521, -0.10332303, ...,  0.03711003,
         0.06903277,  0.10219678],
       [ 0.07492507,  0.00705678,  0.08132959, ..., -0.04550604,
         0.05116318, -0.09901708],
       ...,
       [-0.10708649,  0.02052486, -0.07897175, ...,  0.0645804 ,
         0.10171144, -0.00463585],
       [ 0.03372316, -0.08747175,  0.08211684, ...,  0.05832444,
         0.0219267 , -0.08366399],
       [ 0.05818965, -0.05400216,  0.04064917, ...,  0.00069003,
        -0.08622194,  0.09950692]], dtype=float32)

In [44]:
input_nodes

array([  1,  34,  36,  59,  69,  71,  73,  76,  82,  85,  91,  94, 114,
       132, 139, 141, 154, 157, 172, 196, 222, 238, 249, 268, 274, 276,
       283, 289, 297, 302, 329, 332, 345, 358, 368, 378, 379, 383, 412,
       445, 451, 455], dtype=int64)

In [45]:
weights.max()

0.11684464

In [46]:
weight_mean = np.mean(weights)
weight_std = np.std(weights)

In [47]:
weight_mean

1.9624546e-05

In [48]:
weight_std

0.06324025

In [49]:
threshold =   2 * weight_std+weight_mean
threshold

0.12650012941594468

In [50]:
import csv
filename = 'slp_sst.csv'

with open(filename, 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(['slp+sst'])  # Write the header
    for item in pp:
        writer.writerow([item])
