In [6]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras.layers import Input, Dense
from keras.models import Model
from sklearn.preprocessing import normalize

In [51]:
df = pd.read_csv("project 1.csv")
df

airT         hgt        slp     Uwind     Vwind        olr       sst
0   -32.404984 -768.560791   1.621609 -1.952108 -0.871452 -47.445538 -0.973825
1   -31.890453 -771.096985   1.305570 -2.307280  0.155896 -46.907303 -0.974365
2   -32.320976 -775.395019   1.510948 -2.361962  0.872561 -46.690971 -0.974916
3   -32.411320 -779.455566   1.979502 -2.262750  1.767799 -47.460522 -0.975169
4   -33.016319 -781.542969   2.753553 -1.675639  2.574005 -48.169773 -0.975271
..         ...         ...        ...       ...       ...        ...       ...
319 -11.877342 -577.608826 -15.868583 -0.982829  0.504825 -35.813309       NaN
320 -12.517138 -580.763367 -16.862509 -1.523418  0.658751 -27.960745       NaN
321  -7.067920 -583.211975 -16.822027 -2.153407 -0.357583 -28.176806       NaN
322  -6.312740 -584.704163 -15.592834 -2.110729 -1.700504 -31.524090       NaN
323  -7.275416 -584.904907 -13.663765 -1.352651 -2.704739 -37.533978       NaN

[324 rows x 7 columns]

In [57]:
df1 = df['sst']
df1

0     -0.973825
1     -0.974365
2     -0.974916
3     -0.975169
4     -0.975271
         ...   
319         NaN
320         NaN
321         NaN
322         NaN
323         NaN
Name: sst, Length: 324, dtype: float64

In [58]:
df2= df1.dropna().reset_index(drop=True)
df2

0     -0.973825
1     -0.974365
2     -0.974916
3     -0.975169
4     -0.975271
         ...   
127    1.750946
128    1.718499
129    1.661920
130    1.580395
131    1.514779
Name: sst, Length: 132, dtype: float64

In [60]:
#input_data = df[['airT','hgt']].values
input_data = df2.values
input_data

array([-0.97382492, -0.9743647 , -0.97491556, -0.97516948, -0.97527063,
       -0.9753651 , -0.97533643, -0.9753629 , -0.97537178, -0.97537285,
       -0.97537065, -0.97536433, -0.67272669, -0.8085897 , -0.86937505,
       -0.96777219, -0.93935114, -0.92002577, -0.97536665, -0.97533268,
       -0.97536701, -0.97536808, -0.9753744 , -0.97142476, -0.3641384 ,
       -0.66355604, -0.74829125, -0.87085015, -0.81745541, -0.81745541,
       -0.83718628, -0.8371793 , -0.88057655, -0.93415773, -0.8569262 ,
       -0.88843685, -0.42184678, -0.7056123 , -0.81745541, -0.81745541,
       -0.81745541, -0.81745541, -0.81745541, -0.79201227, -0.74641764,
       -0.7047056 , -0.61824131, -0.7415306 , -0.52608293, -0.79223418,
       -0.81745541, -0.81745541, -0.81745541, -0.81745541, -0.82029706,
       -0.71206063, -0.50992155, -0.38500688, -0.28957784, -0.34195387,
       -0.3563714 , -0.48895377, -0.57575929, -0.81745541, -0.81745541,
       -0.81745541, -0.71013123, -0.36196476, -0.17357695, -0.09

In [56]:
# nan_indices = np.isnan(input_data)
# mean_value = np.nanmean(input_data)
# input_data[nan_indices] = mean_value


0     -0.973825
1     -0.974365
2     -0.974916
3     -0.975169
4     -0.975271
         ...   
127    1.750946
128    1.718499
129    1.661920
130    1.580395
131    1.514779
Name: sst, Length: 132, dtype: float64

In [61]:
normalized_input_data = normalize(input_data.reshape(1, -1))
normalized_input_data

array([[-0.09023085, -0.09028086, -0.0903319 , -0.09035543, -0.0903648 ,
        -0.09037355, -0.0903709 , -0.09037335, -0.09037417, -0.09037427,
        -0.09037407, -0.09037348, -0.06233225, -0.07492079, -0.08055293,
        -0.08967002, -0.08703664, -0.08524602, -0.0903737 , -0.09037055,
        -0.09037373, -0.09037383, -0.09037441, -0.09000846, -0.03373965,
        -0.06148253, -0.06933377, -0.0806896 , -0.07574225, -0.07574225,
        -0.07757044, -0.07756979, -0.08159081, -0.08655544, -0.07939946,
        -0.08231912, -0.03908669, -0.0653793 , -0.07574225, -0.07574225,
        -0.07574225, -0.07574225, -0.07574225, -0.07338479, -0.06916017,
        -0.06529529, -0.05728385, -0.06870735, -0.04874481, -0.07340535,
        -0.07574225, -0.07574225, -0.07574225, -0.07574225, -0.07600555,
        -0.06597678, -0.04724736, -0.03567325, -0.02683116, -0.03168412,
        -0.03301999, -0.04530456, -0.05334763, -0.07574225, -0.07574225,
        -0.07574225, -0.06579801, -0.03353825, -0.0

In [62]:
input_data.shape

(132,)

In [63]:
normalized_input_data.shape

(1, 132)

In [42]:
#normalized_input_data = np.reshape(normalized_input_data)

In [43]:
#input_data_ = np.reshape(input_data, (1, 324))

In [64]:
np.max(np.abs(input_data))

1.750945926

In [69]:
input_dim = 132
hidden_dim = 40
input_layer = Input(shape = (input_dim,))
hidden_layer = Dense(hidden_dim,activation='tanh')(input_layer)
output_layer = Dense(input_dim,activation='linear')(hidden_layer)

In [70]:
autoencoder = Model(inputs=input_layer, outputs=output_layer)

In [71]:
autoencoder.compile(optimizer='adam', loss='mean_squared_error')

In [72]:
autoencoder.fit(normalized_input_data, normalized_input_data, epochs=10, batch_size=32)

Epoch 1/10
1/1 [==============================] - 0s 353ms/step - loss: 0.0104
Epoch 2/10
1/1 [==============================] - 0s 9ms/step - loss: 0.0090
Epoch 3/10
1/1 [==============================] - 0s 20ms/step - loss: 0.0078
Epoch 4/10
1/1 [==============================] - 0s 13ms/step - loss: 0.0068
Epoch 5/10
1/1 [==============================] - 0s 13ms/step - loss: 0.0060
Epoch 6/10
1/1 [==============================] - 0s 14ms/step - loss: 0.0053
Epoch 7/10
1/1 [==============================] - 0s 20ms/step - loss: 0.0048
Epoch 8/10
1/1 [==============================] - 0s 20ms/step - loss: 0.0043
Epoch 9/10
1/1 [==============================] - 0s 12ms/step - loss: 0.0039
Epoch 10/10
1/1 [==============================] - 0s 12ms/step - loss: 0.0035


In [73]:
encoded_data = autoencoder.predict(normalized_input_data)

1/1 [==============================] - 0s 57ms/step


In [74]:
decoded_data = autoencoder.predict(encoded_data)

1/1 [==============================] - 0s 28ms/step


In [75]:
print('Original Data:')
print(input_data)
print('Decoded Data:')
print(decoded_data)

Original Data:
[-0.97382492 -0.9743647  -0.97491556 -0.97516948 -0.97527063 -0.9753651
 -0.97533643 -0.9753629  -0.97537178 -0.97537285 -0.97537065 -0.97536433
 -0.67272669 -0.8085897  -0.86937505 -0.96777219 -0.93935114 -0.92002577
 -0.97536665 -0.97533268 -0.97536701 -0.97536808 -0.9753744  -0.97142476
 -0.3641384  -0.66355604 -0.74829125 -0.87085015 -0.81745541 -0.81745541
 -0.83718628 -0.8371793  -0.88057655 -0.93415773 -0.8569262  -0.88843685
 -0.42184678 -0.7056123  -0.81745541 -0.81745541 -0.81745541 -0.81745541
 -0.81745541 -0.79201227 -0.74641764 -0.7047056  -0.61824131 -0.7415306
 -0.52608293 -0.79223418 -0.81745541 -0.81745541 -0.81745541 -0.81745541
 -0.82029706 -0.71206063 -0.50992155 -0.38500688 -0.28957784 -0.34195387
 -0.3563714  -0.48895377 -0.57575929 -0.81745541 -0.81745541 -0.81745541
 -0.71013123 -0.36196476 -0.17357695 -0.09305207  0.00620225  0.05022698
  0.22498238  0.22686157 -0.64721715 -0.81745541 -0.81745541 -0.81745541
  0.14809579  0.56665373  0.63308007  

In [78]:
weights = autoencoder.get_weights()[0]  # Get the weights of the first layer (between input and hidden)

weight_mean = np.mean(weights)
weight_std = np.std(weights)

threshold = weight_mean +  1.4* weight_std

potential_predictors = []
for i in range(hidden_dim):  # Iterate over the hidden nodes
    input_nodes = np.where(weights[:, i] > threshold)[0]  # Find the input nodes with weights above the threshold
    if len(input_nodes) >= input_dim * 0.1: # Check if at least 10% of input nodes participate
        predictor = np.sum(weights[input_nodes, i] * input_data[input_nodes])
        potential_predictors.append(predictor)

print("Potential predictors:")
print(potential_predictors)

Potential predictors:
[0.3845649388336529, 0.5167435400043403, 0.0638948568320114, -0.5153893785841602, -1.055301862399756, -0.10772278227394844, 0.3989356314482897, -0.48168320773750456, -0.187711997527239, -0.6967700626913551, -0.05231224745561838, -0.6752243341118167, -0.3456914955164907, -0.5294044518524537, -0.015085883692231794, -0.3805185911786958, 0.09111662498278472]


In [79]:
pp = potential_predictors

In [80]:
weights

array([[-0.17458253, -0.0497747 , -0.16327275, ..., -0.15198343,
         0.10619394, -0.10737733],
       [ 0.0414169 ,  0.12503313, -0.04598483, ..., -0.09822471,
         0.18232748, -0.01687104],
       [ 0.12835164, -0.0626469 , -0.03892668, ..., -0.04033702,
         0.09865642, -0.08754932],
       ...,
       [-0.05361469,  0.05118758,  0.17645709, ...,  0.02252793,
        -0.100949  , -0.00836534],
       [-0.10658587, -0.06659551,  0.12365384, ...,  0.15609777,
        -0.02188809, -0.07563095],
       [ 0.07343274,  0.17327942, -0.03437449, ...,  0.11174673,
         0.06821181,  0.08758762]], dtype=float32)

In [81]:
input_nodes

array([  5,   9,  18,  22,  57,  59,  75,  77,  81,  87, 104, 105, 110,
       111, 120, 128], dtype=int64)

In [82]:
weights.max()

0.19452395

In [83]:
weight_mean = np.mean(weights)
weight_std = np.std(weights)

In [84]:
weight_mean

-0.0026151484

In [85]:
weight_std

0.10784538

In [86]:
threshold =   2 * weight_std+weight_mean
threshold

0.21307561337016523

In [87]:
import csv

csv_file_path = 'sst.csv'
new_column_header = 'sst'
#new_column_data = ['data1', 'data2', 'data3']  # Replace with your actual data

# Create a new CSV file and write the header and data
with open(csv_file_path, 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow([new_column_header])  # Write the header row
    writer.writerows(zip(pp))  # Write the data as a new column


In [ ]:
# import csv

# csv_file_path = 'predictors.csv'
# new_column_header = 'slp'
# #new_column_data = ['data1', 'data2', 'data3']  # Replace with your actual data

# # Read the existing data from the CSV file
# existing_data = []
# with open(csv_file_path, 'r') as csvfile:
#     reader = csv.reader(csvfile)
#     existing_data = list(reader)

# # Modify the data by adding the new column
# header = existing_data[0]
# header.append(new_column_header)# Add the new column header to the header row
# if len(pp) == len(existing_data) - 1:
#     for i in range(1, len(pp)):
#         existing_data[i].append(pp[i - 1])  # Add the corresponding data to each row

# # Write the modified data back to the CSV file
# with open(csv_file_path, 'w', newline='') as csvfile:
#     writer = csv.writer(csvfile)
#     writer.writerows(existing_data)
