In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("pearson_corr.csv")
df_month

April_5    July_7     May_2   March_4  November_7  August_6  November  \
0   0.386355 -0.687068 -0.359395  0.248808    0.052698  0.085345  0.541902   
1   0.200515 -0.687068 -0.410397  0.332242    0.052698  0.085345  0.541902   
2   0.018638 -0.379167  0.172456  0.499594    0.284734  0.065937  0.607633   
3   0.151849 -0.152717 -0.222168  0.411549    0.236467  0.086337  0.524124   
4  -0.119454 -0.366530 -0.023508  0.627389    0.120395  0.074738  0.624625   
5   0.151046 -0.611835 -0.364834  0.355478    0.046850  0.146513  0.615718   
6   0.134536 -0.899686 -0.415197 -0.040398    0.324169  0.110645  0.766336   
7  -0.374646 -0.829043 -0.140117  0.596792   -0.087662  0.313885  0.243056   
8   0.330437 -0.550519 -0.279670  0.507744    0.113202  0.431951  0.880321   
9  -0.261064 -0.385054 -0.328111  0.639965   -0.288817  0.296296  0.571846   
10 -0.130175 -0.709560  0.170027  0.253567   -0.009334  0.265436  0.211560   
11  0.297414 -0.398548 -0.400712  0.088951    0.195103  0.382666  0.268865   
12  0.228194 -0.443008 -0.224018  0.340214    0.395684  0.205860  0.747025   
13  0.263182 -0.498184 -0.048799  0.507695    0.216831 -0.034867  0.538737   
14  0.018221 -0.803335 -0.420300  0.624821   -0.267971  0.917005  0.142763   
15  0.244438 -0.652178 -0.245389  0.185812    0.493068  0.518849  0.785315   
16 -0.057759 -0.802299  0.047781  0.449748    0.254794  0.526831  0.650781   
17  0.241546 -0.251446 -0.180453  0.273288    0.175710  0.607277  0.152672   
18  0.060977 -0.620700 -0.544819  0.643423   -0.186615  0.251135  0.207789   
19 -0.158738 -0.471164 -0.117589  0.236057    0.069466  0.369067  0.215516   
20  0.128186 -0.527260  0.019395  0.251580    0.114954  0.313666  0.676299   
21  0.039814 -0.611273 -0.271869  0.536246    0.109990 -0.050793 -0.058267   
22  0.254390 -0.214900 -0.104815  0.420757    0.106813  0.116295  0.547574   
23  0.162752 -0.682979 -0.523009  0.225938   -0.010500  0.648869  0.322339   
24 -0.325163 -0.949788 -0.169897  0.315319    0.261269  0.751988  0.586089   
25  0.240958 -0.575420  0.029600  0.210496    0.483188  0.111736  0.164034   
26  0.248294 -0.235262 -0.158876  0.583716    0.193171  0.114813  0.535310   
27 -0.150259 -0.555927 -0.081093  0.364228    0.258067  0.595125  0.390037   
28  0.035971 -0.291919 -0.339675  0.452587    0.193556  0.326716  0.870554   
29  0.093554 -0.734773 -0.493828  0.557545    0.060857  0.532125 -0.041049   
30  0.229925 -0.358387  0.200629 -0.014199    0.351876 -0.077501  0.915680   
31  0.087705 -0.480159 -0.168156  0.753165    0.347850 -0.196575  0.496599   
32 -0.242806 -1.214202 -0.045030  0.200290    0.159851  0.530737  0.397815   
33 -0.071024 -0.846969 -0.689440  0.528294    0.000512  0.198456  0.428175   
34 -0.119237 -0.788468 -0.899160  0.552526   -0.054222  0.558346  0.129697   
35  0.006782 -1.122272 -0.509467  0.572331    0.055553  0.298639  0.220968   
36  0.335751 -0.496194 -0.503257  0.785210    0.138587  0.112088  0.390511   
37 -0.024752 -0.768014 -0.070459  0.290894    0.039381  0.115234  0.480350   
38  0.357600 -0.377814  0.003027  0.397651    0.227297  0.097829  1.014231   
39 -0.298502 -1.053392 -0.559705  0.925974   -0.073056  0.643142  0.427786   
40  0.309806 -0.327206 -0.507612 -0.067446    0.646915 -0.077310  0.612599   
41  0.260029 -0.460937  0.108627  0.386976    0.462585  0.070006  0.874589   
42  0.317833 -0.752640  0.118036  0.312655   -0.046467  0.394538  0.626725   
43  0.044658 -0.899912 -0.064489  0.544122    0.308263  0.384435  0.513656   
44 -0.287725 -0.961909 -0.292402  0.403765    0.160125  0.312296  0.720926   
45  0.113775 -0.748140 -0.139222  0.162987    0.357364  0.380471  0.686093   
46  0.042116 -0.795032  0.035302  0.616137    0.185061  0.604197  0.327447   
47  0.262822 -0.500240 -0.241347 -0.190801    0.135361  0.218758  0.787701   
48 -0.102831 -0.587403 -0.384694 -0.067924    0.357362  0.201222  0.820154   
49  0.093623 -0.507547  0.148943  0.678800    0.492791  0.136164  0.817325   
50  0.179464 -0.617193 -0.0

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :15]
x_train = scaler.fit_transform(x_train)
x_train

array([[ 1.53368555e+00, -3.84487397e-01, -4.87202292e-01,
        -7.22479317e-01, -4.95022061e-01, -7.46555761e-01,
         2.33618405e-01, -3.91954107e-01, -4.30164029e-02,
         2.75800059e-01, -5.89997940e-02, -6.58722016e-01,
         1.31963847e+00, -4.97367549e-01, -1.35937604e+00],
       [ 6.15788713e-01, -3.84487397e-01, -6.94877406e-01,
        -3.36715104e-01, -4.95022061e-01, -7.46555761e-01,
         2.33618405e-01,  2.48668557e-01,  3.84577060e-01,
        -6.54532810e-01, -5.89997940e-02, -6.58722016e-01,
         6.98481849e-01, -6.88423348e-01, -1.35937604e+00],
       [-2.82533172e-01,  8.63461736e-01,  1.67843721e+00,
         4.37052850e-01,  6.95369884e-01, -8.24023004e-01,
         4.87584787e-01,  8.19597175e-01, -4.48761107e-01,
        -1.80526402e+00,  3.44226206e-01,  4.91949748e-01,
         6.87533742e-01, -1.94616493e+00, -1.57843932e+00],
       [ 3.75423122e-01,  1.78128222e+00,  7.15708272e-02,
         2.99719775e-02,  4.47751586e-01, -7.42596413

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [8]:
x_test = df_month.iloc[43:, :15]
x_test = scaler.fit_transform(x_test)
x_test

array([[ 7.87319585e-02, -8.81578560e-01,  4.25834674e-02,
         7.51161434e-01,  1.02643694e-02,  4.00308107e-01,
        -1.41065925e-01, -7.54285244e-01, -3.67154678e-01,
        -6.73029519e-01, -2.09978602e+00, -1.82757143e-01,
        -8.90995036e-01,  1.64003203e+00,  1.24050352e+00],
       [-2.16814405e+00, -1.15016991e+00, -1.03495855e+00,
         3.13416801e-01, -9.13397126e-01,  1.51862948e-03,
         7.94637958e-01, -1.99417989e+00, -1.47670052e-01,
         1.24679204e+00, -7.07576090e-01,  2.44015705e-02,
        -1.16092018e+00, -2.31684718e+00, -3.36299681e-01],
       [ 5.45961485e-01, -2.24059696e-01, -3.10746226e-01,
        -4.37526005e-01,  3.16412534e-01,  3.78397543e-01,
         6.37388871e-01,  3.03686959e-01,  1.61864952e+00,
        -6.93452795e-01, -4.45788545e-01, -7.22119409e-02,
        -4.65035645e-01, -1.00532145e-01,  2.18214391e+00],
       [ 6.15484005e-02, -4.27208561e-01,  5.14381723e-01,
         9.75764969e-01, -7.57913214e-01,  1.61516846

In [9]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] 
    y_test.append(y_ts)

In [10]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 47}
Best Score: 0.1787412907996394
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 7}
Best Score: 0.07716422639312598
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 27}
Best Score: 0.23314831099751004
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 49}
Best Score: 0.22919581161011326
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 4}
Best Score: 0.06961319516345094


In [13]:
y_pred_list

[array([ 0.26647437,  0.57494455, -0.24482811,  0.37696907, -0.11482668,
        -0.46432619, -0.45760594, -0.05754948,  0.05801871, -0.49041862,
         0.02884758,  0.17621207, -0.61737162,  0.33233277, -0.01076358,
        -0.61221484]),
 array([-0.0167027 ,  0.22532984, -0.15210078,  0.35646671, -0.13331607,
        -0.38839883, -0.55738517,  0.06314973, -0.22121517, -0.17293336,
         0.04462396, -0.13695692, -0.5935523 ,  0.50078836,  0.17393729,
        -0.38988708]),
 array([-0.00605082,  0.44303071, -0.24518554,  0.31814285, -0.03755809,
        -0.56119081, -0.39928154,  0.09567413, -0.12625172, -0.45496884,
         0.2097933 , -0.15805677, -0.56516729,  0.35119928, -0.00687428,
        -0.6050918 ]),
 array([ 0.27449259,  0.66108335, -0.20867156,  0.3101733 , -0.04956723,
        -0.44768307, -0.41364453, -0.07296683,  0.293423  , -0.69267352,
         0.04999919,  0.37711919, -0.5266167 ,  0.36616387,  0.20470887,
        -0.64849622]),
 array([ 0.26445502,  1.057     

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.5132170924938808,
 0.43748040197290283,
 0.4362221699217426,
 0.650128215326741,
 0.48457070415394116]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/GPH/15 predictors/pearson/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'GPH (2001-2016) 15p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'15p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/GPH/15 predictors/pearson/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/GPH/15 predictors/pearson/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'GPH Predicted vs Actual 15p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'15p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/GPH/15 predictors/pearson/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:

y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 47}
Best Score: 0.1787412907996394
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 7}
Best Score: 0.07716422639312598
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 27}
Best Score: 0.23314831099751004
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 49}
Best Score: 0.22919581161011326
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 4}
Best Score: 0.06961319516345094


In [21]:
y_pred_list_rf

[array([ 0.26647437,  0.57494455, -0.24482811,  0.37696907, -0.11482668,
        -0.46432619, -0.45760594, -0.05754948,  0.05801871, -0.49041862,
         0.02884758,  0.17621207, -0.61737162,  0.33233277, -0.01076358,
        -0.61221484]),
 array([-0.0167027 ,  0.22532984, -0.15210078,  0.35646671, -0.13331607,
        -0.38839883, -0.55738517,  0.06314973, -0.22121517, -0.17293336,
         0.04462396, -0.13695692, -0.5935523 ,  0.50078836,  0.17393729,
        -0.38988708]),
 array([-0.00605082,  0.44303071, -0.24518554,  0.31814285, -0.03755809,
        -0.56119081, -0.39928154,  0.09567413, -0.12625172, -0.45496884,
         0.2097933 , -0.15805677, -0.56516729,  0.35119928, -0.00687428,
        -0.6050918 ]),
 array([ 0.27449259,  0.66108335, -0.20867156,  0.3101733 , -0.04956723,
        -0.44768307, -0.41364453, -0.07296683,  0.293423  , -0.69267352,
         0.04999919,  0.37711919, -0.5266167 ,  0.36616387,  0.20470887,
        -0.64849622]),
 array([ 0.26445502,  1.057     

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.5132170924938808,
 0.43748040197290283,
 0.4362221699217426,
 0.650128215326741,
 0.48457070415394116]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/GPH/15 predictors/pearson/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'GPH (2001-2016) 15p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'15_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/GPH/15 predictors/pearson/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/GPH/15 predictors/pearson/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'GPH Predicted vs Actual 15p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'15p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/GPH/15 predictors/pearson/comparison plots/randomforest
