In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("kendall_corr.csv")
df_month

May_5  December     May_7       May   April_2  November_3   March_2  \
0   0.313200 -0.346315  0.710976  0.359581  0.084560   -0.596723 -0.522800   
1   0.356062 -0.346315  0.826522  0.444494  0.053162   -0.596723 -0.360933   
2   0.599995 -0.433923  0.541607  0.006345 -0.243489   -0.485163 -0.236472   
3   0.282180 -0.696828  0.865502  0.338369 -0.006795   -0.563371 -0.228254   
4   0.434114 -0.613563  0.557727  0.010838 -0.215218   -0.308393 -0.237256   
5   0.496766 -0.582546  0.673865  0.328808 -0.125061   -0.545654 -0.214241   
6   0.479629 -0.629193  0.327384  0.541366  0.224730    0.071710 -0.044161   
7   0.324634 -0.197325  0.724865  0.268308 -0.037644   -0.275878 -0.516501   
8   0.401587 -0.343663  0.655690  0.132932 -0.157339   -0.124376 -0.114679   
9   0.573596 -0.467842  0.711807  0.370820 -0.107566   -0.125701 -0.479743   
10  0.438417 -0.217902  0.551966 -0.007212  0.026804   -0.416915 -0.422443   
11  0.376374 -0.878123  0.706308  0.266756 -0.001244   -0.086526 -0.319558   
12  0.556534 -0.436839  0.623050  0.141138 -0.101825   -0.557509 -0.083911   
13  0.797434 -0.483410  0.465765 -0.288695  0.153887   -0.506586  0.036279   
14  0.643691 -0.111745  1.117086  0.360439 -0.185428   -0.762569 -0.194696   
15  0.348327 -1.140343  0.517156  0.005684  0.266833   -0.156788 -0.181545   
16  0.786566 -0.514573  0.480896  0.079455  0.189472   -0.162263  0.115011   
17  0.997224 -0.560724  0.374139 -0.108561  0.079522   -0.141452 -0.403741   
18  0.599369 -0.266064  0.418918  0.329294 -0.155210   -0.430647  0.072640   
19  0.311011 -0.300070  0.668914  0.084361 -0.156039   -0.544956  0.081568   
20  0.384169 -0.811855  0.688188  0.068076 -0.204307   -0.696271 -0.489968   
21  0.694259 -0.383486  0.588697  0.190657 -0.114931   -0.916670 -0.251027   
22  0.277925 -0.596405  0.536036  0.311572 -0.115574   -0.893332 -0.606166   
23  0.441042 -0.542055  0.626219  0.394596 -0.081767   -0.212768 -0.309297   
24  0.345690 -0.442951  0.634297  0.233311 -0.216177   -0.915535 -0.675196   
25  0.462511 -0.466116  1.031377  0.353202 -0.195924    0.089388 -0.881626   
26  0.723519 -0.718947  0.885332  0.014647  0.182378   -1.007868 -0.330994   
27  0.675977 -0.636684  0.426803 -0.073985 -0.280346   -0.201970 -0.153487   
28  0.210422 -0.414672  0.715192  0.264451 -0.254935   -0.546150 -0.348820   
29  0.011522 -0.200085  0.498724  0.036712 -0.036059   -0.925854 -0.600703   
30  0.446001 -0.753702  0.209230 -0.022119  0.124317   -0.403305 -0.403416   
31  0.460634 -0.454308  0.037412  0.178908  0.109447   -0.595239 -0.539970   
32  0.309041 -0.377524  0.392225  0.034094 -0.228891   -0.582787 -0.609432   
33  0.216731 -0.636146  0.673147  0.183504  0.035198   -0.014007 -0.577317   
34  0.193871 -0.460876  0.768000  0.606067 -0.475166   -0.466996 -0.590221   
35  0.179747 -0.661824  0.509759  0.329877 -0.240546   -0.718152 -0.774871   
36  0.081266 -0.901798  0.697365  0.422557  0.074274   -0.612216 -0.325645   
37  0.127788 -0.662773  0.303363  0.071152  0.083801   -0.425725 -0.723156   
38  0.431013 -0.608975  0.283603  0.116396  0.079501   -0.689828 -0.467654   
39  0.134610 -0.552806  0.820970  0.204525 -0.231056   -0.882626 -0.782097   
40  0.797112 -0.662845  0.527442  0.455174  0.182616   -0.104801 -0.486892   
41  0.696459 -0.496146  0.178335 -0.064148  0.490155   -0.257812 -0.151652   
42  0.612400 -0.430501  0.434047 -0.042794  0.375951   -0.481036 -0.574770   
43  0.465601 -0.412981  0.476015  0.016701 -0.109276    0.115509 -0.414674   
44  0.412288 -0.261639  0.889475  0.247731 -0.237479   -0.668310 -1.003376   
45  0.345474 -0.358545  0.079300  0.222660 -0.013247   -0.664868 -0.371065   
46  0.246674  0.063299  0.412308  0.012310  0.141053   -0.539534 -0.793722   
47  0.037423 -0.362536  0.487214  0.049564 -0.192501   -0.257848 -0.643003   
48  0.289618  0.090618  0.204310  0.009869  0.338130   -0.457026 -0.554162   
49  0.436520 -0.657101  0.741787 -0.132386 -0.056494   -0.085792  0.008202   
50  0.238579 -0.251158  0.544

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :5]
x_train = scaler.fit_transform(x_train)
x_train

array([[-5.79647404e-01,  8.70065530e-01,  5.83981349e-01,
         8.87015495e-01,  6.81641991e-01],
       [-3.81405603e-01,  8.70065530e-01,  1.11778529e+00,
         1.33077281e+00,  5.11376255e-01],
       [ 7.46835017e-01,  4.41207972e-01, -1.98474592e-01,
        -9.59004921e-01, -1.09729345e+00],
       [-7.23125050e-01, -8.45756411e-01,  1.29786609e+00,
         7.76157542e-01,  1.86245778e-01],
       [-2.03974384e-02, -4.38159229e-01, -1.24000383e-01,
        -9.35529454e-01, -9.43983494e-01],
       [ 2.69380866e-01, -2.86329292e-01,  4.12538028e-01,
         7.26194561e-01, -4.55084766e-01],
       [ 1.90115751e-01, -5.14671747e-01, -1.18814581e+00,
         1.83702733e+00,  1.44174955e+00],
       [-5.26762876e-01,  1.59940119e+00,  6.48148224e-01,
         4.10015721e-01,  1.89561460e-02],
       [-1.70840024e-01,  8.83047626e-01,  3.28571510e-01,
        -2.97459267e-01, -6.30119058e-01],
       [ 6.24733881e-01,  2.75171941e-01,  5.87821111e-01,
         9.45749576e-01

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [8]:
x_test = df_month.iloc[43:, :5]
x_test = scaler.fit_transform(x_test)
x_test

array([[ 0.32086694, -0.85435037, -0.12167892, -0.30401138, -0.51707718],
       [ 0.0923005 , -0.13144464,  1.5878626 ,  0.86430999, -1.0850996 ],
       [-0.19414759, -0.59433235, -1.76198836,  0.73752794, -0.09160704],
       [-0.61772835,  1.42066386, -0.3850921 , -0.32621988,  0.59203959],
       [-1.51483587, -0.61339274, -0.07537512, -0.1378226 , -0.88581601],
       [-0.43361694,  1.55115553, -1.24510708, -0.33856368,  1.46521916],
       [ 0.19618846, -2.02042174,  0.97721197, -1.05795106, -0.28322009],
       [-0.65243368, -0.08138073,  0.16098657, -0.08921531,  1.28817618],
       [ 0.75122941, -0.83675262,  1.39022186,  0.65478089,  0.54543904],
       [ 0.74788876,  0.64421667, -1.18822989, -1.94206257,  1.0700724 ],
       [ 2.3754028 ,  1.82265455, -0.9731417 , -0.63683933,  1.41562717],
       [ 0.61506139, -0.17692461,  0.83938856, -0.04591372, -0.59658018],
       [ 1.44099365,  0.3456758 , -0.88752485, -1.01488979,  0.56015059],
       [-0.88542952,  0.05459723, -0.2

In [9]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] 
    y_test.append(y_ts)

In [10]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 7}
Best Score: 0.449464692360398
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 13}
Best Score: 0.43995412029853037
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 15}
Best Score: 0.21032594002442218
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 6}
Best Score: 0.40990009960648943
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 6}
Best Score: 0.33462394461170347


In [13]:
y_pred_list

[array([-0.08059678,  0.04673895, -0.0735143 ,  0.44330128,  0.62300637,
         0.40565476,  0.02783503, -0.35422078,  0.05743736, -0.74907738,
        -0.1293254 ,  0.0285017 , -0.28385346,  0.16699988,  0.21620604,
         0.29989598]),
 array([ 0.01535686,  0.01535686, -0.14938194,  0.21058436,  0.48732819,
        -0.41259593,  0.01535686, -0.27957029, -0.05997648, -0.75330577,
        -0.71970235,  0.01535686, -0.3009719 ,  0.20695182,  0.30723154,
         0.4547128 ]),
 array([-0.08966985,  0.03811426, -0.14136843,  0.28561505,  0.34168947,
        -0.05419683, -0.09733116, -0.28605457, -0.18457522, -0.74872211,
        -0.3307496 , -0.05636123, -0.44320724,  0.17600915,  0.43501815,
         0.31033321]),
 array([-0.04170378,  0.0302486 , -0.24996589,  0.17746289,  0.3951801 ,
        -0.08      ,  0.3277486 , -0.01269231,  0.0302486 , -0.95560185,
        -0.25375   ,  0.3277486 , -0.18672515, -0.04170378, -0.00641806,
         0.3277486 ]),
 array([-0.21074568,  0.22418365

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.5323544033957743,
 0.6080626656914595,
 0.6141948630928715,
 0.4093838498800967,
 0.36449124592924687]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Air_Temperature/5 predictors/kendall/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'Air_Temperature (2001-2016) 5p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Air_Temperature/5 predictors/kendall/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Air_Temperature/5 predictors/kendall/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'Air_Temperature Predicted vs Actual 5p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Air_Temperature/5 predictors/kendall/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:

y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 7}
Best Score: 0.449464692360398
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 13}
Best Score: 0.43995412029853037
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 15}
Best Score: 0.21032594002442218
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 6}
Best Score: 0.40990009960648943
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 6}
Best Score: 0.33462394461170347


In [21]:
y_pred_list_rf

[array([-0.08059678,  0.04673895, -0.0735143 ,  0.44330128,  0.62300637,
         0.40565476,  0.02783503, -0.35422078,  0.05743736, -0.74907738,
        -0.1293254 ,  0.0285017 , -0.28385346,  0.16699988,  0.21620604,
         0.29989598]),
 array([ 0.01535686,  0.01535686, -0.14938194,  0.21058436,  0.48732819,
        -0.41259593,  0.01535686, -0.27957029, -0.05997648, -0.75330577,
        -0.71970235,  0.01535686, -0.3009719 ,  0.20695182,  0.30723154,
         0.4547128 ]),
 array([-0.08966985,  0.03811426, -0.14136843,  0.28561505,  0.34168947,
        -0.05419683, -0.09733116, -0.28605457, -0.18457522, -0.74872211,
        -0.3307496 , -0.05636123, -0.44320724,  0.17600915,  0.43501815,
         0.31033321]),
 array([-0.04170378,  0.0302486 , -0.24996589,  0.17746289,  0.3951801 ,
        -0.08      ,  0.3277486 , -0.01269231,  0.0302486 , -0.95560185,
        -0.25375   ,  0.3277486 , -0.18672515, -0.04170378, -0.00641806,
         0.3277486 ]),
 array([-0.21074568,  0.22418365

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.5323544033957743,
 0.6080626656914595,
 0.6141948630928715,
 0.4093838498800967,
 0.36449124592924687]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Air_Temperature/5 predictors/kendall/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'Air_Temperature (2001-2016) 5p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Air_Temperature/5 predictors/kendall/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Air_Temperature/5 predictors/kendall/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'Air_Temperature Predicted vs Actual 5p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'5p{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Air_Temperature/5 predictors/kendall/comparison plots/randomforest
