In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("kendall_corr.csv")
df_month

November_3     May_4     May_9    June_5     May_3     May_8    June_4  \
0     0.092858  0.065741 -0.337310 -0.507901  0.033686 -0.676793  0.111761   
1     0.092858  0.061658 -0.290004 -0.507901 -0.016299 -0.213397  0.111761   
2    -0.144591  0.022404 -0.085953 -0.343425 -0.463674  0.376218  0.628831   
3     0.211338  0.277889 -0.161828 -0.256383 -0.300338 -0.143403  0.361572   
4     0.227199  0.221217 -0.055905 -0.333727 -0.444215  0.515070  0.131819   
5     0.489400  0.055913 -0.202906 -0.301398 -0.054209 -0.538951 -0.396615   
6     0.126746  0.217356 -0.197503 -0.443026 -0.288842  0.322864  0.469586   
7     0.238995 -0.190489 -0.571212 -0.247822 -0.170438 -0.214216  0.179807   
8     0.179015  0.263546 -0.407680 -0.469433 -0.436033  0.160824  0.577831   
9     0.141883 -0.104601 -0.403877 -0.512329 -0.333610 -0.016718  0.507636   
10    0.455007 -0.338356 -0.353567 -0.265612 -0.383026  0.228922  0.507752   
11    0.179135 -0.439336 -0.468382 -0.312831  0.036061 -0.229900  0.204858   
12    0.005040  0.952202 -0.157656 -0.289191 -0.324753 -0.030709  0.446252   
13    0.223754  0.284914 -0.357723 -0.457938 -0.244825  0.337207  0.642617   
14    0.633382 -0.035865 -0.508596 -0.317867  0.288398 -0.517346  0.396938   
15    0.032299  0.372827 -0.328302 -0.405808 -0.190055  0.134008  0.652942   
16    0.219758  0.331880 -0.343313 -0.279303 -0.184535  0.360228  0.661218   
17    0.188692  0.405057 -0.273289 -0.430021 -0.049467  0.249421  0.446942   
18    0.351217  0.116308 -0.392977 -0.472817  0.080598  0.012463  0.687818   
19    0.362247  0.313823 -0.529498 -0.225282  0.107968  0.310589  0.519403   
20    0.155631  0.237816 -0.495646 -0.512943  0.011640  0.181356  0.699274   
21    0.519816  0.351049 -0.330601 -0.425709  0.013251 -0.114694  0.614956   
22    0.257569  0.148564 -0.570847 -0.547034  0.026293  0.088831  0.631935   
23    0.247586  0.194159 -0.288451 -0.348933 -0.022313  0.076044  0.559422   
24    0.245470  0.001336 -0.551817 -0.527180  0.175453 -0.046078  0.286124   
25    0.312631  0.334786 -0.628421 -0.625973 -0.104295 -0.074674  1.208381   
26    0.307192  0.566342 -0.437272 -0.402614 -0.045316 -0.065765  0.498734   
27    0.023683  0.395951 -0.615443 -0.596399 -0.127414  0.114085  0.728445   
28    0.303569 -0.513305 -0.678252 -0.468159  0.072611  0.124737  0.485632   
29    0.539929  0.118798 -0.757983 -0.259841  0.105673 -0.246756 -0.060961   
30    0.435356  0.181709 -0.558631 -0.723380  0.196485  0.364203  0.484193   
31    0.317446  0.716615 -0.038487 -0.623419 -0.060383  0.646683  0.631757   
32    0.183706  0.689553 -0.376851 -0.243628 -0.400219  0.218782  0.632023   
33    0.180805  0.111346 -0.538462 -0.269600  0.124658  0.000791  0.158368   
34    0.437062 -0.411987 -0.727665 -0.427091 -0.275532 -0.027459  0.341042   
35    0.243300  0.583618 -0.398867 -0.131301  0.115020 -0.062084  0.815168   
36    0.384718  0.028672 -0.678270 -0.352882  0.102976 -0.292142  0.223709   
37    0.245904  0.626141 -0.122335 -0.144636 -0.136691  0.508471  0.632898   
38    0.227608  0.233171 -0.418038 -0.409067 -0.010835  0.534231  0.601004   
39    0.518986 -0.664347 -0.708745 -0.323314  0.146041 -0.036007  0.462807   
40    0.241738  0.455446 -0.626410 -0.615711 -0.209499  0.315334  1.589115   
41   -0.077160  0.132404 -0.246301 -0.517482  0.023879  0.801749  0.249421   
42    0.191081  0.203907 -0.380387 -0.333935 -0.123845  0.770140  0.726621   
43    0.215475  0.456425 -0.484326 -0.361383 -0.076077  0.418798  0.495013   
44    0.291262 -0.425534 -0.676542 -0.230283  0.142268 -0.071165 -0.224310   
45    0.270770  0.139935 -0.321186 -0.454762 -0.080917  0.552208 -0.049729   
46    0.129345 -0.325004 -0.722667 -0.235599  0.071140  0.146915  0.159311   
47    0.535029  0.279782 -0.345180 -0.447505 -0.156982  0.524433  0.334759   
48    0.198802  0.871391  0.057364 -0.341785 -0.123676  0.127219  0.297363   
49    0.015515  0.140839 -0.074095 -0.486741 -0.149642  0.260533  0.603464   
50    0.216498  0.491093 -

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :5]
x_train = scaler.fit_transform(x_train)
x_train

array([[-0.96468849, -0.33190537,  0.3838594 , -0.78182293,  0.6181742 ],
       [-0.96468849, -0.34424987,  0.63356955, -0.78182293,  0.36021422],
       [-2.40950299, -0.46292821,  1.71066054,  0.4303418 , -1.94857237],
       [-0.24376667,  0.30949184,  1.31015467,  1.07182663, -1.10563495],
       [-0.14725503,  0.13815042,  1.86927352,  0.50181257, -1.84814799],
       [ 1.44817587, -0.36161923,  1.09331683,  0.74007842,  0.16457332],
       [-0.75848523,  0.12647701,  1.12183791, -0.3037024 , -1.04630678],
       [-0.07548051, -1.10657559, -0.85080905,  1.13492277, -0.43525521],
       [-0.44044325,  0.26612801,  0.01240458, -0.49832272, -1.80592121],
       [-0.66637998, -0.84690754,  0.03248278, -0.81445989, -1.27734316],
       [ 1.23890484, -1.55362832,  0.29804364,  1.00381283, -1.5323652 ],
       [-0.43970902, -1.85892789, -0.3080127 ,  0.65581609,  0.6304324 ],
       [-1.49903569,  2.34817116,  1.33217477,  0.8300421 , -1.23163593],
       [-0.16821411,  0.33073007,  0.2

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [8]:
x_test = df_month.iloc[43:, :5]
x_test = scaler.fit_transform(x_test)
x_test

array([[-0.13320599,  0.51902901, -0.49191253,  0.19748644, -0.01166501],
       [ 0.28521327, -1.64900072, -1.19844819,  1.19170479,  1.18829611],
       [ 0.172075  , -0.25896521,  0.10774594, -0.51067382, -0.03826249],
       [-0.60872528, -1.40187958, -1.36799065,  1.15139561,  0.79739778],
       [ 1.63103885,  0.08480577,  0.01954931, -0.45563463, -0.45629377],
       [-0.22525825,  1.53910041,  1.49919519,  0.34610784, -0.27325677],
       [-1.23717723, -0.25674317,  1.01598805, -0.75319284, -0.41595585],
       [-0.12755875,  0.60425039,  0.89098611, -0.44549423, -1.01904208],
       [ 0.50997758, -0.06938458, -0.04937659, -0.14385512,  2.11733752],
       [-1.24824839,  0.85516781,  1.50016142, -1.17518175, -0.17260434],
       [-0.96025619,  1.62471856,  1.5302261 , -2.5683223 , -1.26838503],
       [ 1.23042144,  0.85459774, -0.13587812, -0.39864439, -0.50681666],
       [ 1.00280678,  0.52717042, -0.46917584,  0.94305665,  0.06727486],
       [ 1.51359616, -0.34801057, -0.2

In [9]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] 
    y_test.append(y_ts)

In [10]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 29}
Best Score: 0.34424322473556346
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 27}
Best Score: 0.24011256559088634
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 47}
Best Score: 0.32657801425257715
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 6}
Best Score: 0.37787799416682116
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 19}
Best Score: 0.4129503737183921


In [13]:
y_pred_list

[array([-0.31725477,  0.78995588,  0.12454337,  0.35521924, -0.29231145,
        -0.47281594, -0.29392512, -0.5335644 , -0.07960419, -0.7215405 ,
        -0.69758031, -0.36643371, -0.22391532,  0.4899622 ,  0.77587036,
         0.14175347]),
 array([-3.02144189e-01,  7.75922602e-01, -3.59119496e-02,  2.75409742e-01,
        -2.35750392e-01, -5.10275818e-01, -3.77028898e-01, -5.34359604e-01,
        -3.75069838e-03, -6.90743066e-01, -6.52968530e-01, -3.57377075e-01,
        -1.73253498e-01,  9.88069107e-02,  8.05595442e-01,  2.98059965e-04]),
 array([-0.39059165,  0.67226647,  0.0468071 ,  0.43823826, -0.2392293 ,
        -0.58554038, -0.3000394 , -0.58292739, -0.23325389, -0.78695639,
        -0.78667389, -0.36861937, -0.18348022,  0.54100946,  0.61656145,
         0.18182621]),
 array([-0.20594332,  1.11083333,  0.09434445,  0.77619048, -0.44808114,
        -0.48814773, -0.23530844, -0.56981439, -0.33048718, -0.69223701,
        -0.69223701, -0.52833114, -0.41645614,  0.40743969,  1.0

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.7385073954260949,
 0.8365602333395348,
 0.6265663904360909,
 0.5863689902807314,
 0.7399500626215234]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+uwind/5 predictors/kendall/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'slp+uwind (2001-2016) 5p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+uwind/5 predictors/kendall/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+uwind/5 predictors/kendall/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'slp+uwind Predicted vs Actual 5p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+uwind/5 predictors/kendall/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:

y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 29}
Best Score: 0.34424322473556346
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 27}
Best Score: 0.24011256559088634
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 47}
Best Score: 0.32657801425257715
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 6}
Best Score: 0.37787799416682116
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 19}
Best Score: 0.4129503737183921


In [21]:
y_pred_list_rf

[array([-0.31725477,  0.78995588,  0.12454337,  0.35521924, -0.29231145,
        -0.47281594, -0.29392512, -0.5335644 , -0.07960419, -0.7215405 ,
        -0.69758031, -0.36643371, -0.22391532,  0.4899622 ,  0.77587036,
         0.14175347]),
 array([-3.02144189e-01,  7.75922602e-01, -3.59119496e-02,  2.75409742e-01,
        -2.35750392e-01, -5.10275818e-01, -3.77028898e-01, -5.34359604e-01,
        -3.75069838e-03, -6.90743066e-01, -6.52968530e-01, -3.57377075e-01,
        -1.73253498e-01,  9.88069107e-02,  8.05595442e-01,  2.98059965e-04]),
 array([-0.39059165,  0.67226647,  0.0468071 ,  0.43823826, -0.2392293 ,
        -0.58554038, -0.3000394 , -0.58292739, -0.23325389, -0.78695639,
        -0.78667389, -0.36861937, -0.18348022,  0.54100946,  0.61656145,
         0.18182621]),
 array([-0.20594332,  1.11083333,  0.09434445,  0.77619048, -0.44808114,
        -0.48814773, -0.23530844, -0.56981439, -0.33048718, -0.69223701,
        -0.69223701, -0.52833114, -0.41645614,  0.40743969,  1.0

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.7385073954260949,
 0.8365602333395348,
 0.6265663904360909,
 0.5863689902807314,
 0.7399500626215234]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+uwind/5 predictors/kendall/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'slp+uwind (2001-2016) 5p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+uwind/5 predictors/kendall/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+uwind/5 predictors/kendall/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'slp+uwind Predicted vs Actual 5p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'5p{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+uwind/5 predictors/kendall/comparison plots/randomforest
