In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("pearson_corr.csv")
df_month

May_8    May_10     May_4  November_2       May     March    July_2  \
0   0.313200  0.710976 -0.252040   -0.596723  0.359581 -0.522800  0.319933   
1   0.356062  0.826522  0.129979   -0.596723  0.444494 -0.360933  0.319933   
2   0.599995  0.541607  0.065225   -0.485163  0.006345 -0.236472  0.125910   
3   0.282180  0.865502 -0.030861   -0.563371  0.338369 -0.228254  0.279526   
4   0.434114  0.557727 -0.201459   -0.308393  0.010838 -0.237256  0.220343   
5   0.496766  0.673865 -0.144439   -0.545654  0.328808 -0.214241  0.439730   
6   0.479629  0.327384  0.161632    0.071710  0.541366 -0.044161  0.579496   
7   0.324634  0.724865 -0.064923   -0.275878  0.268308 -0.516501  0.567989   
8   0.401587  0.655690 -0.069111   -0.124376  0.132932 -0.114679  0.033281   
9   0.573596  0.711807 -0.104181   -0.125701  0.370820 -0.479743  0.135141   
10  0.438417  0.551966  0.103396   -0.416915 -0.007212 -0.422443  0.594343   
11  0.376374  0.706308 -0.186416   -0.086526  0.266756 -0.319558  0.340085   
12  0.556534  0.623050 -0.020382   -0.557509  0.141138 -0.083911  0.037228   
13  0.797434  0.465765  0.179514   -0.506586 -0.288695  0.036279  0.046321   
14  0.643691  1.117086 -0.170832   -0.762569  0.360439 -0.194696  0.273730   
15  0.348327  0.517156 -0.011055   -0.156788  0.005684 -0.181545  0.062215   
16  0.786566  0.480896 -0.044857   -0.162263  0.079455  0.115011  0.259600   
17  0.997224  0.374139  0.172604   -0.141452 -0.108561 -0.403741  0.091850   
18  0.599369  0.418918  0.137751   -0.430647  0.329294  0.072640 -0.043489   
19  0.311011  0.668914  0.146347   -0.544956  0.084361  0.081568 -0.069567   
20  0.384169  0.688188  0.073591   -0.696271  0.068076 -0.489968  0.213820   
21  0.694259  0.588697 -0.407518   -0.916670  0.190657 -0.251027  0.570422   
22  0.277925  0.536036 -0.077876   -0.893332  0.311572 -0.606166 -0.129914   
23  0.441042  0.626219  0.028402   -0.212768  0.394596 -0.309297  0.359164   
24  0.345690  0.634297 -0.192132   -0.915535  0.233311 -0.675196  0.497334   
25  0.462511  1.031377  0.179348    0.089388  0.353202 -0.881626  0.043876   
26  0.723519  0.885332 -0.329477   -1.007868  0.014647 -0.330994 -0.361026   
27  0.675977  0.426803 -0.069059   -0.201970 -0.073985 -0.153487  0.485387   
28  0.210422  0.715192  0.055606   -0.546150  0.264451 -0.348820  0.246946   
29  0.011522  0.498724 -0.295399   -0.925854  0.036712 -0.600703  0.352775   
30  0.446001  0.209230  0.387446   -0.403305 -0.022119 -0.403416 -0.016401   
31  0.460634  0.037412  0.368726   -0.595239  0.178908 -0.539970 -0.045673   
32  0.309041  0.392225  0.149879   -0.582787  0.034094 -0.609432  0.521449   
33  0.216731  0.673147  0.030103   -0.014007  0.183504 -0.577317  0.536095   
34  0.193871  0.768000 -0.521802   -0.466996  0.606067 -0.590221  0.184816   
35  0.179747  0.509759 -0.090867   -0.718152  0.329877 -0.774871 -0.048749   
36  0.081266  0.697365 -0.173392   -0.612216  0.422557 -0.325645  0.132264   
37  0.127788  0.303363  0.236434   -0.425725  0.071152 -0.723156 -0.042851   
38  0.431013  0.283603  0.221259   -0.689828  0.116396 -0.467654  0.031621   
39  0.134610  0.820970 -0.459848   -0.882626  0.204525 -0.782097  0.613616   
40  0.797112  0.527442 -0.016955   -0.104801  0.455174 -0.486892 -0.062402   
41  0.696459  0.178335  0.127935   -0.257812 -0.064148 -0.151652  0.363385   
42  0.612400  0.434047  0.104816   -0.481036 -0.042794 -0.574770 -0.017912   
43  0.465601  0.476015 -0.366355    0.115509  0.016701 -0.414674  0.335724   
44  0.412288  0.889475  0.040961   -0.668310  0.247731 -1.003376  0.206966   
45  0.345474  0.079300  0.094450   -0.664868  0.222660 -0.371065  0.212501   
46  0.246674  0.412308  0.071785   -0.539534  0.012310 -0.793722  0.101970   
47  0.037423  0.487214 -0.164844   -0.257848  0.049564 -0.643003  0.068561   
48  0.289618  0.204310  0.274152   -0.457026  0.009869 -0.554162  0.222107   
49  0.436520  0.741787 -0.160953   -0.085792 -0.132386  0.008202  0.204816   
50  0.238579  0.544379  0.439

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :10]
x_train = scaler.fit_transform(x_train)
x_train

array([[-5.79647404e-01,  5.83981349e-01, -1.11921520e+00,
        -4.75959269e-01,  8.87015495e-01, -6.44124823e-01,
         4.40951385e-01, -2.14436459e-01,  8.70065530e-01,
        -2.57276936e-02],
       [-3.81405603e-01,  1.11778529e+00,  7.50204399e-01,
        -4.75959269e-01,  1.33077281e+00,  1.71042109e-02,
         4.40951385e-01, -2.14436459e-01,  8.70065530e-01,
        -2.57276936e-02],
       [ 7.46835017e-01, -1.98474592e-01,  4.33325606e-01,
        -8.91444447e-02, -9.59004921e-01,  5.25528346e-01,
        -3.79879376e-01,  2.16136619e-01,  4.41207972e-01,
         3.63919747e-01],
       [-7.23125050e-01,  1.29786609e+00, -3.68705361e-02,
        -3.60318579e-01,  7.76157542e-01,  5.59100915e-01,
         2.70008912e-01,  1.39786106e-02, -8.45756411e-01,
        -1.12426713e+00],
       [-2.03974384e-02, -1.24000383e-01, -8.71697143e-01,
         5.23770684e-01, -9.35529454e-01,  5.22326510e-01,
         1.96272969e-02,  1.87703493e-01, -4.38159229e-01,
         1.

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [8]:
x_test = df_month.iloc[43:, :10]
x_test = scaler.fit_transform(x_test)
x_test

array([[ 0.32086694, -0.12167892, -1.75140408,  2.00232052, -0.30401138,
         0.28095709,  0.78676754,  0.44688104, -0.85435037,  0.73311563],
       [ 0.0923005 ,  1.5878626 , -0.04213887, -1.1928054 ,  0.86430999,
        -1.93214909, -0.02322927,  0.43438104, -0.13144464, -0.44605376],
       [-0.19414759, -1.76198836,  0.1823223 , -1.17877464,  0.73752794,
         0.4448952 ,  0.01159164, -1.96149241, -0.59433235,  1.74340186],
       [-0.61772835, -0.3850921 ,  0.08721356, -0.6678713 , -0.32621988,
        -1.14399541, -0.68374505, -0.29482454,  1.42066386,  1.18994303],
       [-1.51483587, -0.07537512, -0.9057813 ,  0.48038534, -0.1378226 ,
        -0.5773976 , -0.89391715, -1.29000006, -0.61339274, -0.4760575 ],
       [-0.43361694, -1.24510708,  0.93642492, -0.33153674, -0.33856368,
        -0.24342098,  0.07201837,  0.73684113,  1.55115553, -1.96631631],
       [ 0.19618846,  0.97721197, -0.88945005,  1.18174685, -1.05795106,
         1.87067633, -0.03675523, -0.67251383

In [9]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] 
    y_test.append(y_ts)

In [10]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 15}
Best Score: 0.3935616705125041
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 8}
Best Score: 0.336979694625004
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 6}
Best Score: 0.2866146784346373
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 13}
Best Score: 0.4632621910798335
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 4}
Best Score: 0.22764766672695863


In [13]:
y_pred_list

[array([-0.13069731,  0.08491905, -0.32863195,  0.37881574,  0.40698681,
         0.59774583, -0.36791733, -0.00695686,  0.15105855, -0.43851389,
         0.46406944, -0.42261891, -0.45111257,  0.71809453,  0.4730332 ,
        -0.0065744 ]),
 array([-0.39998859,  0.51864559, -0.22021167,  0.53269132, -0.03514255,
         0.10074468, -0.25376274, -0.26613402,  0.12663721, -0.47086523,
        -0.00977228, -0.48475422, -0.30889207,  0.69328621,  0.49322   ,
        -0.18746736]),
 array([-0.21625   , -0.22408009, -0.37454762,  0.18041667,  0.26783333,
         0.63166667, -0.4188254 ,  0.06686111,  0.38553571, -0.30001263,
         0.84333333, -0.65887302,  0.11863889,  0.87388889,  0.24097222,
        -0.00633333]),
 array([-0.00113003,  0.06372629, -0.49431578,  0.17947114,  0.40123911,
         0.591     , -0.09042406, -0.09136454, -0.02649713, -0.21301874,
         0.5470979 , -0.23628357, -0.32136085,  0.66809777,  0.68589265,
        -0.10176314]),
 array([-0.030625  ,  0.88834559

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.47136477025762047,
 0.7419013729932671,
 0.10791896414983188,
 0.36718221217422303,
 0.4243788178383337]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Air_Temperature/10 predictors/pearson/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'Air_Temperature (2001-2016) 10p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'10p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Air_Temperature/10 predictors/pearson/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Air_Temperature/10 predictors/pearson/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'Air_Temperature Predicted vs Actual 10p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'10p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Air_Temperature/10 predictors/pearson/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:

y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 15}
Best Score: 0.3935616705125041
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 8}
Best Score: 0.336979694625004
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 6}
Best Score: 0.2866146784346373
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 13}
Best Score: 0.4632621910798335
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 4}
Best Score: 0.22764766672695863


In [21]:
y_pred_list_rf

[array([-0.13069731,  0.08491905, -0.32863195,  0.37881574,  0.40698681,
         0.59774583, -0.36791733, -0.00695686,  0.15105855, -0.43851389,
         0.46406944, -0.42261891, -0.45111257,  0.71809453,  0.4730332 ,
        -0.0065744 ]),
 array([-0.39998859,  0.51864559, -0.22021167,  0.53269132, -0.03514255,
         0.10074468, -0.25376274, -0.26613402,  0.12663721, -0.47086523,
        -0.00977228, -0.48475422, -0.30889207,  0.69328621,  0.49322   ,
        -0.18746736]),
 array([-0.21625   , -0.22408009, -0.37454762,  0.18041667,  0.26783333,
         0.63166667, -0.4188254 ,  0.06686111,  0.38553571, -0.30001263,
         0.84333333, -0.65887302,  0.11863889,  0.87388889,  0.24097222,
        -0.00633333]),
 array([-0.00113003,  0.06372629, -0.49431578,  0.17947114,  0.40123911,
         0.591     , -0.09042406, -0.09136454, -0.02649713, -0.21301874,
         0.5470979 , -0.23628357, -0.32136085,  0.66809777,  0.68589265,
        -0.10176314]),
 array([-0.030625  ,  0.88834559

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.47136477025762047,
 0.7419013729932671,
 0.10791896414983188,
 0.36718221217422303,
 0.4243788178383337]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Air_Temperature/10 predictors/pearson/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'Air_Temperature (2001-2016) 10p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'10_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Air_Temperature/10 predictors/pearson/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Air_Temperature/10 predictors/pearson/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'Air_Temperature Predicted vs Actual 10p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'10p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Air_Temperature/10 predictors/pearson/comparison plots/randomforest
