In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("pearson_corr.csv")
df_month

November_5  August_4      July  November     April  September_2     May_9  \
0    -0.136173 -0.184693 -0.164218 -1.214892 -0.033340     0.851391 -0.567464   
1    -0.136173 -0.184693 -0.164218 -1.214892 -0.128477     0.851391 -0.663306   
2     0.108331 -0.868623  0.080121 -1.081003 -0.367615     0.606066 -0.431109   
3    -0.122380 -0.638803 -0.309253 -0.635890  0.070520     1.034079 -0.627715   
4    -0.611427 -0.607522 -0.069573 -1.005138 -0.152520     0.426557 -0.906395   
5    -0.277523 -0.054206 -0.158134 -1.068305 -0.013483     0.617339 -0.383592   
6    -0.628275 -0.508316  0.113819 -0.731337  0.308467     0.856599 -0.663260   
7    -0.114973 -0.210749 -0.410808 -1.387361 -0.353708     0.607791 -0.324771   
8     0.293501 -0.143427 -0.247025 -0.726642 -0.129378     0.392296 -0.611774   
9    -0.018843 -0.238002 -0.025460 -1.174447  0.011126     1.005638 -0.329415   
10    0.198077 -0.429991 -0.144258 -0.670271 -0.145576     0.171280 -0.379937   
11   -0.012159 -0.610245 -0.299184 -1.069782  0.008202     0.649766 -0.115011   
12   -0.354435 -0.700056 -0.235598 -1.116879  0.312304     1.104492 -0.483238   
13   -0.084961 -0.347165 -0.176298 -1.445867  0.381083     1.027871 -0.219925   
14   -0.252092 -0.291765 -0.072705 -0.802770  0.108157     0.359818 -0.241815   
15   -0.350702 -0.250056  0.098047 -1.571487 -0.313800     0.557514 -0.633183   
16   -0.083703 -0.766882 -0.116093 -1.263377 -0.071817     0.583765 -0.340016   
17   -0.370886 -0.442839  0.103842 -1.323865  0.296597     0.383581 -0.416205   
18   -0.456529 -0.568356 -0.095381 -0.611949 -0.077802     0.486675 -0.357906   
19    0.015565 -0.012688  0.149429 -0.728484  0.144133     0.917742 -0.557633   
20   -0.332858 -0.370367  0.266471 -0.335074  0.005774     0.942678 -0.625394   
21    0.256552 -0.313084 -0.096052 -0.898585 -0.001318     0.534038 -0.772303   
22    0.168598  0.035354 -0.098165 -0.671149 -0.131584     0.794348 -0.350416   
23   -0.180514 -0.641326 -0.137716 -0.788098 -0.140502     0.147030 -0.144174   
24    0.256874 -0.109967 -0.170699 -1.021461 -0.476248     0.571855 -0.343119   
25    0.264522 -0.281920 -0.007071 -1.583531  0.396314     0.331380 -0.478992   
26   -0.073100 -0.526368  0.257632 -0.766290  0.248789     0.439960 -0.706103   
27    0.075626 -0.322028 -0.099545 -1.362363 -0.095801     0.601285 -0.506242   
28    0.055525 -0.653181 -0.159428 -0.890509  0.319820     0.459427 -0.254899   
29    0.411534  0.514767 -0.267992 -0.306353  0.091179     0.691675 -0.410458   
30   -0.181485 -0.529146  0.231383 -1.082845  0.500375     1.129001 -0.943048   
31   -0.116002 -0.463989  0.418623 -1.493175  0.774053     0.856742 -0.466552   
32   -0.132405 -0.299324 -0.035964 -1.006522 -0.075311     0.272442 -0.646116   
33   -0.355521  0.031223 -0.207801 -0.651608 -0.062971     0.433883 -0.554129   
34    0.016238 -0.397822  0.137023 -0.336277 -0.034727     0.316534 -0.111153   
35    0.265122  0.003421 -0.295404 -0.942377 -0.335472     0.507977 -0.158202   
36    0.195983  0.021890  0.229772 -0.924365  0.168854     0.454936 -0.376874   
37   -0.039877 -0.383311  0.028154 -0.821479 -0.031632     0.830394 -0.716622   
38   -0.214968 -0.316559  0.305908 -1.127331  0.253941     0.595054 -0.702015   
39    0.394205 -0.237813 -0.586566 -0.279633 -0.714979     0.021481 -0.075563   
40   -0.362133 -0.315666  0.184264 -1.014621  0.310562     1.155282 -0.701655   
41   -0.005038 -0.508975 -0.021340 -1.926629  0.220518     0.956204 -0.289407   
42    0.118010  0.260668 -0.116461 -1.481841  0.366019     0.325073 -0.604991   
43   -0.007947 -0.230796  0.230637 -0.950949  0.069094     0.329085 -0.706124   
44   -0.018967  0.116478 -0.050802 -0.793945 -0.343788     0.784532 -0.196602   
45    0.041523  0.026354  0.096135 -0.537465  0.168505     0.540886 -0.737757   
46    0.369770 -0.172852  0.015129 -0.683440 -0.014284     0.557855 -0.825036   
47    0.039464  0.178887 -0.057228 -0.853255  0.102955     0.481542 -0.276804   
48   -0.340545 -0.304469  0.024225 

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :5]
x_train = scaler.fit_transform(x_train)
x_train

array([[-0.2529537 ,  0.57931097, -0.53383443, -0.65435752, -0.21032053],
       [-0.2529537 ,  0.57931097, -0.53383443, -0.65435752, -0.55432394],
       [ 0.71256455, -2.0346281 ,  0.64946638, -0.28456113, -1.41901195],
       [-0.19848533, -1.15626984, -1.23621922,  0.94482318,  0.16522337],
       [-2.12967502, -1.03671764, -0.0754786 , -0.07502531, -0.64125752],
       [-0.81112901,  1.07802598, -0.50436989, -0.24948889, -0.13852219],
       [-2.19620771, -0.65755475,  0.81266242,  0.68120152,  1.02560276],
       [-0.16923522,  0.47972592, -1.72803756, -1.13070995, -1.36872722],
       [ 1.44377933,  0.73702653, -0.93485924,  0.69416865, -0.55758135],
       [ 0.21036813,  0.37556653,  0.13815426, -0.54265091, -0.04953906],
       [ 1.06696197, -0.35820096, -0.43717167,  0.84986418, -0.61614925],
       [ 0.23676384, -1.04712223, -1.18745605, -0.25356887, -0.06011299],
       [-1.11484262, -1.39037383, -0.87951961, -0.38364846,  1.03947949],
       [-0.05072141, -0.04164649, -0.5

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [8]:
x_test = df_month.iloc[43:, :5]
x_test = scaler.fit_transform(x_test)
x_test

array([[-0.05137416, -0.00716389,  0.52997156, -0.62856208,  0.11232531],
       [-0.10836174,  1.24392774, -1.17971553, -0.00910632, -1.90162317],
       [ 0.20446034,  0.91924568, -0.28710028,  1.0028332 ,  0.59723492],
       [ 1.90198944,  0.20158772, -0.77919693,  0.42689332, -0.29437194],
       [ 0.19381147,  1.46876177, -1.21874913, -0.24311118,  0.27749453],
       [-1.7714059 , -0.27257543, -0.7239425 , -0.37314322, -0.605318  ],
       [ 0.28928596, -0.86382478,  0.13158014, -0.91924549, -0.45332625],
       [-0.48728804, -1.71998173,  0.94319649, -1.52668714,  1.83424217],
       [-0.9244304 ,  0.24519059, -0.13218273,  0.06771392,  2.22604473],
       [-0.48675074, -0.54996709,  1.52043252,  2.40179856,  0.39329954],
       [-1.34549611, -2.1514372 ,  0.7972197 , -0.14449698, -0.25329051],
       [ 0.92664418, -0.14813677, -0.86776972, -0.80250881,  0.40675728],
       [ 0.83755729,  0.44607789,  1.3037028 , -0.82727235, -1.18023307],
       [-0.00552853, -0.44941156, -1.4

In [9]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] 
    y_test.append(y_ts)

In [10]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 9}
Best Score: 0.4441109181238925
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 22}
Best Score: 0.2973495283226207
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 5}
Best Score: 0.4332026107321283
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 26}
Best Score: 0.3795458509254967
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 27}
Best Score: 0.31238360258957454


In [13]:
y_pred_list

[array([-0.39255401,  0.64955461,  0.27307688,  0.65412169,  0.34456454,
        -0.46107787, -0.4111929 , -1.02915807,  0.17942196,  0.15831179,
        -0.23871764, -0.19775309, -0.0235    ,  0.12047983,  0.82726058,
        -0.14167659]),
 array([-0.32295193,  0.51467414,  0.26643091,  0.54244877,  0.38189086,
        -0.23225298, -0.60622673, -0.88987879,  0.06202209, -0.18693922,
        -0.26269805, -0.49910687,  0.18291369,  0.10275824,  0.76489394,
        -0.21858631]),
 array([-0.29803333,  0.68576923,  0.32151282,  0.20667399,  0.46251282,
        -0.38346667, -0.53539841, -0.98935556, -0.1468    ,  0.0908    ,
        -0.34766667, -0.35184286, -0.2114707 , -0.09252601,  0.53151282,
        -0.55131429]),
 array([-0.33239485,  0.60092827,  0.22314814,  0.52378455,  0.58003225,
        -0.20919472, -0.31670418, -0.9530232 , -0.19241381,  0.1241251 ,
        -0.10348255,  0.0565556 , -0.1267948 ,  0.48003242,  0.46145762,
        -0.34002883]),
 array([-0.471257  ,  0.64385337

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.5497821325087755,
 0.6480999208301347,
 0.451733124471351,
 0.38207123372556206,
 0.43635567031244915]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/5 predictors/pearson/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'hgt+vwind (2001-2016) 5p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/5 predictors/pearson/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/5 predictors/pearson/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'hgt+vwind Predicted vs Actual 5p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/5 predictors/pearson/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:

y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 9}
Best Score: 0.4441109181238925
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 22}
Best Score: 0.2973495283226207
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 5}
Best Score: 0.4332026107321283
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 26}
Best Score: 0.3795458509254967
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 27}
Best Score: 0.31238360258957454


In [21]:
y_pred_list_rf

[array([-0.39255401,  0.64955461,  0.27307688,  0.65412169,  0.34456454,
        -0.46107787, -0.4111929 , -1.02915807,  0.17942196,  0.15831179,
        -0.23871764, -0.19775309, -0.0235    ,  0.12047983,  0.82726058,
        -0.14167659]),
 array([-0.32295193,  0.51467414,  0.26643091,  0.54244877,  0.38189086,
        -0.23225298, -0.60622673, -0.88987879,  0.06202209, -0.18693922,
        -0.26269805, -0.49910687,  0.18291369,  0.10275824,  0.76489394,
        -0.21858631]),
 array([-0.29803333,  0.68576923,  0.32151282,  0.20667399,  0.46251282,
        -0.38346667, -0.53539841, -0.98935556, -0.1468    ,  0.0908    ,
        -0.34766667, -0.35184286, -0.2114707 , -0.09252601,  0.53151282,
        -0.55131429]),
 array([-0.33239485,  0.60092827,  0.22314814,  0.52378455,  0.58003225,
        -0.20919472, -0.31670418, -0.9530232 , -0.19241381,  0.1241251 ,
        -0.10348255,  0.0565556 , -0.1267948 ,  0.48003242,  0.46145762,
        -0.34002883]),
 array([-0.471257  ,  0.64385337

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.5497821325087755,
 0.6480999208301347,
 0.451733124471351,
 0.38207123372556206,
 0.43635567031244915]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/5 predictors/pearson/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'hgt+vwind (2001-2016) 5p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/5 predictors/pearson/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/5 predictors/pearson/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'hgt+vwind Predicted vs Actual 5p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'5p{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/5 predictors/pearson/comparison plots/randomforest
