In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("mutual_corr.csv")
df_month

August   April_6  November_9     May_4      July  December  August_6  \
0  -0.738326 -0.301980    0.069234 -0.771465 -0.282972 -0.717073 -0.281517   
1  -0.738326 -0.631036    0.069234 -0.693543 -0.282972 -0.717073 -0.281517   
2  -0.695796 -0.482993    0.096896 -0.833585  0.024735 -0.476478 -0.357975   
3  -0.947883 -0.013548    0.206812 -0.895129 -0.480516 -1.036485 -0.740435   
4  -0.607567 -0.535569    0.281363 -0.806471 -0.318698  0.073743 -0.751791   
5  -0.553747 -0.513097    0.328863 -0.686994 -0.451876 -0.387426 -0.617012   
6  -0.856548 -0.530454   -0.184806 -1.034953 -0.335775 -0.910498 -0.652016   
7  -0.195088 -0.596512    0.016471 -1.052326 -0.317907 -0.018828 -0.285899   
8  -0.644855 -0.643774   -0.164050 -1.066844 -0.228131  0.069151 -0.406965   
9  -0.980771 -0.561194    0.116569 -1.191484 -0.398887 -0.306188 -0.239752   
10 -0.649642  0.047388   -0.338679 -0.783846 -0.176470 -0.103149 -0.374419   
11 -0.869427 -0.295634   -0.305920 -0.780243 -0.612539 -0.394225 -0.216166   
12 -0.923796 -0.135304    0.374637 -0.874649 -0.349064 -0.256789 -0.142124   
13 -0.802844 -0.320404    0.626730 -0.763495 -0.358547 -0.175638 -0.345152   
14 -0.345760 -0.362342    0.089436 -0.661820 -0.608618  0.022039 -0.465585   
15 -0.842513 -0.259362    0.224387 -0.821221 -0.425789 -0.933287 -0.276291   
16 -0.929642 -0.208148    0.458070 -1.067972 -0.239326 -0.095038 -0.250753   
17 -0.613427 -0.234426    0.878477 -0.607790 -0.230007 -0.360705 -0.147925   
18 -0.637092 -0.302807    0.430257 -0.965550 -0.345586 -0.502902 -0.494739   
19 -0.505379 -0.130184    0.452508 -0.627250 -0.658500 -0.477501 -0.634594   
20 -0.937131 -0.030418    0.058221 -0.671692 -0.370724 -0.368491 -0.630319   
21 -0.817189 -0.573952    0.054164 -0.711322 -0.185867 -0.074160 -0.391357   
22 -0.815767 -0.070290   -0.096476 -1.311122  0.020546 -0.630909 -0.519670   
23 -0.815053 -0.224776    0.048739 -0.996655  0.008225 -0.681412 -0.068805   
24 -0.250273 -0.416928    0.208256 -0.785403 -0.432229 -0.209473 -0.502890   
25 -0.983868 -0.643155   -0.454533 -1.044103 -0.609283 -0.761062 -0.197076   
26 -1.031509 -0.359442   -0.197715 -0.744932 -0.353018 -0.607035 -0.149339   
27 -0.538390 -0.140792    0.531348 -0.689302 -0.438923 -0.472494 -0.390628   
28 -0.867833 -0.332336    0.414391 -1.189780 -0.219545  0.055753 -0.592950   
29 -0.413649 -0.251426    0.087649 -0.942845 -0.354293 -0.173729 -0.539136   
30 -1.248001 -0.416882    0.343072 -0.901456 -0.613108 -0.265459 -0.107957   
31 -0.835561 -0.396799    0.383450 -0.815414 -0.107483 -0.227913 -0.194243   
32 -0.834259 -0.631864   -0.168810 -1.157403 -0.222215 -0.976023 -0.256342   
33 -0.710545 -0.197668   -0.004256 -0.626331 -0.179417 -0.373498 -0.474330   
34 -0.493617 -0.355550   -0.268315 -1.136512 -0.663464 -0.753188 -0.308946   
35 -0.168705 -0.331555    0.002615 -0.943248 -0.378801 -0.460430 -0.338856   
36 -0.840497 -0.245685    0.089352 -1.178173 -0.150554 -0.293089 -0.391215   
37 -0.496251 -0.214843    0.058361 -0.913127 -0.000309 -0.255027 -0.766380   
38 -0.983520 -0.591013   -0.243122 -1.008284 -0.312259 -0.234846 -0.298268   
39 -0.172950 -0.755382   -0.042371 -0.842870 -0.487825 -0.068854 -0.252112   
40 -0.646220 -0.449251   -0.379949 -0.930208 -0.277241 -0.727007 -0.640345   
41 -0.915591 -0.639012    0.868201 -0.889877 -0.543093 -0.435933 -0.671405   
42 -0.671021 -0.030581    0.466853 -0.927800 -0.448426 -0.508981 -1.039283   
43 -0.402879 -0.475583    1.062395 -1.019033 -0.228014 -0.326749 -0.502407   
44 -0.341052 -0.927046    0.092848 -0.845561 -0.186894 -0.456510 -0.555655   
45 -0.445320 -0.643108    0.131427 -1.286470 -0.500198 -0.736443 -0.433960   
46 -0.582229  0.015050   -0.266698 -0.653631 -0.505696 -0.649792 -0.623650   
47 -0.424816 -0.663902   -0.108820 -1.028340 -0.029949 -1.081678 -0.689202   
48 -1.000447 -0.093196    0.126523 -1.073609 -0.382071 -0.520092 -0.223768   
49 -0.869858 -0.393340   -0.573848 -0.745181 -0.100789 -0.951528 -0.515654   
50 -1.127384 -0.175981    0.

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :15]
x_train = scaler.fit_transform(x_train)
x_train

array([[-1.07821677e-01,  3.13440165e-01, -1.62861788e-01,
         6.72371308e-01,  2.72433685e-01, -1.07590956e+00,
         6.06672832e-01, -1.50281018e-01,  8.36488634e-01,
        -2.12701516e-01, -9.28816171e-01,  1.04571127e+00,
         1.53690788e+00,  9.11592159e-02, -1.64120631e+00],
       [-1.07821677e-01, -1.35442242e+00, -1.62861788e-01,
         1.11113259e+00,  2.72433685e-01, -1.07590956e+00,
         6.06672832e-01, -4.53600762e-01,  8.36488634e-01,
        -2.12701516e-01,  1.95539191e-01,  1.15535560e+00,
         5.99727218e-01,  9.11592159e-02, -1.64120631e+00],
       [ 6.49284578e-02, -6.04049006e-01, -7.32286804e-02,
         3.22583201e-01,  1.97868312e+00, -2.65676324e-01,
         2.02614500e-01,  1.82726114e+00, -2.24399617e-01,
         2.60623516e-01, -1.34713066e+00,  5.95794401e-01,
         1.91204908e-02, -9.50878221e-01, -1.69715072e+00],
       [-9.59005890e-01,  1.77539741e+00,  2.82944337e-01,
        -2.39628072e-02, -8.22954894e-01, -2.15156659

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [8]:
x_test = df_month.iloc[43:, :15]
x_test = scaler.fit_transform(x_test)
x_test

array([[ 1.21107640e+00, -4.33508186e-01,  2.51912670e+00,
        -8.24263465e-01, -2.86935528e-01,  6.36074584e-01,
        -9.55267444e-02,  1.57533294e-01, -8.88278988e-02,
        -1.52998747e+00,  6.89220703e-01,  9.70701127e-01,
        -1.57351771e+00, -2.00794424e-01, -1.64167362e+00],
       [ 1.41827358e+00, -2.33016484e+00,  2.77875839e-01,
        -1.00986162e-01, -9.57609934e-02,  2.41297868e-01,
        -4.34091237e-01,  5.64452529e-01,  1.02432131e-03,
         1.73659710e+00, -2.55647035e-01, -1.45063250e+00,
         1.01593018e+00,  3.30130341e-01, -1.67394645e+00],
       [ 1.06884947e+00, -1.13730397e+00,  3.67056950e-01,
        -1.93931743e+00, -1.55235753e+00, -6.10353485e-01,
         3.39673534e-01,  1.07882385e+00, -1.23462760e+00,
        -1.12499271e+00, -1.04089839e+00, -3.02443818e-01,
        -2.16103055e-01, -1.95707981e-02, -6.15639236e-01],
       [ 6.10036916e-01,  1.62770559e+00, -5.53268129e-01,
         6.99250297e-01, -1.57791799e+00, -3.46733024

In [9]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] 
    y_test.append(y_ts)

In [10]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 31}
Best Score: 0.41124498702429013
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 14}
Best Score: 0.290679720226803
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 30}
Best Score: 0.4416681326465628
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 47}
Best Score: 0.3842361122052683
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 50}
Best Score: 0.23061360183436547


In [13]:
y_pred_list

[array([ 0.79952078,  0.95220344,  0.80392895, -0.10633201,  0.91803168,
        -0.18425406, -0.18941589, -0.25641315,  0.91808772, -0.54790111,
        -0.46393638, -0.15917805, -0.10319786, -0.16835998, -0.22969687,
        -0.09858132]),
 array([ 0.16208333,  0.60095238,  0.7323869 , -0.01587176,  0.61327848,
        -0.04362404, -0.08919068, -0.35689476,  0.53478175, -0.28066176,
        -0.44545881, -0.42477991, -0.14821151, -0.23509059, -0.0502126 ,
         0.02229175]),
 array([ 0.47751187,  0.71964167,  0.73659141,  0.01278849,  0.61346456,
        -0.24436276, -0.0632792 , -0.23556218,  0.56654444, -0.83159701,
        -0.3467401 , -0.12850135, -0.00199072, -0.40331704, -0.31416913,
         0.06465899]),
 array([ 0.71666255,  0.97111455,  0.64432081, -0.10208493,  0.67934783,
        -0.30766173, -0.13697933, -0.24593591,  0.88215167, -0.62048529,
        -0.28295222, -0.11950921, -0.1218545 , -0.20767699, -0.15512883,
        -0.11945361]),
 array([ 0.81451871,  1.14933219

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.2775961783151399,
 0.3134222038370131,
 0.280712340519857,
 0.2997557594154862,
 0.24750965276688247]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/15 predictors/kendall/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'AT+vwind (2001-2016) 15p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'15p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/15 predictors/kendall/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/15 predictors/kendall/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'AT+vwind Predicted vs Actual 15p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'15p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/15 predictors/kendall/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:

y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 31}
Best Score: 0.41124498702429013
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 14}
Best Score: 0.290679720226803
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 30}
Best Score: 0.4416681326465628
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 47}
Best Score: 0.3842361122052683
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 50}
Best Score: 0.23061360183436547


In [21]:
y_pred_list_rf

[array([ 0.79952078,  0.95220344,  0.80392895, -0.10633201,  0.91803168,
        -0.18425406, -0.18941589, -0.25641315,  0.91808772, -0.54790111,
        -0.46393638, -0.15917805, -0.10319786, -0.16835998, -0.22969687,
        -0.09858132]),
 array([ 0.16208333,  0.60095238,  0.7323869 , -0.01587176,  0.61327848,
        -0.04362404, -0.08919068, -0.35689476,  0.53478175, -0.28066176,
        -0.44545881, -0.42477991, -0.14821151, -0.23509059, -0.0502126 ,
         0.02229175]),
 array([ 0.47751187,  0.71964167,  0.73659141,  0.01278849,  0.61346456,
        -0.24436276, -0.0632792 , -0.23556218,  0.56654444, -0.83159701,
        -0.3467401 , -0.12850135, -0.00199072, -0.40331704, -0.31416913,
         0.06465899]),
 array([ 0.71666255,  0.97111455,  0.64432081, -0.10208493,  0.67934783,
        -0.30766173, -0.13697933, -0.24593591,  0.88215167, -0.62048529,
        -0.28295222, -0.11950921, -0.1218545 , -0.20767699, -0.15512883,
        -0.11945361]),
 array([ 0.81451871,  1.14933219

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.2775961783151399,
 0.3134222038370131,
 0.280712340519857,
 0.2997557594154862,
 0.24750965276688247]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/15 predictors/kendall/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'AT+vwind (2001-2016) 15p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'15_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/15 predictors/kendall/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/15 predictors/kendall/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'AT+vwind Predicted vs Actual 15p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'15p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/15 predictors/kendall/comparison plots/randomforest
