In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("mutual_corr.csv")
df_month

August_3     May_3     March  November_3  October_4  February  November_7  \
0   0.114184  0.033686 -0.655145    0.095877  -0.223095  0.673055    0.331349   
1   0.114184 -0.016299 -0.698491    0.095877  -0.223095  0.363829    0.331349   
2  -0.170711 -0.463674 -0.668487    0.013414  -0.185702  0.252059    0.493727   
3  -0.281879 -0.300338 -0.598952   -0.097387   0.424563  0.305557    0.344451   
4   0.013463 -0.444215 -0.678790   -0.468578   0.006136  0.156514    0.358842   
5   0.009911 -0.054209 -0.532310   -0.184335   0.059998 -0.096582    0.722699   
6  -0.102361 -0.288842 -0.695664   -0.100364   0.228933  0.058638    0.265362   
7  -0.349440 -0.170438 -0.579220    0.095780   0.044146  0.333448    0.388292   
8   0.125238 -0.436033 -0.656381    0.105569  -0.396204  0.781802    0.487561   
9  -0.160472 -0.333610 -0.630780   -0.336637   0.142159  0.198319    0.394522   
10 -0.007530 -0.383026 -0.683142   -0.102008  -0.254581  0.273719    0.581236   
11 -0.106808  0.036061 -0.986569   -0.001181  -0.131963  0.200275    0.399103   
12  0.279311 -0.324753 -0.891774   -0.237661  -0.394445  0.309672    0.213285   
13  0.178162 -0.244825 -1.174396   -0.510577  -0.580903  0.081328    0.102452   
14  0.116568  0.288398 -0.859918   -0.199049  -0.173442  0.434135   -0.041096   
15  0.301243 -0.190055 -0.849515   -0.394707  -0.189769  0.160518    0.395809   
16 -0.024391 -0.184535 -1.028752   -0.335749  -0.614003  0.118981    0.384830   
17  0.004895 -0.049467 -0.709257    0.127342  -0.300777  0.124025    0.433202   
18 -0.028275  0.080598 -1.018913   -0.316292  -0.326551  0.282665    0.334684   
19  0.007084  0.107968 -0.842606    0.329121   0.111593  0.452186    0.811376   
20  0.131031  0.011640 -0.908539   -0.152145  -0.001294  0.426464    0.294283   
21 -0.084481  0.013251 -0.865125   -0.266798  -0.478286  0.502790    0.417085   
22  0.114824  0.026293 -0.603949   -0.016251  -0.148490  0.304775    0.585039   
23 -0.377885 -0.022313 -0.786233    0.029184  -0.037837  0.195714    0.562344   
24 -0.151760  0.175453 -0.955028   -0.106836  -0.301358  0.459818    0.563519   
25  0.414036 -0.104295 -0.829746   -0.272308   0.176718  0.396532    0.410567   
26  0.084770 -0.045316 -1.003712   -0.465155  -0.573705 -0.158917    0.362520   
27  0.082887 -0.127414 -1.121732   -0.468759   0.055374  0.374849    0.279195   
28 -0.005223  0.072611 -0.915685   -0.371766  -0.399898  0.290676    0.168417   
29 -0.083530  0.105673 -0.667030    0.248899  -0.215029  0.526179    0.297900   
30  0.136800  0.196485 -0.853579   -0.019934  -0.104649  0.299438    0.441625   
31  0.287721 -0.060383 -0.977607   -0.597740  -0.512628  0.268476    0.138139   
32  0.256713 -0.400219 -0.816392   -0.336464  -0.188330  0.486745    0.214343   
33 -0.228380  0.124658 -0.815008   -0.314403  -0.419818  0.224530    0.236942   
34 -0.079803 -0.275532 -0.683690    0.165845  -0.277272  0.449034    0.327224   
35 -0.029405  0.115020 -0.749648    0.059985  -0.310617  0.188582    0.413612   
36 -0.000376  0.102976 -0.935625   -0.361571   0.023228  0.484110    0.418764   
37 -0.200508 -0.136691 -0.978033   -0.417251  -0.402621  0.352919    0.259876   
38 -0.161779 -0.010835 -1.009856   -0.194060  -0.243635  0.132113    0.294500   
39 -0.008893  0.146041 -0.773159    0.561520  -0.260350  0.476277    0.455658   
40  0.149709 -0.209499 -1.145452   -0.106318  -0.548532  0.320718    0.650006   
41  0.105416  0.023879 -0.944997   -0.006877   0.121002  0.033595    0.387285   
42  0.060602 -0.123845 -1.196813   -0.461678   0.031874  0.460072    0.173155   
43  0.005421 -0.076077 -1.005319    0.358851   0.177330  0.266948    0.487732   
44  0.205873  0.142268 -0.823896    0.038974   0.009979  0.360246    0.180452   
45  0.246846 -0.080917 -0.834072    0.122741  -0.322776  0.341500    0.491263   
46 -0.051541  0.071140 -0.824993   -0.356602   0.013472  0.370503    0.476091   
47  0.103401 -0.156982 -0.794951    0.109713  -0.146688  0.034715    0.551313   
48  0.265317 -0.123676 -0.931317   

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :20]
x_train = scaler.fit_transform(x_train)
x_train

array([[ 6.07610235e-01,  6.18174203e-01,  1.06543437e+00,
         9.50027360e-01, -1.33383573e-01,  2.04035884e+00,
        -2.97261461e-01,  1.12480149e+00,  7.23663348e-01,
        -7.88168260e-02, -7.94705945e-01, -3.86307153e-01,
         2.30859886e+00,  4.43032828e-01, -8.55106338e-01,
         4.89324331e-01, -1.47071974e+00,  2.61767281e-01,
        -2.35666784e-01,  1.36287778e+00],
       [ 6.07610235e-01,  3.60214219e-01,  7.98366002e-01,
         9.50027360e-01, -1.33383573e-01,  3.59872097e-01,
        -2.97261461e-01, -1.48934508e+00, -1.40347377e+00,
         8.48783102e-01, -8.04812136e-01, -3.86307153e-01,
         2.30859886e+00,  4.43032828e-01, -8.55106338e-01,
         4.89324331e-01,  7.84171699e-01,  2.61767281e-01,
        -2.28044773e-01,  1.36287778e+00],
       [-1.04046523e+00, -1.94857237e+00,  9.83231989e-01,
         6.16238906e-01,  2.23684348e-02, -2.47537863e-01,
         7.18805089e-01,  1.02751903e+00, -5.60647936e-01,
         1.58140399e+00,  6.0

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] #df.iloc[43:]['avg']
    y_test.append(y_ts)

In [8]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [9]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

In [10]:
x_test = df_month.iloc[43:, :20]
x_test = scaler.fit_transform(x_test)
x_test

array([[-0.38808819, -0.01166501, -1.34732728,  1.64234451,  0.66993541,
        -0.39395094,  0.99204064, -0.29318147, -1.47844835,  0.99354782,
         1.74963831,  0.92764041, -0.77302267,  0.42217037, -1.0487191 ,
         0.1835634 , -0.67879011, -0.55810555,  0.65556243,  0.4837364 ],
       [ 1.05079715,  1.18829611,  0.2644326 ,  0.15907934, -0.05418936,
         0.18018119, -0.61855064,  1.1853859 ,  0.37717918, -0.4053082 ,
         0.74250441, -1.19194219,  0.97317196, -0.21749935, -0.0543665 ,
         1.08426086, -1.24142393,  0.82487624,  0.73903003,  2.74387372],
       [ 1.34491522, -0.03826249,  0.17402926,  0.54750453, -1.49401308,
         0.06482449,  1.01055039,  1.06573623,  0.99723865, -0.13595184,
         1.07849695,  0.883684  , -0.71932716, -1.64746139, -0.49247008,
        -1.92242836,  1.37078998,  0.85726191, -0.65670291,  0.07858409],
       [-0.7969692 ,  0.79739778,  0.25468795, -1.67520777, -0.03907311,
         0.2433053 ,  0.93102586,  0.15242815,  

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 13}
Best Score: 0.2651297743133802
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 45}
Best Score: 0.24174759347424346
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 17}
Best Score: 0.2408508273194555
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 37}
Best Score: 0.15133611645866607
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 42}
Best Score: 0.13128596301037865


In [13]:
y_pred_list

[array([-0.22814835,  0.20546062, -0.59077732,  0.09078594, -0.39128564,
        -0.34868208,  0.00673497, -0.2614475 ,  0.31702381,  0.20737981,
        -0.37514209, -0.33021168, -0.21790491,  0.24986293,  0.64502564,
         0.08772001]),
 array([-0.43323168,  0.28490556, -0.57999436, -0.08241232, -0.43349214,
        -0.20335918,  0.04851452, -0.3233973 ,  0.04965766,  0.0066449 ,
        -0.50236755, -0.39790315, -0.3449077 ,  0.09017227,  0.64267328,
        -0.04855807]),
 array([-0.44866148,  0.30965686, -0.43974071, -0.11521964, -0.23863377,
        -0.39293893, -0.00370824, -0.22206546,  0.06040171, -0.00119237,
        -0.32031476, -0.39113978, -0.09645065,  0.26646887,  0.34639379,
        -0.20045949]),
 array([-0.18043982,  0.15053955, -0.57373747,  0.29943041, -0.37124457,
        -0.63464152, -0.16024946, -0.23869545,  0.41959115, -0.12574002,
        -0.31758768, -0.24643666, -0.27317949,  0.27070409,  0.64153162,
        -0.06659017]),
 array([-0.0872717 ,  0.206597  

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.4461225349480443,
 0.7063140042858725,
 0.40780927667896316,
 0.5445870870344346,
 0.4278830390051765]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+uwind/20 predictors/kendall/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'slp+uwind (2001-2016) 20p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+uwind/20 predictors/kendall/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+uwind/20 predictors/kendall/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'slp+uwind Predicted vs Actual 20p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+uwind/20 predictors/kendall/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:
y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 13}
Best Score: 0.2651297743133802
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 45}
Best Score: 0.24174759347424346
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 17}
Best Score: 0.2408508273194555
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 37}
Best Score: 0.15133611645866607
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 42}
Best Score: 0.13128596301037865


In [21]:
y_pred_list_rf

[array([-0.22814835,  0.20546062, -0.59077732,  0.09078594, -0.39128564,
        -0.34868208,  0.00673497, -0.2614475 ,  0.31702381,  0.20737981,
        -0.37514209, -0.33021168, -0.21790491,  0.24986293,  0.64502564,
         0.08772001]),
 array([-0.43323168,  0.28490556, -0.57999436, -0.08241232, -0.43349214,
        -0.20335918,  0.04851452, -0.3233973 ,  0.04965766,  0.0066449 ,
        -0.50236755, -0.39790315, -0.3449077 ,  0.09017227,  0.64267328,
        -0.04855807]),
 array([-0.44866148,  0.30965686, -0.43974071, -0.11521964, -0.23863377,
        -0.39293893, -0.00370824, -0.22206546,  0.06040171, -0.00119237,
        -0.32031476, -0.39113978, -0.09645065,  0.26646887,  0.34639379,
        -0.20045949]),
 array([-0.18043982,  0.15053955, -0.57373747,  0.29943041, -0.37124457,
        -0.63464152, -0.16024946, -0.23869545,  0.41959115, -0.12574002,
        -0.31758768, -0.24643666, -0.27317949,  0.27070409,  0.64153162,
        -0.06659017]),
 array([-0.0872717 ,  0.206597  

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.4461225349480443,
 0.7063140042858725,
 0.40780927667896316,
 0.5445870870344346,
 0.4278830390051765]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+uwind/20 predictors/kendall/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'slp+uwind (2001-2016) 20p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+uwind/20 predictors/kendall/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+uwind/20 predictors/kendall/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'slp+uwind Predicted vs Actual 20p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+uwind/20 predictors/kendall/comparison plots/randomforest
