In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("spearman_corr.csv")
df_month

July_6   April_6  November_7  November    July_7  August_2     May_2  \
0  -0.687068  0.386355    0.052698  0.541902  0.005747 -0.164586 -0.359395   
1  -0.687068  0.200515    0.052698  0.541902  0.005747 -0.164586 -0.410397   
2  -0.379167  0.018638    0.284734  0.607633 -0.021631 -0.042086  0.172456   
3  -0.152717  0.151849    0.236467  0.524124 -0.039958 -0.103642 -0.222168   
4  -0.366530 -0.119454    0.120395  0.624625  0.138605  0.155223 -0.023508   
5  -0.611835  0.151046    0.046850  0.615718  0.180762  0.081915 -0.364834   
6  -0.899686  0.134536    0.324169  0.766336  0.273354  0.370244 -0.415197   
7  -0.829043 -0.374646   -0.087662  0.243056  0.781560 -0.058799 -0.140117   
8  -0.550519  0.330437    0.113202  0.880321  0.421596 -0.224176 -0.279670   
9  -0.385054 -0.261064   -0.288817  0.571846  0.230158  0.036304 -0.328111   
10 -0.709560 -0.130175   -0.009334  0.211560  0.479344 -0.231491  0.170027   
11 -0.398548  0.297414    0.195103  0.268865  0.226013 -0.115048 -0.400712   
12 -0.443008  0.228194    0.395684  0.747025 -0.073004 -0.116296 -0.224018   
13 -0.498184  0.263182    0.216831  0.538737  0.274466  0.127278 -0.048799   
14 -0.803335  0.018221   -0.267971  0.142763  0.632543 -0.079797 -0.420300   
15 -0.652178  0.244438    0.493068  0.785315  0.071791 -0.005844 -0.245389   
16 -0.802299 -0.057759    0.254794  0.650781  0.543830  0.023952  0.047781   
17 -0.251446  0.241546    0.175710  0.152672  0.650860 -0.070248 -0.180453   
18 -0.620700  0.060977   -0.186615  0.207789  0.692031 -0.066985 -0.544819   
19 -0.471164 -0.158738    0.069466  0.215516  0.448468 -0.091662 -0.117589   
20 -0.527260  0.128186    0.114954  0.676299  0.123114 -0.097620  0.019395   
21 -0.611273  0.039814    0.109990 -0.058267  0.555055 -0.455986 -0.271869   
22 -0.214900  0.254390    0.106813  0.547574 -0.010089 -0.361533 -0.104815   
23 -0.682979  0.162752   -0.010500  0.322339  0.122740  0.386190 -0.523009   
24 -0.949788 -0.325163    0.261269  0.586089  0.524701 -0.073055 -0.169897   
25 -0.575420  0.240958    0.483188  0.164034  0.335422  0.051619  0.029600   
26 -0.235262  0.248294    0.193171  0.535310  0.095669  0.362861 -0.158876   
27 -0.555927 -0.150259    0.258067  0.390037  0.459989  0.044619 -0.081093   
28 -0.291919  0.035971    0.193556  0.870554  0.172043 -0.049929 -0.339675   
29 -0.734773  0.093554    0.060857 -0.041049  0.326728 -0.257445 -0.493828   
30 -0.358387  0.229925    0.351876  0.915680  0.367604 -0.203046  0.200629   
31 -0.480159  0.087705    0.347850  0.496599 -0.025625  0.317094 -0.168156   
32 -1.214202 -0.242806    0.159851  0.397815  0.784604  0.076864 -0.045030   
33 -0.846969 -0.071024    0.000512  0.428175  0.616459 -0.270377 -0.689440   
34 -0.788468 -0.119237   -0.054222  0.129697  0.528097  0.035065 -0.899160   
35 -1.122272  0.006782    0.055553  0.220968  0.374215 -0.188977 -0.509467   
36 -0.496194  0.335751    0.138587  0.390511  0.347274 -0.336829 -0.503257   
37 -0.768014 -0.024752    0.039381  0.480350  0.203004  0.125807 -0.070459   
38 -0.377814  0.357600    0.227297  1.014231  0.177600  0.151097  0.003027   
39 -1.053392 -0.298502   -0.073056  0.427786  0.611980  0.019398 -0.559705   
40 -0.327206  0.309806    0.646915  0.612599 -0.096091  0.157952 -0.507612   
41 -0.460937  0.260029    0.462585  0.874589  0.265853  0.378506  0.108627   
42 -0.752640  0.317833   -0.046467  0.626725  0.300623  0.061774  0.118036   
43 -0.899912  0.044658    0.308263  0.513656  0.933453  0.096127 -0.064489   
44 -0.961909 -0.287725    0.160125  0.720926  0.530569  0.006735 -0.292402   
45 -0.748140  0.113775    0.357364  0.686093  0.482076 -0.123168 -0.139222   
46 -0.795032  0.042116    0.185061  0.327447  0.300931 -0.062652  0.035302   
47 -0.500240  0.262822    0.135361  0.787701  0.022576 -0.302282 -0.241347   
48 -0.587403 -0.102831    0.357362  0.820154 -0.011689  0.148256 -0.384694   
49 -0.507547  0.093623    0.492791  0.817325  0.022856  0.453313  0.148943   
50 -0.617193  0.179464    0.

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :10]
x_train = scaler.fit_transform(x_train)
x_train

array([[-0.3844874 ,  1.53368555, -0.49502206,  0.2336184 , -1.21721547,
        -0.71316807, -0.48720229,  0.62127951,  0.27580006, -0.86493631],
       [-0.3844874 ,  0.61578871, -0.49502206,  0.2336184 , -1.21721547,
        -0.71316807, -0.69487741,  0.62127951, -0.65453281, -0.86493631],
       [ 0.86346174, -0.28253317,  0.69536988,  0.48758479, -1.32881726,
        -0.10004714,  1.67843721, -0.26813222, -1.80526402,  1.72353971],
       [ 1.78128222,  0.37542312,  0.44775159,  0.16492866, -1.40352552,
        -0.40813785,  0.07157083,  0.87839713, -0.79530258,  0.74431584],
       [ 0.91467986, -0.96459088, -0.14772305,  0.55323941, -0.67563236,
         0.88749054,  0.88049164,  0.72729897, -0.87495891,  1.0367486 ],
       [-0.07955925,  0.3714552 , -0.5250228 ,  0.51882578, -0.5037836 ,
         0.52058363, -0.50935007,  1.02336025, -0.66811617, -1.10379462],
       [-1.24624642,  0.28990999,  0.89768227,  1.10077452, -0.12634608,
         1.9636826 , -0.7144219 ,  0.65603416

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [8]:
x_test = df_month.iloc[43:, :10]
x_test = scaler.fit_transform(x_test)
x_test

array([[-8.81578560e-01,  7.87319585e-02,  1.02643694e-02,
        -1.41065925e-01,  2.55516552e+00,  2.24268386e-01,
         4.25834674e-02,  1.68896292e-01, -6.73029519e-01,
        -4.33777674e-02],
       [-1.15016991e+00, -2.16814405e+00, -9.13397126e-01,
         7.94637958e-01,  9.06456192e-01, -2.33990067e-01,
        -1.03495855e+00,  4.58826275e-01,  1.24679204e+00,
         3.48786325e-02],
       [-2.24059696e-01,  5.45961485e-01,  3.16412534e-01,
         6.37388871e-01,  7.08006865e-01, -8.99915067e-01,
        -3.10746226e-01, -6.16280721e-01, -6.93452795e-01,
        -4.90882087e-01],
       [-4.27208561e-01,  6.15484005e-02, -7.57913214e-01,
        -9.81688128e-01, -3.32848993e-02, -5.89688293e-01,
         5.14381723e-01,  1.12424937e+00, -2.21690089e+00,
         3.44124416e-01],
       [ 8.49914270e-01,  1.55350830e+00, -1.06780203e+00,
         1.09608703e+00, -1.17239077e+00, -1.81811442e+00,
        -7.93577301e-01, -6.43270766e-01,  7.56894464e-01,
        -1.

In [9]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] 
    y_test.append(y_ts)

In [10]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 45}
Best Score: 0.3598656764656439
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 5}
Best Score: 0.27150521996350363
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 11}
Best Score: 0.37622031072110607
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 43}
Best Score: 0.3818898337448683
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 43}
Best Score: 0.2185709928127874


In [13]:
y_pred_list

[array([ 0.16843586,  0.42505783, -0.18084751,  0.15383707, -0.07570791,
        -0.2374877 , -0.59537536, -0.12062879, -0.08044808, -0.20121173,
         0.1360661 ,  0.10858712, -0.12673126,  0.06259178,  0.05292032,
        -0.43969672]),
 array([ 0.10037088,  0.23410333, -0.07362699,  0.1855435 ,  0.0634435 ,
        -0.38802079, -0.75792675,  0.1855435 ,  0.07974143, -0.26592079,
         0.42526216, -0.07872436, -0.4173619 ,  0.05834614,  0.03487454,
        -0.23084461]),
 array([ 0.0360728 ,  0.74234643, -0.21523293,  0.15235489,  0.11194796,
        -0.27691108, -0.53978553, -0.02296454, -0.16336786, -0.13824466,
         0.22999378, -0.05412701, -0.22469843, -0.00735847, -0.25799843,
        -0.41735103]),
 array([-0.08234756,  0.78818315, -0.25869699,  0.30834495,  0.01556744,
        -0.16256624, -0.75323293,  0.0807011 , -0.05445174, -0.4627266 ,
         0.04240806,  0.02046269,  0.04767558, -0.02186538,  0.0086777 ,
        -0.60646475]),
 array([-0.14897454,  0.84477748

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.47375394240826957,
 0.26989916771672057,
 0.19133645028745425,
 0.5293359246609585,
 0.602579801109889]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/GPH/10 predictors/spearson/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'GPH (2001-2016) 10p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'10p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/GPH/10 predictors/spearson/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/GPH/10 predictors/spearson/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'GPH Predicted vs Actual 10p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'10p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/GPH/10 predictors/spearson/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:

y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 45}
Best Score: 0.3598656764656439
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 5}
Best Score: 0.27150521996350363
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 11}
Best Score: 0.37622031072110607
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 43}
Best Score: 0.3818898337448683
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 43}
Best Score: 0.2185709928127874


In [21]:
y_pred_list_rf

[array([ 0.16843586,  0.42505783, -0.18084751,  0.15383707, -0.07570791,
        -0.2374877 , -0.59537536, -0.12062879, -0.08044808, -0.20121173,
         0.1360661 ,  0.10858712, -0.12673126,  0.06259178,  0.05292032,
        -0.43969672]),
 array([ 0.10037088,  0.23410333, -0.07362699,  0.1855435 ,  0.0634435 ,
        -0.38802079, -0.75792675,  0.1855435 ,  0.07974143, -0.26592079,
         0.42526216, -0.07872436, -0.4173619 ,  0.05834614,  0.03487454,
        -0.23084461]),
 array([ 0.0360728 ,  0.74234643, -0.21523293,  0.15235489,  0.11194796,
        -0.27691108, -0.53978553, -0.02296454, -0.16336786, -0.13824466,
         0.22999378, -0.05412701, -0.22469843, -0.00735847, -0.25799843,
        -0.41735103]),
 array([-0.08234756,  0.78818315, -0.25869699,  0.30834495,  0.01556744,
        -0.16256624, -0.75323293,  0.0807011 , -0.05445174, -0.4627266 ,
         0.04240806,  0.02046269,  0.04767558, -0.02186538,  0.0086777 ,
        -0.60646475]),
 array([-0.14897454,  0.84477748

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.47375394240826957,
 0.26989916771672057,
 0.19133645028745425,
 0.5293359246609585,
 0.602579801109889]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/GPH/10 predictors/spearson/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'GPH (2001-2016) 10p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'10_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/GPH/10 predictors/spearson/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/GPH/10 predictors/spearson/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'GPH Predicted vs Actual 10p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'10p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/GPH/10 predictors/spearson/comparison plots/randomforest
