In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [4]:
df_month = pd.read_csv("kendall_corr.csv")
df_month

March_4     March   March_5   April_4     May_9     May_4    May_13  \
0  -0.597235  0.886949  0.034284  0.541441 -0.371839  0.312194 -0.037982   
1  -0.458683  0.508031  0.424149  0.268301  0.032328 -0.042392 -0.345492   
2  -0.700613  0.916458  0.057256  0.204770 -0.328456  0.426428 -0.824342   
3   0.126041  0.562934 -0.184119  0.053606 -0.016677 -0.070442 -0.406799   
4  -0.360737  0.751612 -0.093170  0.585037 -0.196454  0.521449 -0.515565   
5  -0.754349  0.738639  0.293678  0.483146 -0.029274  0.000201 -0.269247   
6  -0.224324  0.459291  0.415315 -0.011717 -0.127890 -0.143192 -0.479352   
7  -0.195441  0.542577  0.158096  0.319329  0.376984 -0.018072 -0.355345   
8  -0.651975  0.739133 -0.110485  0.039460  0.284982  0.018544 -0.614544   
9  -0.531579  0.707722  0.401159  0.369665  0.339524  0.179937 -0.475808   
10 -0.666139  0.751349  0.230030 -0.199104 -0.333221 -0.221079 -0.627531   
11 -0.306020  0.607847 -0.093077  0.539876  0.159931  0.022646 -0.579155   
12 -0.027769  0.366952  0.399143  0.159516 -0.338306  0.401022 -0.573415   
13 -0.063556  0.501265  0.532389 -0.116940 -0.322649  0.377961 -0.956940   
14 -0.601455  0.641262  0.405061  0.824919  0.191709  0.064482 -0.394882   
15 -0.246323  0.845008  0.245995  0.075705 -0.193163  0.294981 -0.511459   
16 -0.460741  0.366628  0.611921 -0.206305 -0.141180  0.006737 -0.525799   
17 -0.355195  0.638750  0.413304 -0.029763 -0.452342  0.172354 -0.467461   
18 -0.772579  0.989592  0.540243  0.135976  0.146373  0.040846 -0.408424   
19 -0.500483  0.749541  0.372074  0.236743 -0.514841 -0.028215 -0.364520   
20 -0.349875  0.797988  0.217566  0.007975 -0.414203  0.373061 -0.587050   
21 -0.762531  0.950415  0.253418  0.202641 -0.179037  0.462755 -0.446842   
22 -0.250137  0.942241 -0.037835  0.067362  0.244737  0.288708 -0.405588   
23 -0.597708  0.658206  0.028388  0.282442 -0.049777  0.100781 -0.318385   
24 -0.758570  0.884313  0.133886  0.480586 -0.126737  0.041785 -0.382179   
25 -0.335512  0.722039  0.004240  0.162910  0.134768  0.347733 -0.149387   
26 -0.398250  0.629598  0.465921  0.145849 -0.153305  0.532691 -0.400163   
27 -0.436170  0.501587  0.434785  0.207523 -0.168121  0.194798 -0.671023   
28 -0.604960  0.934423  0.171339  0.313821 -0.223436  0.149220 -0.502773   
29 -0.514492  1.007014 -0.082163 -0.083241 -0.281623  0.344610 -0.544043   
30 -0.164822  0.670826  0.571903  0.051701 -0.358911  0.849731 -0.730549   
31 -0.228114  0.736553  0.423382  0.266647 -0.150433  0.255451 -0.277710   
32 -0.253347  0.700686  0.303688  0.387528 -0.320521 -0.012747 -0.551052   
33 -0.699935  1.037870  0.167275  0.690966 -0.119270 -0.130797 -0.217039   
34 -0.498755  0.788757 -0.015333  0.208540  0.028292  0.003924 -0.231963   
35 -0.270284  0.912815  0.025888  0.127738 -0.047677 -0.470272 -0.114641   
36 -0.514036  0.751946  0.176678  0.046937 -0.321734 -0.213479 -0.096476   
37 -0.486717  0.677675  0.547373  0.178277 -0.328828  0.032706 -0.378597   
38 -0.426509  0.872224  0.537087 -0.313101  0.373732  0.083071 -0.520596   
39 -0.583974  0.687589  0.035108  0.445078 -0.175417 -0.005703 -0.191311   
40 -0.371906  0.609252  0.203829  0.224205 -0.541816  0.363857 -0.510043   
41 -0.783773  0.781274  0.450619  0.103355 -0.238573  0.031693 -0.272448   
42 -0.103646  0.735529  0.591495  0.190756 -0.263997  0.253097 -0.608671   
43 -0.459218  0.686483  0.190198 -0.084276 -0.415303  0.298885 -0.510232   
44 -0.426851  0.681892 -0.065780  0.198803 -0.005664 -0.272542 -0.296915   
45 -0.158547  0.566614  0.251022  0.116316 -0.054822  0.153389 -0.390441   
46 -0.724274  1.012589  0.082481  0.238151 -0.276285 -0.000650 -0.311562   
47 -0.511650  0.677462  0.156938 -0.092728 -0.147870 -0.023047 -0.216147   
48 -0.294115  0.731109  0.245374  0.098885 -0.189538 -0.409804 -0.350525   
49 -0.403162  0.841295  0.520373  0.126487 -0.433313  0.200526 -0.764874   
50 -0.320780  0.601252  0.494049 -0.001931 -0.087602  0.149591 -0.277404   
51 -0.409716  0.777072  0.225956  0.371858  0.255187 

In [5]:
scaler = StandardScaler()

In [6]:
x_train = df_month.iloc[:42, :5]
x_train = scaler.fit_transform(x_train)
x_train

array([[-0.70839569,  0.96305782, -0.93230785,  1.42238854, -1.03010097],
       [-0.06872067, -1.31598942,  0.83655266,  0.27819605,  0.65694009],
       [-1.18568262,  1.14054353, -0.82808222,  0.0120621 , -0.84901359],
       [ 2.63087605, -0.98576948, -1.92322712, -0.62116725,  0.45238645],
       [ 0.38348494,  0.1490597 , -1.51058196,  1.60501232, -0.29802187],
       [-1.4337747 ,  0.07102939,  0.2445928 ,  1.17818954,  0.3998056 ],
       [ 1.01328442, -1.60913762,  0.79647162, -0.89480863, -0.01182969],
       [ 1.1466356 , -1.10820648, -0.37055749,  0.49195489,  2.09556871],
       [-0.96112474,  0.07399975, -1.58914121, -0.68042663,  1.71154292],
       [-0.40527412, -0.11492073,  0.73224716,  0.70281442,  1.93920852],
       [-1.02651749,  0.1474735 , -0.04418546, -1.67977812, -0.86890451],
       [ 0.6361048 , -0.71563369, -1.51015977,  1.41583314,  1.18956541],
       [ 1.92075404, -2.1645209 ,  0.72309815, -0.17750745, -0.89012977],
       [ 1.75553285, -1.35668194,  1.3

In [7]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [8]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [9]:
x_test = df_month.iloc[43:, :5]
x_test = scaler.fit_transform(x_test)
x_test

array([[-1.50029294e-01, -5.97687919e-01,  1.64517284e-03,
        -9.91897105e-01, -1.66002774e+00],
       [ 2.78610264e-02, -6.23405339e-01, -1.39933191e+00,
         5.94905560e-01,  3.65989278e-01],
       [ 1.50248291e+00, -1.26915680e+00,  3.34537288e-01,
         1.32521860e-01,  1.22859362e-01],
       [-1.60679938e+00,  1.22904779e+00, -5.87894450e-01,
         8.15472165e-01, -9.72465783e-01],
       [-4.38198770e-01, -6.48221138e-01, -1.80385301e-01,
        -1.03927245e+00, -3.37342648e-01],
       [ 7.57390670e-01, -3.47710899e-01,  3.03625555e-01,
         3.48161321e-02, -5.43426228e-01],
       [ 1.58059356e-01,  2.69514370e-01,  1.80870779e+00,
         1.89535292e-01, -1.74910482e+00],
       [ 6.10838665e-01, -1.07512663e+00,  1.66463599e+00,
        -5.30308617e-01, -3.92688634e-02],
       [ 1.22036491e-01, -9.02388672e-02,  1.97352764e-01,
         1.56496486e+00,  1.65611853e+00],
       [ 4.26423341e-01, -6.32574226e-01, -1.24127874e+00,
        -5.15090847e-01

In [10]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] 
    y_test.append(y_ts)

In [11]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

# Bagging Regressor:

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [13]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 20}
Best Score: 0.1983965177293996
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 22}
Best Score: 0.11021464537006453
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 21}
Best Score: 0.2505513423730657
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 38}
Best Score: 0.3145120062491736
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 5}
Best Score: 0.19134815408455397


In [14]:
y_pred_list

[array([-0.06168962,  0.28363648, -0.08322229,  0.25179555,  0.08142335,
        -0.08116105, -0.70702827, -0.60305521,  0.22002601,  0.06349766,
        -0.54317827, -0.07382371,  0.280295  ,  0.33249693,  0.51093073,
        -0.13214407]),
 array([ 0.12391638,  0.23923512,  0.11311915,  0.23923512,  0.1634712 ,
         0.16483632, -0.60967658, -0.65059652,  0.16483632,  0.19831518,
        -0.66139375, -0.60967658,  0.23923512,  0.23923512,  0.19831518,
         0.03565881]),
 array([-0.37635494,  0.15547904, -0.27682715,  0.17248089, -0.09293658,
        -0.26490306, -0.39733049, -0.46757186,  0.22075379, -0.18608566,
        -0.57197941,  0.17210961,  0.2820593 ,  0.30139349,  0.36678209,
        -0.13448969]),
 array([-0.23002834,  0.15961852, -0.26043232,  0.46133256, -0.03336155,
        -0.25329104, -0.37351192, -0.42351441,  0.14367197, -0.13246371,
        -0.43259871,  0.21064336,  0.37278354,  0.30713807,  0.11874148,
        -0.12648561]),
 array([ 0.37967964,  0.387005  

In [15]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [16]:
correlation_list

[0.610751848785699,
 0.37075250575758034,
 0.5914774020828648,
 0.4735309598883665,
 0.3143743095309832]

In [17]:
months = ['jjas-mean','june','july','august','september']

In [18]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Vwind/5 predictors/kendall/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'Vwind (2001-2016) 5p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Vwind/5 predictors/kendall/coorelation_plots/bagging_regressor


In [19]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Vwind/5 predictors/kendall/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'Vwind Predicted vs Actual 5p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Vwind/5 predictors/kendall/comparison plots/bagging_regressor


# Random Forest

In [20]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [21]:

y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 20}
Best Score: 0.1983965177293996
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 22}
Best Score: 0.11021464537006453
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 21}
Best Score: 0.2505513423730657
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 38}
Best Score: 0.3145120062491736
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 5}
Best Score: 0.19134815408455397


In [22]:
y_pred_list_rf

[array([-0.06168962,  0.28363648, -0.08322229,  0.25179555,  0.08142335,
        -0.08116105, -0.70702827, -0.60305521,  0.22002601,  0.06349766,
        -0.54317827, -0.07382371,  0.280295  ,  0.33249693,  0.51093073,
        -0.13214407]),
 array([ 0.12391638,  0.23923512,  0.11311915,  0.23923512,  0.1634712 ,
         0.16483632, -0.60967658, -0.65059652,  0.16483632,  0.19831518,
        -0.66139375, -0.60967658,  0.23923512,  0.23923512,  0.19831518,
         0.03565881]),
 array([-0.37635494,  0.15547904, -0.27682715,  0.17248089, -0.09293658,
        -0.26490306, -0.39733049, -0.46757186,  0.22075379, -0.18608566,
        -0.57197941,  0.17210961,  0.2820593 ,  0.30139349,  0.36678209,
        -0.13448969]),
 array([-0.23002834,  0.15961852, -0.26043232,  0.46133256, -0.03336155,
        -0.25329104, -0.37351192, -0.42351441,  0.14367197, -0.13246371,
        -0.43259871,  0.21064336,  0.37278354,  0.30713807,  0.11874148,
        -0.12648561]),
 array([ 0.37967964,  0.387005  

In [23]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [24]:
correlation_list_rf

[0.610751848785699,
 0.37075250575758034,
 0.5914774020828648,
 0.4735309598883665,
 0.3143743095309832]

In [25]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Vwind/5 predictors/kendall/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'Vwind (2001-2016) 5p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Vwind/5 predictors/kendall/coorelation_plots/randomforest


In [26]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Vwind/5 predictors/kendall/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'Vwind Predicted vs Actual 5p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'5p{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Vwind/5 predictors/kendall/comparison plots/randomforest
