In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("kendall_corr.csv")
df_month

May_3   April_4  October_2   March_3  November_5    May_14  November  \
0  -0.456360  0.290480  -0.210838 -0.062858    0.073594 -0.716983  0.096351   
1   0.332166  0.164445  -0.210838 -0.027647    0.073594 -0.600944  0.096351   
2   0.030945 -0.268834   0.303240  0.008277    0.207152 -1.118022 -0.218011   
3   0.290044 -0.496887  -0.589375 -0.231707    0.329676 -0.522947 -0.267691   
4   0.402890 -0.201643   0.282277  0.035182    0.089461 -0.877231 -0.853638   
5   0.230979  0.082711  -0.428839 -0.287736   -0.061063 -0.664730 -0.460603   
6   0.322157 -0.551298   0.262491 -0.288759    0.608538 -0.505595 -0.569302   
7   0.354008  0.307158  -0.580313 -0.703806    0.352647 -0.741585 -0.455045   
8   0.327928  0.391321  -0.218753 -0.533328    0.240825 -0.521199 -0.491130   
9   0.192342  0.117575   0.287858 -0.393036    0.229326 -0.272887 -0.381082   
10 -0.063031  0.218417  -0.499944 -0.709442   -0.035277 -0.765650 -0.223781   
11 -0.114406  0.040984  -0.533035 -0.012446    0.186543 -0.363894 -0.325987   
12  0.021920 -0.160446   0.360109 -0.182263    0.233974 -0.557729 -0.399345   
13  0.286119 -0.398839   0.038163 -0.292407    0.372497 -0.659954 -0.632852   
14  0.020598  0.131099  -0.802573 -0.393688    0.112438  0.002888 -0.342819   
15  0.335569 -0.048285   0.240227  0.045857    0.531581 -0.829339 -0.468334   
16  0.247891 -0.156792   0.117188  0.062589    0.198031 -0.477459 -0.529670   
17  0.318348  0.176132  -0.041346 -0.470595    0.514377 -0.928691 -0.736686   
18  0.414038 -0.161554  -0.345791 -0.161340   -0.025164 -0.549468 -0.280268   
19  0.067252  0.113504  -0.366100 -0.642900    0.212695 -0.679537 -0.326095   
20  0.070045  0.122277  -0.355024 -0.566334   -0.031506 -0.845112 -0.070872   
21 -0.382901  0.511570  -0.180115 -0.403377    0.012282 -0.077725 -0.149519   
22 -0.042180  0.220496  -0.423262 -0.757404    0.344545 -0.888704 -0.334561   
23  0.170591  0.218912  -0.405287 -0.724866    0.265176 -0.288975 -0.586579   
24 -0.477079  0.077702   0.478720 -0.506557   -0.160620 -0.402018 -0.469922   
25  0.010484  0.088793   0.271629 -0.031828    0.279368 -0.459669 -0.111070   
26  0.511520 -0.239668  -0.171369  0.082820   -0.134660 -0.721574 -0.488867   
27  0.327672 -0.078340  -0.055635 -0.226747    0.571301 -0.677720 -0.652156   
28 -0.065343  0.455561   0.101585 -0.700363    0.240151 -0.587432 -0.110388   
29 -0.069999  0.419751  -0.324390 -0.102963    0.209285 -0.469357  0.193019   
30  0.250170 -0.286756   0.039644 -0.372858    0.065410 -0.996616 -0.183245   
31 -0.194828  0.396065  -0.274910 -0.194250   -0.012236 -0.380367 -0.560692   
32 -0.100025  0.244974  -0.486714 -0.799930   -0.136327 -0.390745 -0.203547   
33 -0.099539  0.166901  -0.265438 -0.450965   -0.012782 -0.306758 -0.090510   
34 -0.600707  0.659000   0.064188 -0.522468    0.258359 -0.149346 -0.063094   
35  0.358204  0.470924  -0.425367 -0.832665    0.325486 -0.535494 -0.505929   
36 -0.020360  0.472139  -0.266163 -0.333786   -0.108083 -0.263312 -0.212730   
37  0.284456  0.483400  -0.143178 -0.294396    0.190032 -0.319552 -0.622502   
38  0.562448  0.094757  -0.282885 -0.417864    0.188281 -0.283463 -0.353471   
39 -0.583505  0.004679   0.049860 -0.780467   -0.240613 -0.148893 -0.316742   
40 -0.129896  0.045534   0.266669 -0.194842    0.456074 -0.706615 -0.880529   
41  0.347877 -0.265441  -0.114781  0.023194    0.349326 -0.616150 -0.783033   
42  0.314423 -0.210901   0.128262 -0.379909    0.116063 -0.130639 -0.708644   
43 -0.004871 -0.156734  -0.158563 -0.289568    0.271347 -0.436109 -0.465749   
44 -0.302775  0.483117  -0.364414 -0.929939   -0.171668 -0.328246 -0.441833   
45 -0.417653  0.043698   0.150685  0.011626    0.404814 -0.091303 -0.207491   
46 -0.489848  0.216409  -0.481954 -0.582901    0.189015 -0.586678 -0.422501   
47 -0.274274  0.080922  -0.335765 -0.307369    0.240966 -0.327148 -0.400856   
48 -0.127321 -0.004535  -0.714655 -0.496037    0.272282 -0.266972 -0.245966   
49 -0.009694 -0.160039  -0.171428 -0.299153    0.140593 -

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :20]
x_train = scaler.fit_transform(x_train)
x_train

array([[-1.88665970e+00,  6.97894032e-01, -2.34716689e-01,
         1.02521255e+00, -4.95579236e-01, -6.83315842e-01,
         1.85431768e+00,  1.49082540e-02,  1.72017970e+00,
         3.36065980e-01,  1.79288861e-01, -3.64915468e-01,
        -1.90761157e-01,  1.62211379e+00,  3.72418786e-01,
        -7.78329576e-01, -4.96627115e-01,  7.30308831e-01,
        -5.54863580e-01,  8.59520599e-01],
       [ 8.47134604e-01,  2.54279284e-01, -2.34716689e-01,
         1.15467839e+00, -4.95579236e-01, -2.23764939e-01,
         1.85431768e+00,  1.49082540e-02, -4.18747741e-01,
        -5.82141663e-01,  7.55424477e-01,  4.87470856e-01,
        -1.90761157e-01, -2.57207131e-01,  9.16269466e-01,
         2.95853325e-01, -7.32118035e-01,  7.30308831e-01,
        -1.52606145e-01,  8.59520599e-01],
       [-1.97189420e-01, -1.27076587e+00,  1.44516672e+00,
         1.28676298e+00,  1.55035944e-01, -2.27154884e+00,
         5.90571766e-01, -1.06074600e+00, -6.55917737e-01,
        -5.61169926e-01, -1.9

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] #df.iloc[43:]['avg']
    y_test.append(y_ts)

In [8]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [9]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

In [10]:
x_test = df_month.iloc[43:, :20]
x_test = scaler.fit_transform(x_test)
x_test

array([[ 2.45885216e-01, -6.61707920e-01,  1.73521236e-01,
         1.68956663e-01,  7.63943307e-01, -1.67218337e-01,
        -5.11147803e-01,  6.69799873e-01,  2.55298411e-02,
        -1.27662941e+00, -1.40430815e+00,  7.40045036e-01,
        -4.19307987e-01,  1.70448428e-01,  4.58816365e-01,
         1.88734353e-01, -2.14435349e-01, -3.81811302e-01,
        -9.30222073e-01,  1.47341572e+00],
       [-6.06591046e-01,  2.63531981e+00, -5.54016941e-01,
        -2.67712018e+00, -1.30714695e+00,  3.21101212e-01,
        -2.84989083e-01,  3.27185018e-01,  5.93968746e-01,
        -1.32586270e+00, -4.93923794e-01,  1.16698720e-01,
         4.50826731e-01,  2.16949031e-01,  5.76420547e-01,
         6.73467556e-01, -3.36523829e-01, -3.40445202e-01,
         3.65714803e-02,  1.06492233e-01],
       [-9.35323787e-01,  3.71082246e-01,  1.26649612e+00,
         1.50758370e+00,  1.38789800e+00,  1.39379247e+00,
         1.93100532e+00, -1.26808362e+00,  1.39100504e+00,
        -1.93225430e+00, -1.0

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 39}
Best Score: 0.24908618604276433
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 38}
Best Score: 0.24798992920512863
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 29}
Best Score: 0.24972567877675572
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 36}
Best Score: 0.2262479061158451
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 30}
Best Score: 0.30058598903914835


In [13]:
y_pred_list

[array([-0.34883179, -0.10737246, -0.42854486, -0.19208953, -0.04936893,
        -0.27644425,  0.13470952, -0.65568235, -0.00537946, -0.02368151,
         0.4673072 , -0.1649401 , -0.68429571, -0.33761165,  0.21057333,
        -0.41015629]),
 array([-0.26404375, -0.04929933, -0.19238866, -0.04929933, -0.04929933,
        -0.05141961,  0.00469746, -0.1472512 , -0.09092788,  0.03905417,
         0.05121027, -0.4024649 , -0.20003141, -0.15438138, -0.04089863,
        -0.11510408]),
 array([-0.41616601, -0.28615171, -0.3096123 , -0.28615171, -0.28615171,
        -0.2189578 ,  0.3008036 , -0.3096123 , -0.3096123 ,  0.27734301,
         0.44650754, -0.41616601, -0.34363538, -0.37243269, -0.20205253,
        -0.3096123 ]),
 array([-0.36317525, -0.28029829, -0.2305244 , -0.24401743, -0.20715858,
        -0.24700636,  0.2873007 , -0.23038649, -0.31148064,  0.2060663 ,
         0.56736904, -0.29954841, -0.23338997, -0.20455689,  0.07058241,
        -0.29612719]),
 array([-0.60566482, -0.07594805

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.13528832734969054,
 0.03206623228073801,
 -0.44768918218608966,
 -0.3798647058824413,
 0.38586677912632605]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/SLP/20 predictors/kendall/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'SLP (2001-2016) 20p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/SLP/20 predictors/kendall/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/SLP/20 predictors/kendall/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'SLP Predicted vs Actual 20p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/SLP/20 predictors/kendall/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:
y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 39}
Best Score: 0.24908618604276433
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 38}
Best Score: 0.24798992920512863
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 29}
Best Score: 0.24972567877675572
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 36}
Best Score: 0.2262479061158451
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 30}
Best Score: 0.30058598903914835


In [21]:
y_pred_list_rf

[array([-0.34883179, -0.10737246, -0.42854486, -0.19208953, -0.04936893,
        -0.27644425,  0.13470952, -0.65568235, -0.00537946, -0.02368151,
         0.4673072 , -0.1649401 , -0.68429571, -0.33761165,  0.21057333,
        -0.41015629]),
 array([-0.26404375, -0.04929933, -0.19238866, -0.04929933, -0.04929933,
        -0.05141961,  0.00469746, -0.1472512 , -0.09092788,  0.03905417,
         0.05121027, -0.4024649 , -0.20003141, -0.15438138, -0.04089863,
        -0.11510408]),
 array([-0.41616601, -0.28615171, -0.3096123 , -0.28615171, -0.28615171,
        -0.2189578 ,  0.3008036 , -0.3096123 , -0.3096123 ,  0.27734301,
         0.44650754, -0.41616601, -0.34363538, -0.37243269, -0.20205253,
        -0.3096123 ]),
 array([-0.36317525, -0.28029829, -0.2305244 , -0.24401743, -0.20715858,
        -0.24700636,  0.2873007 , -0.23038649, -0.31148064,  0.2060663 ,
         0.56736904, -0.29954841, -0.23338997, -0.20455689,  0.07058241,
        -0.29612719]),
 array([-0.60566482, -0.07594805

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.13528832734969054,
 0.03206623228073801,
 -0.44768918218608966,
 -0.3798647058824413,
 0.38586677912632605]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/SLP/20 predictors/kendall/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'SLP (2001-2016) 20p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/SLP/20 predictors/kendall/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/SLP/20 predictors/kendall/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'SLP Predicted vs Actual 20p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/SLP/20 predictors/kendall/comparison plots/randomforest
