In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("mutual_corr.csv")
df_month

August_2    June_7     May_6  February_2   October   April_6   January  \
0   0.332739 -0.243393  0.125011    0.096543 -0.117277  0.612834 -0.471739   
1   0.332739 -0.243393  0.416001    0.126257 -0.117277  0.646307 -0.657610   
2   0.382103 -0.217922  0.173353    0.131943 -0.137758  0.717280 -0.628682   
3   0.346119  0.007338  0.166003    0.413606 -0.270592  0.640720 -0.392340   
4  -0.208397 -0.034780  0.285112    0.444157 -0.310862  0.392004 -0.618448   
5  -0.120453  0.140976  0.174490   -0.455097 -0.495172  0.801301 -0.741867   
6   0.148718 -0.046154  0.330274    0.553804 -0.570540  0.692184 -0.507058   
7   0.591574  0.128425  0.613340    0.018864 -0.360013  0.366707 -0.298362   
8   0.467219 -0.106765  0.010267    0.217917 -0.149430  0.072521 -0.096446   
9   0.147391  0.187472  0.552164    0.334107 -0.382866  0.567211 -0.478672   
10  0.320072 -0.201146  0.199318   -0.326548 -0.429430  0.173368 -0.607678   
11  0.732798  0.181471 -0.040019    0.426935 -0.766853  0.650653 -0.107170   
12 -0.067682 -0.043213 -0.048458    0.134437 -0.638818  0.746598 -0.416109   
13 -0.031570  0.034192  0.324676    0.209853 -0.311064  0.485885 -0.410091   
14 -0.136891 -0.060823  0.168434    0.121643  0.133852  0.795375 -0.628854   
15  0.233460  0.030133  0.163459    0.229495 -0.198151  0.281547 -0.477228   
16 -0.448463  0.065009  0.514681   -0.041169 -0.042574 -0.034982 -0.628581   
17  0.126398  0.055453  0.041669   -0.230035  0.037662  0.627089 -0.153531   
18  0.067911  0.020874  0.221625   -0.000839  0.066094  0.678443 -0.491169   
19  0.092335  0.084907  0.202586    0.097216 -0.353384  0.902505 -0.319463   
20  0.151447 -0.062482  0.174316   -0.050544 -0.032455  0.392883 -0.270666   
21  0.076803 -0.097561 -0.133504   -0.244137  0.048115  0.236456 -0.676585   
22  0.598494 -0.105826  0.864163    0.070183 -0.072651 -0.015087 -0.595975   
23  0.055636 -0.021394 -0.020667    0.133857  0.048789  0.647475 -0.619334   
24 -0.583677 -0.101969  0.359006   -0.112990 -0.256736  0.572832 -0.417062   
25  0.309582 -0.101719  0.668397    0.132313  0.137589  0.061103 -0.349485   
26 -0.465872  0.048816  0.442782    0.866262 -0.026883  0.352247 -0.673514   
27 -0.603944  0.069790  0.313570    0.438343  0.073570  0.500246 -0.407739   
28 -0.289100 -0.402729  0.328237    0.406472  0.394841  0.554627 -0.479122   
29 -0.208725  0.239777  0.274116   -0.113654 -0.203508  0.057671 -0.342679   
30  0.138139  0.074080  0.288639    0.362345 -0.180551  0.462034 -0.159096   
31 -0.539437 -0.040020  0.416629   -0.063199  0.016892  0.131519 -0.494713   
32 -0.036864  0.015506  0.284950    0.187468  0.294694  0.039839 -0.467627   
33 -0.317120  0.201671  0.252890    0.045104  0.275290  0.327769 -0.534497   
34 -0.075806  0.187361  0.441978   -0.219360  0.253174 -0.180060 -0.452015   
35 -0.331380  0.131102  0.202499    0.068007  0.413841  0.030706 -0.486155   
36 -0.340778 -0.011635  0.193404    0.037039  0.211798  0.057680 -0.254556   
37  0.421005  0.306846  0.409236   -0.232378 -0.013376  0.664104 -0.368894   
38 -0.375912 -0.009102  0.580935    0.126489  0.034509 -0.425842 -0.375079   
39 -0.201537  0.349507  0.598017   -0.192202  0.089490  0.450258 -0.659231   
40  0.257169 -0.401161  0.303523    0.153783 -0.077978 -0.005812 -0.425432   
41 -0.572316  0.051566 -0.167559    0.356682  0.111189  0.837698 -0.350079   
42 -0.258691 -0.028074  0.324730   -0.182323 -0.286793 -0.000459 -0.814454   
43 -0.741072 -0.165194  0.298402    0.473098 -0.205801  0.396922 -0.401896   
44 -0.206921  0.199477  0.146683   -0.042709 -0.298344 -0.210286 -0.233282   
45 -0.245809 -0.003392  0.596458    0.158845 -0.205333  0.118917 -0.308834   
46 -0.290689 -0.070044  0.688272   -0.234666 -0.136543 -0.085745 -0.462116   
47 -0.113323 -0.178710  0.154070    0.372255  0.086532  0.074094 -0.281368   
48  0.110280 -0.100060  0.217543    0.318453 -0.095231  0.221480 -0.493037   
49  0.087705 -0.245716  0.193345   -0.113074 -0.046912 -0.037005 -0.175975   
50  0.294589  0.090721  0.

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :20]
x_train = scaler.fit_transform(x_train)
x_train

array([[ 9.35340631e-01, -1.51172944e+00, -7.05007578e-01,
        -5.60081900e-02, -9.36474949e-02,  6.99135820e-01,
        -1.22702970e-01, -2.11578525e+00, -7.29005948e-01,
         1.33600871e-01, -7.03348104e-01,  1.57944416e+00,
        -8.01724321e-01, -1.51300323e+00, -7.27029050e-01,
         2.74945005e-01,  5.95054910e-01,  1.15763120e+00,
        -5.26409866e-01,  1.25472872e+00],
       [ 9.35340631e-01, -1.51172944e+00,  6.37288092e-01,
         5.96859457e-02, -9.36474949e-02,  8.06282488e-01,
        -1.28744837e+00, -2.11578525e+00,  1.21648867e+00,
         1.33600871e-01, -9.33061692e-01,  1.57944416e+00,
        -1.47179976e+00, -6.48109643e-01, -1.14836285e+00,
        -5.68381521e-01,  5.95054910e-01, -1.44151710e+00,
        -5.26409866e-01,  1.25472872e+00],
       [ 1.07791930e+00, -1.35443348e+00, -4.82011495e-01,
         8.18229288e-02, -1.70305396e-01,  1.03347087e+00,
        -1.10617099e+00, -8.08480726e-02, -1.46294263e-01,
        -8.07504827e-01,  3.1

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] #df.iloc[43:]['avg']
    y_test.append(y_ts)

In [8]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [9]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

In [10]:
x_test = df_month.iloc[43:, :20]
x_test = scaler.fit_transform(x_test)
x_test

array([[-2.2404648 , -0.80257844, -0.57048901,  1.18639103, -0.6287374 ,
         0.49015741,  0.11413546,  0.21352675,  1.60527526, -1.83922507,
        -0.94902332,  1.38947852,  0.13483157, -0.11542639,  0.07418014,
        -1.18097298,  1.94184495, -0.02477278, -0.96693167, -0.48386171],
       [-0.5424157 ,  1.25755677, -1.38104783, -0.45590096, -1.22245596,
        -1.47004787,  1.42896471,  0.59202406,  0.80361303, -0.71361946,
         1.71190782, -1.18577993,  0.63495714,  0.25956819,  0.76239246,
        -1.02836745,  1.34398349,  0.88865428,  1.54311721,  0.70191831],
       [-0.66604052,  0.11149102,  1.02186818,  0.18583186, -0.6257355 ,
        -0.40730534,  0.83982313,  0.71723249, -0.37450164, -0.31706427,
        -0.8917125 , -0.68414936, -1.93380751,  0.20474738,  0.54718028,
         0.35399581, -0.9784971 , -1.1299439 ,  0.71675224,  2.22157739],
       [-0.80871146, -0.2650473 ,  1.51238504, -1.06707959, -0.1844037 ,
        -1.06800138, -0.35544974,  0.43338428, -

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 29}
Best Score: 0.04028307855695007
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 7}
Best Score: -0.17308313542672704
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 48}
Best Score: 0.0472576198088539
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 2}
Best Score: 0.13799348493280245
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 48}
Best Score: 0.11796152228627788


In [13]:
y_pred_list

[array([-0.149377  ,  0.2101612 ,  0.04923089, -0.16258875, -0.26320853,
        -0.20207658,  0.03507929,  0.13395901,  0.32563312, -0.23019365,
        -0.12550742, -0.12967521, -0.00863214,  0.27493713,  0.14136747,
        -0.23205619]),
 array([-0.09299132,  0.25788362, -0.10026621, -0.0616032 , -0.19801729,
        -0.19801729,  0.14491659,  0.13218232,  0.25788362, -0.19801729,
        -0.08581069, -0.10026621,  0.01997572,  0.2820911 ,  0.13218232,
        -0.33099348]),
 array([-0.27075861,  0.24393981,  0.03587823, -0.24292426, -0.27489039,
        -0.29769377, -0.07465089,  0.09719931,  0.27180281, -0.25621476,
        -0.21136455, -0.1416972 ,  0.02733614,  0.4240693 ,  0.14410466,
        -0.30089264]),
 array([-0.23718295, -0.23718295,  0.76638462, -0.23718295, -0.23718295,
        -0.23718295, -0.23718295, -0.23718295, -0.23718295, -0.23718295,
        -0.23718295, -0.23718295, -0.23718295,  0.7190991 , -0.23718295,
        -0.23718295]),
 array([-0.3339607 ,  0.13805261

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.4663095463717788,
 0.44840704534049847,
 0.46912030545362876,
 -0.002900646509156047,
 0.49205578446965303]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/uwind+vwind/20 predictors/kendall/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'uwind+vwind (2001-2016) 20p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/uwind+vwind/20 predictors/kendall/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/uwind+vwind/20 predictors/kendall/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'uwind+vwind Predicted vs Actual 20p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/uwind+vwind/20 predictors/kendall/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:
y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 29}
Best Score: 0.04028307855695007
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 7}
Best Score: -0.17308313542672704
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 48}
Best Score: 0.0472576198088539
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 2}
Best Score: 0.13799348493280245
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 48}
Best Score: 0.11796152228627788


In [21]:
y_pred_list_rf

[array([-0.149377  ,  0.2101612 ,  0.04923089, -0.16258875, -0.26320853,
        -0.20207658,  0.03507929,  0.13395901,  0.32563312, -0.23019365,
        -0.12550742, -0.12967521, -0.00863214,  0.27493713,  0.14136747,
        -0.23205619]),
 array([-0.09299132,  0.25788362, -0.10026621, -0.0616032 , -0.19801729,
        -0.19801729,  0.14491659,  0.13218232,  0.25788362, -0.19801729,
        -0.08581069, -0.10026621,  0.01997572,  0.2820911 ,  0.13218232,
        -0.33099348]),
 array([-0.27075861,  0.24393981,  0.03587823, -0.24292426, -0.27489039,
        -0.29769377, -0.07465089,  0.09719931,  0.27180281, -0.25621476,
        -0.21136455, -0.1416972 ,  0.02733614,  0.4240693 ,  0.14410466,
        -0.30089264]),
 array([-0.23718295, -0.23718295,  0.76638462, -0.23718295, -0.23718295,
        -0.23718295, -0.23718295, -0.23718295, -0.23718295, -0.23718295,
        -0.23718295, -0.23718295, -0.23718295,  0.7190991 , -0.23718295,
        -0.23718295]),
 array([-0.3339607 ,  0.13805261

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.4663095463717788,
 0.44840704534049847,
 0.46912030545362876,
 -0.002900646509156047,
 0.49205578446965303]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/uwind+vwind/20 predictors/kendall/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'uwind+vwind (2001-2016) 20p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/uwind+vwind/20 predictors/kendall/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/uwind+vwind/20 predictors/kendall/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'uwind+vwind Predicted vs Actual 20p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/uwind+vwind/20 predictors/kendall/comparison plots/randomforest
