In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("kendall_corr.csv")
df_month

March_5  August_4  August_8  November_5       May  November_8   April_6  \
0   0.386832 -0.738326 -0.081476    0.582192  0.354584    0.247386 -0.557806   
1   0.185237 -0.738326 -0.081476    0.582192  0.439268    0.247386 -0.351881   
2  -0.522044 -0.695796  0.042423    0.500314  0.704365    0.360082 -0.545842   
3   0.037356 -0.947883 -0.030157    0.805822  0.456551    0.301041  0.012633   
4   0.753036 -0.607567  0.199598    0.590018  0.420335    0.298148 -0.691691   
5  -0.149220 -0.553747 -0.259849    0.871422  0.467133    0.114645 -0.424972   
6   0.002876 -0.856548 -0.123362    0.071080  0.606806    0.685788 -0.101287   
7   0.445065 -0.195088 -0.442182    0.611319  0.451416    0.326984 -0.342192   
8  -0.053046 -0.644855  0.037516    1.154874  0.456371    0.517858 -0.202636   
9   0.283769 -0.980771 -0.004844    0.513852  0.410204    0.230598 -0.229558   
10  0.632384 -0.649642  0.063318    1.019115  0.579671    0.374857 -0.518793   
11  0.456598 -0.869427 -0.034801    0.373050  0.262634    0.318735 -0.634050   
12  0.536721 -0.923796  0.079639    0.488297  0.652690    0.510362 -0.167199   
13  0.579242 -0.802844 -0.142100    0.728631  0.526819    0.431792 -0.526592   
14  0.119036 -0.345760 -0.225313    0.860443  0.239085    0.211159 -0.618779   
15  0.301503 -0.842513  0.046842    0.009546  0.414201    0.816625 -0.172950   
16  0.067928 -0.929642 -0.107703    0.952317  0.635298    0.302793 -0.415819   
17  0.603741 -0.613427 -0.189513    0.343810  0.715707    0.309171 -0.218347   
18  0.143476 -0.637092 -0.221560    0.357194  0.110080    0.107668 -0.439097   
19 -0.038171 -0.505379 -0.190806    0.733284  0.229253    0.289948 -0.337869   
20 -0.163956 -0.937131 -0.272474    0.536078  0.740130    0.663477 -0.282692   
21 -0.144114 -0.817189 -0.094299    0.766620  0.311275    0.223728 -0.297447   
22 -0.260572 -0.815767 -0.223018    0.868340  0.487992    0.304915 -0.572111   
23  0.132653 -0.815053 -0.077267    0.684649  0.217638    0.211460 -0.203589   
24 -0.408281 -0.250273 -0.393314    0.976596  0.654147    0.285456 -0.649784   
25  0.435453 -0.983868 -0.058037    0.555187  0.774100    0.538365 -0.441303   
26 -0.176423 -1.031509  0.030883    0.489094  0.695952    0.516467  0.055977   
27 -0.029874 -0.538390  0.060546    0.373707  0.090116    0.624339 -0.112805   
28 -0.412288 -0.867833 -0.380078    0.048241  0.456150    0.749677 -0.561670   
29 -0.141160 -0.413649 -0.806893    0.806635  0.478126    0.710612 -0.306424   
30  0.484167 -1.248001  0.179913    0.544587  0.833675    0.454388  0.003360   
31 -0.233913 -0.835561 -0.344508    0.320285  0.345885    0.669469 -0.347012   
32  0.015711 -0.834259 -0.096127    0.564288  0.361363    0.598150 -0.387478   
33 -0.686719 -0.710545 -0.392373    0.546148 -0.068296    0.170460 -0.307723   
34  0.280681 -0.493617 -0.259099    0.409129  0.262295    0.338506 -0.122235   
35 -0.207028 -0.168705 -0.544150    0.526071  0.237944    0.354573 -0.588877   
36 -0.371372 -0.840497 -0.293183    0.238930  0.349237    0.569568 -0.543767   
37  0.146697 -0.496251 -0.206167    0.721908  0.597590    0.656108 -0.259860   
38  0.147909 -0.983520 -0.395638    0.105575  0.135728    0.468615 -0.170550   
39 -0.313916 -0.172950 -0.498631    1.086495  0.368938    0.172333 -0.381546   
40  0.465485 -0.646220 -0.384563   -0.058230  0.318557    0.729976 -0.214029   
41  0.120786 -0.915591 -0.223073    0.451430  0.765500    0.486453 -0.392997   
42  0.178429 -0.671021 -0.690136    0.881883  0.670236    0.608043 -0.398119   
43 -0.027975 -0.402879 -0.320311    0.396267  0.726200    0.630470 -0.168794   
44 -0.326891 -0.341052 -0.580911    1.132607  0.363527    0.491829 -0.589712   
45 -0.010702 -0.445320 -0.954607    0.635659  0.666059    0.807014 -0.308603   
46 -0.576985 -0.582229 -0.396162    0.830462  0.697035    0.354225 -0.313313   
47  0.277569 -0.424816 -0.461887    0.936742  0.594604    0.376401 -0.379695   
48  0.246533 -1.000447 -0.281622    1.081293  0.280829    0.464721 -0.304160   
49 -0

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :20]
x_train = scaler.fit_transform(x_train)
x_train

array([[ 8.93872688e-01, -1.07821677e-01,  4.53186055e-01,
         6.13117473e-02, -4.22898529e-01, -8.91838192e-01,
        -1.10851692e+00, -9.41709261e-02, -2.63288165e-02,
         1.63174077e-01,  2.35226007e-01, -9.97881301e-02,
         3.61446367e-01, -8.21632322e-01,  1.10763297e-01,
        -6.67603842e-01,  8.74779221e-01,  2.56002309e-01,
         1.31104727e-01,  7.67133127e-01],
       [ 3.02345626e-01, -1.07821677e-01,  4.53186055e-01,
         6.13117473e-02, -1.12555970e-02, -8.91838192e-01,
        -2.62405613e-02, -1.09685833e+00,  1.35062858e+00,
         1.63174077e-01, -1.16647193e+00, -5.29565604e-01,
         3.61446367e-01, -8.21632322e-01,  1.10763297e-01,
        -6.67603842e-01,  8.74779221e-01,  9.87929450e-01,
         7.72296697e-01,  7.67133127e-01],
       [-1.77298402e+00,  6.49284578e-02,  1.05549471e+00,
        -2.23023532e-01,  1.27736491e+00, -2.98123595e-01,
        -1.04563524e+00,  1.04309785e+00, -2.06693970e-01,
        -8.45476277e-01, -3.4

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] #df.iloc[43:]['avg']
    y_test.append(y_ts)

In [8]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [9]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

In [10]:
x_test = df_month.iloc[43:, :20]
x_test = scaler.fit_transform(x_test)
x_test

array([[ 1.49492542e-01,  1.21107640e+00,  3.54267868e-01,
        -1.93055675e+00,  5.94804657e-01,  7.45654678e-01,
         5.31255698e-01,  1.62626640e+00,  4.70768494e-02,
        -4.13260491e-01, -4.53325453e-01,  2.02184992e-01,
        -1.55683659e+00, -4.96754217e-01, -6.04043847e-01,
        -1.67656207e+00,  2.59343190e-01, -4.30910006e-01,
         1.04403107e+00,  1.04520796e+00],
       [-8.45480826e-01,  1.41827358e+00, -1.08843785e+00,
         5.46205867e-01, -8.99930996e-01,  8.89970847e-03,
        -1.90666683e+00, -2.20117312e-03,  7.84417144e-01,
         2.40985394e-01, -5.68652090e-01, -8.79414850e-01,
         3.69536934e-01,  5.75030989e-01,  6.82674402e-01,
         2.12687569e-01,  1.01241842e+00,  3.13750428e-02,
         1.99478507e+00, -6.47655194e-01],
       [ 2.06987554e-01,  1.06884947e+00, -3.15726053e+00,
        -1.12533353e+00,  3.46939054e-01,  1.68383096e+00,
        -2.78507379e-01,  1.05018842e+00,  1.40879336e-01,
        -1.12970410e+00,  7.2

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 7}
Best Score: 0.4996747731644787
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 33}
Best Score: 0.3273351290711576
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 42}
Best Score: 0.42199187895708223
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 10}
Best Score: 0.4663223833688347
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 33}
Best Score: 0.42366000502096923


In [13]:
y_pred_list

[array([ 0.52504464,  0.8875    ,  0.68177083,  0.13071772,  0.57471726,
        -0.11999557, -0.45286264, -0.49249414,  0.96053571, -0.68578869,
        -0.4357793 , -0.20205014, -0.23816522,  0.07217795,  0.10356593,
        -0.56163095]),
 array([-0.14413701,  0.2008017 , -0.20212033,  0.15247358,  0.21872198,
         0.3709567 , -0.19053571, -0.31492925,  0.43132571, -0.50155246,
        -0.22042407,  0.07700912, -0.14512415,  0.27113486,  0.18284844,
        -0.19197054]),
 array([ 0.32365806,  0.40465573,  0.2576216 ,  0.11133993,  0.27653158,
        -0.03767927, -0.49071103, -0.39914929,  0.49019462, -0.7278731 ,
        -0.30566848,  0.12953787, -0.21490361,  0.14145394, -0.09428219,
        -0.48222807]),
 array([ 0.309     ,  0.48159286,  1.1642967 , -0.06738057,  0.70732657,
         0.13961479, -0.51846667, -0.38103442,  0.81044048, -0.6143619 ,
         0.02401597, -0.08556845, -0.19862552,  0.18306082, -0.18957898,
        -0.31654524]),
 array([ 0.52472558,  0.51369192

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.5448828568938641,
 0.754543121800755,
 0.5823761991513295,
 0.29932831629523515,
 0.4916906532621564]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/20 predictors/kendall/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'AT+vwind (2001-2016) 20p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/20 predictors/kendall/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/20 predictors/kendall/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'AT+vwind Predicted vs Actual 20p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/20 predictors/kendall/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:
y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 7}
Best Score: 0.4996747731644787
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 33}
Best Score: 0.3273351290711576
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 42}
Best Score: 0.42199187895708223
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 10}
Best Score: 0.4663223833688347
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 33}
Best Score: 0.42366000502096923


In [21]:
y_pred_list_rf

[array([ 0.52504464,  0.8875    ,  0.68177083,  0.13071772,  0.57471726,
        -0.11999557, -0.45286264, -0.49249414,  0.96053571, -0.68578869,
        -0.4357793 , -0.20205014, -0.23816522,  0.07217795,  0.10356593,
        -0.56163095]),
 array([-0.14413701,  0.2008017 , -0.20212033,  0.15247358,  0.21872198,
         0.3709567 , -0.19053571, -0.31492925,  0.43132571, -0.50155246,
        -0.22042407,  0.07700912, -0.14512415,  0.27113486,  0.18284844,
        -0.19197054]),
 array([ 0.32365806,  0.40465573,  0.2576216 ,  0.11133993,  0.27653158,
        -0.03767927, -0.49071103, -0.39914929,  0.49019462, -0.7278731 ,
        -0.30566848,  0.12953787, -0.21490361,  0.14145394, -0.09428219,
        -0.48222807]),
 array([ 0.309     ,  0.48159286,  1.1642967 , -0.06738057,  0.70732657,
         0.13961479, -0.51846667, -0.38103442,  0.81044048, -0.6143619 ,
         0.02401597, -0.08556845, -0.19862552,  0.18306082, -0.18957898,
        -0.31654524]),
 array([ 0.52472558,  0.51369192

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.5448828568938641,
 0.754543121800755,
 0.5823761991513295,
 0.29932831629523515,
 0.4916906532621564]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/20 predictors/kendall/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'AT+vwind (2001-2016) 20p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/20 predictors/kendall/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/20 predictors/kendall/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'AT+vwind Predicted vs Actual 20p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/20 predictors/kendall/comparison plots/randomforest
