In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("pearson_corr.csv")
df_month

August_4   March_4  August_7  November_5  April_11       May  December_4  \
0  -0.738326  0.386832 -0.081476    0.582192 -0.165895  0.354584   -0.322289   
1  -0.738326  0.185237 -0.081476    0.582192 -0.214565  0.439268   -0.322289   
2  -0.695796 -0.522044  0.042423    0.500314  0.046446  0.704365   -0.342403   
3  -0.947883  0.037356 -0.030157    0.805822  0.352231  0.456551   -0.464380   
4  -0.607567  0.753036  0.199598    0.590018 -0.261425  0.420335   -0.488369   
5  -0.553747 -0.149220 -0.259849    0.871422 -0.411933  0.467133   -0.263892   
6  -0.856548  0.002876 -0.123362    0.071080 -0.114798  0.606806   -0.596444   
7  -0.195088  0.445065 -0.442182    0.611319  0.122476  0.451416   -0.082821   
8  -0.644855 -0.053046  0.037516    1.154874 -0.052350  0.456371   -0.492986   
9  -0.980771  0.283769 -0.004844    0.513852 -0.182110  0.410204   -0.332168   
10 -0.649642  0.632384  0.063318    1.019115 -0.041994  0.579671   -0.605087   
11 -0.869427  0.456598 -0.034801    0.373050 -0.414041  0.262634   -0.332312   
12 -0.923796  0.536721  0.079639    0.488297  0.107902  0.652690   -0.695082   
13 -0.802844  0.579242 -0.142100    0.728631  0.534287  0.526819   -0.545626   
14 -0.345760  0.119036 -0.225313    0.860443 -0.261157  0.239085   -0.409926   
15 -0.842513  0.301503  0.046842    0.009546 -0.244903  0.414201   -0.673484   
16 -0.929642  0.067928 -0.107703    0.952317  0.018025  0.635298   -0.450775   
17 -0.613427  0.603741 -0.189513    0.343810  0.086307  0.715707   -0.515633   
18 -0.637092  0.143476 -0.221560    0.357194  0.330746  0.110080   -0.659839   
19 -0.505379 -0.038171 -0.190806    0.733284 -0.208657  0.229253   -0.733996   
20 -0.937131 -0.163956 -0.272474    0.536078  0.304304  0.740130   -0.228860   
21 -0.817189 -0.144114 -0.094299    0.766620  0.116359  0.311275   -0.582547   
22 -0.815767 -0.260572 -0.223018    0.868340  0.387497  0.487992   -0.434620   
23 -0.815053  0.132653 -0.077267    0.684649 -0.143442  0.217638   -0.174779   
24 -0.250273 -0.408281 -0.393314    0.976596 -0.591234  0.654147   -0.454347   
25 -0.983868  0.435453 -0.058037    0.555187  0.372062  0.774100   -0.768054   
26 -1.031509 -0.176423  0.030883    0.489094  0.130537  0.695952   -0.439776   
27 -0.538390 -0.029874  0.060546    0.373707  0.419839  0.090116   -0.399560   
28 -0.867833 -0.412288 -0.380078    0.048241  0.269521  0.456150   -0.557226   
29 -0.413649 -0.141160 -0.806893    0.806635 -0.098755  0.478126   -0.385682   
30 -1.248001  0.484167  0.179913    0.544587  0.715087  0.833675   -0.830642   
31 -0.835561 -0.233913 -0.344508    0.320285  0.172026  0.345885   -0.676463   
32 -0.834259  0.015711 -0.096127    0.564288 -0.277648  0.361363   -0.362989   
33 -0.710545 -0.686719 -0.392373    0.546148 -0.281898 -0.068296   -0.340459   
34 -0.493617  0.280681 -0.259099    0.409129  0.207255  0.262295   -0.345308   
35 -0.168705 -0.207028 -0.544150    0.526071  0.101500  0.237944   -0.444936   
36 -0.840497 -0.371372 -0.293183    0.238930 -0.275988  0.349237   -0.387642   
37 -0.496251  0.146697 -0.206167    0.721908 -0.101909  0.597590   -0.411119   
38 -0.983520  0.147909 -0.395638    0.105575  0.319204  0.135728   -0.315825   
39 -0.172950 -0.313916 -0.498631    1.086495 -0.504714  0.368938   -0.073731   
40 -0.646220  0.465485 -0.384563   -0.058230 -0.124128  0.318557   -0.635181   
41 -0.915591  0.120786 -0.223073    0.451430  0.616551  0.765500   -0.465465   
42 -0.671021  0.178429 -0.690136    0.881883  0.276691  0.670236   -0.336433   
43 -0.402879 -0.027975 -0.320311    0.396267  0.724304  0.726200   -0.289716   
44 -0.341052 -0.326891 -0.580911    1.132607  0.188570  0.363527   -0.552516   
45 -0.445320 -0.010702 -0.954607    0.635659  0.806317  0.666059   -0.526902   
46 -0.582229 -0.576985 -0.396162    0.830462  0.464534  0.697035   -0.580932   
47 -0.424816  0.277569 -0.461887    0.936742  0.192379  0.594604   -0.141019   
48 -1.000447  0.246533 -0.281622    1.081293  0.408022  0.280829   -0.332249   
49 -

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :10]
x_train = scaler.fit_transform(x_train)
x_train

array([[-1.07821677e-01,  8.93872688e-01,  4.53186055e-01,
         6.13117473e-02, -6.05277590e-01, -4.22898529e-01,
         7.67133127e-01, -1.10851692e+00, -9.97881301e-02,
         1.63174077e-01],
       [-1.07821677e-01,  3.02345626e-01,  4.53186055e-01,
         6.13117473e-02, -7.65458506e-01, -1.12555970e-02,
         7.67133127e-01, -2.62405613e-02, -5.29565604e-01,
         1.63174077e-01],
       [ 6.49284578e-02, -1.77298402e+00,  1.05549471e+00,
        -2.23023532e-01,  9.35721149e-02,  1.27736491e+00,
         6.49490800e-01, -1.04563524e+00, -1.00143208e+00,
        -8.45476277e-01],
       [-9.59005890e-01, -1.31570943e-01,  7.02661237e-01,
         8.37899231e-01,  1.09996000e+00,  7.27556865e-02,
        -6.39104029e-02,  1.88952117e+00, -5.10707954e-02,
         5.58291595e-01],
       [ 4.23299604e-01,  1.96840123e+00,  1.81956731e+00,
         8.84872550e-02, -9.19682217e-01, -1.03286302e-01,
        -2.04211605e-01, -1.81217077e+00,  3.27177145e-01,
         4.

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [8]:
x_test = df_month.iloc[43:, :10]
x_test = scaler.fit_transform(x_test)
x_test

array([[ 1.2110764 ,  0.14949254,  0.35426787, -1.93055675,  1.44032151,
         0.59480466,  1.04520796,  0.5312557 ,  0.20218499, -0.41326049],
       [ 1.41827358, -0.84548083, -1.08843785,  0.54620587, -0.36769888,
        -0.899931  , -0.64765519, -1.90666683, -0.87941485,  0.24098539],
       [ 1.06884947,  0.20698755, -3.15726053, -1.12533353,  1.71710269,
         0.34693905, -0.48265645, -0.27850738, -1.97708071, -1.1297041 ],
       [ 0.61003692, -1.67794253, -0.06564878, -0.47009186,  0.56363861,
         0.474604  , -0.83069811, -0.30579033,  0.06359282,  1.09830025],
       [ 1.13756046,  1.16652462, -0.42951019, -0.11260819, -0.35484685,
         0.0524396 ,  2.00305962, -0.69026563,  0.48879718, -0.02353504],
       [-0.79150174,  1.06321954,  0.56845674,  0.37360493,  0.37291917,
        -1.24076978,  0.77122874, -0.25277521,  0.15375037,  0.70185471],
       [-0.35386805,  0.00463548,  0.48552784,  0.01422231,  0.09338375,
         1.12168798, -1.10606816,  0.88468864

In [9]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] 
    y_test.append(y_ts)

In [10]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 20}
Best Score: 0.5088493546865477
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 32}
Best Score: 0.28286026564946287
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 49}
Best Score: 0.5216049841025837
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 49}
Best Score: 0.5414916675750614
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 49}
Best Score: 0.4568604639123658


In [13]:
y_pred_list

[array([ 0.21287012,  0.47990068,  0.34034293, -0.12728729,  0.42420553,
        -0.17889417, -0.24578441, -0.3505222 ,  0.57988675, -0.83008745,
        -0.19606364,  0.11944864, -0.0927366 , -0.10419124, -0.11132932,
        -0.22207789]),
 array([ 0.3250714 ,  0.47289807,  0.18782292, -0.21406069,  0.49927961,
         0.02918308, -0.29843896, -0.46759447,  0.58759137, -0.7556985 ,
        -0.17769603,  0.03486275, -0.16022998, -0.03696425, -0.10421511,
        -0.36510755]),
 array([ 0.30109737,  0.51913792,  0.39857362, -0.09269432,  0.48408632,
        -0.17441831, -0.40424579, -0.36817087,  0.58137098, -0.87963227,
         0.02517307,  0.17336348, -0.17600047,  0.02094743, -0.06138018,
        -0.53055075]),
 array([ 0.42099201,  0.66556186,  0.4084334 , -0.1933905 ,  0.67577882,
        -0.16339125, -0.58765993, -0.32644818,  0.79867081, -0.88471818,
         0.17918804,  0.22967608,  0.07344294, -0.15843118,  0.1521712 ,
        -0.61484761]),
 array([ 0.53967714,  0.94477447

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.5066818677002557,
 0.4972270415560124,
 0.5404223991028325,
 0.5072084236757494,
 0.5562809523461456]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/10 predictors/pearson/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'AT+vwind (2001-2016) 10p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'10p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/10 predictors/pearson/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/10 predictors/pearson/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'AT+vwind Predicted vs Actual 10p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'10p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/10 predictors/pearson/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:

y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 20}
Best Score: 0.5088493546865477
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 32}
Best Score: 0.28286026564946287
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 49}
Best Score: 0.5216049841025837
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 49}
Best Score: 0.5414916675750614
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 49}
Best Score: 0.4568604639123658


In [21]:
y_pred_list_rf

[array([ 0.21287012,  0.47990068,  0.34034293, -0.12728729,  0.42420553,
        -0.17889417, -0.24578441, -0.3505222 ,  0.57988675, -0.83008745,
        -0.19606364,  0.11944864, -0.0927366 , -0.10419124, -0.11132932,
        -0.22207789]),
 array([ 0.3250714 ,  0.47289807,  0.18782292, -0.21406069,  0.49927961,
         0.02918308, -0.29843896, -0.46759447,  0.58759137, -0.7556985 ,
        -0.17769603,  0.03486275, -0.16022998, -0.03696425, -0.10421511,
        -0.36510755]),
 array([ 0.30109737,  0.51913792,  0.39857362, -0.09269432,  0.48408632,
        -0.17441831, -0.40424579, -0.36817087,  0.58137098, -0.87963227,
         0.02517307,  0.17336348, -0.17600047,  0.02094743, -0.06138018,
        -0.53055075]),
 array([ 0.42099201,  0.66556186,  0.4084334 , -0.1933905 ,  0.67577882,
        -0.16339125, -0.58765993, -0.32644818,  0.79867081, -0.88471818,
         0.17918804,  0.22967608,  0.07344294, -0.15843118,  0.1521712 ,
        -0.61484761]),
 array([ 0.53967714,  0.94477447

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.5066818677002557,
 0.4972270415560124,
 0.5404223991028325,
 0.5072084236757494,
 0.5562809523461456]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/10 predictors/pearson/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'AT+vwind (2001-2016) 10p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'10_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/10 predictors/pearson/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/10 predictors/pearson/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'AT+vwind Predicted vs Actual 10p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'10p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+vwind/10 predictors/pearson/comparison plots/randomforest
