In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("kendall_corr.csv")
df_month

May_3     April     May_5       May   April_4     May_4     May_8  \
0   0.577766 -0.430054 -0.177727 -0.180019  0.061221 -0.143343  0.267263   
1   0.820856 -0.520912  0.092602 -0.615977  0.410492  0.501064  0.213306   
2   0.021220 -0.358331 -0.048001 -0.178367 -0.036227  0.423062  0.753563   
3   0.500332 -0.086501  0.095828  0.046174 -0.278462  0.620112  0.289163   
4  -0.251811 -0.367780 -0.099620 -0.182557 -0.026178  0.802453  0.407351   
5   0.458342 -0.159302 -0.427378 -0.081093  0.636828  0.346501  0.240314   
6  -0.114251 -0.367052 -0.161893 -0.014260  0.225270  0.480851  0.517479   
7   0.075238 -0.398510 -0.419050 -0.213742  0.562983  0.248047  0.122107   
8  -0.349220 -0.673035 -0.257485  0.182326  0.093394  0.331374  0.606392   
9   0.516521 -0.369849 -0.296065 -0.344650  0.577139  0.250620  0.467968   
10  0.053496 -0.443677 -0.155900 -0.025549  0.097090  0.737559  0.687919   
11  0.477420 -0.546708 -0.221875 -0.393709 -0.085792 -0.228722 -0.026778   
12  0.261303 -0.644085 -0.052309 -0.002864 -0.224852  0.445582  0.600023   
13 -0.495674 -0.004837 -0.141789 -0.024835 -0.423795  0.644251  0.491176   
14  0.486630 -0.450886 -0.222755 -0.320542  0.525145 -0.100301 -0.145526   
15 -0.104747 -0.305415  0.141706  0.064711 -0.625929  0.395119  0.593675   
16 -0.064491 -0.207265  0.003711 -0.181569  0.011725  0.604786  0.802402   
17 -0.098106 -0.314901  0.117635 -0.067952 -0.471747  0.562186  0.565097   
18  0.010616 -0.151849  0.096726  0.045880 -0.386009  0.055343  0.316251   
19  0.113180 -0.513836 -0.130024 -0.055479  0.221726  0.044861  0.349533   
20  0.114094 -0.326592 -0.208379 -0.176095 -0.039532  0.293984  0.745111   
21  0.450880 -0.636979 -0.032409 -0.254300 -0.409998 -0.297831  0.407504   
22  0.622281 -0.353437 -0.131458 -0.426231  0.068833 -0.209509  0.735779   
23  0.164387 -0.194189 -0.122296 -0.128847 -0.247676  0.151921  0.388512   
24  0.711878 -0.540526 -0.279606 -0.458170  0.277872 -0.096546  0.728042   
25  0.412946 -0.493669 -0.241783 -0.420402 -0.496902 -0.518226  0.245132   
26  0.118837 -0.351681 -0.109263 -0.182188 -0.594793 -0.273137  0.463500   
27  0.269881 -0.156951  0.080523 -0.325741 -0.593033 -0.042735  0.570935   
28  0.173976 -0.593733 -0.317153 -0.230264 -0.253115 -0.153812  0.499950   
29  0.369832 -0.491272 -0.521813 -0.315852  0.015227 -0.654724  0.514664   
30  0.120492 -0.140813 -0.096186 -0.073732 -0.649337  0.051565  0.690763   
31  0.388065 -0.309273 -0.426897  0.225002 -0.368900  0.378486  0.531380   
32  0.081675 -0.390943 -0.670446 -0.306253 -0.133477 -0.188837  0.454212   
33  0.407648 -0.700036 -0.228686 -0.370909 -0.219963 -0.611811  0.410884   
34  0.556777 -0.432551 -0.577198 -0.363772  0.077821 -0.511510  0.227570   
35  0.811035 -0.470361 -0.221692 -0.428568  0.047228 -0.330770  0.099152   
36  0.562864 -0.664281 -0.154715 -0.146677  0.184075 -0.460952  0.456082   
37  0.556032 -0.524946 -0.227681 -0.105153 -0.392025 -0.186101  0.887455   
38  0.344646 -0.203675 -0.120010  0.008827 -0.680302  0.171582  0.311885   
39  1.067685 -0.375660 -0.253199 -0.603182  0.283465 -0.190904  0.376959   
40  0.106473 -0.684186 -0.327395 -0.475304 -0.251755 -0.676944  0.923639   
41  0.131864 -0.249639 -0.020463  0.148388 -0.898004  0.311569  0.592544   
42  0.053287 -0.141654 -0.211397  0.022847 -0.602105  0.097732  0.462879   
43  0.345609 -0.461839  0.104858 -0.122466 -0.568506  0.083712  0.525970   
44  0.923827 -0.613392 -0.185096 -0.562546 -0.590228 -0.279545  0.353706   
45  0.335699 -0.374658 -0.174285 -0.228336 -0.322609 -0.241882  0.528986   
46  0.981348 -0.605423 -0.049028 -0.286210 -0.372253 -0.011234  0.873777   
47  0.616844 -0.615657  0.289334 -0.034236 -0.350668 -0.265064  0.544087   
48  0.642008 -0.432088 -0.265844 -0.132647 -0.615273  0.110441  1.246458   
49  0.385183 -0.168515 -0.006247 -0.050175 -0.411403 -0.212674  0.575042   
50  0.117611 -0.099066  0.222693 -0.026307 -0.933433  0.395344  0.502548   
51  0.675580 -0.670417 -0.379533 -0.196330 -0.284848  0

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :20]
x_train = scaler.fit_transform(x_train)
x_train

array([[ 9.41004732e-01, -2.00901423e-01,  9.51441790e-04,
         4.64197883e-02,  4.47259681e-01, -5.33899568e-01,
        -8.39352961e-01,  4.55165838e-01,  5.43370210e-01,
        -4.86451468e-01, -2.01425422e+00, -3.84078619e-01,
        -3.71417396e-02, -1.20168885e+00, -2.17503119e+00,
        -6.08307762e-01, -3.74526265e-01, -6.96083435e-01,
         4.51699827e-01,  4.46340203e-01],
       [ 1.68998975e+00, -7.25243495e-01,  1.47162924e+00,
        -2.11798047e+00,  1.38701999e+00,  1.07227509e+00,
        -1.07259528e+00,  4.55165838e-01,  6.11958167e-01,
        -9.48016270e-01, -9.85022860e-01, -3.84078619e-01,
        -3.71417396e-02,  5.64105243e-01, -7.25637819e-01,
        -6.08307762e-01, -3.74526265e-01,  7.54595543e-01,
         1.18114338e+00, -1.68172573e+00],
       [-7.73769207e-01,  2.13013566e-01,  7.06704247e-01,
         5.46233666e-02,  1.85061270e-01,  8.77857486e-01,
         1.26277541e+00, -1.93347302e+00, -1.74581452e-01,
        -1.20465235e+00, -1.1

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] #df.iloc[43:]['avg']
    y_test.append(y_ts)

In [8]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [9]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

In [10]:
x_test = df_month.iloc[43:, :20]
x_test = scaler.fit_transform(x_test)
x_test

array([[-0.61674377, -0.09217359,  0.93993046,  0.14999106, -0.24595085,
         0.49033272, -0.26488861, -1.40604246,  0.04157715, -0.57113805,
         0.46696751, -1.09099635, -1.24764763, -0.90656027,  0.15255562,
         0.6845785 ,  0.78265303,  0.01756495,  0.0228335 ,  0.38408609],
       [ 1.18254379, -0.82468828, -0.22915705, -2.5859565 , -0.35007918,
        -0.8493443 , -0.94326074,  0.94311952,  1.62145399, -0.5543123 ,
        -0.30629162,  0.39377758,  0.03538312, -1.07401388, -0.59797539,
        -0.56146239,  1.05745098,  0.04239516, -0.01979238, -0.60707065],
       [-0.64758364,  0.32920858, -0.18556525, -0.50819673,  0.93280399,
        -0.71044737, -0.25301272, -1.95658582,  1.45574501, -0.22752435,
        -0.36682286, -1.88867896,  0.27737218, -1.63156   , -0.51945563,
         2.56548681, -1.21724802, -0.27717874,  0.23346353,  0.8807394 ],
       [ 1.36153725, -0.78616866,  0.31946864, -0.86799655,  0.69482753,
         0.14017634,  1.10476192,  0.81698969, -

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 46}
Best Score: 0.3378424107276728
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 32}
Best Score: 0.39089168807712926
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 24}
Best Score: 0.32999728968551856
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 40}
Best Score: 0.31175673845208063
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 14}
Best Score: 0.23108980701847381


In [13]:
y_pred_list

[array([-0.09404508,  0.21740805,  0.12890163,  0.16336029,  0.16935806,
         0.20543915, -0.10457955, -0.53109366,  0.1566986 , -0.29111029,
        -0.33541677, -0.04288119, -0.04589136,  0.27992315,  0.55733011,
         0.07771054]),
 array([ 0.04787305,  0.25020455, -0.03810398,  0.129396  ,  0.19612218,
         0.11629987, -0.14232403, -0.41073696,  0.24679084, -0.60185949,
        -0.38943628, -0.00385521,  0.01405748, -0.04240424,  0.47543232,
         0.19981045]),
 array([-0.38312359,  0.09900696, -0.00180494,  0.04969112, -0.03194967,
         0.42140216, -0.15992391, -0.51157135,  0.43880961, -0.41850854,
        -0.24132829, -0.1994866 , -0.05758908,  0.2939948 ,  0.3257286 ,
         0.1306468 ]),
 array([-0.18205344,  0.1344267 ,  0.21358434,  0.17736146,  0.16105028,
         0.35419732,  0.18710558, -0.54400685,  0.19894127, -0.2994553 ,
        -0.23347923, -0.08334017, -0.1326818 ,  0.40759698,  0.43434927,
        -0.0218315 ]),
 array([-0.31719901, -0.00104064

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.7815776006220955,
 0.8233567180720309,
 0.5635340596925726,
 0.5723901744902826,
 0.7258262782066426]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+sst/20 predictors/kendall/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'slp+sst (2001-2016) 20p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+sst/20 predictors/kendall/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+sst/20 predictors/kendall/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'slp+sst Predicted vs Actual 20p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+sst/20 predictors/kendall/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:
y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 46}
Best Score: 0.3378424107276728
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 32}
Best Score: 0.39089168807712926
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 24}
Best Score: 0.32999728968551856
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 40}
Best Score: 0.31175673845208063
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 14}
Best Score: 0.23108980701847381


In [21]:
y_pred_list_rf

[array([-0.09404508,  0.21740805,  0.12890163,  0.16336029,  0.16935806,
         0.20543915, -0.10457955, -0.53109366,  0.1566986 , -0.29111029,
        -0.33541677, -0.04288119, -0.04589136,  0.27992315,  0.55733011,
         0.07771054]),
 array([ 0.04787305,  0.25020455, -0.03810398,  0.129396  ,  0.19612218,
         0.11629987, -0.14232403, -0.41073696,  0.24679084, -0.60185949,
        -0.38943628, -0.00385521,  0.01405748, -0.04240424,  0.47543232,
         0.19981045]),
 array([-0.38312359,  0.09900696, -0.00180494,  0.04969112, -0.03194967,
         0.42140216, -0.15992391, -0.51157135,  0.43880961, -0.41850854,
        -0.24132829, -0.1994866 , -0.05758908,  0.2939948 ,  0.3257286 ,
         0.1306468 ]),
 array([-0.18205344,  0.1344267 ,  0.21358434,  0.17736146,  0.16105028,
         0.35419732,  0.18710558, -0.54400685,  0.19894127, -0.2994553 ,
        -0.23347923, -0.08334017, -0.1326818 ,  0.40759698,  0.43434927,
        -0.0218315 ]),
 array([-0.31719901, -0.00104064

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.7815776006220955,
 0.8233567180720309,
 0.5635340596925726,
 0.5723901744902826,
 0.7258262782066426]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+sst/20 predictors/kendall/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'slp+sst (2001-2016) 20p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+sst/20 predictors/kendall/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+sst/20 predictors/kendall/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'slp+sst Predicted vs Actual 20p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+sst/20 predictors/kendall/comparison plots/randomforest
