In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("spearman_corr.csv")
df_month

March_7     May_8   April_6  October_7   March_6  October_6     May_2  \
0   0.319904 -0.852495 -0.104311  -0.413652 -0.234575   0.143648  0.057135   
1   0.516930 -0.845069  0.035738  -0.413652 -0.318164   0.143648 -0.073538   
2   0.236701 -0.590339 -0.384591   0.027956 -0.338490   0.306010  0.269578   
3   0.216181 -0.520556 -0.387030   0.161050 -0.122469   0.194688  0.024475   
4   0.308101 -0.687532 -0.092262   0.207545 -0.206767   0.150216  0.175943   
5   0.477551 -0.404820  0.208624  -0.158057 -0.202997   0.297595  0.063219   
6   0.676411 -0.416906 -0.209037   0.037837  0.248931   0.427143  0.109402   
7   0.481080 -0.659332  0.260026  -0.095395 -0.159086   0.125576 -0.082889   
8   0.570303 -0.832134 -0.328015  -0.078566  0.000734   0.527194  0.378568   
9   0.783917 -0.844990 -0.004884  -0.247034  0.042361  -0.019894 -0.240418   
10  0.885234 -0.919831 -0.103935   0.192553 -0.015148   0.095273  0.379304   
11  0.557202 -1.201436 -0.348195   0.131053  0.022883   0.160146 -0.320330   
12  0.686012 -0.436037 -0.296909  -0.031763  0.078270   0.191528  0.201133   
13  0.729469 -0.411844 -0.218239   0.212235 -0.115746   0.424944  0.452377   
14  0.538917 -0.846678 -0.001275   0.080725 -0.062301  -0.332785 -0.355286   
15  0.750663 -1.010343 -0.427952   0.216618 -0.129578   0.553397 -0.079824   
16  0.648792 -0.687574 -0.374006   0.068310 -0.048697   0.436605  0.268259   
17  0.798494 -0.589119 -0.025361   0.313999 -0.060721   0.245610  0.211480   
18  0.470566 -0.642845 -0.180371  -0.332513  0.002260  -0.130305 -0.168809   
19  0.412475 -0.700360 -0.114047  -0.106588  0.039469  -0.081769  0.648797   
20  0.609184 -0.650685 -0.154797   0.216280  0.303989   0.354359  0.296062   
21  0.369053 -0.940887 -0.081204  -0.048221 -0.048098   0.367483  0.148760   
22  0.324268 -0.717090  0.072628   0.365339  0.081296   0.147255 -0.119328   
23  0.386027 -0.904664 -0.175884  -0.117264  0.343986   0.279702  0.210529   
24  0.504688 -0.985174 -0.209115   0.368654 -0.210698   0.244827  0.091828   
25  0.660589 -0.569978  0.251590   0.310994  0.179605   0.293256  0.087547   
26  0.598726 -0.539389 -0.112678  -0.238892 -0.018947   0.178640  0.304029   
27  0.713991 -0.514107 -0.051754   0.510461 -0.109409   0.264910  0.312592   
28  0.774835 -1.054893  0.217478  -0.092212 -0.096937   0.003093 -0.217311   
29  0.211223 -1.086590  0.311318  -0.163177 -0.187889   0.083183 -0.048179   
30  1.044898 -0.435573 -0.088113   0.257598  0.063502   0.319226  0.157964   
31  0.618326 -0.450881  0.015785   0.248477  0.027100   0.516840  0.323581   
32  0.574581 -1.101024  0.185852   0.005917 -0.011861   0.055699 -0.248688   
33  0.265454 -1.524831 -0.093495   0.111451  0.088138   0.203600 -0.087389   
34 -0.271505 -1.535719  0.164961   0.070784 -0.011348   0.269340 -0.278620   
35  0.148541 -0.976848 -0.051980  -0.047962 -0.031480   0.426005  0.033174   
36  0.131308 -0.717103 -0.085628   0.137073 -0.164001   0.318126  0.159209   
37  0.545931 -0.913556 -0.263346  -0.085147  0.144200   0.192841  0.030663   
38  0.544718 -0.814521 -0.230546   0.047277  0.018576  -0.023120 -0.103475   
39  0.027603 -1.037813  0.309759   0.009649 -0.207999  -0.038975 -0.231487   
40  0.226183 -1.143089  0.515949  -0.016451  0.150737   0.469697  0.261459   
41  0.587506 -0.524652 -0.396512   0.105164  0.321460  -0.055202 -0.069802   
42  0.580256 -0.823933 -0.131581  -0.105623  0.084074   0.161292 -0.184590   
43  0.722982 -0.807037  0.054877  -0.021870 -0.153756  -0.139907  0.113683   
44  0.539732 -1.048659 -0.089119  -0.243537 -0.170887  -0.225953 -0.173857   
45  0.309253 -0.835871 -0.033668   0.069984 -0.267859   0.313148  0.315144   
46  0.479399 -0.562357  0.007897  -0.268517 -0.042974  -0.182203  0.286030   
47  0.611415 -1.177788 -0.139136   0.231592  0.018968   0.198276 -0.117997   
48  0.918148 -1.012569  0.071401  -0.199849 -0.009664   0.249359  0.370796   
49  0.605242 -0.431466 -0.316671   0.536726  0.008670   0.029967  0.148386   
50  0.663614 -0.544057 -0.3

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :5]
x_train = scaler.fit_transform(x_train)
x_train

array([[-0.69053382, -0.22073677, -0.14352933, -2.20194045, -1.32695675],
       [ 0.10035607, -0.19390055,  0.48871938, -2.20194045, -1.85061348],
       [-1.02451884,  0.72662114, -1.40884924, -0.06389693, -1.97795359],
       [-1.10688881,  0.97879475, -1.41985776,  0.58047876, -0.62464948],
       [-0.73791039,  0.37539444, -0.08913378,  0.80558265, -1.15274614],
       [-0.05771756,  1.39703091,  1.26921256, -0.96447832, -1.12913337],
       [ 0.74053371,  1.35335607, -0.61631211, -0.01605819,  1.70206031],
       [-0.04355063,  0.47730125,  1.50126664, -0.66109998, -0.85404181],
       [ 0.31460114, -0.14715866, -1.1534346 , -0.57962117,  0.14718259],
       [ 1.17207817, -0.19361448,  0.30533466, -1.39525774,  0.4079594 ],
       [ 1.57877673, -0.46407021, -0.1418302 ,  0.73300034,  0.04768681],
       [ 0.26201193, -1.48170725, -1.24453885,  0.43524565,  0.28593519],
       [ 0.77907159,  1.28422294, -1.01300721, -0.35302796,  0.63291922],
       [ 0.95351573,  1.37164863, -0.6

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [8]:
x_test = df_month.iloc[43:, :5]
x_test = scaler.fit_transform(x_test)
x_test

array([[ 0.60266474, -0.05157151,  0.7290428 , -0.20256497, -0.5545848 ],
       [-0.1729158 , -1.1236927 , -0.00956298, -1.03555508, -0.66599333],
       [-1.14838154, -0.17951572,  0.27486703,  0.14260789, -1.29663738],
       [-0.42826589,  1.03411882,  0.48806855, -1.12942563,  0.16586332],
       [ 0.13047322, -1.69666179, -0.26611605,  0.74990653,  0.56869357],
       [ 1.42867253, -0.96355488,  0.81380072, -0.87138157,  0.38249452],
       [ 0.10434667,  1.61490447, -1.17675771,  1.89655142,  0.50172609],
       [ 0.35139571,  1.11531533, -1.56444767,  0.79600056,  0.71374918],
       [-0.98222394,  0.81675205,  1.52336058, -0.37141825,  0.62416114],
       [-0.13847844,  1.52610882, -1.99961978,  1.43543467,  2.03023018],
       [ 2.62335266,  0.57100972, -1.36322011,  0.59198197,  1.25200018],
       [-0.05715745, -0.99161896,  1.30498648, -1.55947545, -1.43456891],
       [-0.24531396, -0.15524622,  0.09677148,  0.17947909,  0.67533232],
       [-0.67273435, -0.04172176,  0.7

In [9]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] 
    y_test.append(y_ts)

In [10]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 4}
Best Score: 0.16619392294717628
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 6}
Best Score: -0.06434212172253162
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 6}
Best Score: 0.15442366231204535
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 9}
Best Score: 0.1720601345636042
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 5}
Best Score: 0.028631226094229634


In [13]:
y_pred_list

[array([-0.19189126,  0.05116677,  0.05116677, -0.25793137,  0.05116677,
        -0.19189126, -0.25793137, -0.25793137,  0.51975515, -0.25793137,
        -0.19189126,  0.05116677,  0.05116677,  0.05116677,  0.05116677,
        -0.19189126]),
 array([-0.40399701,  0.39190958,  0.36328373, -0.11558048,  0.46912646,
        -0.09189384, -0.16268519, -0.50341667,  0.36969729, -0.16268519,
        -0.39378205,  0.43024291,  0.261309  ,  0.15839768,  0.86935897,
        -0.46198465]),
 array([-0.19431136,  0.26104975,  0.27475809, -0.0696936 ,  0.26104975,
        -0.0588947 , -0.3822399 , -0.3822399 ,  0.57615741, -0.3822399 ,
        -0.48113958,  0.28845716,  0.06412334,  0.21153075,  0.3516845 ,
        -0.31478358]),
 array([-0.13495446,  0.21954789,  0.21954789, -0.0877085 ,  0.00582155,
        -0.24202236, -0.19436694, -0.32871879,  0.59850066, -0.0877085 ,
        -0.24202236,  0.21954789,  0.11247999,  0.21954789,  0.21954789,
        -0.13495446]),
 array([-0.37754574,  0.06151378

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.5188682912851197,
 0.6907236154116122,
 0.7093946598796338,
 0.5061543016949459,
 0.27181555258878126]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Uwind/5 predictors/spearson/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'Uwind (2001-2016) 5p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Uwind/5 predictors/spearson/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Uwind/5 predictors/spearson/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'Uwind Predicted vs Actual 5p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Uwind/5 predictors/spearson/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:

y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 4}
Best Score: 0.16619392294717628
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 6}
Best Score: -0.06434212172253162
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 6}
Best Score: 0.15442366231204535
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 9}
Best Score: 0.1720601345636042
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 5}
Best Score: 0.028631226094229634


In [21]:
y_pred_list_rf

[array([-0.19189126,  0.05116677,  0.05116677, -0.25793137,  0.05116677,
        -0.19189126, -0.25793137, -0.25793137,  0.51975515, -0.25793137,
        -0.19189126,  0.05116677,  0.05116677,  0.05116677,  0.05116677,
        -0.19189126]),
 array([-0.40399701,  0.39190958,  0.36328373, -0.11558048,  0.46912646,
        -0.09189384, -0.16268519, -0.50341667,  0.36969729, -0.16268519,
        -0.39378205,  0.43024291,  0.261309  ,  0.15839768,  0.86935897,
        -0.46198465]),
 array([-0.19431136,  0.26104975,  0.27475809, -0.0696936 ,  0.26104975,
        -0.0588947 , -0.3822399 , -0.3822399 ,  0.57615741, -0.3822399 ,
        -0.48113958,  0.28845716,  0.06412334,  0.21153075,  0.3516845 ,
        -0.31478358]),
 array([-0.13495446,  0.21954789,  0.21954789, -0.0877085 ,  0.00582155,
        -0.24202236, -0.19436694, -0.32871879,  0.59850066, -0.0877085 ,
        -0.24202236,  0.21954789,  0.11247999,  0.21954789,  0.21954789,
        -0.13495446]),
 array([-0.37754574,  0.06151378

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.5188682912851197,
 0.6907236154116122,
 0.7093946598796338,
 0.5061543016949459,
 0.27181555258878126]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Uwind/5 predictors/spearson/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'Uwind (2001-2016) 5p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Uwind/5 predictors/spearson/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Uwind/5 predictors/spearson/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'Uwind Predicted vs Actual 5p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'5p{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Uwind/5 predictors/spearson/comparison plots/randomforest
