In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("pearson_corr.csv")
df_month

May_15   April_2     May_7     April     May_4    May_10    May_18  \
0  -0.477951  0.549644 -0.138533  0.057716  0.635403  0.148821 -0.618299   
1  -0.181143  0.301774  0.164138 -0.064300  0.260732  0.127453 -0.379904   
2  -0.143727  0.202343 -0.137255 -0.012720  0.486865 -0.118703 -0.549860   
3   0.021027  0.291771  0.139752 -0.023654  0.462528 -0.113571 -0.679115   
4   0.114325  0.558279 -0.016171  0.156914  0.453230 -0.327550 -0.423173   
5  -0.314992  0.523335  0.148289 -0.056669  0.552951 -0.061617 -0.535356   
6  -0.029512  0.525110  0.014036  0.123758  0.324065 -0.308104 -0.416714   
7  -0.292144  0.569320  0.079009 -0.205982  0.846530 -0.109477 -0.669647   
8  -0.283594  0.377989  0.126428  0.363870  0.499065 -0.218787 -0.532849   
9  -0.233859  0.602878 -0.024452  0.013008  0.133605  0.043251 -0.410779   
10 -0.169542  0.582086  0.353986  0.049062  0.496585 -0.214002 -0.716885   
11 -0.177337  0.574569 -0.138370  0.028621  0.564174  0.252652 -0.441174   
12 -0.229030  0.676845 -0.092830 -0.001097  0.669165 -0.022577 -0.358311   
13  0.333282  0.790988 -0.289065  0.247520  0.004033 -0.131676 -0.180145   
14 -0.038624  0.237500  0.376332 -0.182334  0.428670  0.060125 -0.160727   
15  0.182996  0.308638 -0.195298  0.142518  0.101840 -0.147670 -0.183191   
16  0.429143  0.591607  0.049698  0.184316  0.050566 -0.152759 -0.310144   
17  0.585932  0.794426 -0.284270  0.038876 -0.090178 -0.325534 -0.239934   
18  0.453580  0.616406 -0.186715  0.170326  0.072250 -0.073389 -0.262028   
19  0.152900  0.404405 -0.300958 -0.177224  0.483944  0.035868 -0.712307   
20  0.077736  0.733877 -0.239042  0.009376  0.275260 -0.101167 -0.362419   
21 -0.075145  0.479975 -0.321818 -0.108381  0.533084  0.091610 -0.475389   
22 -0.014531  0.378601 -0.327165 -0.228710  0.448458  0.074344 -0.405252   
23  0.036679  0.548193 -0.338584 -0.050159  0.462476  0.052615 -0.535826   
24 -0.149724  0.267605  0.142882 -0.007061  0.447416  0.102461 -0.633531   
25 -0.052193  0.444430 -0.557842 -0.147402  0.233701  0.613472 -0.254817   
26  0.079446  0.939533 -0.479562 -0.266740  0.306228 -0.032985 -0.359527   
27  0.362441  0.772201 -0.137846  0.121066  0.048527 -0.124771 -0.484984   
28  0.147613  0.873931  0.119458  0.009528  0.392785 -0.108238 -0.495069   
29 -0.092525  0.315279 -0.381123 -0.086061  0.288400  0.179957 -0.550807   
30  0.275484  0.706049 -0.389698  0.042756  0.494057 -0.055750 -0.563222   
31  0.239738  0.877367  0.164729  0.046741  0.407987 -0.081712 -0.609757   
32 -0.091430  0.615651 -0.069960 -0.134148  0.340316 -0.003959 -0.416249   
33  0.063420  0.606966  0.140939  0.071208  0.298584 -0.095469 -0.336885   
34 -0.324643  0.295914 -0.004191  0.037685  0.314441  0.458060 -0.344971   
35 -0.114563  0.428441 -0.142551 -0.203239  0.554963  0.429063 -0.528488   
36  0.013866  0.630835  0.034156  0.062957  0.366936  0.137003 -0.484958   
37 -0.034123  0.342443 -0.086108 -0.103263  0.574402  0.075415 -0.397330   
38 -0.120117  1.069303 -0.255860 -0.092147  0.517151  0.176958 -0.622303   
39 -0.244597  0.176725  0.074763 -0.177324  0.518705  0.166508 -0.812720   
40  0.383722  0.748188 -0.860719  0.111250  0.045578  0.156651 -0.424512   
41  0.576788  0.897683 -0.280526  0.253402  0.107309 -0.369898 -0.356061   
42  0.651952  0.760858 -0.531068 -0.032803  0.103359 -0.107364 -0.511950   
43  0.318207  0.523145 -0.434759 -0.078340  0.256541  0.061802 -0.502073   
44 -0.035711  0.338443  0.092241 -0.331121  0.268282  0.130844 -0.234723   
45  0.161525  0.500749 -0.101354 -0.201092  0.539937 -0.078200 -0.541065   
46 -0.138218  0.349507 -0.026525 -0.271034  0.481738  0.021562 -0.667191   
47 -0.198203  0.366807 -0.295785 -0.077306  0.627494  0.083833 -0.425154   
48  0.007292  0.342485 -0.471063 -0.394812  0.630349 -0.026542 -0.656631   
49  0.230474  0.395220 -0.175676 -0.135236  0.353066 -0.074047 -0.309368   
50  0.340996  0.752640 -0.344626 -0.222435  0.384994 -0.109493 -0.531913   
51 -0.197459  0.621159  0.133510 -0.138369  0.445739  

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :5]
x_train = scaler.fit_transform(x_train)
x_train

array([[-1.96480490e+00, -1.58794912e-02, -1.23784085e-01,
         4.09955393e-01,  1.32505447e+00],
       [-7.82648870e-01, -1.16358009e+00,  1.11477325e+00,
        -4.61701142e-01, -5.24423709e-01],
       [-6.33625774e-01, -1.62396816e+00, -1.18553889e-01,
        -9.32264379e-02,  5.91827056e-01],
       [ 2.25736591e-02, -1.20989417e+00,  1.01498399e+00,
        -1.71340624e-01,  4.71696026e-01],
       [ 3.94173888e-01,  2.41002234e-02,  3.76935528e-01,
         1.11860580e+00,  4.25795633e-01],
       [-1.31575524e+00, -1.37699732e-01,  1.04991977e+00,
        -4.07187224e-01,  9.18046384e-01],
       [-1.78715017e-01, -1.29479851e-01,  5.00545776e-01,
         8.81742979e-01, -2.11797829e-01],
       [-1.22475572e+00,  7.52254498e-02,  7.66419522e-01,
        -1.47385074e+00,  2.36723229e+00],
       [-1.19070162e+00, -8.10686020e-01,  9.60462899e-01,
         2.59705956e+00,  6.52052269e-01],
       [-9.92610126e-01,  2.30606240e-01,  3.43045839e-01,
         9.05719839e-02

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [8]:
x_test = df_month.iloc[43:, :5]
x_test = scaler.fit_transform(x_test)
x_test

array([[ 1.582035  ,  0.13405047, -1.19443032,  1.09726233, -0.7094849 ],
       [-0.56448653, -0.90905174,  0.78739636, -1.20906517, -0.6401869 ],
       [ 0.63175548,  0.00757064,  0.05936566, -0.022708  ,  0.96314181],
       [-1.18619767, -0.84656618,  0.34076718, -0.66083635,  0.61964892],
       [-1.55000812, -0.74886424, -0.67180906,  1.10669788,  1.47991072],
       [-0.30367622, -0.8862223 , -1.33095483, -1.79016816,  1.49676289],
       [ 1.04993329, -0.58840493, -0.22012826,  0.57814939, -0.13978612],
       [ 1.72025362,  1.4301193 , -0.85547927, -0.21743737,  0.04865708],
       [-1.54549373,  0.68758501,  0.9425919 ,  0.54956832,  0.40717707],
       [-0.08733319, -0.04114739, -1.23174772,  1.25584851,  0.06095717],
       [ 1.02391197,  2.34609167,  0.12878112, -0.28640291, -2.12664945],
       [ 0.76957446,  0.51343944, -0.66182413, -1.86895247, -1.55776389],
       [-0.74831246,  1.07767335, -0.58433067,  1.13691646, -0.47320443],
       [-0.22361406,  0.29900829,  1.7

In [9]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] 
    y_test.append(y_ts)

In [10]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 9}
Best Score: 0.028269546268575085
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 10}
Best Score: 0.1079074382567412
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 10}
Best Score: 0.09522213139905156
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 9}
Best Score: 0.130106066959714
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 7}
Best Score: -0.07525388113947662


In [13]:
y_pred_list

[array([-0.33417024,  0.03395029, -0.15089559,  0.22380431,  0.22380431,
         0.11167732, -0.25644321, -0.46577908,  0.01446844,  0.11167732,
        -0.54350611, -0.43185928, -0.17538557,  0.01398828,  0.30804069,
         0.11167732]),
 array([-0.2597349 ,  0.24575155, -0.07621704,  0.24575155,  0.16337655,
         0.24575155, -0.08897047, -0.56078149, -0.22605946,  0.07498713,
        -0.64756482, -0.53613625, -0.30843446, -0.0090102 ,  0.24575155,
         0.16337655]),
 array([-0.35375108,  0.07783744, -0.15707298,  0.17726601,  0.08891879,
        -0.01050978, -0.26540386, -0.53048204,  0.00053506, -0.01050978,
        -0.51141815, -0.50480108, -0.18724074,  0.07783744,  0.24386987,
         0.07783744]),
 array([-0.35633545,  0.17390926, -0.08274191,  0.54691597,  0.17633264,
         0.23509539, -0.08274191, -0.6188285 ,  0.05240284, -0.02082127,
        -0.55148457, -0.46903148, -0.59344312,  0.03544964,  0.6996407 ,
         0.0076198 ]),
 array([-0.53881306,  0.34291794

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.4096798636086967,
 0.47219786853862455,
 0.3585211866466234,
 0.5455580839225649,
 0.7996390851281308]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/SST/5 predictors/pearson/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'SST (2001-2016) 5p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/SST/5 predictors/pearson/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/SST/5 predictors/pearson/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'SST Predicted vs Actual 5p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/SST/5 predictors/pearson/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:

y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 9}
Best Score: 0.028269546268575085
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 10}
Best Score: 0.1079074382567412
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 10}
Best Score: 0.09522213139905156
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 9}
Best Score: 0.130106066959714
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 7}
Best Score: -0.07525388113947662


In [21]:
y_pred_list_rf

[array([-0.33417024,  0.03395029, -0.15089559,  0.22380431,  0.22380431,
         0.11167732, -0.25644321, -0.46577908,  0.01446844,  0.11167732,
        -0.54350611, -0.43185928, -0.17538557,  0.01398828,  0.30804069,
         0.11167732]),
 array([-0.2597349 ,  0.24575155, -0.07621704,  0.24575155,  0.16337655,
         0.24575155, -0.08897047, -0.56078149, -0.22605946,  0.07498713,
        -0.64756482, -0.53613625, -0.30843446, -0.0090102 ,  0.24575155,
         0.16337655]),
 array([-0.35375108,  0.07783744, -0.15707298,  0.17726601,  0.08891879,
        -0.01050978, -0.26540386, -0.53048204,  0.00053506, -0.01050978,
        -0.51141815, -0.50480108, -0.18724074,  0.07783744,  0.24386987,
         0.07783744]),
 array([-0.35633545,  0.17390926, -0.08274191,  0.54691597,  0.17633264,
         0.23509539, -0.08274191, -0.6188285 ,  0.05240284, -0.02082127,
        -0.55148457, -0.46903148, -0.59344312,  0.03544964,  0.6996407 ,
         0.0076198 ]),
 array([-0.53881306,  0.34291794

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.4096798636086967,
 0.47219786853862455,
 0.3585211866466234,
 0.5455580839225649,
 0.7996390851281308]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/SST/5 predictors/pearson/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'SST (2001-2016) 5p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/SST/5 predictors/pearson/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/SST/5 predictors/pearson/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'SST Predicted vs Actual 5p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'5p{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/SST/5 predictors/pearson/comparison plots/randomforest
