In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df['avg'] = df[['june', 'july', 'august', 'september']].mean(axis=1)

In [4]:
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [5]:
df_month = pd.read_csv("kendall_corr.csv")
df_month

February     March   January   October     April   April_2  January_2  \
0  -0.430790 -0.425564 -0.496601 -0.579346 -0.437501 -0.405269  -0.526040   
1  -0.396378 -0.295403 -0.418067 -0.579346 -0.526561 -0.383825  -0.612077   
2  -0.488636 -0.499451 -0.446087 -0.421272 -0.385871 -0.288243  -0.704553   
3  -0.386004 -0.578870 -0.564336 -0.558743 -0.738756 -0.359394  -0.570244   
4  -0.472839 -0.415107 -0.454395 -0.520618 -0.384739 -0.383625  -0.501957   
5  -0.532688 -0.277665 -0.511906 -0.562558 -0.298189 -0.325769  -0.573537   
6  -0.170982 -0.353746 -0.578165 -0.286935 -0.343951 -0.450295  -0.504263   
7  -0.438168 -0.287942 -0.588527 -0.504996 -0.375554 -0.396918  -0.330081   
8  -0.473399 -0.534733 -0.510340 -0.320089 -0.548094 -0.439382  -0.616939   
9  -0.398902 -0.411445 -0.466532 -0.447931 -0.289697 -0.399963  -0.441418   
10 -0.356892 -0.456233 -0.420229 -0.477415 -0.445360 -0.338268  -0.285781   
11 -0.536684 -0.409223 -0.332835 -0.318258 -0.297488 -0.332387  -0.331720   
12 -0.349299 -0.390696 -0.406481 -0.336390 -0.486670 -0.469677  -0.611762   
13 -0.285356 -0.529118 -0.376597 -0.331736 -0.395260 -0.366916  -0.575066   
14 -0.562134 -0.561404 -0.525226 -0.511848 -0.410413 -0.281657  -0.419946   
15 -0.538523 -0.258649 -0.337363 -0.398689 -0.687625 -0.585551  -0.503656   
16 -0.488962 -0.431783 -0.452378 -0.408961 -0.408916 -0.553225  -0.373525   
17 -0.438950 -0.517200 -0.292525 -0.499462 -0.377991 -0.584248  -0.484422   
18 -0.576920 -0.573483 -0.433335 -0.493026 -0.345983 -0.506148  -0.474396   
19 -0.203514 -0.430645 -0.544312 -0.531258 -0.236533 -0.340231  -0.458714   
20 -0.548061 -0.487383 -0.398485 -0.526129 -0.354490 -0.468423  -0.547765   
21 -0.634154 -0.566601 -0.535883 -0.429888 -0.485310 -0.590173  -0.563000   
22 -0.501410 -0.372780 -0.450980 -0.576151 -0.481578 -0.370666  -0.548614   
23 -0.413793 -0.402384 -0.544427 -0.575440 -0.411655 -0.486429  -0.466887   
24 -0.567304 -0.380244 -0.559466 -0.482365 -0.363327 -0.534307  -0.522693   
25 -0.369809 -0.325326 -0.648980 -0.399780 -0.428714 -0.699517  -0.469914   
26 -0.309448 -0.339899 -0.624402 -0.390577 -0.461627 -0.697437  -0.452025   
27 -0.331981 -0.287849 -0.677494 -0.499637 -0.644135 -0.542492  -0.588035   
28 -0.339152 -0.353773 -0.593340 -0.474051 -0.271448 -0.455394  -0.385734   
29 -0.487604 -0.461595 -0.414938 -0.582674 -0.437107 -0.464428  -0.635535   
30 -0.358165 -0.246803 -0.437123 -0.617276 -0.619817 -0.600558  -0.472213   
31 -0.623084 -0.361975 -0.466914 -0.454583 -0.482491 -0.464998  -0.446698   
32 -0.621766 -0.208762 -0.410512 -0.530899 -0.294448 -0.446977  -0.401098   
33 -0.299183 -0.331392 -0.422269 -0.389914 -0.401896 -0.499631  -0.444316   
34 -0.523659 -0.450859 -0.534069 -0.468481 -0.566584 -0.619664  -0.455536   
35 -0.434214 -0.398048 -0.522785 -0.474942 -0.437883 -0.480568  -0.415798   
36 -0.441435 -0.365126 -0.524314 -0.483319 -0.397961 -0.528519  -0.414759   
37 -0.364999 -0.443676 -0.517416 -0.395258 -0.437947 -0.582461  -0.489247   
38 -0.512955 -0.471186 -0.276947 -0.532753 -0.539601 -0.664268  -0.453227   
39 -0.206698 -0.475233 -0.555277 -0.704535 -0.429632 -0.373526  -0.393599   
40 -0.128051 -0.402926 -0.512126 -0.361582 -0.366791 -0.639258  -0.708210   
41 -0.388882 -0.422958 -0.357478 -0.525269 -0.545265 -0.647068  -0.262360   
42 -0.472178 -0.404959 -0.368385 -0.629470 -0.508843 -0.571308  -0.420185   
43 -0.362435 -0.477922 -0.573618 -0.594285 -0.568463 -0.564081  -0.538868   
44 -0.511196 -0.586094 -0.448889 -0.617322 -0.337411 -0.459532  -0.521987   
45 -0.376574 -0.527302 -0.614316 -0.210258 -0.460221 -0.700966  -0.619339   
46 -0.290635 -0.517573 -0.557153 -0.544421 -0.559642 -0.675941  -0.359852   
47 -0.476332 -0.488036 -0.277650 -0.345582 -0.415722 -0.571330  -0.468219   
48 -0.833899 -0.273697 -0.347219 -0.572216 -0.488267 -0.483134  -0.273264   
49 -0.453553 -0.521807 -0.490475 -0.540078 -0.525765 -0.657328  -0.551878   
50 -0.493851 -0.540042 -0.502446 -0.424216 -0.685675 -0.484996  -0.353335   


In [6]:
scaler = StandardScaler()

In [7]:
x_train = df_month.iloc[:42, :10]
x_train = scaler.fit_transform(x_train)
x_train

array([[-3.17099578e-02, -1.75194017e-01, -1.86512617e-01,
        -1.15377724e+00, -2.05353481e-02,  6.40815709e-01,
        -3.94297824e-01, -1.25045248e+00,  4.74405830e-01,
         5.63241626e-03],
       [ 2.52305038e-01,  1.23629930e+00,  6.73428026e-01,
        -1.15377724e+00, -8.36113034e-01,  8.31518880e-01,
        -1.25454276e+00, -1.25045248e+00, -5.91062505e-01,
         5.63241626e-03],
       [-5.09125808e-01, -9.76447596e-01,  3.66619519e-01,
         5.99838078e-01,  4.52271179e-01,  1.68153960e+00,
        -2.17915796e+00, -6.14226315e-01, -1.23526066e+00,
         1.36220264e+00],
       [ 3.37929853e-01, -1.83768657e+00, -9.28201121e-01,
        -9.25208956e-01, -2.77930985e+00,  1.04878395e+00,
        -8.36280226e-01, -2.11762546e-01, -5.04466709e-01,
         1.00154462e+00],
       [-3.78748403e-01, -6.18037877e-02,  2.75646910e-01,
        -5.02269939e-01,  4.62636725e-01,  8.33304763e-01,
        -1.53505255e-01,  1.15290304e-01,  8.95594042e-01,
        -9.

In [8]:
y_train = df.iloc[:42]['june']
y_train

0     0.30
1    -0.33
2    -0.20
3     0.10
4    -0.22
5     0.12
6    -0.88
7     0.45
8     0.14
9    -0.12
10    0.19
11    0.26
12   -0.30
13   -0.78
14    0.66
15   -0.86
16   -0.70
17   -1.25
18    0.00
19    0.36
20   -0.45
21    0.04
22    0.37
23   -0.15
24    0.92
25    0.62
26   -0.90
27   -0.76
28   -0.08
29    1.24
30   -1.46
31   -0.64
32    0.00
33    0.65
34    0.53
35    0.64
36    0.27
37    0.08
38   -0.12
39    1.15
40   -0.39
41   -0.95
Name: june, dtype: float64

In [9]:
x_test = df_month.iloc[43:, :10]
x_test = scaler.fit_transform(x_test)
x_test

array([[ 5.10184248e-01,  3.09986329e-02, -8.15746105e-01,
        -1.08451198e+00, -6.50830451e-01,  8.16145287e-02,
        -8.42791769e-01, -6.61118619e-01, -9.48793526e-02,
        -9.50552309e-01],
       [-3.98034545e-01, -1.06693423e+00,  4.79669044e-01,
        -1.29823284e+00,  1.91073157e+00,  1.25368063e+00,
        -6.76286891e-01,  2.10671572e+00, -2.17428537e-01,
        -7.35199978e-01],
       [ 4.23860383e-01, -4.70201705e-01, -1.23842226e+00,
         2.47822928e+00,  5.49198539e-01, -1.45295006e+00,
        -1.63649391e+00, -3.72517530e-01,  6.26834415e-01,
         6.63152261e-01],
       [ 9.48541340e-01, -3.71452816e-01, -6.44741508e-01,
        -6.21908884e-01, -5.53038699e-01, -1.17239613e+00,
         9.22891966e-01,  2.02685169e+00, -2.49490979e+00,
         3.53059952e-01],
       [-1.85181192e-01, -7.16531511e-02,  2.25811782e+00,
         1.22278500e+00,  1.04253606e+00,  3.54816391e-04,
        -1.45961872e-01, -9.83615183e-01, -1.48785484e+00,
        -1.

In [10]:
y_test = df.iloc[43:]['june']
y_test

43   -0.11
44    0.68
45   -0.19
46    0.14
47    0.22
48    0.09
49   -0.16
50   -0.44
51    0.49
52   -0.62
53   -0.25
54    0.14
55   -0.33
56    0.48
57    1.28
58    0.06
Name: june, dtype: float64

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

# Assuming x_train and y_train are your training data
# Adjust this based on your actual data

# Define the parameter grid
param_grid = {
    'base_estimator__max_depth': range(1, 5),
    'n_estimators': range(1, 51)
}

# Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

# Create the GridSearchCV object
grid_search = GridSearchCV(bagging_reg, param_grid, cv=3, scoring='r2')

# Fit the grid search to the data
grid_search.fit(x_train, y_train)

# Get the best parameters and the corresponding score
best_params = grid_search.best_params_
best_score = grid_search.best_score_
best_max_depth = best_params['base_estimator__max_depth']
best_n_estimators = best_params['n_estimators']

print(f"Best Parameters: {best_params}")
print(f"Best Score: {best_score}")


Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 12}
Best Score: 0.1164171807123221


In [12]:
best_max_depth

3

In [13]:
best_n_estimators

12

In [14]:
def model_bag_reg(max_depth,n_estimators,x_test):
    regressor = BaggingRegressor(
          base_estimator=DecisionTreeRegressor(max_depth=max_depth),
          n_estimators=n_estimators,
          oob_score=True,
          random_state=0)
    regressor.fit(x_train,y_train)
    score = regressor.score(x_train,y_train)
    y_pred_br5 = regressor.predict(x_test)
    return score,y_pred_br5

In [15]:
score,pred_bag_reg_mean = model_bag_reg(best_max_depth,best_n_estimators,x_test)

In [16]:
pred_bag_reg_mean

array([-0.30443398,  0.49099367,  0.05154884, -0.00822858, -0.60868899,
       -0.01555594, -0.11222652, -0.50461195,  0.35837811,  0.0646192 ,
        0.08973653, -0.01430994, -0.19272229, -0.10962538,  0.27436864,
       -0.15941415])

In [17]:
corr_bag_reg_mean = np.corrcoef(pred_bag_reg_mean, y_test)
corr_bag_reg_mean

array([[1.        , 0.48609893],
       [0.48609893, 1.        ]])

# Random Forest

In [18]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

# Assuming x_train and y_train are your training data
# Adjust this based on your actual data

# Define the parameter grid
param_grid = {
    'n_estimators': range(1,51),  # Adjust as needed
    'max_depth': range(1,5),  # Adjust as needed

}

# Create the RandomForestRegressor
random_forest_reg = RandomForestRegressor(random_state=0)

# Create the GridSearchCV object
grid_search = GridSearchCV(random_forest_reg, param_grid, cv=3, scoring='r2')

# Fit the grid search to the data
grid_search.fit(x_train, y_train)

# Get the best parameters and the corresponding score
best_params = grid_search.best_params_
best_score = grid_search.best_score_

# Save the best values into separate variables
best_max_depth = best_params['max_depth']
best_n_estimators = best_params['n_estimators']

print(f"Best Parameters: {best_params}")
print(f"Best Score: {best_score}")
print(f"Best max_depth: {best_max_depth}")
print(f"Best n_estimators: {best_n_estimators}")


Best Parameters: {'max_depth': 2, 'n_estimators': 12}
Best Score: 0.08571838089905826
Best max_depth: 2
Best n_estimators: 12


In [19]:
def Randomforest(max_depth,n_estimators,x_test): 
    RF = RandomForestRegressor(
          n_estimators=n_estimators,
          max_depth=max_depth,
          
          random_state=0)
    RF.fit(x_train,y_train)
    score = RF.score(x_train,y_train)
    y_pred_rf = RF.predict(x_test)
    return score,y_pred_rf
    

In [20]:
score,pred_rf_mean = Randomforest(best_max_depth,best_n_estimators,x_test)

In [21]:
corr_rf_mean = np.corrcoef(pred_rf_mean, y_test)
corr_rf_mean

array([[1.        , 0.34853613],
       [0.34853613, 1.        ]])