In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("spearman_corr.csv")
df_month

May_13     April  February_2     March     May_9    May_17     May_4  \
0  -0.477951  0.057716   -0.230997  0.440512  0.148821 -0.618299  0.635403   
1  -0.181143 -0.064300   -0.254041  0.193319  0.127453 -0.379904  0.260732   
2  -0.143727 -0.012720   -0.183079  0.209067 -0.118703 -0.549860  0.486865   
3   0.021027 -0.023654   -0.171383  0.328165 -0.113571 -0.679115  0.462528   
4   0.114325  0.156914   -0.257033  0.491634 -0.327550 -0.423173  0.453230   
5  -0.314992 -0.056669   -0.345980  0.442050 -0.061617 -0.535356  0.552951   
6  -0.029512  0.123758   -0.332357  0.553380 -0.308104 -0.416714  0.324065   
7  -0.292144 -0.205982   -0.465901  0.458599 -0.109477 -0.669647  0.846530   
8  -0.283594  0.363870   -0.322331  0.415663 -0.218787 -0.532849  0.499065   
9  -0.233859  0.013008   -0.151193  0.715023  0.043251 -0.410779  0.133605   
10 -0.169542  0.049062   -0.315988  0.343028 -0.214002 -0.716885  0.496585   
11 -0.177337  0.028621   -0.350197  0.360663  0.252652 -0.441174  0.564174   
12 -0.229030 -0.001097   -0.386289  0.590871 -0.022577 -0.358311  0.669165   
13  0.333282  0.247520   -0.149867  0.845078 -0.131676 -0.180145  0.004033   
14 -0.038624 -0.182334   -0.385591  0.416796  0.060125 -0.160727  0.428670   
15  0.182996  0.142518   -0.219307  0.451189 -0.147670 -0.183191  0.101840   
16  0.429143  0.184316   -0.164736  0.623208 -0.152759 -0.310144  0.050566   
17  0.585932  0.038876   -0.184042  0.932861 -0.325534 -0.239934 -0.090178   
18  0.453580  0.170326   -0.104588  0.651660 -0.073389 -0.262028  0.072250   
19  0.152900 -0.177224   -0.426445  0.519323  0.035868 -0.712307  0.483944   
20  0.077736  0.009376   -0.119585  0.593276 -0.101167 -0.362419  0.275260   
21 -0.075145 -0.108381   -0.547643  0.438504  0.091610 -0.475389  0.533084   
22 -0.014531 -0.228710   -0.462815  0.558237  0.074344 -0.405252  0.448458   
23  0.036679 -0.050159   -0.292356  0.572799  0.052615 -0.535826  0.462476   
24 -0.149724 -0.007061   -0.378396  0.280437  0.102461 -0.633531  0.447416   
25 -0.052193 -0.147402   -0.173189  0.220687  0.613472 -0.254817  0.233701   
26  0.079446 -0.266740   -0.280430  0.877947 -0.032985 -0.359527  0.306228   
27  0.362441  0.121066   -0.435237  0.827795 -0.124771 -0.484984  0.048527   
28  0.147613  0.009528   -0.283901  0.809392 -0.108238 -0.495069  0.392785   
29 -0.092525 -0.086061   -0.207837  0.348982  0.179957 -0.550807  0.288400   
30  0.275484  0.042756   -0.451980  0.567002 -0.055750 -0.563222  0.494057   
31  0.239738  0.046741   -0.198569  0.744211 -0.081712 -0.609757  0.407987   
32 -0.091430 -0.134148   -0.550778  0.494980 -0.003959 -0.416249  0.340316   
33  0.063420  0.071208   -0.702053  0.512632 -0.095469 -0.336885  0.298584   
34 -0.324643  0.037685   -0.256422  0.252128  0.458060 -0.344971  0.314441   
35 -0.114563 -0.203239   -0.529662  0.318966  0.429063 -0.528488  0.554963   
36  0.013866  0.062957   -0.383235  0.620227  0.137003 -0.484958  0.366936   
37 -0.034123 -0.103263   -0.569137  0.490743  0.075415 -0.397330  0.574402   
38 -0.120117 -0.092147   -0.440068  0.867776  0.176958 -0.622303  0.517151   
39 -0.244597 -0.177324   -0.405733  0.261464  0.166508 -0.812720  0.518705   
40  0.383722  0.111250   -0.070879  0.672291  0.156651 -0.424512  0.045578   
41  0.576788  0.253402   -0.047603  0.798038 -0.369898 -0.356061  0.107309   
42  0.651952 -0.032803   -0.175420  0.589429 -0.107364 -0.511950  0.103359   
43  0.318207 -0.078340   -0.077071  0.597816  0.061802 -0.502073  0.256541   
44 -0.035711 -0.331121   -0.437085  0.487712  0.130844 -0.234723  0.268282   
45  0.161525 -0.201092   -0.372246  0.484073 -0.078200 -0.541065  0.539937   
46 -0.138218 -0.271034   -0.517195  0.299300  0.021562 -0.667191  0.481738   
47 -0.198203 -0.077306   -0.511950  0.099104  0.083833 -0.425154  0.627494   
48  0.007292 -0.394812   -0.353193  0.377903 -0.026542 -0.656631  0.630349   
49  0.230474 -0.135236   -0.335881  0.247409 -0.074047 -0.309368  0.353066   
50  0.340996 -0.222435   -0.

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :20]
x_train = scaler.fit_transform(x_train)
x_train

array([[-1.96480490e+00,  4.09955393e-01,  5.59276868e-01,
        -4.33502244e-01,  7.18566846e-01, -1.04453785e+00,
         1.32505447e+00, -1.35850911e+00,  7.38160395e-01,
        -1.23784085e-01, -3.12484823e-01, -7.70277625e-01,
         1.24816540e+00,  1.88763483e+00, -9.61793425e-02,
        -2.47446600e-01, -4.71470116e-01,  1.12392686e+00,
         9.99178326e-01, -1.06978466e+00],
       [-7.82648870e-01, -4.61701142e-01,  4.04041332e-01,
        -1.68053421e+00,  6.14007088e-01,  5.08799958e-01,
        -5.24423709e-01, -3.67511959e-01,  8.55150246e-01,
         1.11477325e+00, -3.12484823e-01, -5.90877366e-01,
        -1.31419927e-01,  1.88763483e+00,  1.93930037e-01,
        -2.47446600e-01, -1.56253165e+00,  1.12392686e+00,
         9.99178326e-01, -1.06978466e+00],
       [-6.33625774e-01, -9.32264379e-02,  8.82072175e-01,
        -1.60108881e+00, -5.90510858e-01, -5.98604023e-01,
         5.91827056e-01,  2.29364008e-01,  4.91637913e-01,
        -1.18553889e-01, -1.4

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] #df.iloc[43:]['avg']
    y_test.append(y_ts)

In [8]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [9]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

In [10]:
x_test = df_month.iloc[43:, :20]
x_test = scaler.fit_transform(x_test)
x_test

array([[ 1.582035  ,  1.09726233,  1.690083  ,  0.98081286, -0.21850404,
         0.02182078, -0.7094849 ,  0.71462206, -1.06915375, -1.19443032,
         1.78450242, -0.21589966, -0.82292009, -1.5850601 , -0.82969885,
        -0.14863847, -0.66326108, -2.30398876, -0.60124337,  0.7648754 ],
       [-0.56448653, -1.20906517, -0.68876217,  0.42810012,  0.19346489,
         2.02896413, -0.6401869 , -0.51042412, -0.30159056,  0.78739636,
        -1.12478854,  1.56404507,  0.84074477, -1.85263166, -0.16962846,
        -0.55424502,  0.41431229, -0.61019362, -0.82241683, -1.16850478],
       [ 0.63175548, -0.022708  , -0.26032412,  0.40983088, -1.05387972,
        -0.27091382,  0.96314181, -0.68249203, -0.5418067 ,  0.05936566,
         1.60355088,  0.75303592, -0.05152418, -1.93493726, -0.35508521,
        -1.35679154, -0.03850588, -0.322782  ,  1.27032401,  2.24305238],
       [-1.18619767, -0.66083635, -1.21809795, -0.51771747, -0.45860782,
        -1.21780921,  0.61964892, -0.34455975,  

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 3}
Best Score: 0.3477180776949316
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 28}
Best Score: 0.2565788148711165
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 46}
Best Score: 0.3387580257309199
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 49}
Best Score: 0.3167355080232339
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 36}
Best Score: 0.3189169039270938


In [13]:
y_pred_list

[array([-0.69716667,  0.29883333, -0.79383333,  0.44877778, -0.04508796,
         0.50409722, -0.64122222, -1.13940476, -0.11787963, -0.19503241,
        -0.58672222, -0.88783333, -0.38386574,  0.26977315,  0.26977315,
        -0.04508796]),
 array([-0.57949756,  0.02594667, -0.5909617 ,  0.40805217,  0.25010513,
        -0.07435235, -0.32334107, -0.85483031, -0.01905157, -0.18095454,
        -0.56186797, -0.65260749, -0.2058637 ,  0.16298129,  0.24017855,
         0.13148993]),
 array([-0.5569205 ,  0.4102352 , -0.28292429,  0.48359975,  0.02606409,
        -0.14280775, -0.51467765, -0.87408207, -0.00647538, -0.13008825,
        -0.35771091, -0.39936524, -0.4166576 ,  0.20045663,  0.26454569,
         0.03936496]),
 array([-0.60476339,  0.58850669, -0.37728674,  0.60734886,  0.07238128,
        -0.11088595, -0.38194106, -0.78249303,  0.04930902, -0.40524101,
        -0.10623309, -0.33416081, -0.50662266,  0.18479706,  0.40902438,
        -0.10882826]),
 array([-0.60884732,  0.48850893

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.4549716781723135,
 0.5926881049569281,
 0.46558642107525544,
 0.5783300456894679,
 0.627211038786631]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/SST/20 predictors/spearson/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'SST (2001-2016) 20p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/SST/20 predictors/spearson/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/SST/20 predictors/spearson/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'SST Predicted vs Actual 20p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/SST/20 predictors/spearson/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:
y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 3}
Best Score: 0.3477180776949316
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 28}
Best Score: 0.2565788148711165
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 46}
Best Score: 0.3387580257309199
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 49}
Best Score: 0.3167355080232339
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 36}
Best Score: 0.3189169039270938


In [21]:
y_pred_list_rf

[array([-0.69716667,  0.29883333, -0.79383333,  0.44877778, -0.04508796,
         0.50409722, -0.64122222, -1.13940476, -0.11787963, -0.19503241,
        -0.58672222, -0.88783333, -0.38386574,  0.26977315,  0.26977315,
        -0.04508796]),
 array([-0.57949756,  0.02594667, -0.5909617 ,  0.40805217,  0.25010513,
        -0.07435235, -0.32334107, -0.85483031, -0.01905157, -0.18095454,
        -0.56186797, -0.65260749, -0.2058637 ,  0.16298129,  0.24017855,
         0.13148993]),
 array([-0.5569205 ,  0.4102352 , -0.28292429,  0.48359975,  0.02606409,
        -0.14280775, -0.51467765, -0.87408207, -0.00647538, -0.13008825,
        -0.35771091, -0.39936524, -0.4166576 ,  0.20045663,  0.26454569,
         0.03936496]),
 array([-0.60476339,  0.58850669, -0.37728674,  0.60734886,  0.07238128,
        -0.11088595, -0.38194106, -0.78249303,  0.04930902, -0.40524101,
        -0.10623309, -0.33416081, -0.50662266,  0.18479706,  0.40902438,
        -0.10882826]),
 array([-0.60884732,  0.48850893

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.4549716781723135,
 0.5926881049569281,
 0.46558642107525544,
 0.5783300456894679,
 0.627211038786631]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/SST/20 predictors/spearson/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'SST (2001-2016) 20p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/SST/20 predictors/spearson/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/SST/20 predictors/spearson/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'SST Predicted vs Actual 20p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/SST/20 predictors/spearson/comparison plots/randomforest
