In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("pearson_corr.csv")
df_month

March_4     May_6  April_11  November_3       May     May_5     May_9  \
0  -0.793000  0.426002 -0.050333    0.827789 -0.221579  0.801848 -0.233783   
1   0.095511  0.343893 -0.203332    0.827789  0.086009  0.247275  0.085172   
2   0.481454  0.197382 -0.147272    0.192062  0.073576 -0.153567 -0.037057   
3  -0.478691 -0.069665 -0.409264    0.484618 -0.365990 -0.274169 -0.227975   
4  -0.566542 -0.835852 -0.523008    0.434227 -0.090789  0.327031 -0.348377   
5   0.000645 -0.070522 -0.524921   -0.226640 -0.207692 -0.153949 -0.054448   
6  -0.718722 -0.573413 -0.221674    0.448013 -0.337707 -0.000117  0.106052   
7   0.061034  0.461886 -0.464792    0.431479 -0.424500  0.555998 -0.111373   
8  -1.047455  0.548707 -0.331353    0.661389 -0.421281 -0.477346  0.277176   
9  -0.421432 -0.522139 -0.194850    0.235838 -0.590899  0.547277 -0.006919   
10 -1.179475  0.147972 -0.460464    0.224968 -0.199827 -0.285755  0.049940   
11 -0.858123  0.447703 -0.124631    1.120995 -0.235965  0.608844 -0.502499   
12 -0.913978 -0.126166 -0.154358    0.219366 -0.215992  0.273278  0.008241   
13 -0.834468 -0.078589 -0.291788    0.541565 -0.216597 -0.304380 -0.139703   
14 -0.772143  0.200709 -0.314299    0.264699 -0.432619  0.815331 -0.671877   
15 -0.273288  0.359966  0.115985    0.900897 -0.181004 -0.161642 -0.121169   
16 -0.625430 -0.485582 -0.277699    0.379595  0.182264 -0.242848  0.140323   
17 -0.880096 -0.098261 -0.175685    0.586143  0.169521 -0.058862 -0.032189   
18 -0.765371  0.033565 -0.274249    0.563617 -0.314857 -0.389282 -0.405184   
19 -0.796571  0.759252 -0.518086   -0.052203 -0.055768 -0.313382 -0.311870   
20 -0.532996  0.140413 -0.243194    0.452011 -0.119702  0.143059  0.042738   
21 -0.295079  0.153274 -0.220504    0.334612 -0.281972  0.552573 -0.256178   
22  0.099249  0.216580  0.029581    0.548504 -0.283385  0.301016 -0.481385   
23 -1.572387 -0.012037 -0.406453    0.424697 -0.337215 -0.034955 -0.213966   
24 -0.008535 -0.000847 -0.193465    0.135475 -0.389013  0.291495 -0.279562   
25 -0.683996  0.600718  0.145853    0.544852 -0.515706  0.988951 -0.247540   
26 -0.813408  0.361158 -0.192592    0.892909 -0.162558  0.180052  0.046737   
27 -0.816342 -0.469536 -0.413583    0.813336 -0.289757  0.351103 -0.274469   
28 -0.091332  0.169024 -0.407058    0.500395 -0.413116  0.570842 -0.206386   
29  0.000846  0.776547 -0.310801    0.419865 -0.465625  0.725884 -0.132167   
30 -0.329608 -0.194545 -0.140691    0.674656  0.025310  0.431319 -0.228336   
31 -0.139179 -0.471821 -0.080026    0.418590  0.063888  0.064477 -0.042594   
32  0.057409  0.262121 -0.027045    1.016309  0.117779  0.387319 -0.258528   
33 -0.335463  0.296479 -0.220971    1.041260 -0.056060  0.210045 -0.256317   
34 -0.054790  0.961588 -0.258701    0.529207  0.042120  0.681015 -0.019072   
35  0.286750  0.547697 -0.421496    0.400338 -0.137591  0.242431 -0.145578   
36  0.147011  0.308813 -0.238806    0.593754  0.057853  0.111536 -0.145241   
37 -0.220325 -0.162653 -0.294225    0.875497 -0.181643  0.258418 -0.312764   
38 -0.130870 -0.295998 -0.373260    0.361816 -0.113297  0.123003 -0.184657   
39  0.545492  0.408300 -0.930316   -0.093573 -0.076026  0.841793 -0.273992   
40 -0.537881  0.205959 -0.085119    1.110276 -0.144999 -0.220876 -0.200009   
41 -1.400027 -0.747444 -0.295125    0.677305  0.004242  0.011779 -0.096224   
42 -1.685221 -0.261200 -0.292530    0.714004 -0.103695  0.065364  0.279154   
43 -0.535878  0.075356 -0.310582    0.281642 -0.088091  0.323224  0.051807   
44 -0.086903  0.174079 -0.825710    0.031610  0.015843  0.937425 -0.055557   
45 -0.274778 -0.037975 -0.262568    0.363339 -0.128683  0.614820  0.181674   
46  0.400925 -0.390822 -0.759544    0.683805 -0.248737  0.570350 -0.220443   
47 -0.447715  0.677045 -0.178468    0.586652  0.060841  0.782559  0.074643   
48 -0.661937 -0.148528 -0.032603    0.400467 -0.499063 -0.184392 -0.238054   
49 -0.362886 -0.394659 -0.435647    0.284612 -0.164699  0.298834 -0.067578   
50 -0.937561 -0.063721 -0.3

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :10]
x_train = scaler.fit_transform(x_train)
x_train

array([[-0.75116825,  0.80039226,  1.12945149,  1.00704222, -0.20319432,
         1.59603701, -0.40625923, -0.66419445,  0.46880027,  1.40275185],
       [ 1.09370115,  0.59996274,  0.32393115,  1.00704222,  1.38949412,
         0.11518234,  1.34037948, -0.66419445,  0.54024276, -0.56412998],
       [ 1.89505934,  0.24232587,  0.61907971, -1.05673058,  1.32511327,
        -0.95516961,  0.67103468,  0.01942194,  0.27784207,  0.30363173],
       [-0.09854887, -0.40954537, -0.76027468, -0.10700086, -0.95094927,
        -1.27720874, -0.3744554 , -0.37320494, -0.25693098,  0.50986788],
       [-0.28095893, -2.2798273 , -1.35912341, -0.27058621,  0.47403377,
         0.3281512 , -1.03379364, -1.04733587, -0.99822821,  1.22242219],
       [ 0.8967256 , -0.41163567, -1.3691961 , -2.41596761, -0.13128663,
        -0.95618812,  0.57580227, -1.1578346 , -0.19641182,  0.23782169],
       [-0.59693911, -1.63920739,  0.22735971, -0.2258312 , -0.80450104,
        -0.54541906,  1.45471994, -0.49885641

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [8]:
x_test = df_month.iloc[43:, :10]
x_test = scaler.fit_transform(x_test)
x_test

array([[-0.24989243,  0.55246073,  0.30741913, -0.21366782,  0.7126796 ,
        -0.08432956,  0.81921274, -0.23063938, -0.01423719, -0.41539967],
       [ 0.50769256,  0.91023503, -2.01935477, -1.30719891,  1.23335789,
         1.95867654,  0.25249336,  0.53150929, -0.99370166, -0.30350288],
       [ 0.19067855,  0.14174452,  0.52429441,  0.14363979,  0.50933051,
         0.88560001,  1.50471242,  0.49624286, -0.67549985,  0.48560543],
       [ 1.33083881, -1.1369821 , -1.72048995,  1.54521584, -0.09209925,
         0.73768237, -0.61785256,  1.42786149,  0.41929119, -1.49293413],
       [-0.10112993,  2.73299469,  0.90416377,  1.12031226,  1.45878224,
         1.44354873,  0.93975459, -1.58506623,  1.03633024,  0.39903561],
       [-0.46260105, -0.25890067,  1.56302157,  0.30601799, -1.34615261,
        -1.77280601, -0.71081119,  0.83479   ,  1.11433721,  1.03588076],
       [ 0.04200772, -1.15088632, -0.25748337, -0.20067838,  0.32889893,
        -0.16545754,  0.18904069, -0.13077236

In [9]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] 
    y_test.append(y_ts)

In [10]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 50}
Best Score: 0.32329226306909653
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 9}
Best Score: 0.15051977618301743
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 50}
Best Score: 0.28039323993613513
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 50}
Best Score: 0.38125204765101517
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 49}
Best Score: 0.33888066875735134


In [13]:
y_pred_list

[array([ 0.03143903,  0.5877048 ,  0.11663189, -0.52452985, -0.0450598 ,
         0.02743456, -0.33273674, -0.07606549,  0.24462364, -0.80574163,
        -0.67666491,  0.14646251, -0.33393083,  0.31799606,  0.32752874,
         0.0010444 ]),
 array([-0.01037022,  0.18377793,  0.09162052, -0.23797091, -0.11402454,
         0.10466682, -0.24857894,  0.00267608,  0.09405879, -0.45499252,
        -0.43506827,  0.09162052, -0.24857894,  0.19604954,  0.20498781,
         0.00267608]),
 array([-0.16165701,  0.61238128, -0.0367169 , -0.21912173, -0.21113659,
        -0.38737724, -0.15302634, -0.34916273,  0.33478115, -0.92068137,
        -0.67169343,  0.08449148, -0.26035092,  0.17846544,  0.28334105,
        -0.16712616]),
 array([-0.09570788,  0.77224175,  0.00403351, -0.32678517, -0.04986874,
        -0.11294745, -0.34254433, -0.13046779,  0.4125643 , -0.92539569,
        -0.70048264,  0.0041845 , -0.23313227,  0.33200561,  0.40307851,
        -0.01736282]),
 array([-0.26188611,  0.80045013

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.7150125095725212,
 0.6893169425258283,
 0.7615574216035631,
 0.7393998782411498,
 0.7352424320461352]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+vwind/10 predictors/pearson/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'slp+vwind (2001-2016) 10p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'10p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+vwind/10 predictors/pearson/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+vwind/10 predictors/pearson/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'slp+vwind Predicted vs Actual 10p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'10p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+vwind/10 predictors/pearson/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:

y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 50}
Best Score: 0.32329226306909653
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 9}
Best Score: 0.15051977618301743
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 50}
Best Score: 0.28039323993613513
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 50}
Best Score: 0.38125204765101517
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 49}
Best Score: 0.33888066875735134


In [21]:
y_pred_list_rf

[array([ 0.03143903,  0.5877048 ,  0.11663189, -0.52452985, -0.0450598 ,
         0.02743456, -0.33273674, -0.07606549,  0.24462364, -0.80574163,
        -0.67666491,  0.14646251, -0.33393083,  0.31799606,  0.32752874,
         0.0010444 ]),
 array([-0.01037022,  0.18377793,  0.09162052, -0.23797091, -0.11402454,
         0.10466682, -0.24857894,  0.00267608,  0.09405879, -0.45499252,
        -0.43506827,  0.09162052, -0.24857894,  0.19604954,  0.20498781,
         0.00267608]),
 array([-0.16165701,  0.61238128, -0.0367169 , -0.21912173, -0.21113659,
        -0.38737724, -0.15302634, -0.34916273,  0.33478115, -0.92068137,
        -0.67169343,  0.08449148, -0.26035092,  0.17846544,  0.28334105,
        -0.16712616]),
 array([-0.09570788,  0.77224175,  0.00403351, -0.32678517, -0.04986874,
        -0.11294745, -0.34254433, -0.13046779,  0.4125643 , -0.92539569,
        -0.70048264,  0.0041845 , -0.23313227,  0.33200561,  0.40307851,
        -0.01736282]),
 array([-0.26188611,  0.80045013

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.7150125095725212,
 0.6893169425258283,
 0.7615574216035631,
 0.7393998782411498,
 0.7352424320461352]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+vwind/10 predictors/pearson/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'slp+vwind (2001-2016) 10p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'10_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+vwind/10 predictors/pearson/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+vwind/10 predictors/pearson/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'slp+vwind Predicted vs Actual 10p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'10p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+vwind/10 predictors/pearson/comparison plots/randomforest
