In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("mutual_corr.csv")
df_month

December_3  October_3  November_4  November_7    June_2  December_5  \
0     0.466045   0.144323   -0.414703    0.364390 -0.611637   -0.650081   
1     0.466045   0.144323   -0.414703    0.364390 -0.611637   -0.650081   
2     1.166221   0.456636    0.119779    0.517490 -0.618212    0.081409   
3     0.612788  -0.005480   -0.082401    0.116880 -0.756471   -0.526777   
4     0.584224  -0.036910   -1.015143    0.087180 -0.210719   -0.134372   
5     0.325333   0.018889   -0.818627    0.124234 -0.465539   -0.495115   
6     0.357780   0.334644   -1.069754    0.361295 -0.272340   -0.430412   
7     0.469664   0.353365   -0.768627    0.180017  0.373169   -0.792502   
8     0.756367   0.432310   -0.137888    0.036015 -0.626006   -0.325316   
9     0.592602   0.153622   -0.548753    0.263931 -0.777676   -0.410373   
10    0.148358   0.219812   -0.530598    0.208909 -0.066435   -0.470229   
11    0.336506  -0.171151   -0.857654   -0.327675  0.243320   -0.220577   
12    0.534511   0.272290   -0.811415    0.339928 -0.216475   -0.586695   
13    0.548967  -0.066081   -1.169312    0.220242  0.200812   -0.436441   
14    0.495222   0.299316   -0.400256    0.162571 -0.559447   -0.636674   
15    0.430279   0.339003   -1.089294    0.326688 -0.234420   -0.356303   
16    0.302122   0.017382   -1.062109    0.198819 -0.329345   -0.379323   
17    0.774975   0.300505   -1.445140   -0.005306 -0.530399   -0.769170   
18    0.631056   0.402861   -0.438656    0.150972 -0.128896   -0.298491   
19    0.948232   0.402663   -0.700344    0.672940 -0.256355   -0.455413   
20    0.310469   0.084060   -0.036264   -0.093933 -0.943343   -0.553355   
21    0.493978   0.250269    0.033722    0.030337 -0.315552   -0.382677   
22    0.458726   0.210159   -0.364840    0.441789 -0.028006   -0.692744   
23    0.467053   0.259504   -0.772920    0.104973 -0.790152   -0.682620   
24    0.676752  -0.307894   -0.658674    0.261859 -0.268523    0.037035   
25    0.400709   0.299934   -0.318289    0.476649 -0.754733   -0.661251   
26    0.248256   0.532377   -0.392938   -0.142940 -0.400006   -0.632273   
27    0.988826   0.409156   -0.763604   -0.213495 -0.448028   -0.862679   
28    0.566211   0.590243    0.254993    0.160256 -0.052039   -0.597909   
29    0.530183   0.477734    0.502166    0.302431 -0.390674   -0.580341   
30    0.556720   0.244745   -0.202859    0.254811 -0.191288   -0.785340   
31    0.393760   0.431675   -1.104039   -0.394843  0.421101   -0.361818   
32    0.599657   0.553296    0.043108    0.059915 -0.669827   -0.243084   
33    0.361948   0.045684   -0.015937   -0.092649 -0.464981   -0.532853   
34    0.461284   0.181107   -0.036404    0.239269  0.179654   -0.354007   
35    0.661933  -0.119243    0.164452    0.222469 -0.499880   -0.873604   
36    0.588474   0.244774    0.132246   -0.384063 -0.358223   -0.551353   
37    0.627196   0.031897   -1.059555   -0.359021  0.033728   -0.526078   
38    0.617675   0.086768   -0.496676    0.085878 -0.802586   -0.470367   
39    0.543424   0.449282    0.037235    0.194952 -0.145576   -0.270413   
40    0.621858   0.168095   -1.671818    0.232450 -1.111576   -0.494065   
41    0.465809   0.711065   -1.154535   -0.085968 -0.004549   -0.741065   
42    0.345719   0.444709   -0.586629    0.012992 -0.298738   -0.642618   
43    0.600395   0.576229   -1.054226    0.757104 -0.516827   -0.578317   
44    0.772157   0.411211   -0.426612    0.042300  0.086073   -0.747994   
45    0.281540   0.210264    0.101509   -0.223254  0.166459   -0.702577   
46    0.773322  -0.120768   -0.221160    0.080664 -0.182174   -0.516949   
47    0.436629   0.157808   -0.410010    0.415977 -0.022389   -0.668491   
48    0.648205   0.325207   -0.526568   -0.012437 -0.471267   -0.568326   
49    0.312015   0.008053   -0.523534   -0.045643 -0.496678   -0.618856   
50    0.021480   0.370888   -0.619278    0.350249  0.235533   -0.656292   
51   -0.036592   0.234960   -0.749957    0.169452 -0.540314   -0.505381   
52    0.321657   0.241682   -

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :5]
x_train = scaler.fit_transform(x_train)
x_train

array([[-0.37504551, -0.41664681,  0.19620698,  0.95591253, -0.76348576],
       [-0.37504551, -0.41664681,  0.19620698,  0.95591253, -0.76348576],
       [ 3.28386082,  1.02710229,  1.26539456,  1.59358516, -0.78226197],
       [ 0.39178935, -1.10915421,  0.8609503 , -0.07497828, -1.17708796],
       [ 0.24252472, -1.25444558, -1.00492358, -0.19867984,  0.38140891],
       [-1.11036098, -0.9965017 , -0.61180816, -0.04434993, -0.34627768],
       [-0.94080396,  0.46316382, -1.11416709,  0.94302163,  0.20543984],
       [-0.35613037,  0.54970503, -0.51178793,  0.18799111,  2.04880859],
       [ 1.14208991,  0.91464951,  0.74995229, -0.41178655, -0.8045197 ],
       [ 0.28630181, -0.37366296, -0.07194775,  0.53749699, -1.23764153],
       [-2.03517862, -0.06768189, -0.03563013,  0.30832666,  0.79343927],
       [-1.05197218, -1.87501231, -0.68987829, -1.9265742 ,  1.67800039],
       [-0.01726357,  0.17491255, -0.59738167,  0.8540291 ,  0.3649725 ],
       [ 0.05828297, -1.38929931, -1.3

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [8]:
x_test = df_month.iloc[43:, :5]
x_test = scaler.fit_transform(x_test)
x_test

array([[ 0.82694221,  1.38461552, -1.47227458,  2.55205636, -0.79287118],
       [ 1.55440972,  0.67895349,  0.39980905, -0.50481483,  1.23030729],
       [-0.52350409, -0.18034713,  1.97512047, -1.64046151,  1.50006256],
       [ 1.55934231, -1.59592159,  1.01264568, -0.34075281,  0.33013834],
       [ 0.13334672, -0.40466086,  0.44933151,  1.09321903,  0.86633575],
       [ 1.02943193,  0.31118134,  0.10165494, -0.73889987, -0.63998587],
       [-0.394431  , -1.04505081,  0.11070617, -0.88090679, -0.72525634],
       [-1.62493845,  0.50652437, -0.17488627,  0.81213156,  1.73185684],
       [-1.87089041, -0.07473839, -0.56468268,  0.03895085, -0.87168823],
       [-0.35359559, -0.0459948 , -1.24796977,  0.9823247 ,  0.51199359],
       [-0.28448462, -0.72881323, -0.76475183, -0.99228218, -1.17391672],
       [ 1.1932435 , -1.59594805, -1.56275797, -0.55300252, -1.38869649],
       [-0.75719582,  0.6749163 , -0.02374783, -0.69446646, -1.44783266],
       [-0.28063224, -0.54153595,  1.1

In [9]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] 
    y_test.append(y_ts)

In [10]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 47}
Best Score: 0.06771709297809286
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 19}
Best Score: -0.022545214226519894
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 49}
Best Score: 0.01121608617976183
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 50}
Best Score: 0.08353241068108308
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 21}
Best Score: 0.10320478079756534


In [13]:
y_pred_list

[array([-0.81942199,  0.03885512,  0.82682484,  0.35841687, -0.16788922,
         0.11359524, -0.01911278,  0.1629331 , -0.09372195, -0.78978617,
        -0.19401995, -0.8897748 , -0.01562807,  0.66556595,  0.6257531 ,
        -0.09340793]),
 array([-0.63490025,  0.02176608,  0.20110165,  0.13344237,  0.02176608,
         0.05732999,  0.05732999,  0.02176608, -0.08445572, -0.67046416,
        -0.08445572, -0.63490025,  0.05732999,  0.13344237,  0.16900628,
        -0.08445572]),
 array([-0.79282888,  0.03323162,  0.73904063,  0.11446999, -0.04078584,
        -0.00722067,  0.00936058,  0.10624959, -0.11357482, -0.75138241,
        -0.18009567, -0.93127834,  0.03804409,  0.39510478,  0.38611927,
        -0.07612626]),
 array([-0.87964381, -0.06388599,  0.76849627,  0.18689894, -0.39093197,
         0.03414094, -0.02679882, -0.00632645, -0.10465758, -0.89350992,
        -0.17083597, -0.74836667, -0.06599449,  0.51277784,  0.6483297 ,
         0.00282461]),
 array([-0.66197161,  0.17410192

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.4467323093823497,
 0.35701881521457257,
 0.3205723139614535,
 0.444724882630732,
 0.5065569954693439]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+vwind/5 predictors/kendall/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'slp+vwind (2001-2016) 5p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+vwind/5 predictors/kendall/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+vwind/5 predictors/kendall/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'slp+vwind Predicted vs Actual 5p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+vwind/5 predictors/kendall/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:

y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 47}
Best Score: 0.06771709297809286
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 19}
Best Score: -0.022545214226519894
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 49}
Best Score: 0.01121608617976183
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 50}
Best Score: 0.08353241068108308
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 21}
Best Score: 0.10320478079756534


In [21]:
y_pred_list_rf

[array([-0.81942199,  0.03885512,  0.82682484,  0.35841687, -0.16788922,
         0.11359524, -0.01911278,  0.1629331 , -0.09372195, -0.78978617,
        -0.19401995, -0.8897748 , -0.01562807,  0.66556595,  0.6257531 ,
        -0.09340793]),
 array([-0.63490025,  0.02176608,  0.20110165,  0.13344237,  0.02176608,
         0.05732999,  0.05732999,  0.02176608, -0.08445572, -0.67046416,
        -0.08445572, -0.63490025,  0.05732999,  0.13344237,  0.16900628,
        -0.08445572]),
 array([-0.79282888,  0.03323162,  0.73904063,  0.11446999, -0.04078584,
        -0.00722067,  0.00936058,  0.10624959, -0.11357482, -0.75138241,
        -0.18009567, -0.93127834,  0.03804409,  0.39510478,  0.38611927,
        -0.07612626]),
 array([-0.87964381, -0.06388599,  0.76849627,  0.18689894, -0.39093197,
         0.03414094, -0.02679882, -0.00632645, -0.10465758, -0.89350992,
        -0.17083597, -0.74836667, -0.06599449,  0.51277784,  0.6483297 ,
         0.00282461]),
 array([-0.66197161,  0.17410192

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.4467323093823497,
 0.35701881521457257,
 0.3205723139614535,
 0.444724882630732,
 0.5065569954693439]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+vwind/5 predictors/kendall/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'slp+vwind (2001-2016) 5p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+vwind/5 predictors/kendall/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+vwind/5 predictors/kendall/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'slp+vwind Predicted vs Actual 5p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'5p{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/slp+vwind/5 predictors/kendall/comparison plots/randomforest
