In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("kendall_corr.csv")
df_month

June_7   April_2   April_5     May_5    June_5  November_7    June_3  \
0  -0.202334  0.098415 -0.308200  0.031694 -0.039586   -0.097144 -0.073610   
1  -0.202334 -0.218954 -0.398356  0.413521 -0.039586   -0.097144 -0.073610   
2  -0.168031  0.134482 -0.120259  0.100128 -0.172917    0.441251  0.070093   
3  -0.113727  0.402854  0.106618 -0.065683  0.116948    0.698383 -0.177760   
4  -0.134278  0.002166 -0.136666  0.288075 -0.012212    0.154697  0.112119   
5   0.424991  0.367763 -0.157606  0.341029 -0.661289    0.426955 -0.225224   
6  -0.326554  0.144775 -0.071493  0.327735  0.129275   -0.346314 -0.120880   
7   0.254591  0.094534 -0.386781 -0.050703 -0.380720   -0.562384  0.093717   
8  -0.007211  0.546273 -0.190408  0.223293  0.106507    0.041883 -0.085340   
9   0.125501  0.332107 -0.531581  0.234343  0.214527   -0.095537  0.032189   
10 -0.085683  0.315580  0.271267  0.080238  0.039885    0.485622  0.106157   
11  0.020925 -0.271794 -0.013839 -0.407319 -0.734238   -0.277007  0.189162   
12 -0.201758  0.253371 -0.128148  0.151871  0.275637   -0.008238  0.195733   
13 -0.516032  0.340489  0.391056  0.000441  0.471238   -0.205065 -0.085667   
14 -0.282497 -0.453311 -0.261872 -0.115250  0.017295    0.575208 -0.130879   
15 -0.254071  0.217361  0.231070  0.233386  0.680252   -0.786756  0.291542   
16 -0.170372  0.084304  0.375863  0.563068  0.524977   -0.211309 -0.253101   
17 -0.113023  0.401700 -0.102335  0.076873 -0.466109   -0.235518 -0.012360   
18 -0.110717  0.067185  0.020189  0.164362  0.701026    0.061165  0.070428   
19 -0.055139 -0.149563 -0.039133  0.060371 -0.145463    0.565812 -0.031327   
20 -0.365528  0.349169  0.170313  0.200399  0.001710   -0.200844 -0.035240   
21 -0.055638  0.225569 -0.147821  0.240480  0.379086   -0.065746  0.120100   
22  0.227158 -0.179929 -0.154677  0.353267  0.589681   -0.344781  0.262425   
23 -0.459366 -0.222316  0.118091 -0.059688  0.695847   -0.322996  0.165390   
24  0.105290  0.124218  0.095204 -0.055237  0.087063    0.461537 -0.025640   
25 -0.741868 -0.131234 -0.179034  0.002980  0.187050   -1.007616 -0.098018   
26 -0.088160  0.267340  0.496284  0.208624  0.294124   -0.595122  0.176676   
27 -0.348464 -0.306263  0.087376  0.117035  0.535074   -0.519583  0.191561   
28 -0.385063 -0.150374 -0.695444  0.164876  0.201855   -0.246441 -0.191529   
29 -0.012315 -0.296755 -0.119652  0.014774 -0.178675    0.396827 -0.200966   
30 -0.130641  0.462671  0.189351  0.352510  0.681826   -0.254151 -0.057286   
31 -0.110637 -0.363447  0.007379  0.182716  0.508675   -0.531136  0.050151   
32  0.004365 -0.531508 -0.765086 -0.452751  0.208952   -0.602787 -0.080204   
33 -0.130789 -0.485188 -0.382976  0.158288  0.070308   -0.044094 -0.160681   
34  0.264870 -0.127283 -0.561813  0.001424  0.339194   -0.056958  0.002369   
35 -0.458174 -0.325291 -0.260957 -0.111226  0.335919   -0.183179 -0.165922   
36  0.243992 -0.165157 -0.209163  0.175147 -0.080452   -0.319330 -0.048301   
37 -0.162667  0.258153 -0.094115 -0.259247  0.018785   -0.544089 -0.020757   
38  0.175258 -0.019899  0.120492  0.140741  0.066820   -0.595285  0.080332   
39  0.182851 -0.371199 -0.534351 -0.033873  0.112750    0.351064 -0.220780   
40 -0.315403 -0.213732  0.267592  0.371753  0.125994   -0.963634 -0.043613   
41  0.016906  0.363083  0.366201  0.311461  0.737327   -0.434175  0.011618   
42 -0.097022 -0.276413  0.258543  0.107044  0.038978   -0.601149  0.214762   
43 -0.133805 -0.343296 -0.100606  0.245407 -0.050294   -0.654000 -0.062463   
44  0.301628 -0.600625 -0.165968  0.018992  0.047351    0.185889  0.055107   
45 -0.224710 -0.374762 -0.032706  0.020105  0.560551   -0.512148 -0.125453   
46  0.203601 -0.036025  0.184118  0.241169  0.005094   -0.680414 -0.135913   
47 -0.369446  0.059150 -0.186318  0.314196 -0.018546   -0.419732 -0.087586   
48  0.102952  0.271504 -0.005948 -0.226960  0.656495   -0.479980  0.002663   
49 -0.170943  0.390947 -0.223429 -0.197552  0.304873   -0.616503  0.071326   
50 -0.116007  0.166191  0.26

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :5]
x_train = scaler.fit_transform(x_train)
x_train

array([[-3.88418762e-01,  2.67065412e-01, -7.57721103e-01,
        -3.88512138e-01, -5.64192617e-01],
       [-3.88418762e-01, -8.23887258e-01, -1.06600190e+00,
         1.47422655e+00, -5.64192617e-01],
       [-2.42543001e-01,  3.91045161e-01, -1.15076444e-01,
        -5.46577685e-02, -9.49160023e-01],
       [-1.16183757e-02,  1.31357284e+00,  6.60707012e-01,
        -8.63564367e-01, -1.12230114e-01],
       [-9.90103033e-02, -6.37895011e-02, -1.71178913e-01,
         8.62238421e-01, -4.85154933e-01],
       [ 2.27925847e+00,  1.19294576e+00, -2.42779507e-01,
         1.12057761e+00, -2.35924231e+00],
       [-9.16655534e-01,  4.26428962e-01,  5.16732770e-02,
         1.05572372e+00, -7.66372178e-02],
       [ 1.55463903e+00,  2.53723684e-01, -1.02642176e+00,
        -7.90485324e-01, -1.54915248e+00],
       [ 4.41336967e-01,  1.80657172e+00, -3.54943558e-01,
         5.46202348e-01, -1.42376138e-01],
       [ 1.00568709e+00,  1.07037937e+00, -1.52155466e+00,
         6.00107921e-01

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [8]:
x_test = df_month.iloc[43:, :5]
x_test = scaler.fit_transform(x_test)
x_test

array([[-0.3533441 , -0.76058626,  0.027509  ,  0.97200241, -1.27583361],
       [ 2.02601946, -1.63909757, -0.30373548, -0.26768388, -0.84670646],
       [-0.85008589, -0.86800887,  0.37161831, -0.26159471,  1.40867817],
       [ 1.4903623 ,  0.2884215 ,  1.47045351,  0.94879558, -1.03241944],
       [-1.64097501,  0.61334562, -0.40686495,  1.34863923, -1.13630909],
       [ 0.9403823 ,  1.33831222,  0.50722272, -1.61434388,  1.83032761],
       [-0.55628001,  1.74608567, -0.59493842, -1.45332636,  0.28503552],
       [-0.25609175,  0.9787784 ,  1.88736178, -0.53926646, -0.40887869],
       [ 0.81659718, -0.91970639, -1.01849931, -0.62848133, -0.66409624],
       [-1.29784947,  1.51059546, -0.02896001,  1.04337875,  1.95328605],
       [-0.77920433,  0.24224767,  1.18260223, -0.43806105,  0.08052723],
       [ 1.20828374, -0.78904611, -0.64559051, -0.94617045,  0.30906142],
       [ 0.11238627, -0.16370354, -0.63550034,  0.32535338,  0.52509434],
       [-0.30607408, -1.35558191, -0.2

In [9]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] 
    y_test.append(y_ts)

In [10]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 42}
Best Score: 0.35802974152894734
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 33}
Best Score: 0.28864783471016797
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 19}
Best Score: 0.36467681795736484
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 42}
Best Score: 0.378813287299869
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 29}
Best Score: 0.36234423964824103


In [13]:
y_pred_list

[array([-0.36603124,  0.68789884, -0.15109558, -0.03930901, -0.16087336,
        -0.26370767, -0.21229045, -0.21400823,  0.64982868, -0.87069048,
        -0.23782803,  0.28205173,  0.01522868,  0.40516754,  0.05369794,
        -0.24290238]),
 array([-0.37502073,  0.66604305, -0.00774205, -0.24949711, -0.18173593,
        -0.13953357,  0.06996423, -0.00744444,  0.54836242, -0.87286526,
        -0.02030952,  0.48068151,  0.04808205,  0.56445575, -0.04918504,
        -0.1941301 ]),
 array([-0.21521679,  0.86974524, -0.26174964, -0.0771934 ,  0.23531662,
        -0.29810192,  0.02687093, -0.19234958,  0.45995576, -0.89800752,
        -0.25416454,  0.24503722,  0.05026373,  0.36259027,  0.07027569,
        -0.13874979]),
 array([-0.27970547,  0.75910693, -0.17031849,  0.20950794, -0.15255288,
        -0.49392441, -0.31382217, -0.23364459,  0.74045972, -0.96679167,
        -0.24256645,  0.12551075,  0.02268505,  0.46601829,  0.18402373,
        -0.25926485]),
 array([-0.06396389,  0.51750034

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.6670555575149004,
 0.511187589707271,
 0.5730844300934532,
 0.662910952239835,
 0.7578548678277821]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/uwind+vwind/5 predictors/kendall/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'uwind+vwind (2001-2016) 5p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/uwind+vwind/5 predictors/kendall/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/uwind+vwind/5 predictors/kendall/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'uwind+vwind Predicted vs Actual 5p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/uwind+vwind/5 predictors/kendall/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:

y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 42}
Best Score: 0.35802974152894734
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 33}
Best Score: 0.28864783471016797
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 19}
Best Score: 0.36467681795736484
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 42}
Best Score: 0.378813287299869
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 29}
Best Score: 0.36234423964824103


In [21]:
y_pred_list_rf

[array([-0.36603124,  0.68789884, -0.15109558, -0.03930901, -0.16087336,
        -0.26370767, -0.21229045, -0.21400823,  0.64982868, -0.87069048,
        -0.23782803,  0.28205173,  0.01522868,  0.40516754,  0.05369794,
        -0.24290238]),
 array([-0.37502073,  0.66604305, -0.00774205, -0.24949711, -0.18173593,
        -0.13953357,  0.06996423, -0.00744444,  0.54836242, -0.87286526,
        -0.02030952,  0.48068151,  0.04808205,  0.56445575, -0.04918504,
        -0.1941301 ]),
 array([-0.21521679,  0.86974524, -0.26174964, -0.0771934 ,  0.23531662,
        -0.29810192,  0.02687093, -0.19234958,  0.45995576, -0.89800752,
        -0.25416454,  0.24503722,  0.05026373,  0.36259027,  0.07027569,
        -0.13874979]),
 array([-0.27970547,  0.75910693, -0.17031849,  0.20950794, -0.15255288,
        -0.49392441, -0.31382217, -0.23364459,  0.74045972, -0.96679167,
        -0.24256645,  0.12551075,  0.02268505,  0.46601829,  0.18402373,
        -0.25926485]),
 array([-0.06396389,  0.51750034

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.6670555575149004,
 0.511187589707271,
 0.5730844300934532,
 0.662910952239835,
 0.7578548678277821]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/uwind+vwind/5 predictors/kendall/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'uwind+vwind (2001-2016) 5p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'5p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/uwind+vwind/5 predictors/kendall/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/uwind+vwind/5 predictors/kendall/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'uwind+vwind Predicted vs Actual 5p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'5p{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/uwind+vwind/5 predictors/kendall/comparison plots/randomforest
