In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("mutual_corr.csv")
df_month

May_4       May   April_4  February_2  October_3    June_3   April_7  \
0  -0.152688 -0.537932 -0.510503   -0.237025  -0.238237 -0.205749 -0.189229   
1  -0.434277  0.143875 -0.239307    0.043112  -0.238237 -0.205749  0.247035   
2  -0.491836  0.062558 -0.490269   -0.154323   0.024234 -0.292525  0.627872   
3  -0.425002  0.105073 -0.429062   -0.405000  -0.292296  0.042753  0.339229   
4  -0.100197  0.519645 -0.327994   -0.286091   0.120234 -0.230356  0.330392   
5  -0.586050  0.048646 -0.711481    0.185905  -0.485025 -0.369829  0.224681   
6   0.041170 -0.185863 -0.023152   -0.453909   0.061113 -0.127429 -0.024626   
7   0.383246  0.043587 -0.588995   -0.055208   0.123322 -0.433658  0.229444   
8  -0.137203 -0.076139 -0.479884   -0.270388   0.126905 -0.004318  0.167753   
9  -0.396746  0.306609 -0.374410   -0.195264  -0.310501 -0.324068 -0.003505   
10 -0.171559  0.242783 -0.434295   -0.521914   0.056320 -0.337638  0.051871   
11 -0.299628 -0.085586 -0.463234   -0.645142  -0.484132 -0.060523  0.530420   
12 -0.198090 -0.283183 -0.323603   -0.544568   0.122421  0.036576 -0.065384   
13 -0.181925 -0.369302 -0.274696   -0.483674  -0.571398 -0.183383  0.971499   
14 -0.426650  0.117408 -0.588556   -0.044887  -0.372947 -0.050416  0.126177   
15  0.055938 -0.573000 -0.262094   -0.619189   0.142837  0.036008  0.334856   
16  0.012949  0.028078 -0.340323   -0.081800  -0.750190 -0.322882  0.636354   
17  0.072842 -0.069922 -0.568189   -0.227505   0.121252 -0.232394  0.320109   
18 -0.206571 -0.298891 -0.657684   -0.499514  -0.082731 -0.227325  0.565288   
19 -0.153283 -0.122027 -0.516544   -0.620870  -0.036879  0.056519  0.393333   
20 -0.255737 -0.394076 -0.542961   -0.976114   0.130012 -0.040149  0.643549   
21  0.100671 -0.485566 -0.385256    0.384446   0.355780  0.015485  0.460960   
22  0.132782 -0.609569 -0.948126   -0.958581   0.358613 -0.172808  0.382134   
23 -0.416060  0.007942 -0.286648   -0.803173  -0.095726 -0.036326  0.379680   
24 -0.038356 -0.001466 -0.744531   -0.035854   0.044676 -0.325549 -0.030718   
25 -0.353664 -0.424552 -0.564827   -1.107605   0.314497  0.331386 -0.627091   
26 -0.100381 -0.900787 -0.539879   -0.968495   0.007501 -0.076765  0.460079   
27  0.064222 -0.437391 -0.531012    0.189873   0.477997  0.046889  0.759060   
28  0.346274 -0.427360 -0.877572   -0.705508  -0.082268 -0.040300  0.485920   
29  0.006332 -0.250865 -0.606927   -0.815156   0.283780 -0.282494  0.379124   
30  0.069763 -0.773382 -0.627581   -0.721728   0.251761  0.212849  0.308812   
31 -0.081738 -0.193436 -0.973872   -0.573792  -0.361001 -0.181216  0.878591   
32  0.142405 -0.400540 -0.502868   -0.641733   0.014263 -0.008640  0.204955   
33  0.025944 -0.148868 -0.687596   -0.357787   0.257823  0.145979  0.456805   
34 -0.084464 -0.542844 -0.697204   -0.502756   0.691813 -0.191851 -0.240373   
35 -0.256494 -0.133582 -0.973692   -0.653997   0.035465 -0.217857  0.171956   
36  0.121803 -0.166860 -0.728457    0.328062   0.520139  0.225112  0.149466   
37 -0.072703  0.081555 -0.826396   -0.411424  -0.086196  0.017107  0.671882   
38 -0.230584  0.294920 -0.916167   -0.257934  -0.114404  0.271108  1.002142   
39 -0.175541  0.172050 -0.453759   -0.438978   0.229353 -0.128439  0.137990   
40  0.216430 -0.907750 -0.199919   -0.722134  -0.352979  0.138510 -0.489344   
41  0.157629  0.213686 -0.400329   -0.972503  -0.278796 -0.084516  0.864503   
42 -0.122866 -0.303407 -0.233550   -0.739660   0.014775 -0.226864  1.087192   
43  0.590969 -0.641909 -0.478935   -0.823011   0.362414 -0.306631  0.420027   
44 -0.100808 -0.503912 -0.201842   -0.731942  -0.294580 -0.127690  0.142173   
45  0.173356 -0.445905 -0.367241   -0.185841   0.324772  0.010011  0.208739   
46 -0.053981 -0.093558 -0.564272   -0.676430  -0.240637 -0.046777  0.685232   
47  0.179998 -0.076233 -0.615292   -0.505314  -0.088164 -0.196490  0.462303   
48 -0.273318 -0.074612 -0.905365   -0.585817  -0.078271  0.274010  1.210510   
49 -0.238860 -0.645269 -0.519076   -0.022344  -0.176763  

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :20]
x_train = scaler.fit_transform(x_train)
x_train

array([[-2.06522675e-01, -1.10387076e+00,  1.28642413e-01,
         5.18546777e-01, -7.54891034e-01, -6.32758149e-01,
        -1.43348109e+00, -1.75933928e-01,  8.07740111e-01,
        -8.34276234e-01,  5.68646224e-01, -8.75152937e-01,
         1.14820287e+00, -2.58077498e-01,  3.05209638e-01,
        -4.08111022e-01, -9.56659953e-01,  6.98361747e-01,
        -1.44166730e+00,  1.37115743e-01],
       [-1.46822054e+00,  9.78382568e-01,  1.37171900e+00,
         1.29229509e+00, -7.54891034e-01, -6.32758149e-01,
        -1.92847488e-01, -1.75933928e-01,  1.18967678e+00,
        -8.34276234e-01,  5.68646224e-01, -8.75152937e-01,
        -7.12181490e-01, -2.58077498e-01,  3.05209638e-01,
        -2.25112756e+00, -9.56659953e-01,  1.41051676e-02,
         1.18663342e+00,  5.95140605e-02],
       [-1.72612303e+00,  7.30037947e-01,  2.21386021e-01,
         7.46972059e-01,  1.07993587e-01, -1.11095444e+00,
         8.90164078e-01,  7.69890960e-02, -8.28520883e-01,
         1.47429449e-01, -3.6

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] #df.iloc[43:]['avg']
    y_test.append(y_ts)

In [8]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [9]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

In [10]:
x_test = df_month.iloc[43:, :20]
x_test = scaler.fit_transform(x_test)
x_test

array([[ 2.50077554, -1.35813348, -0.09530993, -1.189308  ,  1.89602607,
        -1.95123443, -0.57437211,  2.00379002, -1.41656375, -0.44774127,
         1.11363232, -0.70249344,  0.58207209,  0.68085548,  2.15675789,
        -0.3150367 ,  0.9910266 ,  0.32241931, -1.06588149, -1.07353798],
       [-0.09689622, -0.89966   ,  1.1233477 , -0.90480286, -0.69541265,
        -0.67862256, -1.37911077, -0.60286642, -0.36445283,  1.54030203,
        -1.16673793, -0.44676419,  0.5250594 ,  0.62707108, -0.90713619,
         0.06206294,  0.10770214, -0.4771657 ,  1.82626057, -1.49051858],
       [ 0.93260979, -0.70694143,  0.39592217,  0.80126121,  1.74755175,
         0.30069846, -1.18631954,  0.76075986,  0.74467782,  1.13010551,
         0.36200867, -0.11541447,  1.48073281,  0.26102071, -0.88227514,
         0.09666425, -0.5719801 , -0.53962207, -0.70415722, -0.94714916],
       [ 0.07894492,  0.46367304, -0.47062222, -0.73137776, -0.48263755,
        -0.10317363,  0.19372977, -1.07452773, -

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 16}
Best Score: 0.17941132937021437
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 20}
Best Score: -0.15744277450584754
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 7}
Best Score: 0.24730715366790318
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 14}
Best Score: 0.22945866800471298
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 18}
Best Score: 0.14430371072044162


In [13]:
y_pred_list

[array([-0.51250706,  0.20571332, -0.40734709, -0.1190264 ,  0.01961494,
        -0.01141689, -0.14270029,  0.01569949, -0.02567114, -0.19096886,
         0.28850464, -0.08372285, -0.22816866,  0.16408053,  0.0708919 ,
        -0.29727028]),
 array([-0.10023813,  0.14646543, -0.33804798, -0.05808628,  0.09572289,
        -0.04078553,  0.04007503, -0.41066044, -0.08185903, -0.29077619,
        -0.04483635, -0.22666286,  0.05325707, -0.08572807, -0.06680918,
        -0.15047115]),
 array([ 0.18785714,  0.11948452, -0.19666667,  0.12178571,  0.23496071,
         0.22464286,  0.26011905, -0.55945055,  0.17345238, -0.22571429,
         0.0432861 ,  0.17880952, -0.14332501,  0.39952381, -0.08421245,
        -0.635     ]),
 array([-0.2929202 ,  0.06382067, -0.2804956 , -0.28839583,  0.0250203 ,
         0.04945651, -0.31384592,  0.23341045, -0.25720813, -0.23628241,
         0.30040373, -0.04391254, -0.18898051, -0.04197298,  0.30040373,
         0.05735675]),
 array([-0.26201407,  0.10133635

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.314420964555463,
 0.4265468383692095,
 0.21465921928674536,
 0.27257532161208975,
 0.29858239112119683]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+hgt/20 predictors/kendall/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'AT+hgt (2001-2016) 20p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+hgt/20 predictors/kendall/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+hgt/20 predictors/kendall/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'AT+hgt Predicted vs Actual 20p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+hgt/20 predictors/kendall/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:
y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 16}
Best Score: 0.17941132937021437
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 20}
Best Score: -0.15744277450584754
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 7}
Best Score: 0.24730715366790318
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 14}
Best Score: 0.22945866800471298
Best Parameters: {'base_estimator__max_depth': 1, 'n_estimators': 18}
Best Score: 0.14430371072044162


In [21]:
y_pred_list_rf

[array([-0.51250706,  0.20571332, -0.40734709, -0.1190264 ,  0.01961494,
        -0.01141689, -0.14270029,  0.01569949, -0.02567114, -0.19096886,
         0.28850464, -0.08372285, -0.22816866,  0.16408053,  0.0708919 ,
        -0.29727028]),
 array([-0.10023813,  0.14646543, -0.33804798, -0.05808628,  0.09572289,
        -0.04078553,  0.04007503, -0.41066044, -0.08185903, -0.29077619,
        -0.04483635, -0.22666286,  0.05325707, -0.08572807, -0.06680918,
        -0.15047115]),
 array([ 0.18785714,  0.11948452, -0.19666667,  0.12178571,  0.23496071,
         0.22464286,  0.26011905, -0.55945055,  0.17345238, -0.22571429,
         0.0432861 ,  0.17880952, -0.14332501,  0.39952381, -0.08421245,
        -0.635     ]),
 array([-0.2929202 ,  0.06382067, -0.2804956 , -0.28839583,  0.0250203 ,
         0.04945651, -0.31384592,  0.23341045, -0.25720813, -0.23628241,
         0.30040373, -0.04391254, -0.18898051, -0.04197298,  0.30040373,
         0.05735675]),
 array([-0.26201407,  0.10133635

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.314420964555463,
 0.4265468383692095,
 0.21465921928674536,
 0.27257532161208975,
 0.29858239112119683]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+hgt/20 predictors/kendall/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'AT+hgt (2001-2016) 20p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+hgt/20 predictors/kendall/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+hgt/20 predictors/kendall/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'AT+hgt Predicted vs Actual 20p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+hgt/20 predictors/kendall/comparison plots/randomforest
