In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("spearman_corr.csv")
df_month

May_5  February_2    August   April_7   April_3     May_9  April_13  \
0  -0.175275    0.483186 -0.469484 -0.192907 -0.510503  0.056523 -0.139798   
1  -0.767088    0.116145 -0.469484 -0.155950 -0.239307  0.650787 -0.343262   
2  -0.225223    0.471996 -0.720683 -0.271062 -0.490269 -0.117836 -0.176245   
3  -0.321780    0.420501 -0.270299  0.424437 -0.429062  0.573503 -0.350389   
4  -0.419739    0.158944 -0.794188 -0.115674 -0.327994 -0.201221 -0.457755   
5  -0.525846    0.522460 -0.810097  0.022826 -0.711481  0.868295 -0.221788   
6  -0.043810    0.014395 -0.177833  0.090922 -0.023152  0.184597  0.146627   
7  -0.391165    0.171814 -1.010284 -0.177244 -0.588995  0.145341  0.111823   
8  -0.261227    0.445708 -0.426508 -0.057897 -0.479884  0.333250  0.077770   
9  -0.571863    0.261804 -0.589004  0.377096 -0.374410  0.446709 -0.154538   
10 -0.505085    0.465199 -0.508138  0.334326 -0.434295  0.231010 -0.195763   
11 -0.594258    0.244581 -0.157695  0.484893 -0.463234  0.382020 -0.161660   
12 -0.550491    0.096500 -0.057424  0.551070 -0.323603  0.420440 -0.051273   
13 -0.404356    0.333806 -0.743766  0.572507 -0.274696  0.080987 -0.084647   
14 -0.608884    0.352461 -0.845307  0.274774 -0.588556  0.667429 -0.150287   
15 -0.575092    0.196864  0.022840  0.068549 -0.262094  0.173762 -0.319073   
16 -0.170720    0.483426 -0.668412  0.007659 -0.340323  0.435828 -0.067115   
17 -0.198763    0.247179 -0.797616  0.488492 -0.568189  0.172119 -0.546462   
18 -0.411539    0.358140 -1.059092  0.215832 -0.657684  0.497148 -0.067374   
19 -0.977604    0.431020 -0.437608  0.189262 -0.516544  0.350859  0.033085   
20 -0.368971    0.368795 -0.658091  0.424504 -0.542961  0.253109  0.035218   
21 -0.598015    0.273820 -0.866576  0.088431 -0.385256  0.519236  0.344285   
22 -0.070184    0.607189 -0.899598 -0.170636 -0.948126  0.418227  0.196858   
23 -0.716888    0.425008 -0.694944  0.160750 -0.286648  0.722396 -0.253765   
24 -0.567340    0.518474 -0.782615 -0.103443 -0.744531  0.243054  0.076128   
25 -0.565253    0.378434 -0.515197  0.467573 -0.564827  0.380592  0.037681   
26 -0.912115    0.283115 -0.223814  0.209547 -0.539879  0.587398 -0.233703   
27 -0.486629    0.130374 -0.796961  0.258291 -0.531012  0.488550  0.153029   
28 -0.642474    0.657592 -1.035925  0.251720 -0.877572  0.267687  0.146892   
29 -0.839966    0.524346 -1.033375 -0.009784 -0.606927  0.612330  0.216212   
30 -0.057363    0.033915 -0.062094  0.665729 -0.627581  0.133563 -0.124561   
31 -0.949919    0.190141 -0.411049  0.213110 -0.973872  0.332286 -0.521395   
32 -0.593693    0.326841 -0.841190  0.074446 -0.502868  0.213819 -0.139217   
33 -0.637474    0.651757 -0.832795  0.040981 -0.687596  0.520987 -0.079620   
34 -1.465676    0.529202 -0.864321 -0.183152 -0.697204  0.708655 -0.101057   
35 -1.143802    0.514517 -0.557614 -0.030128 -0.973692  0.637498 -0.120001   
36 -0.677969    0.313176 -0.431356  0.108277 -0.728457  0.381741 -0.315031   
37 -0.796513    0.322641 -0.947460  0.013706 -0.826396  0.200599 -0.699852   
38 -0.781170    0.378289 -0.195066  0.301585 -0.916167  0.307844 -0.280432   
39 -0.940303    0.461420 -0.809278 -0.154568 -0.453759  0.482336  0.355944   
40  0.225964    0.208526 -0.575750  0.693824 -0.199919 -0.209821 -0.554980   
41 -0.416839    0.212041 -0.685616  0.577300 -0.400329  0.017713 -0.782115   
42 -0.489539    0.464546 -0.960741  0.496532 -0.233550  0.138547 -0.506736   
43 -0.480705    0.527591 -0.785014  0.272305 -0.478935 -0.282776 -0.158381   
44 -0.497181    0.234869 -1.129207  0.231853 -0.201842  0.543379  0.237430   
45 -0.220992    0.406447 -0.413180  0.568305 -0.367241  0.133375 -0.320745   
46 -0.476177    0.388426 -0.669047  0.145854 -0.564272  0.120069 -0.241148   
47 -1.259505    0.215182 -0.763223  0.407086 -0.615292  0.224655 -0.049664   
48 -0.792219    0.346305 -0.582140  0.435672 -0.905365 -0.242156 -0.735551   
49 -0.446306    0.366034 -0.338984  0.322293 -0.519076  0.129416 -0.263333   
50 -0.520736    0.073928 -0.4

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :15]
x_train = scaler.fit_transform(x_train)
x_train

array([[ 1.14820287e+00,  8.46604291e-01,  4.93987433e-01,
        -1.38666439e+00,  1.28642413e-01, -1.19059994e+00,
        -1.02080814e-02,  7.93408267e-01, -1.14241968e+00,
         6.98441533e-01,  2.66153833e-01,  6.98630001e-02,
         7.80981853e-01,  9.22093577e-03, -2.55429926e-01],
       [-7.12181490e-01, -1.43981540e+00,  4.93987433e-01,
        -1.24442718e+00,  1.37171900e+00,  1.24568302e+00,
        -8.04032398e-01,  7.62520528e-01, -1.14241968e+00,
         6.98441533e-01,  1.00472307e+00, -6.60970324e-01,
         7.80981853e-01,  9.22093577e-03, -3.05792788e-01],
       [ 9.91190101e-01,  7.76902108e-01, -3.75732655e-01,
        -1.68746489e+00,  2.21386021e-01, -1.90541201e+00,
        -1.52410116e-01, -1.50970878e+00,  7.42110791e-01,
        -4.23141589e-01,  8.01873134e-01, -2.79941279e-01,
        -3.56822821e-01, -3.06661824e-01, -1.17112239e-01],
       [ 6.87659667e-01,  4.56120085e-01,  1.18362149e+00,
         9.89353439e-01,  5.01941216e-01,  9.28844580

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [8]:
x_test = df_month.iloc[43:, :15]
x_test = scaler.fit_transform(x_test)
x_test

array([[ 0.58207209,  1.58349574, -0.5242643 , -0.56834002, -0.09530993,
        -1.23143643,  0.70012832,  1.93545575,  0.08860568,  1.72019939,
         0.70498912,  0.97541413,  0.90921348,  1.30321924, -0.62236905],
       [ 0.5250594 , -0.32727854, -1.82921775, -0.79142582,  1.1233477 ,
         1.40762748,  2.3168683 ,  0.39000974, -1.15112758,  0.15761628,
        -1.78412667, -0.2912169 , -0.64766769,  1.1258208 , -0.49046046],
       [ 1.48073281,  0.79271338,  0.88548891,  1.06403682,  0.39592217,
         0.09791316,  0.03693208, -1.63516606,  0.25577448,  0.58035655,
        -0.21425681, -1.36685227, -0.02588163,  1.31423715,  0.51676383],
       [ 0.59774003,  0.6750798 , -0.08459292, -1.26569071, -0.47062222,
         0.05540889,  0.36205552,  0.46784355,  0.51027961,  0.84446834,
         0.62282088, -0.19432086,  0.10140005,  0.70177579,  0.17230108],
       [-2.11274412, -0.45579125, -0.44164646,  0.17494873, -0.69500983,
         0.38949863,  1.14419741,  0.92072275, 

In [9]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] 
    y_test.append(y_ts)

In [10]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 42}
Best Score: 0.3435186032569754
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 19}
Best Score: 0.1735700678518593
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 48}
Best Score: 0.42515914652342174
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 4}
Best Score: 0.39338695103018934
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 31}
Best Score: 0.3030705621857832


In [13]:
y_pred_list

[array([ 0.14464384,  0.13842845, -0.02054328, -0.08868536, -0.0968723 ,
        -0.12759456,  0.0866579 , -0.41900735,  0.06443885, -0.45082928,
        -0.62529538, -0.25488913,  0.24886254,  0.39053854,  0.010077  ,
        -0.03867408]),
 array([ 0.23791697,  0.03757918, -0.13309418,  0.07440816,  0.02005701,
        -0.1343079 ,  0.07955783, -0.36517652,  0.17847314, -0.24212285,
        -0.73217355, -0.07267523, -0.20905158,  0.28285063,  0.04795109,
        -0.01735738]),
 array([ 0.20218946,  0.22896746,  0.06800148,  0.11817298,  0.04915392,
        -0.10960503,  0.09126892, -0.41820404,  0.29828248, -0.48209283,
        -0.39940124, -0.18365661,  0.00927884,  0.24490934, -0.01848714,
        -0.10618599]),
 array([ 0.56720752,  0.06648066,  0.210875  ,  0.06648066,  0.06648066,
        -0.07300463,  0.34510566,  0.101875  ,  0.06648066, -0.735125  ,
        -0.4735    , -0.28076471,  0.101875  ,  0.19099537, -0.12625463,
        -0.03214434]),
 array([ 0.12179322,  0.29423875

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.3704076601083887,
 0.5279149886066908,
 0.4449551445697151,
 0.21993789019805074,
 0.30302137148111685]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/15 predictors/spearson/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'hgt+vwind (2001-2016) 15p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'15p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+hgt/15 predictors/spearson/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/15 predictors/spearson/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'hgt+vwind Predicted vs Actual 15p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'15p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+hgt/15 predictors/spearson/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:

y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 42}
Best Score: 0.3435186032569754
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 19}
Best Score: 0.1735700678518593
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 48}
Best Score: 0.42515914652342174
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 4}
Best Score: 0.39338695103018934
Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 31}
Best Score: 0.3030705621857832


In [21]:
y_pred_list_rf

[array([ 0.14464384,  0.13842845, -0.02054328, -0.08868536, -0.0968723 ,
        -0.12759456,  0.0866579 , -0.41900735,  0.06443885, -0.45082928,
        -0.62529538, -0.25488913,  0.24886254,  0.39053854,  0.010077  ,
        -0.03867408]),
 array([ 0.23791697,  0.03757918, -0.13309418,  0.07440816,  0.02005701,
        -0.1343079 ,  0.07955783, -0.36517652,  0.17847314, -0.24212285,
        -0.73217355, -0.07267523, -0.20905158,  0.28285063,  0.04795109,
        -0.01735738]),
 array([ 0.20218946,  0.22896746,  0.06800148,  0.11817298,  0.04915392,
        -0.10960503,  0.09126892, -0.41820404,  0.29828248, -0.48209283,
        -0.39940124, -0.18365661,  0.00927884,  0.24490934, -0.01848714,
        -0.10618599]),
 array([ 0.56720752,  0.06648066,  0.210875  ,  0.06648066,  0.06648066,
        -0.07300463,  0.34510566,  0.101875  ,  0.06648066, -0.735125  ,
        -0.4735    , -0.28076471,  0.101875  ,  0.19099537, -0.12625463,
        -0.03214434]),
 array([ 0.12179322,  0.29423875

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.3704076601083887,
 0.5279149886066908,
 0.4449551445697151,
 0.21993789019805074,
 0.30302137148111685]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/15 predictors/spearson/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'hgt+vwind (2001-2016) 15p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'15_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+hgt/15 predictors/spearson/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/hgt+vwind/15 predictors/spearson/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'hgt+vwind Predicted vs Actual 15p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'15p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/AT+hgt/15 predictors/spearson/comparison plots/randomforest
