In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.tree import DecisionTreeRegressor
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("enso_index.csv")
df

year  january  february  march  april   may  june  july  august  \
0   1958     1.54      1.40   0.99   0.31  0.32  0.30  0.04    0.24   
1   1959     0.43      0.50   0.26   0.27 -0.01 -0.33 -0.28   -0.41   
2   1960     0.02     -0.24  -0.08   0.01  0.05 -0.20 -0.25    0.00   
3   1961    -0.15      0.04  -0.10   0.13 -0.01  0.10 -0.32   -0.25   
4   1962    -0.25     -0.16  -0.41  -0.32 -0.42 -0.22 -0.30   -0.13   
5   1963    -0.32     -0.26  -0.06  -0.06  0.00  0.12  0.72    0.90   
6   1964     0.76      0.55  -0.16  -0.53 -0.74 -0.88 -0.65   -0.76   
7   1965    -0.57     -0.36  -0.34  -0.09  0.19  0.45  0.81    1.25   
8   1966     1.13      0.83   0.83   0.54 -0.06  0.14  0.23   -0.10   
9   1967    -0.55     -0.56  -0.47  -0.53 -0.24 -0.12 -0.10   -0.31   
10  1968    -0.60     -0.74  -0.76  -0.47 -0.44  0.19  0.31    0.33   
11  1969     0.90      1.02   0.61   0.33  0.39  0.26  0.10    0.52   
12  1970     0.55      0.36   0.26   0.18  0.01 -0.30 -0.98   -0.95   
13  1971    -1.47     -1.28  -1.29  -0.97 -0.82 -0.78 -0.64   -0.65   
14  1972    -0.58     -0.22  -0.25   0.21  0.33  0.66  0.83    1.30   
15  1973     1.60      1.08   0.58  -0.07 -0.56 -0.86 -1.14   -1.21   
16  1974    -2.02     -1.50  -1.44  -1.00 -0.79 -0.70 -0.65   -0.32   
17  1975    -0.37     -0.33  -0.59  -0.59 -1.00 -1.25 -1.24   -1.16   
18  1976    -1.80     -1.05  -0.68  -0.42 -0.49  0.00  0.15    0.31   
19  1977     0.84      0.55   0.40  -0.25 -0.03  0.36  0.45    0.25   
20  1978     0.72      0.51   0.06  -0.37 -0.49 -0.45 -0.48   -0.62   
21  1979     0.05      0.09   0.13   0.17 -0.09  0.04 -0.20    0.21   
22  1980     0.55      0.33   0.09   0.20  0.13  0.37  0.02   -0.23   
23  1981    -0.45     -0.45  -0.02  -0.17 -0.11 -0.15 -0.43   -0.18   
24  1982    -0.04     -0.13  -0.02   0.24  0.65  0.92  0.64    0.93   
25  1983     2.43      2.22   1.69   1.12  1.12  0.62 -0.11   -0.13   
26  1984    -0.80     -0.53  -0.48  -0.60 -0.64 -0.90 -0.40   -0.40   
27  1985    -0.89     -0.91  -0.96  -0.98 -0.90 -0.76 -0.61   -0.49   
28  1986    -0.79     -0.64  -0.51  -0.41 -0.47 -0.08  0.16    0.24   
29  1987     1.19      1.17   1.24   0.89  0.91  1.24  1.34    1.48   
30  1988     0.69      0.35   0.29  -0.49 -1.05 -1.46 -1.54   -1.44   
31  1989    -1.95     -1.37  -1.33  -1.11 -0.80 -0.64 -0.47   -0.58   
32  1990     0.02      0.36   0.20   0.26  0.32  0.00  0.15    0.17   
33  1991     0.51      0.32   0.10   0.21  0.44  0.65  0.62    0.43   
34  1992     1.61      1.62   1.50   1.41  1.27  0.53  0.27   -0.15   
35  1993     0.28      0.42   0.47   0.92  0.93  0.64  0.33    0.16   
36  1994     0.03     -0.16  -0.06   0.03  0.14  0.27  0.16    0.52   
37  1995     1.10      0.87   0.49   0.27  0.03  0.08  0.03   -0.38   
38  1996    -0.65     -0.66  -0.48  -0.34 -0.40 -0.12 -0.14   -0.30   
39  1997    -0.43     -0.24  -0.06   0.34  0.87  1.15  1.60    1.94   
40  1998     2.42      2.08   1.49   0.90  0.68 -0.39 -0.73   -0.83   
41  1999    -1.53     -1.41  -0.92  -0.81 -0.87 -0.95 -0.84   -0.98   
42  2000    -1.79     -1.53  -1.26  -0.80 -0.80 -0.75 -0.57   -0.36   
43  2001    -0.88     -0.63  -0.48  -0.30 -0.30 -0.11  0.01   -0.07   
44  2002    -0.14      0.00   0.11   0.14  0.21  0.68  0.57    0.70   
45  2003     0.98      0.64   0.48  -0.03 -0.52 -0.19  0.14    0.05   
46  2004     0.26      0.17  -0.10   0.06  0.10  0.14  0.41    0.66   
47  2005     0.56      0.26   0.28   0.28  0.30  0.22 -0.01   -0.04   
48  2006    -0.98     -0.71  -0.73  -0.30 -0.11  0.09  0.03    0.37   
49  2007     0.59      0.12  -0.15  -0.16 -0.39 -0.16 -0.37   -0.57   
50  2008    -1.79     -1.70  -1.17  -0.89 -0.64 -0.44 -0.04   -0.04   
51  2009    -1.00     -0.71  -0.72  -0.25  0.17  0.49  0.69    0.62   
52  2010     1.43      1.18   1.07   0.56 -0.15 -0.62 -0.89   -1.33   
53  2011    -1.70     -1.26  -0.98  -0.74 -0.53 -0.25 -0.23   -0.66   
54  2012    -0.93     -0.61  -0.48  -0.29 -0.18  0.14  0.44    0.66   
55  2013    -0.42     -0.40 

In [3]:
df_month = pd.read_csv("kendall_corr.csv")
df_month

May_7   March_8   April_4  October_8   March_7     May_6   April_9  \
0  -0.852495  0.319904 -0.104311  -0.413652 -0.234575 -0.580149  0.015370   
1  -0.845069  0.516930  0.035738  -0.413652 -0.318164 -0.195247 -0.162453   
2  -0.590339  0.236701 -0.384591   0.027956 -0.338490 -0.120445 -0.038483   
3  -0.520556  0.216181 -0.387030   0.161050 -0.122469 -0.315405 -0.039148   
4  -0.687532  0.308101 -0.092262   0.207545 -0.206767 -0.278210  0.123145   
5  -0.404820  0.477551  0.208624  -0.158057 -0.202997  0.064851  0.017840   
6  -0.416906  0.676411 -0.209037   0.037837  0.248931 -0.243972  0.131043   
7  -0.659332  0.481080  0.260026  -0.095395 -0.159086 -0.311494  0.604414   
8  -0.832134  0.570303 -0.328015  -0.078566  0.000734 -0.340315  0.161723   
9  -0.844990  0.783917 -0.004884  -0.247034  0.042361 -0.480035  0.389663   
10 -0.919831  0.885234 -0.103935   0.192553 -0.015148 -0.452106  0.033886   
11 -1.201436  0.557202 -0.348195   0.131053  0.022883 -0.313123  0.041223   
12 -0.436037  0.686012 -0.296909  -0.031763  0.078270 -0.324667 -0.265606   
13 -0.411844  0.729469 -0.218239   0.212235 -0.115746 -0.255317  0.269274   
14 -0.846678  0.538917 -0.001275   0.080725 -0.062301 -0.503914  0.153323   
15 -1.010343  0.750663 -0.427952   0.216618 -0.129578 -0.320360 -0.272563   
16 -0.687574  0.648792 -0.374006   0.068310 -0.048697 -0.188983  0.158237   
17 -0.589119  0.798494 -0.025361   0.313999 -0.060721 -0.258141 -0.109129   
18 -0.642845  0.470566 -0.180371  -0.332513  0.002260 -0.443004  0.101165   
19 -0.700360  0.412475 -0.114047  -0.106588  0.039469 -0.609817  0.280700   
20 -0.650685  0.609184 -0.154797   0.216280  0.303989 -0.240010 -0.314197   
21 -0.940887  0.369053 -0.081204  -0.048221 -0.048098 -0.443608 -0.105826   
22 -0.717090  0.324268  0.072628   0.365339  0.081296 -0.333763 -0.027849   
23 -0.904664  0.386027 -0.175884  -0.117264  0.343986 -0.337448 -0.317301   
24 -0.985174  0.504688 -0.209115   0.368654 -0.210698 -0.496479 -0.118893   
25 -0.569978  0.660589  0.251590   0.310994  0.179605 -0.410104 -0.076516   
26 -0.539389  0.598726 -0.112678  -0.238892 -0.018947 -0.473291 -0.232176   
27 -0.514107  0.713991 -0.051754   0.510461 -0.109409 -0.112919  0.064487   
28 -1.054893  0.774835  0.217478  -0.092212 -0.096937 -0.467269 -0.158259   
29 -1.086590  0.211223  0.311318  -0.163177 -0.187889 -0.454395  0.268362   
30 -0.435573  1.044898 -0.088113   0.257598  0.063502 -0.136659 -0.102577   
31 -0.450881  0.618326  0.015785   0.248477  0.027100 -0.313414  0.203477   
32 -1.101024  0.574581  0.185852   0.005917 -0.011861 -0.352305  0.197465   
33 -1.524831  0.265454 -0.093495   0.111451  0.088138 -0.513456  0.069132   
34 -1.535719 -0.271505  0.164961   0.070784 -0.011348 -0.857210  0.129629   
35 -0.976848  0.148541 -0.051980  -0.047962 -0.031480 -0.494073 -0.069755   
36 -0.717103  0.131308 -0.085628   0.137073 -0.164001 -0.361113 -0.017554   
37 -0.913556  0.545931 -0.263346  -0.085147  0.144200 -0.411644 -0.041280   
38 -0.814521  0.544718 -0.230546   0.047277  0.018576 -0.376923 -0.190205   
39 -1.037813  0.027603  0.309759   0.009649 -0.207999 -0.430244  0.113666   
40 -1.143089  0.226183  0.515949  -0.016451  0.150737 -0.443402 -0.237093   
41 -0.524652  0.587506 -0.396512   0.105164  0.321460 -0.318724 -0.508567   
42 -0.823933  0.580256 -0.131581  -0.105623  0.084074 -0.297998 -0.156116   
43 -0.807037  0.722982  0.054877  -0.021870 -0.153756 -0.427415  0.134999   
44 -1.048659  0.539732 -0.089119  -0.243537 -0.170887 -0.404995  0.366699   
45 -0.835871  0.309253 -0.033668   0.069984 -0.267859 -0.282874 -0.033999   
46 -0.562357  0.479399  0.007897  -0.268517 -0.042974 -0.108122  0.121511   
47 -1.177788  0.611415 -0.139136   0.231592  0.018968 -0.538433  0.048261   
48 -1.012569  0.918148  0.071401  -0.199849 -0.009664 -0.359096 -0.132190   
49 -0.431466  0.605242 -0.316671   0.536726  0.008670 -0.285946 -0.117421   
50 -0.544057  0.663614 -0.392254   0.243858  0.041273 -0.493109 -0.198876   
51 

In [4]:
scaler = StandardScaler()

In [5]:
x_train = df_month.iloc[:42, :20]
x_train = scaler.fit_transform(x_train)
x_train

array([[-2.20736769e-01, -6.90533815e-01, -1.43529326e-01,
        -2.20194045e+00, -1.32695675e+00, -1.40559123e+00,
         5.95009832e-02, -3.35551855e-01, -5.54931184e-02,
         5.29819361e-01,  1.27564677e+00, -4.68294956e-01,
        -8.45939168e-01, -4.57014003e-01,  6.96097583e-02,
         8.02366461e-02,  6.17643967e-01, -4.26673025e-01,
        -9.90005995e-01,  3.24045363e-01],
       [-1.93900555e-01,  1.00356075e-01,  4.88719378e-01,
        -2.20194045e+00, -1.85061348e+00,  1.08648338e+00,
        -7.88982693e-01, -3.35551855e-01, -6.27967900e-01,
        -4.56116999e-01,  8.66305021e-01, -9.15026323e-01,
        -8.45939168e-01,  4.95432641e-01,  6.96097583e-02,
         8.02366461e-02,  5.67043312e-01, -4.26673025e-01,
        -9.90005995e-01,  1.24096836e+00],
       [ 7.26621135e-01, -1.02451884e+00, -1.40884924e+00,
        -6.38969250e-02, -1.97795359e+00,  1.57079413e+00,
        -1.97457818e-01,  5.13177854e-01,  8.75206260e-01,
         6.55410758e-01, -3.5

In [6]:
y_train = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_tr= df.iloc[:42][i]
    y_train.append(y_tr)
    

In [7]:
y_test = []
target_variables = ['avg', 'june', 'july', 'august', 'september']
for i in target_variables:
    y_ts= df.iloc[43:][i] #df.iloc[43:]['avg']
    y_test.append(y_ts)

In [8]:
y_train

[0     0.0675
 1    -0.3875
 2    -0.1050
 3    -0.2475
 4    -0.3025
 5     0.5975
 6    -0.8050
 7     0.9425
 8     0.0550
 9    -0.2800
 10    0.2200
 11    0.3375
 12   -0.7525
 13   -0.7050
 14    0.9950
 15   -1.1525
 16   -0.5050
 17   -1.2725
 18    0.2575
 19    0.3750
 20   -0.5375
 21    0.1325
 22    0.0100
 23   -0.2075
 24    0.9700
 25   -0.0300
 26   -0.5125
 27   -0.6075
 28    0.2275
 29    1.3975
 30   -1.4425
 31   -0.5175
 32    0.1100
 33    0.4800
 34    0.1275
 35    0.3475
 36    0.3375
 37   -0.2100
 38   -0.2250
 39    1.6975
 40   -0.6925
 41   -0.9025
 Name: avg, dtype: float64,
 0     0.30
 1    -0.33
 2    -0.20
 3     0.10
 4    -0.22
 5     0.12
 6    -0.88
 7     0.45
 8     0.14
 9    -0.12
 10    0.19
 11    0.26
 12   -0.30
 13   -0.78
 14    0.66
 15   -0.86
 16   -0.70
 17   -1.25
 18    0.00
 19    0.36
 20   -0.45
 21    0.04
 22    0.37
 23   -0.15
 24    0.92
 25    0.62
 26   -0.90
 27   -0.76
 28   -0.08
 29    1.24
 30   -1.46
 31   -0.64


In [9]:
y_test

[43   -0.1125
 44    0.6925
 45    0.0375
 46    0.4700
 47    0.0225
 48    0.2800
 49   -0.5350
 50   -0.2000
 51    0.6200
 52   -1.1000
 53   -0.4750
 54    0.4200
 55   -0.2475
 56    0.2800
 57    1.6800
 58   -0.2825
 Name: avg, dtype: float64,
 43   -0.11
 44    0.68
 45   -0.19
 46    0.14
 47    0.22
 48    0.09
 49   -0.16
 50   -0.44
 51    0.49
 52   -0.62
 53   -0.25
 54    0.14
 55   -0.33
 56    0.48
 57    1.28
 58    0.06
 Name: june, dtype: float64,
 43    0.01
 44    0.57
 45    0.14
 46    0.41
 47   -0.01
 48    0.03
 49   -0.37
 50   -0.04
 51    0.69
 52   -0.89
 53   -0.23
 54    0.44
 55   -0.28
 56    0.13
 57    1.56
 58   -0.25
 Name: july, dtype: float64,
 43   -0.07
 44    0.70
 45    0.05
 46    0.66
 47   -0.04
 48    0.37
 49   -0.57
 50   -0.04
 51    0.62
 52   -1.33
 53   -0.66
 54    0.66
 55   -0.29
 56    0.14
 57    1.87
 58   -0.48
 Name: august, dtype: float64,
 43   -0.28
 44    0.82
 45    0.15
 46    0.67
 47   -0.08
 48    0.63
 49   -1.04

In [10]:
x_test = df_month.iloc[43:, :20]
x_test = scaler.fit_transform(x_test)
x_test

array([[-5.15715144e-02,  6.02664743e-01,  7.29042805e-01,
        -2.02564973e-01, -5.54584804e-01, -7.37367498e-01,
         9.09095293e-01, -1.18514886e+00,  6.36417817e-02,
         8.80626696e-01, -6.04449222e-03, -5.21936042e-01,
         3.11737255e-01,  6.93907358e-01,  7.33780414e-03,
        -9.68145293e-01, -3.74211584e-01, -1.07868857e+00,
         1.54061900e+00,  5.23569542e-01],
       [-1.12369270e+00, -1.72915796e-01, -9.56297598e-03,
        -1.03555508e+00, -6.65993333e-01, -5.82647806e-01,
         2.37053819e+00, -1.60365510e+00, -1.30725011e+00,
        -4.13469213e-01, -1.05342093e-01,  1.24543560e+00,
        -1.99282091e+00,  2.91291349e-02, -5.86921485e-01,
        -2.06803445e+00, -7.21657078e-01,  7.68270519e-01,
        -1.87979481e+00,  1.97182703e+00],
       [-1.79515716e-01, -1.14838154e+00,  2.74867035e-01,
         1.42607886e-01, -1.29663738e+00,  2.60121585e-01,
        -1.56860376e-01,  1.01840904e+00,  1.02414040e+00,
        -1.04320221e+00, -6.3

# Bagging Regressor:

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import BaggingRegressor

def perform_grid_search(x_train, y_train, x_test):
    param_grid = {
        'base_estimator__max_depth': range(1, 5),
        'n_estimators': range(1, 51)
    }

    # Create the BaggingRegressor with DecisionTreeRegressor as the base estimator
    bagging_reg = BaggingRegressor(base_estimator=DecisionTreeRegressor(), oob_score=True, random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(bagging_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    best_max_depth = best_params['base_estimator__max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")

    # Use the best parameters to train a BaggingRegressor and make predictions
    regressor = BaggingRegressor(
        base_estimator=DecisionTreeRegressor(max_depth=best_max_depth),
        n_estimators=best_n_estimators,
        oob_score=True,
        random_state=0)
    
    regressor.fit(x_train, y_train)
    score = regressor.score(x_train, y_train)
    y_pred = regressor.predict(x_test)

    return best_params, best_score, score, y_pred


In [12]:

y_pred_list = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list.append(y_pred)



Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 40}
Best Score: 0.28256702559269475
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 21}
Best Score: 0.24758613588208922
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 8}
Best Score: 0.4064915954406937
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 32}
Best Score: 0.3022594400887844
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 19}
Best Score: 0.19581519186643692


In [13]:
y_pred_list

[array([-0.12376118,  0.61728205, -0.04248191, -0.00530878,  0.37630829,
        -0.10330762, -0.41237601, -0.25929398,  0.36969252, -0.19114925,
        -0.50910267,  0.07107683,  0.06973026,  0.25870391, -0.18854609,
        -0.58383489]),
 array([-0.11313167,  0.15423291,  0.01444268, -0.14369596,  0.18437644,
        -0.11239737, -0.31014951, -0.21459799,  0.23155645, -0.28886414,
        -0.59893946,  0.20552573,  0.26413703,  0.47214849,  0.08381776,
        -0.39905516]),
 array([-0.03555128,  0.53201122, -0.19796131,  0.07650794,  0.23308761,
         0.06993284, -0.55885417, -0.30022837,  0.33      , -0.40236359,
        -0.47233185,  0.50281235,  0.27152511,  0.22666667,  0.02504861,
         0.17434028]),
 array([-0.11259789,  0.9403486 , -0.06568116,  0.022368  ,  0.54100417,
        -0.20287804, -0.41060572, -0.19091988,  0.70862627, -0.21170069,
        -0.5055884 ,  0.1183314 , -0.03384295, -0.03380826, -0.25059126,
        -0.61398966]),
 array([-0.20135323,  0.7808939 

In [14]:
correlation_list = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list.append(corr_bag_reg_mean[0][1])

In [15]:
correlation_list

[0.43477514080334456,
 0.5012474346370916,
 0.483231870927939,
 0.38898247622669696,
 0.46881841332617824]

In [16]:
months = ['jjas-mean','june','july','august','september']

In [17]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Uwind/20 predictors/kendall/coorelation_plots/bagging_regressor'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'Uwind (2001-2016) 20p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)


Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Uwind/20 predictors/kendall/coorelation_plots/bagging_regressor


In [18]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Uwind/20 predictors/kendall/comparison plots/bagging_regressor'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'Uwind Predicted vs Actual 20p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Uwind/20 predictors/kendall/comparison plots/bagging_regressor


# Random Forest

In [19]:


def perform_random_forest_grid_search(x_train, y_train, x_test):
    # Define the parameter grid
    param_grid = {
        'n_estimators': range(1, 51),
        'max_depth': range(1, 5),
    }

    # Create the RandomForestRegressor
    random_forest_reg = RandomForestRegressor(random_state=0)

    # Create the GridSearchCV object
    grid_search = GridSearchCV(random_forest_reg, param_grid, cv=2, scoring='r2')

    # Fit the grid search to the data
    grid_search.fit(x_train, y_train)

    # Get the best parameters and the corresponding score
    best_params = grid_search.best_params_
    best_score = grid_search.best_score_
    
    # Save the best values into separate variables
    best_max_depth = best_params['max_depth']
    best_n_estimators = best_params['n_estimators']

    print(f"Best Parameters: {best_params}")
    print(f"Best Score: {best_score}")
    print(f"Best max_depth: {best_max_depth}")
    print(f"Best n_estimators: {best_n_estimators}")

    # Use the best parameters to train a RandomForestRegressor and make predictions
    RF = RandomForestRegressor(
        n_estimators=best_n_estimators,
        max_depth=best_max_depth,
        random_state=0)

    RF.fit(x_train, y_train)
    score = RF.score(x_train, y_train)
    y_pred_rf = RF.predict(x_test)

    return best_params, best_score, score, y_pred_rf


In [20]:
y_pred_list_rf = []

for target_variable in y_train:
    best_params, best_score, model_score, y_pred = perform_grid_search(x_train, target_variable, x_test)
    y_pred_list_rf.append(y_pred)


Best Parameters: {'base_estimator__max_depth': 3, 'n_estimators': 40}
Best Score: 0.28256702559269475
Best Parameters: {'base_estimator__max_depth': 2, 'n_estimators': 21}
Best Score: 0.24758613588208922
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 8}
Best Score: 0.4064915954406937
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 32}
Best Score: 0.3022594400887844
Best Parameters: {'base_estimator__max_depth': 4, 'n_estimators': 19}
Best Score: 0.19581519186643692


In [21]:
y_pred_list_rf

[array([-0.12376118,  0.61728205, -0.04248191, -0.00530878,  0.37630829,
        -0.10330762, -0.41237601, -0.25929398,  0.36969252, -0.19114925,
        -0.50910267,  0.07107683,  0.06973026,  0.25870391, -0.18854609,
        -0.58383489]),
 array([-0.11313167,  0.15423291,  0.01444268, -0.14369596,  0.18437644,
        -0.11239737, -0.31014951, -0.21459799,  0.23155645, -0.28886414,
        -0.59893946,  0.20552573,  0.26413703,  0.47214849,  0.08381776,
        -0.39905516]),
 array([-0.03555128,  0.53201122, -0.19796131,  0.07650794,  0.23308761,
         0.06993284, -0.55885417, -0.30022837,  0.33      , -0.40236359,
        -0.47233185,  0.50281235,  0.27152511,  0.22666667,  0.02504861,
         0.17434028]),
 array([-0.11259789,  0.9403486 , -0.06568116,  0.022368  ,  0.54100417,
        -0.20287804, -0.41060572, -0.19091988,  0.70862627, -0.21170069,
        -0.5055884 ,  0.1183314 , -0.03384295, -0.03380826, -0.25059126,
        -0.61398966]),
 array([-0.20135323,  0.7808939 

In [22]:
correlation_list_rf = []
for i in range(5):
    corr_bag_reg_mean = np.corrcoef(y_pred_list[i], y_test[i])
    correlation_list_rf.append(corr_bag_reg_mean[0][1])

In [23]:
correlation_list_rf

[0.43477514080334456,
 0.5012474346370916,
 0.483231870927939,
 0.38898247622669696,
 0.46881841332617824]

In [24]:
import os

output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Uwind/20 predictors/kendall/coorelation_plots/randomforest'

for i in range(5):
    actual_values = y_test[i] # Replace with your actual values
    predicted_values = y_pred_list_rf[i] # Replace with your predicted values
    years = range(2001, 2017)  # Adjust as needed

    plt.figure(figsize=(8, 6))

    # Create scatter plot and annotations
    for year, actual, predicted in zip(years, actual_values, predicted_values):
        plt.scatter(actual, predicted, s=80)
        plt.annotate(f"{year}", (actual, predicted), xytext=(-8, -15), textcoords='offset points',fontsize=8)

    # Add diagonal line and plot elements
    plt.plot([-2, 2], [-2, 2], color='red', linestyle='--', label=f'correlation: {correlation_list[i]:.2f}')
    plt.xlabel('Actual Values', fontsize=12)
    plt.ylabel('Predicted Values', fontsize=12)
    plt.title(f'Uwind (2001-2016) 20p {months[i]}', fontsize=14)  # Updated this line
    plt.xlim(-2, 2)  # Set limits from -2 to 2
    plt.ylim(-2, 2)
    plt.grid(True)
    plt.legend()

    # Save the plot
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)

Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Uwind/20 predictors/kendall/coorelation_plots/randomforest


In [25]:
output_directory = '/home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Uwind/20 predictors/kendall/comparison plots/randomforest'

for i in range(5):
    plt.plot(df['year'][43:], y_test[i], label='Actual', color='blue', marker='o', linestyle='-')
    plt.plot(df['year'][43:], y_pred_list_rf[i], label='Predicted', color='green', marker='s', linestyle='--', alpha=0.7)

    
    plt.grid(True)
    plt.axhline(y=0, color='black', linestyle='--')
    plt.xlabel('Year', fontsize=12)
    plt.ylabel('Enso Indices', fontsize=12)
    plt.title(f'Uwind Predicted vs Actual 20p {months[i]}', fontsize=14)
    plt.legend(loc='upper left')


    
    plot_filename = f'20p_{months[i]}.png'
    plot_filepath = os.path.join(output_directory, plot_filename)
    plt.savefig(plot_filepath)
    plt.close()  # Close the plot to avoid displaying in the notebook

print("Plots saved in:", output_directory)



Plots saved in: /home/ravi/myfolder/enso_code/enso_code-20240105T103408Z-001/enso_code/Uwind/20 predictors/kendall/comparison plots/randomforest
